email password flow
ice-blockchain/mobile-app pull request #10
Opened 2023-03-27 08:32 UTC by ice-orion

Enables email + password auth for devices with Chinese language

2023-03-27 22:07 UTC, ice-atlas requested changes

2023-03-27 22:07 UTC, ice-atlas commented on src/assets/svg/PasswordIcon.tsx
> +  <Svg width={rem(24)} height={rem(24)} fill="none" {...props}>
add `viewBox` here pls

2023-03-28 02:42 UTC, ice-orion commented on src/assets/svg/PasswordIcon.tsx
> +  <Svg width={rem(24)} height={rem(24)} fill="none" {...props}>
done

2023-03-28 06:56 UTC, ice-atlas submitted a review, later dismissed

2023-03-28 07:11 UTC, ice-atlas approved these changes

2023-03-28 07:14 UTC, ice-hades approved these changes

2023-03-28 07:18 UTC, ice-hector approved these changes

2023-03-28 07:46 UTC, merged