feat: integrated moengage sdk
ice-blockchain/mobile-app pull request #102
Opened 2023-01-16 08:34 UTC by ice-hades

2023-01-16 08:38 UTC, ice-orion submitted a review, later dismissed

2023-01-16 08:47 UTC, ice-ares commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +                .setDataCenter(DataCenter.DATA_CENTER_2)
This should be in env file

2023-01-16 08:47 UTC, ice-ares commented on ios/ice/AppDelegate.mm
> +   sdkConfig.moeDataCenter = MODataCenterData_center_02;
From env

2023-01-16 08:47 UTC, ice-ares commented on src/services/datatracking/index.ts
> +import ReactMoE from 'react-native-moengage';
Its analytics, not datatracking

2023-01-16 08:47 UTC, ice-ares commented on src/services/datatracking/index.ts
> +  In a scenario where you have to update the User Attribute Unique ID value
Why would we ever update the user id?

2023-01-16 08:47 UTC, ice-ares commented on src/services/datatracking/index.ts
> +export function trackLogout() {
stop()

2023-01-16 08:47 UTC, ice-ares commented on src/store/modules/Notifications/hooks/useInitNotifications.tsx
> +        Make sure you are setting the Push/InApp callback listeners before calling the initialize().
Where are u setting em?

2023-01-16 08:56 UTC, ice-hades commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +                .setDataCenter(DataCenter.DATA_CENTER_2)
that is not a constant. that is a native enum value

2023-01-16 08:56 UTC, ice-hades commented on ios/ice/AppDelegate.mm
> +   sdkConfig.moeDataCenter = MODataCenterData_center_02;
that is not a constant. that is a native enum value

2023-01-16 08:56 UTC, ice-hades commented on src/services/datatracking/index.ts
> +import ReactMoE from 'react-native-moengage';
ok

2023-01-16 09:00 UTC, ice-hades commented on src/services/datatracking/index.ts
> +import ReactMoE from 'react-native-moengage';
but in moengage it is a data tracking
<img width="215" alt="Screenshot 2023-01-16 at 11 59 07" src="https://user-images.githubusercontent.com/119406114/212638180-2466e660-f20c-47eb-adb7-7178376a338a.png">

2023-01-16 09:00 UTC, ice-ares commented on ios/ice/AppDelegate.mm
> +   sdkConfig.moeDataCenter = MODataCenterData_center_02;
So? Switch on env val

2023-01-16 09:01 UTC, ice-ares commented on src/services/datatracking/index.ts
> +import ReactMoE from 'react-native-moengage';
Same thing

2023-01-16 09:10 UTC, ice-hades commented on src/services/datatracking/index.ts
> +export function trackLogout() {
stop what?

2023-01-16 09:11 UTC, ice-ares commented on src/services/datatracking/index.ts
> +export function trackLogout() {
The name of the function

2023-01-16 09:11 UTC, ice-hades commented on src/store/modules/Notifications/hooks/useInitNotifications.tsx
> +        Make sure you are setting the Push/InApp callback listeners before calling the initialize().
we are not currently. just in case we would need them in the future if we need something more than deep link handling

2023-01-16 09:17 UTC, ice-ares commented on src/services/datatracking/index.ts
> +export function trackLogout() {
It doesnt actually logout the user, it just stops the tracking

2023-01-16 09:33 UTC, ice-hades commented on src/services/datatracking/index.ts
> +export function trackLogout() {
it doesn't stop as well. it tracks logout event and continue tracking but events are not bound to any user until we call `setUserUniqueID ` again

2023-01-16 09:36 UTC, ice-hades commented on src/services/datatracking/index.ts
> +  In a scenario where you have to update the User Attribute Unique ID value
for our app maybe we are not. I just added the events while reading the documentation. as you can see those are not called from anywhere yet. 
what about when we need it. like when a user signs out and signs in again but using a different sign in method do we treat it as a new user or just update the user id?

2023-01-16 12:57 UTC, ice-ares commented on src/services/datatracking/index.ts
> +  In a scenario where you have to update the User Attribute Unique ID value
just update the user id

2023-01-18 11:55 UTC, ice-ares commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
Only 3 data centers?

2023-01-18 11:55 UTC, ice-ares commented on ios/ice.xcodeproj/project.pbxproj
> +		CE4746292976D78D00D4F514 /* Debug */ = {
There's alot of stuff here. Are those cuz u run the debug build instead of release?

2023-01-18 11:55 UTC, ice-ares commented on ios/ice/AppDelegate.mm
> +   sdkConfig.appGroupID = @"group.io.ice.app";
Whats that group for?

2023-01-18 12:03 UTC, ice-hades commented on ios/ice/AppDelegate.mm
> +   sdkConfig.appGroupID = @"group.io.ice.app";
moengage rich notifications setup requires to add `App Groups` capability and add some group to be shared between targets (our default ice and a new NotificationServices one)

2023-01-18 12:04 UTC, ice-hades commented on ios/ice.xcodeproj/project.pbxproj
> +		CE4746292976D78D00D4F514 /* Debug */ = {
I need to roll back automatic signing for ios. apart from that everything should be fine

2023-01-18 12:05 UTC, ice-hades commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
yeah, 3

2023-01-18 12:07 UTC, ice-ares commented on src/services/datatracking/index.ts
> +import ReactMoE from 'react-native-moengage';
Did u rename it to analytics?

2023-01-18 12:07 UTC, ice-ares commented on src/services/datatracking/index.ts
> +  In a scenario where you have to update the User Attribute Unique ID value
Did u impl this?

2023-01-18 12:08 UTC, ice-hades commented on src/services/datatracking/index.ts
> +  In a scenario where you have to update the User Attribute Unique ID value
will remove this method in next commit

2023-01-18 12:08 UTC, ice-ares commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
There’s [4](https://help.moengage.com/hc/en-us/articles/360057030512-Data-Centers-in-MoEngage)

2023-01-18 12:11 UTC, ice-hades commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
data center 0 is default one when you don't specify any

2023-01-18 12:11 UTC, ice-hades commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
I see. in your link there are 4. let me check. enums should have only 3

2023-01-18 12:12 UTC, ice-hades commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
```
typedef SWIFT_ENUM(NSInteger, MODataCenter, open) {
  MODataCenterData_center_default = 0,
  MODataCenterData_center_01 = 1,
  MODataCenterData_center_02 = 2,
  MODataCenterData_center_03 = 3,
};

```

2023-01-18 12:12 UTC, ice-ares commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
Add an explicit case for 0 as well

2023-01-18 12:21 UTC, ice-ares commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
Wow, thats strange, pls ask the support about that

2023-01-18 12:23 UTC, ice-hades commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
probably for ios there goes a bit older API when moengage had only 3 data centers. but that version goes with RN package

2023-01-18 12:24 UTC, ice-hades commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_03": {
I added latest version of react-native-moengage

2023-01-18 12:36 UTC, ice-ares commented on android/app/src/main/java/io/ice/app/MainApplication.java
> +      case "DATA_CENTER_01": {
and 0

2023-01-18 12:38 UTC, ice-ares commented on src/services/eventstracking/index.ts
> +import {User} from '@api/user/types';
analytics includes tracking. Rename it to analytics, thats the purpose of the tracking, for analytics.

2023-01-18 12:38 UTC, ice-ares commented on src/services/eventstracking/index.ts
> +
updateUserAttributes

2023-01-18 12:40 UTC, ice-ares commented on src/services/eventstracking/index.ts
> +  if (user.firstName) {
handle the case when u delete ur first & last name

2023-01-18 12:42 UTC, ice-ares commented on src/services/eventstracking/index.ts
> +export function setUserUniqueID(userID: string) {
i think u should get the userId from a selector, and rename this to “startTrackingCurrentUser()”

2023-01-18 12:46 UTC, ice-ares commented on src/store/modules/Account/hooks/useTrackUserInfo.ts
> +      EventsTracking.trackUserAttributes(user);
this should be called on a listener for changes to the user

2023-01-18 12:49 UTC, ice-hades commented on src/services/eventstracking/index.ts
> +export function setUserUniqueID(userID: string) {
Ok. will rename. I get it from the selector.

2023-01-18 12:49 UTC, ice-hades commented on src/store/modules/Account/hooks/useTrackUserInfo.ts
> +      EventsTracking.trackUserAttributes(user);
whenever the user data is changed this will be called. we do it that way on Framey

2023-01-18 12:53 UTC, ice-hector commented on android/settings.gradle
> +project(':react-native-moengage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-moengage/android')
Do we need these 2 lines? Why does it not linked automatically?

2023-01-18 12:54 UTC, ice-hector commented on ios/NotificationService/NotificationService.swift
> +        MORichNotification.setAppGroupID("group.io.ice.app");
Will it work for staging? I assume not. Please specify the app groups depending on ENV

2023-01-18 12:56 UTC, ice-hades commented on ios/NotificationService/NotificationService.swift
> +        MORichNotification.setAppGroupID("group.io.ice.app");
yeah, it will. I could have named it `group.moengage`. Probably should rename it that way not to confuse

2023-01-18 12:57 UTC, ice-hades commented on android/settings.gradle
> +project(':react-native-moengage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-moengage/android')
I can try autolinking. it is just what they have in their guides

2023-01-18 14:52 UTC, ice-hades commented on ios/NotificationService/NotificationService.swift
> +        MORichNotification.setAppGroupID("group.io.ice.app");
renamed to `group.io.ice`

2023-01-18 14:52 UTC, ice-hades commented on ios/NotificationService/NotificationService.swift
> +        MORichNotification.setAppGroupID("group.io.ice.app");
and checked it is building for both envs

2023-01-18 14:52 UTC, ice-hades commented on android/settings.gradle
> +project(':react-native-moengage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-moengage/android')
removed

2023-01-18 14:52 UTC, ice-hades commented on src/services/eventstracking/index.ts
> +  if (user.firstName) {
done

2023-01-18 14:53 UTC, ice-hades commented on src/services/eventstracking/index.ts
> +
done

2023-01-18 14:53 UTC, ice-hades commented on src/services/eventstracking/index.ts
> +import {User} from '@api/user/types';
renamed

2023-01-18 14:53 UTC, ice-hades commented on src/services/datatracking/index.ts
> +import ReactMoE from 'react-native-moengage';
renamed

2023-01-18 15:02 UTC, ice-ares commented on ios/NotificationService/NotificationService.entitlements
> +	<key>com.apple.security.application-groups</key>
should this be in secrets like the other entitlements?

2023-01-18 15:09 UTC, ice-orion commented on src/store/modules/Account/sagas/signOut.ts
> +    stopTrackingCurrentUser();
let's call functions using `call`, so we can test it later on:
`yield call(stopTrackingCurrentUser);`

And let's call `yield put(AccountActions.SIGN_OUT.SUCCESS.create());` at the very end, when all the logout function are done

2023-01-18 15:09 UTC, ice-orion commented on src/services/analytics/index.ts
> +  ReactMoE.logout();
What does `ReactMoE.logout` return? If promise, let's return it:
`return ReactMoE.logout()`

2023-01-18 20:50 UTC, ice-atlas requested changes

2023-01-18 20:50 UTC, ice-atlas commented on android/settings.gradle
> +
Do we really need this in current PR? Usually better have as main changes as possible, only related to PR topic

2023-01-18 20:50 UTC, ice-atlas commented on src/store/modules/Notifications/hooks/useInitNotifications.tsx
> +        Make sure you are setting the Push/InApp callback listeners before calling the initialize().
Better to add link as reference to doc

2023-01-18 20:50 UTC, ice-atlas commented on src/store/modules/Notifications/hooks/useInitNotifications.tsx
> +  React.useEffect(() => {
let's use as `useEffect(...`, same approach as everywhere

2023-01-18 20:50 UTC, ice-atlas commented on src/store/modules/Notifications/hooks/useInitNotifications.tsx
> +    ReactMoE.initialize(ENV.MO_ENGAGE_APP_ID ?? '');
Is it OK to call this method more than once? If permission will change to `granted`?

2023-01-18 20:50 UTC, ice-atlas commented on src/store/modules/Account/hooks/useTrackUserInfo.ts
> +      startTrackingCurrentUser(user.id);
Do we need to `stopTrackingCurrentUser`? `GDPR`, logout?

2023-01-18 20:50 UTC, ice-atlas commented on src/navigation/Main.tsx
> +  useInitNotifications();
Maybe better to have it as saga in business logic layer? What a benefit to use hook instead?
@ice-orion what do u think?

2023-01-18 20:50 UTC, ice-atlas commented on ios/Podfile
> +  reactnative_pods()
Why you do this? How it is relates to `moengage`?

2023-01-19 07:42 UTC, ice-hades commented on ios/NotificationService/NotificationService.entitlements
> +	<key>com.apple.security.application-groups</key>
moved

2023-01-19 07:43 UTC, ice-hades commented on src/services/analytics/index.ts
> +  ReactMoE.logout();
void function

2023-01-19 07:44 UTC, ice-hades commented on android/settings.gradle
> +
nide catch

2023-01-19 07:46 UTC, ice-hades commented on src/store/modules/Account/hooks/useTrackUserInfo.ts
> +      startTrackingCurrentUser(user.id);
it handled seperately

2023-01-19 07:46 UTC, ice-hades commented on src/navigation/Main.tsx
> +  useInitNotifications();
@ice-orion please answer

2023-01-19 08:08 UTC, ice-orion commented on src/navigation/Main.tsx
> +  useInitNotifications();
I would also place everything related to analytics / user tracking in sagas, moreover we will have custom events so we could keep everything in 1 place: initNotifications (content of useInitNotifications) + trackUserInfo (content of useTrackUserInfo) + custom events.

Hooks also work, but in my opinion it would be better to go with sagas as we do in other cases (using hooks only to define listeners)

2023-01-19 08:34 UTC, ice-hades commented on ios/Podfile
> +  reactnative_pods()
done

2023-01-19 08:34 UTC, ice-hades commented on src/store/modules/Notifications/hooks/useInitNotifications.tsx
> +    ReactMoE.initialize(ENV.MO_ENGAGE_APP_ID ?? '');
yep

2023-01-19 08:34 UTC, ice-hades commented on src/store/modules/Notifications/hooks/useInitNotifications.tsx
> +  React.useEffect(() => {
done

2023-01-19 08:55 UTC, ice-hades commented on src/navigation/Main.tsx
> +  useInitNotifications();
@ice-atlas where do you place notifications init? In which saga?

2023-01-19 12:05 UTC, ice-hector commented on .gitignore
> +NotificationService.entitlements
Did you add this file to mobile-app-secrets repo? Same as we did for the general project Plist and entitlements

2023-01-19 12:05 UTC, ice-hector commented on ios/NotificationService/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Please move to mobile-app-secrets repo and add to gitignore (and of course remove from current project)

2023-01-19 12:10 UTC, ice-hades commented on ios/NotificationService/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
I just removed it from there

2023-01-19 12:10 UTC, ice-hades commented on ios/NotificationService/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
and moved back here

2023-01-19 12:12 UTC, ice-hades commented on ios/NotificationService/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
https://frameyapp.slack.com/archives/C0391DUR5GD/p1674113719765129

2023-01-19 12:13 UTC, ice-hades commented on .gitignore
> +NotificationService.entitlements
yep

2023-01-19 13:11 UTC, ice-atlas requested changes

2023-01-19 13:11 UTC, ice-atlas commented on ios/Podfile
> +      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = "NO"
Why we need this? Looks like it is not safe

2023-01-19 13:14 UTC, ice-atlas commented on src/navigation/Main.tsx
> +  useInitNotifications();
Need to agree where to put it, based on the purpose (example `Notifications` module)

2023-01-19 13:15 UTC, ice-hades commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AdHoc io.ice.app.staging";
added it to fix the builds. is it right @ice-orion ?

2023-01-19 14:55 UTC, ice-orion commented on src/navigation/Main.tsx
> +  useInitNotifications();
not really, `Notifications` module is for in-app notifications (get-stream). We currently don't have a module for push-notifications, so i would create one (+ we could handle push notifications interactions there).
As for the `useTrackUserInfo` - we also don't have a module for analytics, so i would also create one for that (+ define custom events there via an action dispatching).

2023-01-19 14:59 UTC, ice-orion commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AdHoc io.ice.app.staging";
Not really, the match profile and cert renewal fixed the build.
Here is we define the default profile for signing the app. So if someone wants to build and install the app on their own device, nothing is needed to be changed. We can leave it blank as it was previously, but we will need to set this 99% of time (cuz we're working with stage usually).
On CI we set this value depending on the env via script, so for CI it doesn't matter what is set here.

2023-01-19 14:59 UTC, ice-hades commented on src/navigation/Main.tsx
> +  useInitNotifications();
for analytics - let's leave them as is for now. it is a glimpse from the next PR I would say. Analytics will come separately later.
for notifications - so I create a new module and call an action from here instead of the hook, that is what you want?

2023-01-19 15:04 UTC, ice-orion commented on ios/NotificationService/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Have you tried [using .xcconfig to define PRODUCT_BUNDLE_IDENTIFIER](https://stackoverflow.com/questions/35230370/how-to-pass-bundle-id-of-extension-as-environment-variable/69007621#69007621)?
Or using `.xcode.env.local` to somehow pass ENV variable  to the `project.pbxproj`?

If it's too complicated, let's write this down to the tech debt and try to improve later

2023-01-19 15:05 UTC, ice-orion commented on ios/NotificationService/Info.plist
> +    <string>io.ice.app.staging.NotificationService</string>
Anyway, we can at least remove `CFBundleIdentifier` from here, since we have it defined in the project.pbxproj

2023-01-19 15:11 UTC, ice-hades commented on ios/NotificationService/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
yep, let's move to tech debt

2023-01-19 15:19 UTC, ice-orion commented on src/navigation/Main.tsx
> +  useInitNotifications();
Notifications module might be exactly the same as Linking module now -
- a hook to subscribe to events and other stuff
- saga for handling interactions (arrival when the app foreground / user presses a push and so on)

Since we don't have interactions now (but we will have it later, as i understood), we could just create a dummy module PushNotifications with only 1 folder - hooks. Place this useInitNotifications hook there and that's it. So later on we could extend it.

@ice-atlas if you have an idea how to rewrite `useInitNotifications` via saga, feel free to suggest.

2023-01-19 15:24 UTC, ice-orion commented on ios/NotificationService/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Ok, could you please add it to the [notion](https://www.notion.so/leftclick/Tech-debt-2a7217b55d77440e8755e239dd21e410) with small description of the problem and possible solutions?

2023-01-19 15:27 UTC, ice-hades commented on ios/NotificationService/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
done

2023-01-19 15:39 UTC, ice-hades commented on ios/NotificationService/Info.plist
> +    <string>io.ice.app.staging.NotificationService</string>
done

2023-01-19 15:39 UTC, ice-hades commented on ios/Podfile
> +      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = "NO"
removed

2023-01-22 09:31 UTC, ice-orion approved these changes

2023-01-22 09:58 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;
Why do we need this boolean set to true? Pls revert

2023-01-22 09:59 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AdHoc io.ice.app.staging";
Remove this, its unneeded, app and extension should be signed and provision profiles should be set automatically on fastlane level, or on CI/CD level

2023-01-22 10:00 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;
Why do we need this boolean set to true? Pls revert

2023-01-22 10:00 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Manual;
Why should we specify it? It should be manual by default

2023-01-22 10:00 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AdHoc io.ice.app.staging";
Remove this, its unneeded, app and extension should be signed and provision profiles should be set automatically on Fastlane level, or on CI/CD level

2023-01-22 10:01 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +		CE4746292976D78D00D4F514 /* Debug */ = {
Pls remove this Debug part

2023-01-22 10:06 UTC, ice-orion commented on ios/ice.xcodeproj/project.pbxproj
> +		CE4746292976D78D00D4F514 /* Debug */ = {
i'm not sure that we need to remove it - this is a configuration for debug builds. We have the same blocks for the main target

2023-01-22 10:07 UTC, ice-orion commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AdHoc io.ice.app.staging";
yea, that was me who suggested to add those, but now i also think that it might be better to leave it blank as it was before

2023-01-22 10:22 UTC, ice-hades commented on ios/ice.xcodeproj/project.pbxproj
> +		CE4746292976D78D00D4F514 /* Debug */ = {
@ice-hector close the tread?

2023-01-22 10:50 UTC, ice-orion approved these changes

2023-01-23 12:05 UTC, ice-orion commented on src/store/modules/Devices/sagas/index.ts
> +        PermissionsActions.GET_PERMISSIONS.SUCCESS.type,
Why? It seems that `updateDeviceMetadataSaga` doesn't rely on permissions

2023-01-23 12:25 UTC, ice-orion commented on src/store/modules/Devices/sagas/index.ts
> +        PermissionsActions.GET_PERMISSIONS.SUCCESS.type,
let's revert this then?

2023-01-23 12:54 UTC, ice-orion approved these changes

2023-01-23 13:00 UTC, ice-hector approved these changes

2023-01-23 13:13 UTC, ice-atlas approved these changes

2023-01-23 13:42 UTC, merged