Balance history and mining-stacking improvements
ice-blockchain/mobile-app pull request #103
Opened 2023-01-17 10:08 UTC by ice-orion

https://www.notion.so/leftclick/Mining-staking-ca0e13ded0e14ac296fd6e51edec2354

https://www.notion.so/leftclick/Balance-history-00507561069f45e58a5b1d1506fe9021

2023-01-17 10:24 UTC, ice-ares commented on src/constants/links.ts
> +  APP_STORE: `https://apps.apple.com/app/${ENV.APPSTORE_APP_ID}`,
Will this work for staging?

2023-01-17 10:24 UTC, ice-ares commented on src/services/audio/index.ts
> +  startMining = 'start_mining.wav',
Bad design. U have a generic service, with specific data

2023-01-17 10:24 UTC, ice-ares commented on src/translations/translations.json
> +            "benefits_description": "Pre-stake your mining rewards for up to 5 years and increase your mining rate by up to 250%",
Parameters!! Never add hardcoded values in translations

2023-01-17 10:24 UTC, ice-ares commented on src/translations/translations.json
> +            "mining_holiday_reset_tooltip": "You are using a Day Off! Press for 3 seconds to reset your mining session",
Parameters!

2023-01-17 10:34 UTC, ice-orion commented on src/constants/links.ts
> +  APP_STORE: `https://apps.apple.com/app/${ENV.APPSTORE_APP_ID}`,
We won't publish the staging app, so on staging it won't find the actual app (but will open the appstore)

2023-01-17 11:27 UTC, ice-orion commented on src/services/audio/index.ts
> +  startMining = 'start_mining.wav',
done, added `src/assets/audio/index.ts` for actual data

2023-01-17 11:27 UTC, ice-orion commented on src/translations/translations.json
> +            "benefits_description": "Pre-stake your mining rewards for up to 5 years and increase your mining rate by up to 250%",
done, `constatns/stacking.ts`

2023-01-17 11:28 UTC, ice-orion commented on src/translations/translations.json
> +            "mining_holiday_reset_tooltip": "You are using a Day Off! Press for 3 seconds to reset your mining session",
done

2023-01-17 11:35 UTC, ice-ares submitted a review, later dismissed

2023-01-18 07:22 UTC, ice-ares submitted a review, later dismissed

2023-01-18 08:17 UTC, ice-hades commented on src/screens/Staking/components/Footer/index.tsx
> +  let termsAgreeText = reactStringReplace(
can you please move it to a function so you don't have to use `let`

2023-01-18 08:18 UTC, ice-hades commented on src/screens/Staking/components/Intro/index.tsx
> +  const onLinkPress = () => {
no need to declare it as an embedded function. it can be declared on a file level

2023-01-18 08:20 UTC, ice-orion commented on src/screens/Staking/components/Footer/index.tsx
> +  let termsAgreeText = reactStringReplace(
What do you mean?

2023-01-18 08:32 UTC, ice-hades commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    if (longPressTimer) {
to my understanding `clearTimer` captures value of `longPressTimer` on the moment of its creation. it won't see any changes to it. what can save here is rerendering and recreation of `clearTimer` with a new latest value of `longPressTimer`. but again, updates to it from `activateLongPress` should not cause any rerenders so I don't see how it works properly. What do you think guys @ice-hector @ice-atlas

2023-01-18 08:33 UTC, ice-hades commented on src/screens/Staking/components/Footer/index.tsx
> +  let termsAgreeText = reactStringReplace(
mean to avoid declaring a `let` and reassigning to it better stick to the functional programming. if you move this termsAgreeText logic to a function you won't need to declare a `let` and reassign to it

2023-01-18 08:39 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    if (longPressTimer) {
>  it won't see any changes to it
Why not? It works fine, i even logged the timer value to make sure :) So any time you start the longPress and drops it, `longPressTimer` has different value (cuz it refers to a different timer)

2023-01-18 08:42 UTC, ice-orion commented on src/screens/Staking/components/Footer/index.tsx
> +  let termsAgreeText = reactStringReplace(
can you give an example?
currently it works like this:
```
let result = doStuff(text, propsA)
result = doStuff(result, propsB)
```

How do you suggest to handle this?

2023-01-18 08:47 UTC, ice-hades commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    if (longPressTimer) {
closures capture current values only. if you want to mutate some value a container is used. Like `const longPressTimerContainer = {current: null};`. But better event to use useRef here to store longPressTimer. as it also will prevent from clearing of `longPressTimer` on rerender.

reassigning variables is on the same level as mutating data objects in terms of possible bugs now or in the future

2023-01-18 08:50 UTC, ice-hades commented on src/screens/Staking/components/Footer/index.tsx
> +  let termsAgreeText = reactStringReplace(
const result = doStuff(text, propsA)
return doStuff(result, propsB)

2023-01-18 08:50 UTC, ice-hades commented on src/screens/Staking/components/Footer/index.tsx
> +  let termsAgreeText = reactStringReplace(
you can keep it here. main concern is `let`

2023-01-18 08:52 UTC, ice-hector commented on src/components/CheckBox/index.tsx
> +  value: boolean;
value? Rename please to `isActive`

2023-01-18 08:55 UTC, ice-hector commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    <GestureDetector gesture={longPressActivation ? longTap : singleTap}>
isLongPressActivated

2023-01-18 08:56 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    if (longPressTimer) {
> closures capture current values only.

Here is what happens there

<img width="364" alt="image" src="https://user-images.githubusercontent.com/102020833/213125993-f70e67bf-4ab9-415a-9296-3098c8fd1865.png">

2023-01-18 08:58 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    if (longPressTimer) {
So closures use a memory reference to a variable, so you always have the correct value

2023-01-18 08:59 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    if (longPressTimer) {
You're probably confusing it with passing a primitive as an arg?

<img width="341" alt="image" src="https://user-images.githubusercontent.com/102020833/213127722-12953193-5196-4ac8-aa75-4256dc6946b0.png">

2023-01-18 09:05 UTC, ice-hades commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    if (longPressTimer) {
you are right, it works

2023-01-18 09:08 UTC, ice-orion commented on src/components/CheckBox/index.tsx
> +  value: boolean;
I took it from the RN naming of the similar component - https://reactnative.dev/docs/switch#value
We also have a custom `Switch` component and we're using name `value` for this prop here and there - i would say it's pretty common

2023-01-18 09:09 UTC, ice-hector commented on src/utils/device.ts
> +  return InAppBrowser.open(url, {
How does it handle the navigation stacks? Or it just opens over everything?

2023-01-18 09:10 UTC, ice-orion commented on src/screens/Staking/components/Footer/index.tsx
> +  let termsAgreeText = reactStringReplace(
done

2023-01-18 09:10 UTC, ice-orion commented on src/screens/Staking/components/Intro/index.tsx
> +  const onLinkPress = () => {
done

2023-01-18 09:11 UTC, ice-orion commented on src/utils/device.ts
> +  return InAppBrowser.open(url, {
yea, it works like a modal or something, so it has nothing to do with our main navigation

2023-01-18 09:27 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    <GestureDetector gesture={longPressActivation ? longTap : singleTap}>
I would suggest you to reconsider using `is` as prefix for boolean values everywhere (Hungarian notation that is pretty much dead). It is redundant when type-checking is done by the compiler + nowhere in react-native this notation is used (e.g. take a look at boolean props from FlatList - `refreshing`, `inverted`, boolean props from reanimated `AnimationCallback->finished`, react-navigation `LinkingOptions->enabled` and so on).

Sometimes i also add this prefix for const variables for some reason :) But my point is that it is not something required at all...

2023-01-18 09:30 UTC, ice-ares approved these changes

2023-01-18 09:36 UTC, ice-hector commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    <GestureDetector gesture={longPressActivation ? longTap : singleTap}>
Yeah, you are right, but refreshing is a process, inverted means should it be done or not (don't know how to explain it correctly). In your case you use `activation` it's a simple noun that does not reflect the meaning of what it does.
Would it be better to add suffix -ed to activated like `longPressActivated`? 
`-ed is added to nouns to form adjectives that describe someone or something as having a particular feature or features`

2023-01-18 09:39 UTC, ice-hector commented on src/components/CheckBox/index.tsx
> +  value: boolean;
Yeah, I also agree but in the scope of CheckBox as I see from the context it is Active or Not active (and related to design). In this case when we name it `value` it is not at all clear what the meaning of this `value` inside the CheckBox (without reading the implementation inside)

2023-01-18 09:43 UTC, ice-hades submitted a review, later dismissed

2023-01-18 09:44 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButtonHandlers.tsx
> +    <GestureDetector gesture={longPressActivation ? longTap : singleTap}>
Well, as for this particular case - this variable belongs to some mining stage. It describes how this particular step might be activated (meaning this boolean describes a step rather than keeping that something  is happened or not).
If it would have been for keeping that activation is happened or not, then yea, it had been fine to name it  `longPressActivated `

2023-01-18 09:56 UTC, ice-orion commented on src/components/CheckBox/index.tsx
> +  value: boolean;
Would it be fine if we named it `checked` (like in react-native-elements)?

2023-01-18 10:07 UTC, ice-ares approved these changes

2023-01-18 10:26 UTC, ice-hades approved these changes

2023-01-18 10:41 UTC, merged

2023-01-18 10:52 UTC, ice-atlas requested changes

2023-01-18 10:52 UTC, ice-atlas commented on src/translations/translations.json
> +            "pre_staking": "https://ice.io/pre-staking/",
Do we really want to have links in translations?

2023-01-18 10:56 UTC, ice-orion commented on src/assets/svg/SettingsIcons.tsx
>  export const SettingsIcon = ({fill = COLORS.white}: Props) => (
fixed, will be in the next pr

2023-01-18 11:04 UTC, ice-orion commented on src/constants/links.ts
> +  PRIVACY: t('links.privacy'),
this is a topic to discuss

2023-01-18 11:05 UTC, ice-orion commented on src/constants/staking.ts
> +
this is a topic to discuss

2023-01-18 11:05 UTC, ice-orion commented on src/translations/translations.json
> +            "pre_staking": "https://ice.io/pre-staking/",
this is a topic to discuss

2023-01-18 11:26 UTC, ice-ares commented on src/constants/staking.ts
> +
We’ll bother with that later, but yea, we’ll have everything fetched from BE