mining button api
ice-blockchain/mobile-app pull request #104
Opened 2023-01-19 08:47 UTC by ice-orion

2023-01-21 12:16 UTC, ice-ares commented on src/api/tokenomics/types.ts
> +  endedAt: string;
Cant u use some sort of date type for those?

2023-01-21 12:16 UTC, ice-ares commented on src/store/modules/Tokenomics/selectors/index.ts
> +    return 'undefined';
We might need to add some ❗️ icon to that gray state to differentiate loading gray from error gray

2023-01-21 12:16 UTC, ice-ares commented on src/store/modules/Tokenomics/selectors/index.ts
> +  if (dayjs(miningSession.warnAboutExpirationStartingAt).isBefore(Date.now())) {
Only dayjs

2023-01-22 11:14 UTC, ice-ares commented on src/store/modules/Tokenomics/selectors/index.ts
> +    Date.now() - (state.tokenomics.balanceSummaryUpdateTimestamp ?? 0) >
Dayjs

2023-01-22 12:57 UTC, ice-ares commented on src/api/tokenomics/types.ts
> +  total: string;
Add totalReferrals as well

2023-01-22 12:57 UTC, ice-ares commented on src/navigation/components/MainTabBar/components/MiningTooltip/index.tsx
> +      <MiningInfo timeLeft={timeLeft} rate={`+${miningRates?.total.amount}`} />
I think we should add - or + based on miningSession being null or not

2023-01-22 12:57 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +          number={`+${miningRates?.total.amount}`}
Same thing everywhere: add the sign based if user's mining or not

2023-01-22 12:57 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/LadderBar/index.tsx
> +    const refNumber =
I think u have a selector for that

2023-01-22 12:57 UTC, ice-ares commented on src/screens/Team/components/Header/components/Info/index.tsx
> +              number={balanceSummary?.total ?? '0'}
U can use the correct one even if its not returned yet

2023-01-22 12:57 UTC, ice-ares commented on src/screens/Team/components/TierList/components/Header/index.tsx
> +          {`${title}: ${miningRate} `}
Whats this for?

2023-01-22 12:57 UTC, ice-ares commented on src/screens/Team/components/TierList/index.tsx
> +            balanceSummary?.[referralType === 'T1' ? 't1' : 't2'] ?? '0'
U can just to lowercase the referraltype

2023-01-22 13:08 UTC, ice-hades commented on ios/NotificationService/NotificationService.entitlements
> +</plist>
please remove the file

2023-01-22 13:12 UTC, ice-hades commented on src/navigation/components/MainTabBar/components/MiningTooltip/index.tsx
> +      <MiningInfo timeLeft={timeLeft} rate={`+${miningRates?.total.amount}`} />
`+undefined` will be displayed if `miningRates` is undefined

2023-01-22 13:18 UTC, ice-hades commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +          number={`+${miningRates?.total.amount}`}
'+undefined'

2023-01-22 13:19 UTC, ice-hades commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +    //TODO: add loading
do we need it? Maybe just display `0` ?

2023-01-22 19:06 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +    //TODO: add loading
yep, we need some sort of inline loading indicator

2023-01-22 19:07 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +          number={`+${miningRates?.total.amount}`}
not possible, miningRates?.total.amount is always present

2023-01-22 19:07 UTC, ice-ares commented on src/navigation/components/MainTabBar/components/MiningTooltip/index.tsx
> +      <MiningInfo timeLeft={timeLeft} rate={`+${miningRates?.total.amount}`} />
miningRates?.total.amount is always present

2023-01-23 06:48 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +    //TODO: add loading
we have a design for that but it's not implemented yet - 
<img width="279" alt="image" src="https://user-images.githubusercontent.com/102020833/213980518-40d81921-c0e8-4aee-b110-c18e1ad57513.png">

2023-01-23 07:23 UTC, ice-orion commented on src/api/tokenomics/types.ts
> +  endedAt: string;
unfortunately not, from ts perspective it's just a string

2023-01-23 07:24 UTC, ice-orion commented on src/store/modules/Tokenomics/selectors/index.ts
> +  if (dayjs(miningSession.warnAboutExpirationStartingAt).isBefore(Date.now())) {
done

2023-01-23 07:24 UTC, ice-orion commented on src/store/modules/Tokenomics/selectors/index.ts
> +    Date.now() - (state.tokenomics.balanceSummaryUpdateTimestamp ?? 0) >
done

2023-01-23 07:24 UTC, ice-orion commented on src/api/tokenomics/types.ts
> +  total: string;
done

2023-01-23 07:27 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/MiningTooltip/index.tsx
> +      <MiningInfo timeLeft={timeLeft} rate={`+${miningRates?.total.amount}`} />
Sign is handled
`miningRates` is really always not undefined there, so i removed the optional chaining

2023-01-23 07:27 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +          number={`+${miningRates?.total.amount}`}
Sign is handled
miningRates is really always not undefined there, so i removed the optional chaining

2023-01-23 07:28 UTC, ice-orion commented on src/screens/Team/components/Header/components/Info/index.tsx
> +              number={balanceSummary?.total ?? '0'}
done

2023-01-23 07:29 UTC, ice-orion commented on src/screens/Team/components/TierList/components/Header/index.tsx
> +          {`${title}: ${miningRate} `}
This is this part

<img width="392" alt="Screenshot 2023-01-23 at 11 28 43" src="https://user-images.githubusercontent.com/102020833/213986199-330fae98-a6dd-44f9-9c43-c6019de85858.png">

2023-01-23 07:30 UTC, ice-orion commented on ios/NotificationService/NotificationService.entitlements
> +</plist>
done

2023-01-23 07:38 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/LadderBar/index.tsx
> +    const refNumber =
Yea we have a selector for the own user, but here we have to calculate refNumber of a user that we pass as param (might be someone else's profile). By the way - we also need to get "glabal rank" and "level" for that (not own) user.  Will we need to perform [/tokenomics/{userId}/ranking-summary](https://staging.r.api.ice.io/tokenomics/r/swagger/index.html#/Tokenomics/get_tokenomics__userId__ranking_summary) for that?

2023-01-23 07:39 UTC, ice-orion commented on src/screens/Team/components/TierList/index.tsx
> +            balanceSummary?.[referralType === 'T1' ? 't1' : 't2'] ?? '0'
Well, yea this is the first thing i tried, but `referralType` contains also `TO` and `CONTACTS` so just lowercase doesn't work here since `balanceSummary` contains only `t1` and `t2`

2023-01-24 11:13 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/startMiningSession.ts
> +    yield call(confirmResurrect, params);
both buttons have the exact same logic. they only differ in the resurrect flag value

2023-01-24 11:13 UTC, ice-ares commented on src/store/modules/Tokenomics/selectors/index.ts
> +export const miningSummaryUpdateAvailableSelector = (
the same thing goes for ranking summary and adoption

2023-01-24 11:13 UTC, ice-ares commented on src/translations/translations.json
> +      "resurrection_no_confirm_message": "You will lose your [[:amount]] coins forever. Are you sure you want to continue?",
lets use the same pattern as with translations params, which is {{amount}} i think

2023-01-24 11:13 UTC, ice-ares commented on src/store/modules/Tokenomics/utils/openConfirmResurrect.tsx
> +        {params.amount}
the amount's gonna be with 9 decimals, u have to display 2

2023-01-27 12:50 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/components/AdoptionCard/components/LevelRow.tsx
> +              <Text style={styles.valueText}>{`${item.baseMiningRate}/h`}</Text>
those /h have to be i18ned

2023-01-27 12:50 UTC, ice-ares commented on src/store/modules/Stats/sagas/getAdoption.ts
> +export function* getAdoptionSaga() {
this should be called in the background just like mining summary, balance summary ,etc

2023-01-29 12:57 UTC, ice-ares commented on src/api/client/index.ts
> +  queryParams?: {[key: string]: unknown},
what other type is there?

2023-01-29 12:57 UTC, ice-ares commented on src/api/tokenomics/startPreStaking.ts
> +export function startPreStaking({userId, allocation, years}: Params) {
startOrUpdate

2023-01-29 12:57 UTC, ice-ares commented on src/screens/Staking/components/Calculator/hooks/useCalculatorSliderValues.ts
> +  const availableYearsPercentage =
where are u using these percentages?

2023-01-29 12:57 UTC, ice-ares commented on src/screens/Staking/hooks/usePreStakingCalculator.ts
> +      const miningRate =
did u check if u're losing precision here?

2023-01-29 12:57 UTC, ice-ares commented on src/store/modules/Tokenomics/reducer/index.ts
> +        draft.manualUpdateTimestamp = Date.now();
dayjs all the time

2023-01-29 12:57 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/getBalanceHistory.ts
> +      const startDate = dayjs(start).toISOString();
are start and end with local tz?

2023-01-29 12:57 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/getBalanceHistory.ts
> +      const endDate = dayjs(end).toISOString();
is end always before start?

2023-01-29 12:57 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/getRankingSummary.ts
> +  } catch (error) {
make sure u retry with backpressure if 404 & user not found, for all api calls in tokenomics

2023-01-29 12:57 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/manualUpdate.ts
> +    showError(errorMessage);
don't show any error

2023-01-29 12:57 UTC, ice-ares commented on src/utils/numbers.ts
> +  return parseInt(input.replace(/,/g, ''), 10);
thats actually a float

2023-01-30 11:39 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/getBalanceHistory.ts
> +      const startDate = dayjs(start).add(1, 'd').subtract(1, 's').format();
why are u adding a day?

2023-01-30 14:09 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/LadderBar/index.tsx
> +    const refNumber =
global rank implemented

2023-01-30 14:10 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/MiningTooltip/index.tsx
> +        rate={`${isMiningActive ? '+' : '-'}${miningRates.total.amount}`}
`formatNumber` is used here

2023-01-30 14:14 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/startMiningSession.ts
> +    yield call(confirmResurrect, params);
not really understood what do you mean - this part is for the second step of the resurrection flow, where we show the confirmation warning and yes both flows end up as one logic and different flag (the `if (warningConfirmResult === 'yes')` condition part) and we're going back to the main confirmation if user changed his mind.

```
if (warningConfirmResult === 'yes') {
    yield put(
      TokenomicsActions.START_MINING_SESSION.START.create({
        resurrect: mainConfirmResult === 'yes',
      }), // user confirmed resurrect or not-resurrect 
    );
  } else {
    yield call(confirmResurrect, params); // here we're going back to the main confirm
  }
  ```

2023-01-30 14:14 UTC, ice-orion commented on src/store/modules/Tokenomics/selectors/index.ts
> +export const miningSummaryUpdateAvailableSelector = (
pull-to refresh handled in different way, but ranking summary and adoption are updated there

2023-01-30 14:15 UTC, ice-orion commented on src/translations/translations.json
> +      "resurrection_no_confirm_message": "You will lose your [[:amount]] coins forever. Are you sure you want to continue?",
discussed, [[:tags]] are used for markdown in translations

2023-01-30 14:15 UTC, ice-orion commented on src/store/modules/Tokenomics/utils/openConfirmResurrect.tsx
> +        {params.amount}
handled by using `formatNumber` util

2023-01-30 14:17 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/startMiningSession.ts
> +    yield call(confirmResurrect, params);
yea, I forgot there are 2 modals there. nvm

2023-01-30 14:20 UTC, ice-ares commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AdHoc io.ice.app.staging";
whats app with these?

2023-01-30 14:20 UTC, ice-ares commented on ios/ice.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
> +<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
whats app with these?

2023-01-30 14:22 UTC, ice-orion commented on src/store/modules/Stats/sagas/getAdoption.ts
> +export function* getAdoptionSaga() {
yea, i is called by interval

2023-01-30 14:24 UTC, ice-orion commented on src/api/client/index.ts
> +  queryParams?: {[key: string]: unknown},
we can pass null / undefined there, `axios` handles that fine (in this case the params are not added to the final query string)

2023-01-30 14:26 UTC, ice-orion commented on src/screens/Staking/components/Calculator/hooks/useCalculatorSliderValues.ts
> +  const availableYearsPercentage =
this is the percentage of the slider that you can interact with:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/102020833/215503875-6753a1ef-6418-4fd9-ac12-24f9c7ccf59c.png">
here the availableYearsPercentage is `50`

2023-01-30 14:26 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/getBalanceHistory.ts
> +      const endDate = dayjs(end).toISOString();
yea, checked that

2023-01-30 14:26 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/manualUpdate.ts
> +    showError(errorMessage);
done

2023-01-30 14:26 UTC, ice-orion commented on src/utils/numbers.ts
> +  return parseInt(input.replace(/,/g, ''), 10);
fixed

2023-01-30 14:30 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/getRankingSummary.ts
> +  } catch (error) {
only if userID is the user logged in

2023-01-30 14:31 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/getBalanceHistory.ts
> +      const startDate = dayjs(start).add(1, 'd').subtract(1, 's').format();
E.g. we want to show history for 2 days (start and end are just days - without time):
```
const start = '13-10-2023'
const end = '12-10-2023'
```

So in terms of time it should be:
```
const startDate = '2023-13-11T23:59:59+04:00'; // to get this i add a day and subtract a second
const endDate = '2023-12-10T00:00:00+04:00'
```

2023-01-30 14:31 UTC, ice-orion commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AdHoc io.ice.app.staging";
i will clean this up

2023-01-30 14:31 UTC, ice-orion commented on ios/ice.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
> +<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
i will clean this up

2023-01-30 14:32 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/getRankingSummary.ts
> +  } catch (error) {
and handle the case where user hide the ranking from privacy 403 + GLOBAL_RANK_HIDDEN

2023-01-30 14:32 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/getBalanceHistory.ts
> +      const startDate = dayjs(start).toISOString();
yes, `dayjs().format()` is used that return ISO string with local tz

2023-01-30 14:33 UTC, ice-ares commented on src/api/client/index.ts
> +  queryParams?: {[key: string]: unknown},
then declare em explicitly `string | number | null | undefined`

2023-01-30 14:44 UTC, ice-orion commented on src/api/tokenomics/startPreStaking.ts
> +export function startPreStaking({userId, allocation, years}: Params) {
done

2023-01-30 14:49 UTC, ice-orion commented on src/api/client/index.ts
> +  queryParams?: {[key: string]: unknown},
done

2023-01-30 15:03 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/components/AdoptionCard/components/LevelRow.tsx
> +              <Text style={styles.valueText}>{`${item.baseMiningRate}/h`}</Text>
done

2023-01-30 22:39 UTC, ice-ares commented on src/screens/Staking/hooks/usePreStakingCalculator.ts
> +      const totalMiningRate = parseNumber(miningRates.total.amount);
miningRates.totalNoPreStakingBonus.amount

2023-02-01 07:27 UTC, ice-orion commented on src/screens/Staking/hooks/usePreStakingCalculator.ts
> +      const totalMiningRate = parseNumber(miningRates.total.amount);
done

2023-02-01 11:23 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/getBalanceHistory.ts
> +      const startDate = dayjs(start).add(1, 'd').subtract(1, 's').format();
discussed, this part is changed according to comment + for calendar dates this logic with +day - 1 sec is applied

2023-02-01 13:41 UTC, ice-atlas requested changes

2023-02-01 13:41 UTC, ice-atlas commented on src/assets/svg/SettingsIcons.tsx
> +export const SettingsIcon = ({color = COLORS.white}: SvgProps) => (
How to set `width` and `height`?

2023-02-01 13:41 UTC, ice-atlas commented on src/navigation/components/MainTabBar/components/MiningTooltip/index.tsx
> +    navigation.goBack();
I think, it is better to place it under `useEffect`. Not in render definitely

2023-02-01 15:37 UTC, ice-hades approved these changes

2023-02-01 15:56 UTC, ice-atlas requested changes

2023-02-01 15:56 UTC, ice-atlas commented on src/navigation/hooks/useUpdateRequiredListener.tsx
> +  ) {
use `useEffect` for this

2023-02-01 15:56 UTC, ice-atlas commented on src/navigation/hooks/useUpdateSuccessfulListener.tsx
> +  navigation.navigate('PopUp', {
same about `useEffect`

2023-02-01 16:10 UTC, ice-hector commented on src/navigation/components/MainTabBar/components/MiningTooltip/components/PreStakingInfo.tsx
> +        <Text style={styles.bonusValueText}>+{preStakingSummary?.bonus}%</Text>
Such % location will not work with RTL

2023-02-01 16:19 UTC, ice-hector commented on src/screens/HomeFlow/BalanceHistory/components/HistoryList/hooks/useGetHistorySections.ts
> +    setSections([]);
Should we set sections to an empty array before we get success / failed result from GET_BALANCE_HISTORY ?

2023-02-01 16:41 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Overview/components/AdoptionCard/index.tsx
> +      sharedItems.value = viewableItems.map(i => ({...i, item: {...i.item}}));
Let's not use one-letter naming. and index generally also looks like `i` so not clear.

2023-02-01 16:43 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +          number={`${miningSign}${formatNumberString(
What about rtl?

2023-02-01 17:00 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +            +
Pls check rtl results with google translate version of same text

2023-02-01 17:00 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +            +{miningRates.total.bonuses?.extra ?? 0}%
Pls check rtl results with google translate version of same text

2023-02-01 17:00 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +            +{miningRates.total.bonuses?.preStaking ?? 0}%
Pls check rtl results with google translate version of same text

2023-02-01 17:04 UTC, ice-hector commented on src/screens/Modals/PopUp/components/PopUpButton/index.tsx
> +  button_outlined: {
Lets use one style naming format in styles `buttonOutlined`

2023-02-01 17:04 UTC, ice-hector commented on src/screens/Modals/PopUp/components/PopUpButton/index.tsx
> +  labelText_outlined: {
labelTextOutlined

2023-02-01 17:04 UTC, ice-hector commented on src/screens/Modals/PopUp/components/PopUpButton/index.tsx
> +  labelText_destructive: {
labelTextDestructive

2023-02-01 17:07 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/hooks/useMiningCalculator.ts
> +          ((tierOneValue * 0.25 + tierTwoValue * 0.05) * activeMinersPerc) /
Add please some comment there with explantation for this formula/calculations

2023-02-01 17:07 UTC, ice-hector commented on src/screens/Staking/components/Calculator/index.tsx
> +                {calculatedResults ? ` (+${calculatedResults.bonus}%)` : ''}
Same here, check rtl pls

2023-02-01 17:12 UTC, ice-hector commented on src/screens/Staking/components/Calculator/index.tsx
> +            <IceLabel iconSize={14} label={t('general.ice_per_hour')} />
I'm thinking if we can use replaceString here after merging my progress with translations?

2023-02-01 19:16 UTC, ice-atlas requested changes

2023-02-01 19:16 UTC, ice-atlas commented on src/utils/numbers.ts
> +    formatters[key] = Intl.NumberFormat('en', {
Do we need to respect `locale` here?

2023-02-01 19:16 UTC, ice-atlas commented on src/utils/date.ts
> +    {value: duration.hours(), unit: t('general.hours_short')},
Based on localization doc it should be `general.hoursShort`. Check other places

2023-02-02 07:28 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/MiningTooltip/components/PreStakingInfo.tsx
> +        <Text style={styles.bonusValueText}>+{preStakingSummary?.bonus}%</Text>
Have you tried to enable RTL? The whole app is currently not working with it. I think we'll need to dedicate some time, research how to make it and then change / improve the markdown so it supports RTL. 
As for this particular case: what do you suggest?

2023-02-02 07:32 UTC, ice-orion commented on src/screens/HomeFlow/BalanceHistory/components/HistoryList/hooks/useGetHistorySections.ts
> +    setSections([]);
Yea, as soon as you select a different filter, you shouldn't see the results for the previous filter (you see the loading actually)

2023-02-02 07:36 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +          number={`${miningSign}${formatNumberString(
https://github.com/ice-blockchain/mobile-app/pull/104#discussion_r1094134331

2023-02-02 07:36 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +            +{miningRates.total.bonuses?.extra ?? 0}%
https://github.com/ice-blockchain/mobile-app/pull/104#discussion_r1094134331

2023-02-02 07:36 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> +            +{miningRates.total.bonuses?.preStaking ?? 0}%
https://github.com/ice-blockchain/mobile-app/pull/104#discussion_r1094134331

2023-02-02 07:38 UTC, ice-orion commented on src/screens/Staking/components/Calculator/index.tsx
> +                {calculatedResults ? ` (+${calculatedResults.bonus}%)` : ''}
https://github.com/ice-blockchain/mobile-app/pull/104#discussion_r1094134331

2023-02-02 07:39 UTC, ice-orion commented on src/assets/svg/SettingsIcons.tsx
> +export const SettingsIcon = ({color = COLORS.white}: SvgProps) => (
fixed

2023-02-02 07:39 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/MiningTooltip/index.tsx
> +    navigation.goBack();
done

2023-02-02 07:40 UTC, ice-orion commented on src/navigation/hooks/useUpdateRequiredListener.tsx
> +  ) {
done

2023-02-02 07:40 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/components/AdoptionCard/index.tsx
> +      sharedItems.value = viewableItems.map(i => ({...i, item: {...i.item}}));
done

2023-02-02 07:41 UTC, ice-orion commented on src/navigation/hooks/useUpdateSuccessfulListener.tsx
> +  navigation.navigate('PopUp', {
done

2023-02-02 07:41 UTC, ice-orion commented on src/screens/Modals/PopUp/components/PopUpButton/index.tsx
> +  button_outlined: {
done

2023-02-02 07:41 UTC, ice-orion commented on src/screens/Modals/PopUp/components/PopUpButton/index.tsx
> +  labelText_outlined: {
done

2023-02-02 07:41 UTC, ice-orion commented on src/screens/Modals/PopUp/components/PopUpButton/index.tsx
> +  labelText_destructive: {
done

2023-02-02 07:50 UTC, ice-orion commented on src/screens/Staking/components/Calculator/index.tsx
> +            <IceLabel iconSize={14} label={t('general.ice_per_hour')} />
I think it's pretty clear what "Current rate" means here even without the variables in translations. This is a general stuff that can be user somewhere else and doesn't require context to understand. Just like "Mining rate" or "Staked Period"

2023-02-02 07:53 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/components/Calculator.tsx
> -                  {result}{' '}
nope, you can't use markdown in string templates, js will call 'toString()' and you'll get `[object Object]` instead of markdown

2023-02-02 07:59 UTC, ice-orion commented on src/utils/date.ts
> +    {value: duration.hours(), unit: t('general.hours_short')},
Why so? We're using snake_case everywhere in translation file and in the [doc](https://www.notion.so/leftclick/Localization-rules-1c6a80eb00c1499da8927f9bd3067558) `empty_title` is used as example. @ice-hector but in the same file `nickname.textInput.placeholder` is used, i think it should be `nickname.text_input.placeholder`

2023-02-02 08:01 UTC, ice-orion commented on src/screens/Staking/components/Intro/index.tsx
> +        ratePercentages: MAX_STAKING_RATE_PERCENTAGES,
done

2023-02-02 08:10 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/getMiningSummary.ts
> +    if (isAuthorized && isAppActive) {
It's not an error. If we throw it here, we'll get a lot of false positive logged sentry errors. Actually the only case when no Success and no Failed actions would be dispatched here is when we run this saga on AppStateChange / UserStateChange and in those cases we don't need to track end states (for loading for example)

2023-02-02 08:11 UTC, ice-orion commented on src/utils/numbers.ts
> +    formatters[key] = Intl.NumberFormat('en', {
This is the only one supported atm. And i think we'll have to rewrite this function in the future cuz it doesn't support 'compact' formatting on iOS

2023-02-02 08:34 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/hooks/useMiningCalculator.ts
> +          ((tierOneValue * 0.25 + tierTwoValue * 0.05) * activeMinersPerc) /
Added calculateMiningRate and calculateStakingBonus util functions. I don't really think that a comment will make these functions more understandable. Or if you have suggestion for the comment, please write, i'll add it

2023-02-02 10:20 UTC, ice-ares approved these changes

2023-02-02 10:22 UTC, ice-hector approved these changes

2023-02-02 11:07 UTC, ice-atlas approved these changes

2023-02-02 11:07 UTC, merged