News screen
ice-blockchain/mobile-app pull request #113
Opened 2023-01-25 17:57 UTC by ice-atlas

2023-01-25 18:46 UTC, ice-ares requested changes

2023-01-25 18:46 UTC, ice-ares commented on src/api/news/types.ts
> +  updatedAt: string;
U dont need this

2023-01-25 18:46 UTC, ice-ares commented on src/screens/News/components/FeaturedPost/index.tsx
> +    openLinkWithInAppBrowser({
If !viewed{
Mark it as viewed
 If error, log it, but dont show it
}
Open in app browser.


This is the logic for all of em, featured one and any regular ones

2023-01-25 18:46 UTC, ice-ares commented on src/screens/News/components/FeaturedPost/index.tsx
> +          <Text style={styles.updatedAt}>{`${views} ${t('news.views')}`}</Text>
Nope, its based on createdAt

2023-01-25 18:46 UTC, ice-ares commented on src/screens/News/components/Post/index.tsx
> +  postId: string;
Its not any kind of post, its a subset type of posts, called news. So name everything news, not posts

2023-01-25 18:46 UTC, ice-ares commented on src/screens/News/components/Post/index.tsx
> +                ? t('news.today')
Can we recycle those duration transactions? Cuz the are the same for all screens

2023-01-25 18:46 UTC, ice-ares commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +const LIMIT = 20;
10, enough for 2 viewports

2023-01-25 18:46 UTC, ice-ares commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +        offset: isRefresh ? 0 : newsIds.length,
Why not store the counter instead of the array of ids?

2023-01-25 18:46 UTC, ice-ares commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +        language: appLocale,
use the one from device settings

2023-01-25 18:46 UTC, ice-ares commented on src/store/modules/News/sagas/loadUnreadNewsCountSaga.ts
> +        language: appLocale,
Same here

2023-01-25 18:46 UTC, ice-ares commented on src/store/modules/News/sagas/loadUnreadNewsCountSaga.ts
> +export function* loadUnreadNewsCountSaga() {
This should be called every 5 minutes and after every mark viewed response

2023-01-25 18:46 UTC, ice-ares commented on src/store/modules/News/selectors/getNewsIds.ts
> +        new Date(newsById[postBId].createdAt).getTime() -
Why do u need to sort em? And why do u need em?

2023-01-25 18:46 UTC, ice-ares commented on src/store/modules/News/selectors/getRecentFeaturedNewsPost.ts
> +export const getRecentFeaturedNewsPost = createSelector(
Nope, you dont worry about that. You'll always get an array of 1 elem when querying for featured news

2023-01-25 18:46 UTC, ice-ares commented on src/translations/i18n.ts
> +export type SupportedLocale = keyof typeof locales;
This is nice to have, keep it, but dont use it

2023-01-26 11:11 UTC, ice-atlas commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +        language: appLocale,
This values contains current locale of the app (selected by user or automatically)

2023-01-26 11:11 UTC, ice-atlas commented on src/store/modules/News/sagas/loadUnreadNewsCountSaga.ts
> +        language: appLocale,
https://github.com/ice-blockchain/mobile-app/pull/113#discussion_r1087704802

2023-01-26 11:14 UTC, ice-ares commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +        language: appLocale,
@ice-orion is that true? If I modify the language in settings, will the value here be updated?

2023-01-26 11:19 UTC, ice-orion commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +        language: appLocale,
discussed with @ice-atlas

2023-01-26 11:24 UTC, ice-ares commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +        language: appLocale,
Great, that was my concern

2023-01-26 11:33 UTC, ice-atlas commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +        offset: isRefresh ? 0 : newsIds.length,
Ids are used for presentation of list on UI. Just easy to get count from it

2023-01-26 11:33 UTC, ice-atlas commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +        language: appLocale,
Oh, now I see. Thnx!

2023-01-26 16:32 UTC, ice-ares commented on src/api/statistics/getTopMiners.ts
> +    createdAt: '2022-01-03T16:20:52.156534Z',
why do u need this here?

2023-01-26 16:37 UTC, ice-ares commented on src/services/dayjs/index.ts
> +switch (appLocale) {
why not 
```
require(`dayjs/locale/${appLocale}`)
```
?

2023-01-26 16:39 UTC, ice-ares commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +  const language = deviceSettings?.language ?? appLocale;
deviceSettings?.language should never ever be undefined

2023-01-26 16:40 UTC, ice-ares commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +      featuredNewsArticle = featuredNews[0];
featuredNews.?[0] just to be safe

2023-01-27 09:05 UTC, ice-atlas commented on src/api/statistics/getTopMiners.ts
> +    createdAt: '2022-01-03T16:20:52.156534Z',
`Miner` extends `User`. I added `createdAt` to `User` type.

2023-01-27 09:06 UTC, ice-atlas commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +  const language = deviceSettings?.language ?? appLocale;
But currently by types it can be, so just added fallback to fix linter

2023-01-27 09:07 UTC, ice-atlas commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +      featuredNewsArticle = featuredNews[0];
so it is possible to get `200` and `null` (not just empty array as by design)?

2023-01-27 09:21 UTC, ice-ares commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +      featuredNewsArticle = featuredNews[0];
no, u're gonna get an array of 1 or an empty array (unexpected)

2023-01-27 13:59 UTC, ice-atlas commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +      featuredNewsArticle = featuredNews[0];
then `featuredNews` always array for `200`, so nothing to worry about

2023-01-27 14:33 UTC, ice-atlas commented on src/services/dayjs/index.ts
> +switch (appLocale) {
dynamic require does not work in RN

2023-01-27 16:33 UTC, ice-ares commented on src/screens/News/hooks/useNewsBrowser.ts
> +          NewsActions.NEWS_ARTICLE_MARK_VIEWED(newsArticle.id).START.create({
isn't it redundant to have newsArticle.id twice?

2023-01-27 16:35 UTC, ice-ares commented on src/store/modules/News/sagas/markViewedNewsArticleSaga.ts
> +    logError(error);
I think the error is logged automatically if u throw it, right @ice-orion ?

2023-01-27 16:57 UTC, ice-atlas commented on src/screens/News/hooks/useNewsBrowser.ts
> +          NewsActions.NEWS_ARTICLE_MARK_VIEWED(newsArticle.id).START.create({
Agree for 100%, but it is required redesign of action Creator itself (not so easy for now). We will do it later
https://github.com/ice-blockchain/mobile-app/pull/92#discussion_r1060413373

2023-01-30 07:55 UTC, ice-orion commented on src/store/modules/News/sagas/markViewedNewsArticleSaga.ts
> +    logError(error);
yea in `rootSaga`

2023-01-30 07:57 UTC, ice-atlas commented on src/store/modules/News/sagas/markViewedNewsArticleSaga.ts
> +    logError(error);
Looks like `true`

2023-01-31 11:58 UTC, ice-atlas commented on src/screens/News/components/Post/index.tsx
> +                ? t('news.today')
Done

2023-02-06 10:39 UTC, ice-hector commented on src/assets/svg/NewsFeaturedNewBadge.tsx
> +    <Rect width={28} height={18} rx={9} fill={'url(#a)'} />
Should rem also be added to <Rect /> tag? Will it work properly if scaled with different size?

2023-02-06 10:40 UTC, ice-hector commented on src/screens/News/components/FeaturedNewsArticle/index.tsx
> +        resizeMode={'cover'}
cover is default

2023-02-06 10:41 UTC, ice-hector commented on src/screens/News/components/NewsArticle/index.tsx
> +          resizeMode={'cover'}
cover is default

2023-02-06 16:05 UTC, ice-atlas commented on src/assets/svg/NewsFeaturedNewBadge.tsx
> +    <Rect width={28} height={18} rx={9} fill={'url(#a)'} />
No need. This is relative position/size inside SVG container itself. So it works fine with changing only container size

2023-02-06 16:58 UTC, ice-hector submitted a review, later dismissed

2023-02-07 07:50 UTC, ice-orion commented on src/api/news/getNews.ts
> +  const queryParams: QueryParams = qParams;
Why do you reassign `qParams` to `queryParams` here? It doesn't seem to add safety

2023-02-07 07:50 UTC, ice-orion commented on src/api/news/markViewed.ts
> +  return patch<FormData, unknown>(
Why `unknown`? What does it return?

2023-02-07 07:50 UTC, ice-orion commented on src/navigation/components/MainTabBar/components/Icons/NewsIcon/hooks/useNewsUnreadCount.ts
> +const AUTO_REFRESH_INTERVAL = dayjs
There is `AppCommonActions.INTERVAL_UPDATE` action that is dispatched every 5 minutes on prod. Probably it would be better to just trigger `NewsActions.UNREAD_NEWS_COUNT_LOAD.START` on this action?
Then we won't need this hook at all, just like this:

```
takeLeading(
      [
        AppCommonActions.INTERVAL_UPDATE.type, // <---here
        NewsActions.UNREAD_NEWS_COUNT_LOAD.START.type,
        NewsActions.NEWS_ARTICLE_MARK_VIEWED(null).SUCCESS.type,
      ],
      loadUnreadNewsCountSaga,
    ),
    ```

2023-02-07 07:50 UTC, ice-orion commented on src/services/dayjs/index.ts
> +switch (appLocale) {
FYI: `appLocale` actually stores the preferred system lang that we support (the variable name could have been better), but not the lang that user has chosen via in app settings->select language screen. So even if user changed the lang, the dayjs will still use the old (default) locale. It is definitely better then nothing and i dough a lot of people will change the lang anyway.
Just thoughts out loud, you can close the thread

2023-02-07 08:05 UTC, ice-ares commented on src/services/dayjs/index.ts
> +switch (appLocale) {
that's not good, everything should be in user's selected language

2023-02-07 08:22 UTC, ice-atlas commented on src/api/news/getNews.ts
> +  const queryParams: QueryParams = qParams;
try to use some from `QueryParams` as `language`. It will ask you to add it back to `const queryParams: QueryParams`

2023-02-07 08:24 UTC, ice-atlas commented on src/api/news/markViewed.ts
> +  return patch<FormData, unknown>(
Because it will return some part of `NewsArticle` (or even part + extended) and @ice-ares said to ignore it

2023-02-07 08:25 UTC, ice-atlas commented on src/navigation/components/MainTabBar/components/Icons/NewsIcon/hooks/useNewsUnreadCount.ts
> +const AUTO_REFRESH_INTERVAL = dayjs
It was implemented before `INTERVAL_UPDATE`, so now can be adjusted

2023-02-07 08:26 UTC, ice-orion commented on src/api/news/markViewed.ts
> +  return patch<FormData, unknown>(
got it

2023-02-07 08:26 UTC, ice-atlas commented on src/services/dayjs/index.ts
> +switch (appLocale) {
it was omitted previously at all. So make sense to commit as is and ask to fix this in scope of settings task @ice-aiolos

2023-02-07 08:31 UTC, ice-orion commented on src/api/news/getNews.ts
> +  const queryParams: QueryParams = qParams;
I mean this way:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/102020833/217192490-2bddb959-4907-48b9-bfc6-3a4590ec06a7.png">
Seems to work fine:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/102020833/217192577-af8597f1-ac31-4e9c-badf-ee04fbf9fe96.png">

And tsc check passes fine

2023-02-07 08:40 UTC, ice-atlas commented on src/navigation/components/MainTabBar/components/Icons/NewsIcon/hooks/useNewsUnreadCount.ts
> +const AUTO_REFRESH_INTERVAL = dayjs
Done

2023-02-07 08:44 UTC, ice-atlas commented on src/api/news/getNews.ts
> +  const queryParams: QueryParams = qParams;
I know, but try to use as `{language, type, ...queryParams}` (type is used for some extra calculations for example), then it may lead to error

2023-02-07 08:48 UTC, ice-orion commented on src/api/news/getNews.ts
> +  const queryParams: QueryParams = qParams;
I see... Yea, you're right, but it would be better to add `QueryParams` type to the `get` function generic in addition to the return Type.

2023-02-07 08:48 UTC, ice-orion commented on src/api/news/getNews.ts
> +  const queryParams: QueryParams = qParams;
anyway it works

2023-02-07 09:27 UTC, ice-ares commented on src/services/dayjs/index.ts
> +switch (appLocale) {
Sure

2023-02-07 09:29 UTC, ice-orion approved these changes

2023-02-07 09:31 UTC, ice-ares approved these changes

2023-02-07 10:00 UTC, ice-hector approved these changes

2023-02-07 10:00 UTC, merged