Fix/settings UI
ice-blockchain/mobile-app pull request #116
Opened 2023-02-02 08:41 UTC by ice-aiolos

2023-02-03 14:46 UTC, ice-atlas requested changes

2023-02-08 07:50 UTC, ice-ares requested changes

2023-02-08 07:50 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +          if (isEmailNotificationChannel && type === 'BONUS') {
don do any logic here

2023-02-08 07:50 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +              setAllNotifications(false);
what does this do?

2023-02-08 07:50 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/index.tsx
> +  const [notificationSettings, updateSettings] =
nope, u have 2 lists, one for email, one for push

2023-02-08 07:50 UTC, ice-ares commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/ProfileMenuSection.tsx
> +      {/* <MenuItem
why did u remove it?

2023-02-08 07:50 UTC, ice-ares commented on src/translations/i18n.ts
> -const i18n = new I18n(locales);
u dont need to do this anymore?

2023-02-08 07:50 UTC, ice-ares commented on src/translations/i18n.ts
> +import {Translations} from '@translations/locales/en.json';
what do u need this for?

2023-02-08 07:50 UTC, ice-ares commented on src/translations/localeConfig.ts
> +    flag: '🇷🇴',
i think we might need the flag icons, ask the business

2023-02-08 07:50 UTC, ice-ares commented on src/translations/locales/en.json
> -      "no_referrals_description": "You don't have any referrals yet"
why did u remove it?

2023-02-08 07:50 UTC, ice-ares commented on src/translations/locales/en.json
> +      "disable_notifications_description": "By disabling notifications you will not be\nable to receive updates when you can start\nmine, news or team information",
remove the \n

2023-02-08 07:50 UTC, ice-ares commented on src/translations/locales/en.json
> +    "update_email_confirmation_subtitle": "Changing your email address will require\nyou to re-login. Are you sure you want\nto proceed?",
remove \n

2023-02-08 07:50 UTC, ice-ares commented on src/translations/locales/en.json
> +      "weekly": {
move those under channel field. notifications.channel.XXXX

2023-02-08 13:11 UTC, ice-aiolos commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +              setAllNotifications(false);
it shows popup
![image](https://user-images.githubusercontent.com/92715104/217539361-2f3284b0-6266-4010-885b-55263607f492.png)

2023-02-08 13:20 UTC, ice-aiolos commented on src/screens/SettingsFlow/NotificationSettings/index.tsx
> +  const [notificationSettings, updateSettings] =
I've made it based on the logic which we have in the current master.

in the current implementation, I save the state of notifications in the local state of the component just to show that ui part works, bc API hasn't been ready for it. @ice-ares if you have some updates related to API, pls share them and I'll prepare all stuff

2023-02-08 13:23 UTC, ice-aiolos commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/ProfileMenuSection.tsx
> +      {/* <MenuItem
bc I have a related point in the task

<img width="400" alt="image" src="https://user-images.githubusercontent.com/92715104/217542151-34363f90-812f-4527-a940-935e387e93ba.png">

2023-02-08 13:24 UTC, ice-aiolos commented on src/translations/locales/en.json
> -      "no_referrals_description": "You don't have any referrals yet"
bc it was a duplication of the string above

2023-02-08 14:06 UTC, ice-aiolos commented on src/translations/i18n.ts
> -const i18n = new I18n(locales);
yes, bc we discussed in some thread that we should load only one language. 

in this case, we load all languages
```
import en, {Translations} from '@translations/locales/en.json';
import ro from '@translations/locales/ro.json';

const locales = {
  en,
  ro,
};

const i18n = new I18n(locales);

```

2023-02-08 14:07 UTC, ice-aiolos commented on src/translations/i18n.ts
> +import {Translations} from '@translations/locales/en.json';
what do you mean?

2023-02-08 19:31 UTC, ice-atlas requested changes

2023-02-08 19:31 UTC, ice-atlas commented on src/screens/SettingsFlow/LanguageSettings/components/LanguageListItem.tsx
> +          {localeConfig[language].flag}
Use destructuring pls `const {flag, name} = localeConfig[language]`

2023-02-08 19:31 UTC, ice-atlas commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/NotificationRow.tsx
> +  console.log(!commonToggleEnabled);
remove this pls

2023-02-11 04:24 UTC, ice-orion commented on src/api/devices/types.ts
> +export type NotificationType =
For any of those keys we need to have a translation on FE side (e.g. `channel_achievements` or `channel_reminders`). So we anyway need to know possible values.

2023-02-11 04:31 UTC, ice-orion commented on src/assets/svg/PrivacyIcon.tsx
> +    height={rem(14)}
the width / height aspect ratio should be the same as in the viewbox. Currently in viewbox it's 1.5 (18/12), but width/height = 1.57.

2023-02-11 04:38 UTC, ice-orion commented on src/components/UserAvatarHeader/index.tsx
> +        {`@${user?.username}`}
probably user here might not be undefined but if we follow the types and it might, it's better to have it with empty string fallback: `user?.username ?? ''` so `undefined` won't be printed

2023-02-11 09:42 UTC, ice-ares commented on src/api/devices/types.ts
> +export type NotificationType =
Nope, u dont have to know em, if we want to change them, we only  add/remove keys in translations jsons. Code should be geberic

2023-02-13 08:22 UTC, ice-aiolos commented on src/assets/svg/PrivacyIcon.tsx
> +    height={rem(14)}
made it based on the design 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/92715104/218406478-5aafa655-fb78-4eab-b8fd-e7ff469adc9c.png">

2023-02-13 08:36 UTC, ice-aiolos commented on src/api/devices/types.ts
> +export type NotificationType =
@ice-ares i've made it based on our discussion.

and without notifications types we have ts lint issues, bc Type 'string' is not assignable to type weekly for example

2023-02-13 09:42 UTC, ice-ares commented on src/api/devices/types.ts
> +export type NotificationType =
Just keep em as strings and get em like u would from a map

2023-02-13 09:44 UTC, ice-ares commented on src/api/devices/types.ts
> +export type NotificationType =
And remove the ts types

2023-02-13 10:24 UTC, ice-ares commented on src/store/modules/Devices/sagas/initDevice.ts
> +    pushNotificationSettings: [
You dont init anything. You just display whatever the be returns

2023-02-13 10:24 UTC, ice-ares commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/SupportMenuSection.tsx
> +        onPress={() => Linking.openURL('mailto:hi@ice.io').catch(logError)}
Put it in config

2023-02-13 10:24 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +      if (notificationDeliveryChannel === 'push' && !hasPushPermissions) {
The checks in push notifications page should be disabled if we dont have push permissions

2023-02-13 12:15 UTC, ice-hector commented on src/navigation/components/Header/components/LangButton.tsx
> +          {localeConfig[i18n.locale as SupportedLocale].flag}
Can we avoid force casting here?

2023-02-13 12:25 UTC, ice-hector commented on src/screens/SettingsFlow/NotificationSettings/index.tsx
> +  ) as Notifications;
Pls avoid type force casting

2023-02-13 12:26 UTC, ice-atlas requested changes

2023-02-14 02:33 UTC, ice-orion commented on src/assets/svg/PrivacyIcon.tsx
> +    height={rem(14)}
If it's 22x14 in design then after export viewbox should be `0 0 22 14`

2023-02-14 02:35 UTC, ice-orion commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/SupportMenuSection.tsx
> +        onPress={() => Linking.openURL('mailto:hi@ice.io').catch(logError)}
probably to `constants/links`?

2023-02-14 02:42 UTC, ice-orion commented on src/api/devices/types.ts
> +export type NotificationType =
Can we discuss it once again please?
We can't make this NotificationType to be fully generic because simply adding new values from the BE won't work, because we still need to create translations on FE side for those new values (to display them in the list). That's why we're keeping the possible values to make sure all the translations for all possible values exist.
So why do we need to make it just `string`?

2023-02-14 02:53 UTC, ice-orion commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/AllNotifications.tsx
> -import {Switch} from '@components/Switch';
is it used somewhere? if not, remove the component please

2023-02-14 03:00 UTC, ice-orion commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/AllNotifications.tsx
> +    paddingVertical: 12,
rem?

2023-02-14 03:04 UTC, ice-orion commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/NotificationRow.tsx
> +  commonToggleEnabled,
I would suggest to rename like so

usage:
```
disabled={!commonToggleEnabled}
```
so `commonToggleEnabled` -> `disabled` (and revert it)

usage:
```
{disabled ? <RoundCheckboxInactiveIcon /> :  <RoundCheckboxActiveIcon .../>
```
so `disabled` -> `checked` (and revert it)

2023-02-14 03:04 UTC, ice-orion commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/NotificationRow.tsx
> +    paddingVertical: 12,
rem here in all other places

2023-02-14 03:09 UTC, ice-orion commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +      if (notificationDeliveryChannel === 'push' && !hasPushPermissions) {
If i remember correctly last time we discussed it, if we don't have push permissions, checke should be not disabled but unchecked and when user tried to check one of those, we suggest to give permissions.

2023-02-14 03:13 UTC, ice-orion commented on src/screens/SettingsFlow/NotificationSettings/index.tsx
> +  const updateNotificationSettings = (
i would highly encourage you to use separation of concepts -> so to place everything related to data to some hook, e.g. `useNotificationSettings`. So everything related to receiving data / updating and so on will be in a separate hook.

2023-02-14 03:14 UTC, ice-orion commented on src/screens/SettingsFlow/NotificationSettings/index.tsx
> +  const pushNotification = useSelector(pushNotificationByTypeSelector);
Probably we don't need to select both email and push data if we need only one of those?
Something like `const data = useSelector(isPushNotificationChannel  ? pushNotificationByTypeSelector : emailNotificationByTypeSelector)`

2023-02-14 03:15 UTC, ice-orion commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/ProfileMenuSection.tsx
> -import {NotificationsIcon} from '@svg/NotificationsIcon';
please remove the icon itself if it is not used anymore

2023-02-14 03:16 UTC, ice-orion commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/ProfileMenuSection.tsx
> +      {/* <MenuItem
add `TODO:` to the comment please if you temporary disabling something

2023-02-14 03:19 UTC, ice-orion commented on src/store/modules/Devices/sagas/initDevice.ts
> +    pushNotificationSettings: [
we can rename it to `getOrCreateDeviceSettingsSaga` and action to `DeviceActions.GET_OR_CREATE_DEVICE_SETTINGS.START`

2023-02-14 03:20 UTC, ice-orion commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +      setLocale(settings.language as SupportedLocale);
Why do we need it here since we restart the app anyway?

2023-02-14 03:22 UTC, ice-orion commented on src/translations/i18n.ts
> +import {Translations} from '@translations/locales/en.json';
@ice-ares we import `Translations` type here that was generated based on `@translations/locales/en.json`

2023-02-14 03:23 UTC, ice-orion commented on src/translations/localeConfig.ts
> +    flag: '🇷🇴',
Yes not long ago we added png flags (take a look in assets). The reason was that curved flags look not that good, if i remember correctly

2023-02-14 07:21 UTC, ice-ares commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/SupportMenuSection.tsx
> +        onPress={() => Linking.openURL('mailto:hi@ice.io').catch(logError)}
that would be ok as well

2023-02-14 07:23 UTC, ice-ares commented on src/api/devices/types.ts
> +export type NotificationType =
Anybody can create translations, thats the point, I want the code to be unchanged if we add/remove types in the future.

We just add/remove keys in translation files.

It is just a string from ur perspective, don't add a typing system to it

2023-02-14 07:25 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +      if (notificationDeliveryChannel === 'push' && !hasPushPermissions) {
we could flip the "turn off all notifications" toggle off manually in that case, which will make all the others disabled

2023-02-14 07:32 UTC, ice-orion commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +      if (notificationDeliveryChannel === 'push' && !hasPushPermissions) {
Will that make the checkboxes unchecked? If not, this still can be misleading since user might think that checked checkbox (even disabled) == turned on notifications.
We had a call with Iulian this morning, and i asked about this part - he told that uncheck the checkboxes if we don't have permissions is good (like we have before) + ask user to give permissions if he tries to check any of those.

2023-02-14 07:40 UTC, ice-orion commented on src/api/devices/types.ts
> +export type NotificationType =
Translations are part of the code currently - we keep those in repo, we protecting ourselves from using not existing translations by having translation types.
So if you add a new value on the backend, someone will add this value to the type and typescript will tell you that you also need to add a translation (if we shared the types between backend and frontend automatically this would worked perfectly).
Other way (without types in code) - you add a new value on the backend, someone should add a translation just because he knows that those types require translations and that someone also knows possible values to map the values to translations.

2023-02-14 07:45 UTC, ice-ares commented on src/api/devices/types.ts
> +export type NotificationType =
Let's please just keep it generic. Don't expect it to be anything. The fact that FE handles translations does not forces us to hardcode or type check it.

FE doesn't care what those types are, it just renders the appropriate translations.

2023-02-14 08:43 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +      if (notificationDeliveryChannel === 'push' && !hasPushPermissions) {
👌

2023-02-15 07:42 UTC, ice-atlas commented on src/api/devices/types.ts
> +export type NotificationType =
It is contract where we claim to support some sort of notifications/translations.

2023-02-15 12:02 UTC, ice-hector commented on src/store/modules/Devices/reducer/index.ts
> +                v => v.type === type,
Pls avoid one letter naming
`setting => setting.type === type`

2023-02-15 12:02 UTC, ice-hector commented on src/store/modules/Devices/reducer/index.ts
> +                v => v.type === type,
Same here

2023-02-15 12:03 UTC, ice-hector commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +      RNRestart.Restart();
This one is depricated. 
`.restart(); `
was the [correct](https://github.com/avishayil/react-native-restart#usage) one

2023-02-15 12:15 UTC, ice-hector submitted a review, later dismissed

2023-02-15 12:22 UTC, ice-ares commented on src/api/devices/getUserNotificationChannels.ts
> +      case 'ACHIEVEMENTS':
I was hoping you'd figure out those should be case insensitive, so you would lowercase them. Didnt you ask urself why some are caps locked, others start with a upper case, others don't?

2023-02-15 12:33 UTC, ice-ares commented on src/api/devices/types.ts
> +export type ApiNotificationChannel = {
u can remove the old code

2023-02-15 12:34 UTC, ice-ares commented on src/api/devices/types.ts
>    notificationSettings: NotificationSettings;
old api

2023-02-15 12:34 UTC, ice-ares commented on src/api/devices/types.ts
> +export type ApiNotificationChannel = {
also, move the new api into a separate domain. src/api/notifications

2023-02-15 12:36 UTC, ice-ares commented on src/api/devices/updateUserNotificationChannel.ts
> +  {type, enabled}: NotificationChannel,
thats more of a NotificationChannelToggle

2023-02-15 12:37 UTC, ice-ares commented on src/api/devices/updateUserNotificationChannel.ts
> +export function updateUserNotificationChannel(
toggleNotificationDomainOnOff

2023-02-15 12:38 UTC, ice-ares commented on src/api/devices/updateUserNotificationChannel.ts
> +  {type, enabled}: NotificationChannel,
NotificationDomainToggle actually

2023-02-15 12:39 UTC, ice-ares commented on src/api/devices/types.ts
> +export type NotificationType = string;
NotificationDomain

2023-02-15 12:39 UTC, ice-ares commented on src/api/devices/types.ts
> +export type NotificationChannel = {
NotificationDomainToggle

2023-02-15 12:40 UTC, ice-ares commented on src/api/devices/types.ts
> +export type NotificationChannels = Array<NotificationChannel>;
NotificationDomainToggles

2023-02-15 12:40 UTC, ice-ares commented on src/api/devices/types.ts
>    notificationSettings: NotificationSettings;
remove it

2023-02-15 12:42 UTC, ice-aiolos commented on src/api/devices/getUserNotificationChannels.ts
> +      case 'ACHIEVEMENTS':
so should i unify the types? could be there camelCase, PascalCase ?

anyway we should know the types which we'll receive bc the translations of channels on the ui are static and there should a dev who will add translations. i think it will be easier to use one predetermined spelling type.

2023-02-15 12:42 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/NotificationRow.tsx
> +    `settings.notifications.channel.${type}.description` as keyof Translations;
settings.notifications.domain

2023-02-15 12:44 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/NotificationRow.tsx
> +        <RoundCheckboxInactiveIcon />
this should also be able to be disabled

2023-02-15 12:44 UTC, ice-aiolos commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/NotificationRow.tsx
> +    `settings.notifications.channel.${type}.description` as keyof Translations;
made based on your comment above

https://github.com/ice-blockchain/mobile-app/pull/116#discussion_r1099767738

2023-02-15 12:49 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/hooks/useNotificationSettings.ts
> +    dispatch(DeviceActions.GET_OR_CREATE_DEVICE_SETTINGS.START.create());
what you are doing replaces the old implementation. You don't keep both

2023-02-15 12:50 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/index.tsx
> +          {!!deviceSettings && notificationSettings ? (
This is the old UI

2023-02-15 12:55 UTC, ice-ares commented on src/api/devices/getUserNotificationChannels.ts
> +      case 'ACHIEVEMENTS':
lowercase is enough

2023-02-15 12:56 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/NotificationRow.tsx
> +    `settings.notifications.channel.${type}.description` as keyof Translations;
I know, I remember everything I said

2023-02-15 12:58 UTC, ice-aiolos commented on src/screens/SettingsFlow/NotificationSettings/index.tsx
> +          {!!deviceSettings && notificationSettings ? (
no, it's new

2023-02-15 13:00 UTC, ice-aiolos commented on src/screens/SettingsFlow/NotificationSettings/hooks/useNotificationSettings.ts
> +    dispatch(DeviceActions.GET_OR_CREATE_DEVICE_SETTINGS.START.create());
not clear what i should do

2023-02-15 13:15 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/NotificationRow.tsx
> +        <RoundCheckboxInactiveIcon />
so if an unchecked row is disabled I can't check it back right?

2023-02-15 13:17 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/index.tsx
> +          {!!deviceSettings && notificationSettings ? (
ok, then remove the old stuff from it

2023-02-15 13:20 UTC, ice-aiolos commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/components/NotificationRow.tsx
> +        <RoundCheckboxInactiveIcon />
yes

2023-02-15 13:44 UTC, ice-atlas requested changes

2023-02-15 13:44 UTC, ice-atlas commented on src/translations/localeConfig.ts
> +export type SupportedLocale = 'en' | 'ro' | 'de';
It must be `keys` of `localeConfig`

2023-02-15 13:44 UTC, ice-atlas commented on src/store/modules/Devices/reducer/index.ts
> +              if (draft.settings && index !== -1) {
`if (draft.settings &&` on `line 66` already checked.
Also try `.find` and just alter `notification` object as `notification.enabled = enabled;`

2023-02-15 13:44 UTC, ice-atlas commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/SupportMenuSection.tsx
> +          <InviteIcon fill={COLORS.primaryLight} width={24} height={24} />
`rem(<size>)`

2023-02-15 13:44 UTC, ice-atlas commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +                ? !(!!disableAll?.enabled && hasPushPermissions)
`!(!!disableAll?.enabled && hasPushPermissions)` -> `!disableAll?.enabled || !hasPushPermissions`

and in general hard to understand `disableAll?.enabled` meaning

2023-02-15 14:22 UTC, ice-ares commented on src/api/devices/getUserNotificationChannels.ts
> +} from '@api/devices/types';
wrong place. it should be '@api/notifications/types'

2023-02-15 14:23 UTC, ice-ares commented on src/api/devices/getUserNotificationChannels.ts
> +export async function getUserNotificationChannels(
getNotificationDomainToggles

2023-02-15 14:23 UTC, ice-ares commented on src/api/devices/getUserNotificationChannels.ts
> +  const notificationChannels: NotificationDomainToggles = [];
notificationDomainToggles

2023-02-15 14:24 UTC, ice-ares commented on src/api/devices/index.ts
> +  toggleNotificationDomainOnOff,
still wrong place

2023-02-15 14:24 UTC, ice-ares commented on src/api/devices/types.ts
>  // SPDX-License-Identifier: BUSL-1.1
wrong place

2023-02-15 14:26 UTC, ice-ares commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +          DeviceActions.UPDATE_NOTIFICATION_CHANNEL.START.create(
keep the same naming as the API method, and move it to the appropriate location (which is not devices)

2023-02-15 19:03 UTC, ice-atlas approved these changes

2023-02-16 17:55 UTC, ice-ares submitted a review, later dismissed

2023-02-16 18:24 UTC, ice-hector approved these changes

2023-02-17 04:52 UTC, ice-orion commented on src/screens/SettingsFlow/Settings/index.tsx
> +        <UserAvatarHeader onChange={onChangeProfileImage} />
1. Don't import things from another screens. On screens use only components that belong to this screen or common ones (from `@components`, `@hooks` etc).
2. How do you change avatar on settings screen? `onChangeProfileImage` from `PersonalInformation` screen just set the new image to the userDraft and userDraft is saved to the BE only when user presses Save button. How does it work here?

2023-02-17 04:58 UTC, ice-orion commented on src/store/modules/Devices/reducer/index.ts
> +        if (draft.settings) {
Optional:
this switch looks like copy / paste, might be:
```
const key = ({
   email: 'emailNotificationSettings',
   push: 'pushNotificationSettings',
} as const)[notificationDeliveryChannel];
const notification = draft.settings[key].find(
   notificationDomain => notificationDomain.type === type,
);
if (notification) {
   notification.enabled = enabled;
}
```

2023-02-17 05:00 UTC, ice-orion commented on src/store/modules/Devices/sagas/getOrCreateDeviceSettings.ts
> +    pushNotificationChannel = yield call(
You have 3 requests here, you `yield all()` to perform them in parallel

2023-02-17 05:03 UTC, ice-orion commented on src/store/modules/Devices/sagas/index.ts
>          // In case of USER_STATE_CHANGE.FAILED we still need to init device
I forgot to remove it - can you please remove this comment and `AccountActions.USER_STATE_CHANGE.FAILED.type` from this array?

2023-02-17 05:06 UTC, ice-orion commented on src/translations/i18n.ts
> +) as Array<SupportedLocale>;
`as Array<keyof typeof locales>`

2023-02-17 05:08 UTC, ice-orion commented on src/translations/localeConfig.ts
> +export type SupportedLocale = 'en' | 'ro' | 'de';
we have `export type SupportedLocale = keyof typeof locales;` in src/translations/i18n.ts

2023-02-17 12:58 UTC, ice-orion approved these changes

2023-02-17 13:09 UTC, ice-hector approved these changes

2023-02-17 13:11 UTC, ice-hades approved these changes

2023-02-17 13:11 UTC, merged