chore: phone verification screen
ice-blockchain/mobile-app pull request #123
Opened 2023-02-06 08:12 UTC by ice-hades

2023-02-06 08:37 UTC, ice-ares commented on src/components/Forms/ModifyPhoneNumberForm/hooks/useModifyPhoneNumber.tsx
> +          fullPhoneRef.current ||
call e164NumberFormat

2023-02-06 08:47 UTC, ice-orion commented on src/screens/Team/components/Contacts/index.tsx
> -  const phoneVerificationStep = useSelector(phoneVerificationStepSelector);
What is this task about? Why we can't rely on tempPhoneNumber now and need those 3 states here?

2023-02-06 08:51 UTC, ice-hades commented on src/screens/Team/components/Contacts/index.tsx
> -  const phoneVerificationStep = useSelector(phoneVerificationStepSelector);
Go back from confirm code screen and modify the phone (should be filled)

2023-02-06 09:03 UTC, ice-orion commented on src/screens/Team/components/Contacts/index.tsx
> -  const phoneVerificationStep = useSelector(phoneVerificationStepSelector);
Can't we just add `phoneVerificationStep` to the store and set values there (`code` or `phone`) explicitly?
So to go back we just set `phone` and that's it?
Then we probably won't need to handle it here via states / add all those new props.
Also we have the same step in settings, is it handled there as well?

2023-02-06 09:12 UTC, ice-hades commented on src/screens/Team/components/Contacts/index.tsx
> -  const phoneVerificationStep = useSelector(phoneVerificationStepSelector);
On settings it should be empty. Confirmed with business team.

Do you see how it can be improved here or just asking why it was done that way and not the way you see it?

2023-02-06 09:42 UTC, ice-orion commented on src/screens/Team/components/Contacts/index.tsx
> -  const phoneVerificationStep = useSelector(phoneVerificationStepSelector);
I'm just curious if we can do it like this:
keep `temporaryPhoneNumber: {country: string; body: string}`
+ add `phoneVerificationStep: 'code' | 'phone'` to the store

then this file remains the same -> we're showing `ModifyPhoneNumber` / `ConfirmPhoneNumber` relying on `phoneVerificationStep` + we prefill the phone number input with `temporaryPhoneNumber` if it's set (contains both country and body separately)

will it work? 🤔
then we'll rely only on things from store + won't need to handle it manually with states, props passing here and on the settings screen if we even need it there

2023-02-06 10:13 UTC, ice-hector commented on src/components/Forms/ConfirmPhoneNumberForm/hooks/useConfirmPhoneNumber.ts
> +    resetValidation: onModifyPhoneNumber ?? resetValidation,
How resetValidation can be onModifyPhoneNumber ? Not clear at all

2023-02-06 10:16 UTC, ice-hector commented on src/components/Forms/components/ConfirmCode/index.tsx
> +          <View style={styles.backButton}>{DoThisLaterButton}</View>
Does it have the same style as the back button?

2023-02-06 13:28 UTC, ice-ares commented on src/utils/phoneNumber.ts
> +export function getCountryByPhoneNumber(phoneNumber: string | null): {
what are u doing with this?

2023-02-06 13:29 UTC, ice-hades commented on src/utils/phoneNumber.ts
> +export function getCountryByPhoneNumber(phoneNumber: string | null): {
parse phone number to get country code and national number

2023-02-06 13:34 UTC, ice-orion submitted a review, later dismissed

2023-02-06 18:20 UTC, ice-hector submitted a review, later dismissed

2023-02-07 09:46 UTC, ice-atlas requested changes

2023-02-07 09:46 UTC, ice-atlas commented on src/components/Forms/ConfirmPhoneNumberForm/hooks/useConfirmPhoneNumber.ts
> +  const doNoResetValidationOnGoBack = !!onModifyPhoneNumber;
`const resetValidationOnGoBack = !onModifyPhoneNumber;`
then
```
if (resetValidationOnGoBack) {
      resetValidation();
    }
```
and adjust `resetValidation`

motivation: easier to read expression with out `!`

2023-02-07 09:46 UTC, ice-atlas commented on src/store/modules/Validation/actions/index.ts
> +    STATE: (
it is better to use 
```
STATE: (payload: {
  temporaryPhoneVerificationStep: TemporaryPhoneVerificationStepType,
}) => payload
```
easier to extend, less code AND named params for function

2023-02-07 10:19 UTC, ice-atlas approved these changes

2023-02-07 10:22 UTC, ice-orion submitted a review, later dismissed

2023-02-07 10:59 UTC, ice-atlas approved these changes

2023-02-07 11:02 UTC, ice-hector approved these changes

2023-02-07 11:03 UTC, merged