chore: added fcmToken to device metadata
ice-blockchain/mobile-app pull request #125
Opened 2023-02-06 14:47 UTC by ice-hades

2023-02-06 14:54 UTC, ice-orion commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +      console.log('pushNotificationToken', pushNotificationToken);
console.log

2023-02-06 14:56 UTC, ice-orion commented on src/store/modules/PushNotifications/hooks/useInitNotifications.tsx
> +      dispatch(DeviceActions.UPDATE_DEVICE_METADATA.START.create());
Why are you dispatching it from here? As i understand `messaging().getToken()` stays the same no matter if you have or have no push permissions

2023-02-06 15:02 UTC, ice-hades commented on src/store/modules/PushNotifications/hooks/useInitNotifications.tsx
> +      dispatch(DeviceActions.UPDATE_DEVICE_METADATA.START.create());
@ice-ares btw should we send fcm token if user revoked permissions? Or send an empty string in that case?

2023-02-06 15:24 UTC, ice-ares commented on src/store/modules/PushNotifications/hooks/useInitNotifications.tsx
> +      dispatch(DeviceActions.UPDATE_DEVICE_METADATA.START.create());
send empty string. Logic is simple:

1. if I can send push notification to user, set the field with the correct value
2. else (if no permissions or whatever reason) set it to empty

2023-02-06 15:26 UTC, ice-ares commented on src/store/modules/PushNotifications/hooks/useInitNotifications.tsx
> +      dispatch(DeviceActions.UPDATE_DEVICE_METADATA.START.create());
and it should be updated to reflect the latest state. If user revoked permissions, set it to empty string immediately

2023-02-06 16:31 UTC, ice-orion submitted a review, later dismissed

2023-02-06 18:21 UTC, ice-hector approved these changes

2023-02-07 07:07 UTC, ice-ares commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +      action.type === DeviceActions.UPDATE_DEVICE_METADATA.START.type ||
when does this happen?

2023-02-07 07:09 UTC, ice-hades commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +      action.type === DeviceActions.UPDATE_DEVICE_METADATA.START.type ||
when user grants permission initially or revokes/grants later

2023-02-07 07:13 UTC, ice-orion commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        hasPushPermissions ? messaging().getToken() : Promise.resolve(''),
```suggestion
        hasPushPermissions ? messaging().getToken() : '',
```

2023-02-07 07:13 UTC, ice-orion commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +      action.type === DeviceActions.UPDATE_DEVICE_METADATA.START.type ||
it's not quite good to rely on an action type that started the saga - just add a param "forceUpdate" and set it to true when you need to bypass the time restrictions and update metadata

2023-02-07 10:03 UTC, ice-orion approved these changes

2023-02-07 10:05 UTC, ice-hector submitted a review, later dismissed

2023-02-07 10:05 UTC, ice-atlas requested changes

2023-02-07 10:05 UTC, ice-atlas commented on src/store/modules/Devices/actions/index.ts
> +  START: ({forceUpdate}: {forceUpdate?: boolean}) => ({forceUpdate}),
`START: (payload: {forceUpdate?: boolean}) => payload,`

2023-02-07 10:07 UTC, ice-hades commented on src/store/modules/Devices/actions/index.ts
> +  START: ({forceUpdate}: {forceUpdate?: boolean}) => ({forceUpdate}),
are you serious? Guys need to approve it again because of this?)

2023-02-07 10:08 UTC, ice-atlas commented on src/store/modules/Devices/actions/index.ts
> +  START: ({forceUpdate}: {forceUpdate?: boolean}) => ({forceUpdate}),
imagine to add new param here. 3 places instead of 1

2023-02-07 10:10 UTC, ice-hades commented on src/store/modules/Devices/actions/index.ts
> +  START: ({forceUpdate}: {forceUpdate?: boolean}) => ({forceUpdate}),
6 secs instead of 2?

2023-02-07 10:11 UTC, ice-ares commented on src/store/modules/Devices/actions/index.ts
> +  START: ({forceUpdate}: {forceUpdate?: boolean}) => ({forceUpdate}),
@ice-hades dont worry about approvals, those will come, if there’s a fix needed, we do it regardless

2023-02-07 10:12 UTC, ice-orion commented on src/store/modules/Devices/actions/index.ts
> +  START: ({forceUpdate}: {forceUpdate?: boolean}) => ({forceUpdate}),
for me it's not a problem to reapprove -> just trigger me if needed

2023-02-07 10:14 UTC, ice-atlas commented on src/store/modules/Devices/actions/index.ts
> +  START: ({forceUpdate}: {forceUpdate?: boolean}) => ({forceUpdate}),
motivation: you can add any param to type and linter will be OK with it, but actual usage will be missed

2023-02-07 10:21 UTC, ice-atlas approved these changes

2023-02-07 10:23 UTC, ice-orion approved these changes

2023-02-07 10:30 UTC, merged