bonuses
ice-blockchain/mobile-app pull request #128
Opened 2023-02-07 14:18 UTC by ice-orion

2023-02-07 14:19 UTC, ice-ares commented on ios/ice.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
> +	<key>PreviewsEnabled</key>
whats this?

2023-02-07 14:25 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/handleExtraBonus.ts
> +      if (!extraBonus.availableExtraBonus) {
this never happens. u get an error, not an empty response

2023-02-07 14:26 UTC, ice-ares commented on src/store/modules/Tokenomics/sagas/handleExtraBonus.ts
> +      yield call(openClaimBonus);
does this block until I press "Claim now" ?

2023-02-07 14:29 UTC, ice-ares commented on src/store/modules/Tokenomics/utils/openBonusClaimed.tsx
> +  if (claimedBonus <= 130) {
const the values

2023-02-07 14:32 UTC, ice-ares commented on src/store/modules/Tokenomics/utils/openClaimBonus.tsx
> +          Icon: <StakeIcon />,
can you wrap that stakeIcon and name it differently, I.E> ClaimBonusIcon.

Cuz its confusing to see this here

2023-02-07 15:21 UTC, ice-atlas requested changes

2023-02-07 16:40 UTC, ice-orion commented on ios/ice.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
> +	<key>PreviewsEnabled</key>
removed, added to gitignore

2023-02-07 16:40 UTC, ice-orion commented on src/navigation/Router.tsx
> +  console.log('isRegistrationComplete', isRegistrationComplete);
done

2023-02-07 16:40 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/handleExtraBonus.ts
> +      if (!extraBonus.availableExtraBonus) {
removed this block

2023-02-07 16:41 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/handleExtraBonus.ts
> +      yield call(openClaimBonus);
yes

2023-02-07 16:41 UTC, ice-orion commented on src/store/modules/Tokenomics/utils/openBonusClaimed.tsx
> +  if (claimedBonus <= 130) {
done

2023-02-07 16:41 UTC, ice-orion commented on src/store/modules/Tokenomics/utils/openClaimBonus.tsx
> +          Icon: <StakeIcon />,
done, renamed to CoinsStakeIcon

2023-02-07 16:41 UTC, ice-orion commented on src/store/modules/Tokenomics/sagas/handleExtraBonus.ts
> +      while (!(yield* isRegistrationComplete())) {
done

2023-02-07 16:58 UTC, ice-ares commented on src/store/modules/Tokenomics/utils/openClaimBonus.tsx
> +          Icon: <StakeIcon />,
😆 thats even worse. There's nothing related to staking there, thats my point.

2023-02-07 17:30 UTC, ice-orion commented on src/store/modules/Tokenomics/utils/openClaimBonus.tsx
> +          Icon: <StakeIcon />,
Right, it supposed to be CoinsStack :)
We're dreaming icons by what it is depicted there, so this way you're not restricted by the usage case.

2023-02-07 17:33 UTC, ice-ares commented on src/store/modules/Tokenomics/utils/openClaimBonus.tsx
> +          Icon: <StakeIcon />,
yea

2023-02-07 17:34 UTC, ice-orion commented on src/store/modules/Tokenomics/utils/openClaimBonus.tsx
> +          Icon: <StakeIcon />,
renamed

2023-02-08 18:21 UTC, ice-ares commented on fastlane/Matchfile
> +app_identifier(["io.ice.app.staging", "io.ice.app", "io.ice.app.staging.NotificationService", "io.ice.app.NotificationService"])
whats this for?

2023-02-08 18:24 UTC, ice-ares submitted a review, later dismissed

2023-02-08 19:12 UTC, ice-atlas submitted a review, later dismissed

2023-02-09 10:10 UTC, ice-atlas submitted a review, later dismissed

2023-02-09 10:24 UTC, ice-hector commented on fastlane/Matchfile
> +app_identifier(["io.ice.app.staging", "io.ice.app", "io.ice.app.staging.NotificationService", "io.ice.app.NotificationService"])
@ice-ares  When we make match:read (and other related fastlane script runs) locally it always asks us to fill manually the bundle ids. This setting prevents this, and passes this step automatically

2023-02-09 10:40 UTC, ice-hector approved these changes

2023-02-09 10:43 UTC, ice-hector submitted a review, later dismissed

2023-02-09 10:47 UTC, ice-atlas submitted a review, later dismissed

2023-02-10 22:31 UTC, ice-hector approved these changes

2023-02-10 23:14 UTC, merged