chore: moengage events tracking
ice-blockchain/mobile-app pull request #139
Opened 2023-02-09 10:00 UTC by ice-hades

2023-02-10 14:37 UTC, ice-hector commented on src/components/InviteButton/index.tsx
> +      AnalyticsActions.TRACK_INVITE_FRIENDS_BANNER_PRESSED.START.create(),
Are we gonna make separate action and create separate saga for each screen opening event tracking? 
Like you did in `trackInviteFriendsBannerPressedSaga`. 
Just create some moengage service with track function and pass there the screen name. Or create one tracking saga for the whole project and also pass the screen name as params (but i don't even think you need a saga here, as I see from the code you do nothing with the `TRACK_INVITE_FRIENDS_BANNER_PRESSED.SUCCESS` event

2023-02-10 14:38 UTC, ice-hector commented on src/navigation/Router.tsx
> +    routeNameRef.current = navigationRef?.getCurrentRoute()?.name;
getCurrentRoute is an async function if you take if from ref. Are you sure it works correctly here?

2023-02-10 14:38 UTC, ice-hector commented on src/navigation/Router.tsx
> +  console.log('user', user?.id, user?.firstName);
Remove

2023-02-10 14:39 UTC, ice-ares commented on src/components/InviteButton/index.tsx
> +      AnalyticsActions.TRACK_INVITE_FRIENDS_BANNER_PRESSED.START.create(),
yea, rollback those changes to delete the existing analytics service

2023-02-10 14:39 UTC, ice-hector commented on src/navigation/Router.tsx
> +          console.log('onStateChange', {previousRouteName, currentRouteName});
remove

2023-02-10 14:39 UTC, ice-hector commented on src/navigation/Router.tsx
> +      onStateChange={async () => {
Move to separate const function

2023-02-10 14:40 UTC, ice-hades commented on src/components/InviteButton/index.tsx
> +      AnalyticsActions.TRACK_INVITE_FRIENDS_BANNER_PRESSED.START.create(),
One saga for all screens tracking src/store/modules/Analytics/sagas/trackViewScreen.ts

2023-02-10 14:40 UTC, ice-hades commented on src/navigation/Router.tsx
> +    routeNameRef.current = navigationRef?.getCurrentRoute()?.name;
yeah, checked it

2023-02-10 14:42 UTC, ice-hades commented on src/services/analytics/index.ts
> -
that is no moengage integration. here are just analytics

2023-02-10 14:43 UTC, ice-hades commented on src/store/modules/Account/hooks/useTrackUserInfo.ts
> -      updateUserAttributes(user);
yep. even when I committed this team requested to move it to sagas. we agreed to do it when I continue with moengage

2023-02-10 14:44 UTC, ice-hector commented on src/navigation/Router.tsx
> +          dispatch(
Can we wrap it to some tracking service with `trackScreenView(screenName: string)` function? Looks like there would be a lot of similar dispatches across the project so let's just incapsulate it

2023-02-10 14:44 UTC, ice-hades commented on src/store/modules/Account/sagas/signOut.ts
> -    yield call(stopTrackingCurrentUser);
@ice-ares check stopTracking.ts file

2023-02-10 14:45 UTC, ice-hades commented on src/store/modules/Account/sagas/userStateChange.ts
> +      } else {
check next commit

2023-02-10 14:45 UTC, ice-hector commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButton/index.tsx
> +          AnalyticsActions.TRACK_TAP_TO_MINE.START.create({
Just remove all this, dont create for each tracking action separate action and saga

2023-02-10 14:45 UTC, ice-hector commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButton/index.tsx
> +            AnalyticsActions.TRACK_TAP_TO_MINE.START.create({
Just remove all this, dont create for each tracking action separate action and saga

2023-02-10 14:45 UTC, ice-hector commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButton/index.tsx
> +            AnalyticsActions.TRACK_TAP_TO_MINE.START.create({
Just remove all this, dont create for each tracking action separate action and saga

2023-02-10 14:47 UTC, ice-hades commented on src/navigation/Router.tsx
> +          dispatch(
only one dispatch to AnalyticsActions.TRACK_VIEW_SCREEN.START in one place

2023-02-10 14:49 UTC, ice-hades commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButton/index.tsx
> +            AnalyticsActions.TRACK_TAP_TO_MINE.START.create({
we can discuss it once @ice-orion is back

2023-02-10 14:50 UTC, ice-hades commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButton/index.tsx
> +            AnalyticsActions.TRACK_TAP_TO_MINE.START.create({
we can discuss it once @ice-orion is back

2023-02-10 14:50 UTC, ice-hades commented on src/navigation/components/MainTabBar/components/TabBarMiningItem/components/MiningButton/index.tsx
> +          AnalyticsActions.TRACK_TAP_TO_MINE.START.create({
we can discuss it once @ice-orion is back

2023-02-13 08:21 UTC, ice-ares commented on ios/Podfile
> +$RNFirebaseAnalyticsWithoutAdIdSupport = true
whats “without ad id support”?

2023-02-13 08:22 UTC, ice-ares commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AdHoc io.ice.app.staging";
rollback this file

2023-02-13 08:29 UTC, ice-hades commented on ios/Podfile
> +$RNFirebaseAnalyticsWithoutAdIdSupport = true
Firebase Analytics

2023-02-13 08:43 UTC, ice-ares requested changes

2023-02-13 08:43 UTC, ice-ares commented on src/components/InviteButton/index.tsx
> +import {EVENT_NAMES} from '@services/analytics/constants';
this does not belong there. move each constant into where its used

2023-02-13 08:43 UTC, ice-ares commented on src/screens/InviteFlow/InviteFriend/index.tsx
> -    dispatch(ContactsActions.INVITE_CONTACT.START.create(contact?.recordID));
why did u remove it?

2023-02-13 08:43 UTC, ice-ares commented on src/services/analytics/index.ts
> +export const Events = {
this does not belong here. move it to where it is used

2023-02-13 08:43 UTC, ice-ares commented on src/services/analytics/index.ts
> +      eventProps: {'Screen Name': screenName},
what kind of key is that, with spaces init?

2023-02-13 08:43 UTC, ice-ares commented on src/services/analytics/index.ts
> +export const Attributes = {
why do u need this? u have that other one

2023-02-13 08:43 UTC, ice-ares commented on src/services/analytics/types.ts
> +export type TapToMineActionType = 'Default' | 'Extended' | 'Info';
nothing in this file belongs here

2023-02-13 08:43 UTC, ice-ares commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +      yield call(Attributes.trackUserFirstName, firstName);
use that other one for the whole user type

2023-02-13 08:43 UTC, ice-ares commented on src/store/modules/Analytics/sagas/updateResurrectResponseType.ts
> +    yield call(ReactMoE.setUserAttribute, 'Resurrect', resurrectResponseType);
"moe" keyword belongs only in services/analytics

2023-02-13 08:43 UTC, ice-ares commented on src/services/analytics/constants.ts
> +export const EVENT_NAMES = {
doesn't belong here

2023-02-13 09:05 UTC, ice-hades commented on src/components/InviteButton/index.tsx
> +import {EVENT_NAMES} from '@services/analytics/constants';
@ice-ares like inline each constant?

2023-02-13 09:06 UTC, ice-hades commented on src/screens/InviteFlow/InviteFriend/index.tsx
> -    dispatch(ContactsActions.INVITE_CONTACT.START.create(contact?.recordID));
@ice-ares put Events.trackEvent({eventName: EVENT_NAMES.INVITE_CONTACT_BY_SMS}); instead

2023-02-13 09:07 UTC, ice-hades commented on src/services/analytics/index.ts
> +export const Events = {
You want me to inline those functions into places where they used or what?

2023-02-13 09:07 UTC, ice-hades commented on src/services/analytics/index.ts
> +      eventProps: {'Screen Name': screenName},
Business key. it is for moengage

2023-02-13 09:11 UTC, ice-hades commented on src/services/analytics/index.ts
> +export const Attributes = {
It calls ReactMoE.setUserName

2023-02-13 09:11 UTC, ice-hades commented on src/services/analytics/types.ts
> +export type TapToMineActionType = 'Default' | 'Extended' | 'Info';
where it belongs?

2023-02-13 09:12 UTC, ice-hades commented on src/services/analytics/constants.ts
> +export const EVENT_NAMES = {
where it belongs?

2023-02-13 09:12 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateResurrectResponseType.ts
> +    yield call(ReactMoE.setUserAttribute, 'Resurrect', resurrectResponseType);
ok

2023-02-13 09:13 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +      yield call(Attributes.trackUserFirstName, firstName);
It is special moengage attribute tracker. we should use them

2023-02-13 10:05 UTC, ice-ares commented on ios/Podfile
> +$RNFirebaseAnalyticsWithoutAdIdSupport = true
Yea but why without ad id support?

2023-02-13 10:06 UTC, ice-ares commented on src/screens/InviteFlow/InviteFriend/index.tsx
> -    dispatch(ContactsActions.INVITE_CONTACT.START.create(contact?.recordID));
Does it open the invite screen or what?

2023-02-13 10:49 UTC, ice-hades commented on src/screens/InviteFlow/InviteFriend/index.tsx
> -    dispatch(ContactsActions.INVITE_CONTACT.START.create(contact?.recordID));
There is no such logic for now. IDK, probably some of the guys working on it

2023-02-13 10:50 UTC, ice-hades commented on ios/Podfile
> +$RNFirebaseAnalyticsWithoutAdIdSupport = true
We don't want to track any ad ids in the app. you can confirm with the business team

2023-02-13 11:14 UTC, ice-ares commented on src/store/modules/Permissions/sagas/index.ts
> -    takeLatest(AppCommonActions.APP_LOADED.STATE.type, checkAllPermissionsSaga),
u dont need this?

2023-02-13 11:14 UTC, ice-ares commented on src/store/modules/Analytics/sagas/updateReferredBy.ts
> +    yield call(ReactMoE.setUserAttribute, 'Referred By', referredBy);
please search for "moe" across all codebase. And make sure it is found only in services/analytics

2023-02-13 11:14 UTC, ice-ares commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const language = i18n.locale;
nope, u have a selector for that

2023-02-13 11:14 UTC, ice-ares commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const tz = RNLocalize.getTimeZone();
u have a selector for that as well

2023-02-13 11:14 UTC, ice-ares commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    if (userAttributes.profilePicture !== user.profilePicture?.uri) {
u're gonna include the default pic as well, which u shouldn't

2023-02-13 11:14 UTC, ice-ares commented on src/store/modules/Analytics/constants.ts
> +          Referral: user?.referredBy ?? '',
nope, thats userid, u have the username in that set referral saga in onboarding

2023-02-13 11:14 UTC, ice-ares commented on src/screens/InviteFlow/InviteFriend/index.tsx
> -    dispatch(ContactsActions.INVITE_CONTACT.START.create(contact?.recordID));
but what did the code u remove do?

2023-02-13 11:24 UTC, ice-hades commented on src/store/modules/Analytics/types.ts
> +export type ResurrectResponseType = 'accepted' | 'denied' | '';
to track that attribute from the beginning and not only when resurrect happens

2023-02-13 11:25 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateResurrectResponseType.ts
> +    !curResurrectResponseType &&
in order not to override on the app startup. when we start the app most of the values are not set in the app but we already tracked some meaningful values. so not to override those meaningful values

2023-02-13 11:26 UTC, ice-hades commented on src/store/modules/Permissions/sagas/index.ts
> -    takeLatest(AppCommonActions.APP_LOADED.STATE.type, checkAllPermissionsSaga),
I noticed it is redundant since just above we call the same saga for the same event
```
   takeLatest(
      [
        AppCommonActions.APP_STATE_CHANGE.STATE.type,
        AppCommonActions.APP_LOADED.STATE.type,
      ],
      checkAllPermissionsSaga,
    ),
    ```

2023-02-13 11:27 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateReferredBy.ts
> +    yield call(ReactMoE.setUserAttribute, 'Referred By', referredBy);
done

2023-02-13 11:28 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const language = i18n.locale;
I can't find one. You can search by `i18n.locale`

2023-02-13 11:28 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const tz = RNLocalize.getTimeZone();
The one @ice-orion added recently? It returns in numbers format. This one is more human readable.

2023-02-13 11:29 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    if (userAttributes.profilePicture !== user.profilePicture?.uri) {
@ice-ares how to properly get the user picture then in this case?

2023-02-13 11:29 UTC, ice-hades commented on src/store/modules/Analytics/constants.ts
> +          Referral: user?.referredBy ?? '',
right

2023-02-13 12:05 UTC, ice-ares commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const tz = RNLocalize.getTimeZone();
+03:00 seems pretty human readable to me. use it, its the most accurate

2023-02-13 12:05 UTC, ice-ares commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const language = i18n.locale;
@ice-orion

2023-02-13 12:28 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    if (userAttributes.profilePicture !== user.profilePicture?.uri) {
@ice-ares close according to https://frameyapp.slack.com/archives/C0391DUR5GD/p1676290520884959?thread_ts=1676034687.976929&cid=C0391DUR5GD

2023-02-13 15:00 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const tz = RNLocalize.getTimeZone();
done, but it is not stored in the store. But I reused the same util

2023-02-13 15:00 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const language = i18n.locale;
done

2023-02-13 15:42 UTC, ice-ares approved these changes

2023-02-13 16:28 UTC, ice-atlas requested changes

2023-02-13 16:28 UTC, ice-atlas commented on src/store/modules/Analytics/constants.ts
> +export const Events = {
Maybe better to name it as `AnalyticsEventLogger`?

2023-02-13 16:46 UTC, ice-hector commented on src/screens/WelcomeFlow/IceBonus/hooks/useIceBonus.ts
> +    Events.trackSignUp();
yep looks correct

2023-02-14 05:13 UTC, ice-hades commented on src/store/modules/Analytics/types.ts
> +export type ResurrectResponseType = 'accepted' | 'denied' | '';
should be not null

2023-02-14 05:16 UTC, ice-hades commented on src/screens/InviteFlow/InviteFriend/index.tsx
> +  const dispatch = useDispatch();
to call `dispatch(ContactsActions.INVITE_CONTACT.START.create(contact?.recordID));`

2023-02-14 05:17 UTC, ice-hades commented on src/screens/News/hooks/useNewsBrowser.ts
> +    Events.trackReadArticle({articleName: newsArticle.title});
opening

2023-02-14 05:19 UTC, ice-hades commented on src/store/modules/Account/sagas/signOut.ts
> +    yield call(stopTrackingCurrentUser);
What was previous place and what comment do you mean?

2023-02-14 05:21 UTC, ice-hades commented on src/store/modules/Analytics/constants.ts
> +export const EVENT_NAMES = {
Why is it bad to keep them in constants?

2023-02-14 05:21 UTC, ice-hades commented on src/store/modules/Analytics/constants.ts
> +export const Events = {
@ice-orion suggested the naming here

2023-02-14 05:25 UTC, ice-hades commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const lastName = user.lastName ?? '';
they don't keep it. and also we need to keep track because on startup most of those values are empty in the app memory. and we can override meaningful values that way

2023-02-14 05:28 UTC, ice-hades commented on src/store/modules/Analytics/actions/index.ts
> +const SET_MINING_ATTRIBUTES = createAction('SET_MINING_ATTRIBUTES', {
@ice-orion ^

2023-02-14 05:28 UTC, ice-orion commented on src/navigation/Router.tsx
> +  const onStateChange = async () => {
Can we please place track screen logic to a separate hook to keep the main Router as clean as possible?
So the usage will be something like 
```
const {trackViewScreen} = useTrackViewScreen()
...
const onStateChange =() => {
   trackViewScreen();
}
...


```

2023-02-14 05:28 UTC, ice-orion commented on src/store/modules/Account/sagas/signInSocial.ts
> +          signInType: action.payload.provider,
yea, you can grab it from firebase id token: `sign_in_provider`
`auth().currentUser.getIdTokenResult().then(claims => claims.firebase.sign_in_provider)`

2023-02-14 05:28 UTC, ice-orion commented on src/store/modules/Account/sagas/userStateChange.ts
> +        Events.trackSignIn({user});
It actually not always signIn - when you open the app, this method will also be called with saved user.

2023-02-14 05:35 UTC, ice-orion commented on src/store/modules/Analytics/constants.ts
> +export const Events = {
not really, my suggestion was to do it in a slightly different way - 
to have `trackEvent` method and `const Events` constant that keeps all the events, so the usage would be like so:
`trackEvent(Events.InviteShare({param1: '1'}))`

In your implementation `const Events` contain not the Events but methods to track those, so renaming might have sense.

2023-02-14 05:38 UTC, ice-orion commented on src/store/modules/Analytics/actions/index.ts
> +const SET_MINING_ATTRIBUTES = createAction('SET_MINING_ATTRIBUTES', {
hm?

2023-02-14 06:40 UTC, ice-hades commented on src/store/modules/Analytics/constants.ts
> +export const EVENT_NAMES = {
new if you need to change an event name you change it in one place - in the constant.
with your approach you will need to change it in the type AnalyticsEvent and everywhere it is passed as a param

2023-02-14 07:38 UTC, ice-ares commented on src/screens/News/hooks/useNewsBrowser.ts
> +    Events.trackReadArticle({articleName: newsArticle.title});
then it should be trackOpenNewsArticle

2023-02-14 07:42 UTC, ice-hades commented on src/screens/News/hooks/useNewsBrowser.ts
> +    Events.trackReadArticle({articleName: newsArticle.title});
@ice-ares From the business requirements
> Read Article (when a person presses on the article on news tab)

2023-02-14 07:46 UTC, ice-ares commented on src/screens/News/hooks/useNewsBrowser.ts
> +    Events.trackReadArticle({articleName: newsArticle.title});
@ice-atlas when is that mark as read call happening? before browser is opened or after its closed?

2023-02-14 09:59 UTC, ice-hades commented
@ice-orion we can use auth().currentUser.getIdTokenResult().then(claims => claims.firebase.sign_in_provider) but what values will it return when you sign in with an email or phone?

2023-02-14 10:45 UTC, ice-ares submitted a review, later dismissed

2023-02-14 11:21 UTC, ice-orion commented
> @ice-orion we can use auth().currentUser.getIdTokenResult().then(claims => claims.firebase.sign_in_provider) but what values will it return when you sign in with an email or phone?

just tried, for email it's probably 'email', but not sure.
"sign_in_provider":"phone"

2023-02-14 12:29 UTC, ice-atlas commented on src/screens/InviteFlow/InviteFriend/index.tsx
> +  const dispatch = useDispatch();
but it was there previously added. What the benefit to change position of this row?

2023-02-14 12:47 UTC, ice-orion commented on src/services/auth/index.ts
> +export const getAuthProvider = async () => {
How do you use it? it seems you still using `signInTypeSelector`

2023-02-14 12:47 UTC, ice-atlas requested changes

2023-02-14 12:47 UTC, ice-atlas commented on src/navigation/hooks/useOnStateChange.ts
> +  return async () => {
From best practices: hook must return any call backs only wrapped in `useCallback`. Because user (developer) of your code will not know that it will be new on every render

2023-02-14 12:47 UTC, ice-atlas commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const lastName = user.lastName ?? '';
1) Maybe you don't get the point. We may call this method as many times as we want. It will not trigger API call to service right away;
2) Then maybe need to wait for rehydration of state or/and rethink your current implementation.

2023-02-14 12:47 UTC, ice-atlas commented on src/store/modules/Analytics/reducer/index.ts
> +        draft.userAttributes = {};
you may just `return INITIAL_STATE`, but maybe need clone this object (need to check)

2023-02-14 12:47 UTC, ice-atlas commented on src/store/modules/Analytics/constants.ts
> +export const EVENT_NAMES = {
But name of event same as text under it. We may end up in chaos of naming (name of property not related any how to value) and chance of changing name quite low, because you will lose previous data.
`tsc` + `linter` will prevent bugs.

2023-02-14 12:47 UTC, ice-atlas commented on src/store/modules/Account/sagas/signOut.ts
> +    yield call(stopTrackingCurrentUser);
it was on `line 12` (before `SUCCESS`) before, now on `line 14`(after `SUCCESS`). Why?

2023-02-14 12:49 UTC, ice-orion commented on src/navigation/hooks/useOnStateChange.ts
> +  return async () => {
+ and it doesn't have to be `async`

2023-02-14 12:53 UTC, ice-orion commented on src/services/auth/index.ts
> +export const getAuthProvider = async () => {
If you think that we don't need it and we 're going to stick to saving the auth method to the store manually, then just don't define this function

2023-02-14 12:58 UTC, ice-atlas commented on src/navigation/hooks/useOnStateChange.ts
> +  return async () => {
it is OK to have `async` in `useCallback`, but it is depends on purpose

2023-02-14 12:59 UTC, ice-orion commented on src/navigation/hooks/useOnStateChange.ts
> +  return async () => {
yea, i mean in this particular function there is nothing that requires it to be async

2023-02-14 13:37 UTC, ice-orion submitted a review, later dismissed

2023-02-14 15:19 UTC, ice-hades commented on src/screens/News/hooks/useNewsBrowser.ts
> +    Events.trackReadArticle({articleName: newsArticle.title});
@ice-ares can we close this thread? @ice-atlas won't close until you agree

2023-02-14 16:33 UTC, ice-ares commented
> > @ice-orion we can use auth().currentUser.getIdTokenResult().then(claims => claims.firebase.sign_in_provider) but what values will it return when you sign in with an email or phone?
> 
> 
> 
> just tried with phone:
> 
> "sign_in_provider":"phone"
> 
> 
> 
> for email it's probably 'email', but not sure.
> 
> it should be emailLink

it should be emailLink

2023-02-15 09:19 UTC, ice-orion commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AdHoc io.ice.app.staging";
Should not be here?

2023-02-15 09:23 UTC, ice-orion commented on src/store/modules/Analytics/constants.ts
> +export const AnalyticsEventLogger = {
Why don't we keep the `trackSignUp` and `trackSignIn` here? We can call `getAuthProvider` and use selectors there, so this way we won't have those 2 actions/events separately

2023-02-15 09:41 UTC, ice-orion commented on src/store/modules/Analytics/constants.ts
> +export const AnalyticsEventLogger = {
discussed

2023-02-15 09:48 UTC, ice-orion approved these changes

2023-02-15 10:11 UTC, ice-ares approved these changes

2023-02-15 10:14 UTC, ice-ares commented on src/store/modules/Analytics/sagas/updateAttributes.ts
> +    const lastName = user.lastName ?? '';
@ice-atlas open a new comment if this is not resolved

2023-02-15 13:23 UTC, ice-atlas submitted a review, later dismissed

2023-02-18 10:50 UTC, ice-ares commented on src/store/modules/Analytics/constants.ts
> +      eventName: enabled
This is !enabled for disable_all

2023-02-18 10:50 UTC, ice-ares commented on src/store/modules/Analytics/constants.ts
> +      `[${getEnabledNotificationDomains(
That's how they support arrays?

2023-02-20 10:05 UTC, ice-atlas requested changes

2023-02-20 11:38 UTC, ice-hades commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +                  : !enabled
Why should I do this?

2023-02-21 10:12 UTC, ice-atlas commented on src/screens/SettingsFlow/NotificationSettings/components/NotificationControls/index.tsx
> +                  : !enabled
easier to read and edit. Same as `X * Z + X * Y * 2` -> `X * (Z + Y * 2)`

2023-02-22 02:52 UTC, ice-orion commented on src/navigation/Router.tsx
> +  const onStateChange = useOnStateChange(routeNameRef);
Let's incapsulate everything related to route name tracking to that `useOnStateChange` -> 
```
export function useOnStateChange() {
  const routeNameRef = useRef(navigationRef?.getCurrentRoute()?.name);
  return useCallback(() => {
    const previousRouteName = routeNameRef.current;
    const currentRouteName = navigationRef?.getCurrentRoute()?.name;
    if (previousRouteName !== currentRouteName && currentRouteName) {
      routeNameRef.current = currentRouteName;
      AnalyticsEventLogger.trackViewScreen({screenName: currentRouteName});
    }
  }, []);
}
```

2023-02-22 02:52 UTC, ice-orion commented on src/services/analytics/index.ts
> +export function trackEvent({eventName, eventProps}: TrackEventParams) {
Disable Moengage debug logs please

2023-02-22 02:52 UTC, ice-orion commented on src/store/modules/Analytics/reducer/index.ts
> +      case AnalyticsActions.CLEAN_ANALYTICS_STATE.STATE.type:
No need to create separate action for this - all other modules that has to be cleaned on logout are subscribed to `AccountActions.SIGN_OUT.SUCCESS` directly, e.g. Accounts module:
```
case AccountActions.SIGN_OUT.SUCCESS.type: {
        return {
          ...INITIAL_STATE,
        };
      }
```

2023-02-22 02:52 UTC, ice-orion commented on src/store/modules/Account/sagas/userStateChange.ts
> +        yield put(AnalyticsActions.TRACK_SIGN_IN.START.create({user}));
Don't you call `TRACK_SIGN_IN.START` twice? Here and on line 32?

2023-02-22 02:52 UTC, ice-orion commented on src/store/modules/Analytics/utils/utils.ts
> +export function getEnabledNotificationDomains(
Consider using `selectors` instead of `utils` if you need to encapsulate some data fetching / manipulating from the store. e.g. `enabledNotificationDomainsSelector('pushNotificationSettings') -> grabs NotificationDomainToggles by the given key and returns array of enabled domains`. Utils are usually for something more generic.
If you still going to use utils, please give the file some meaningful name (by domain or by function name)

2023-02-22 02:52 UTC, ice-orion commented on src/store/modules/PushNotifications/hooks/useInitNotifications.tsx
> +  }, [dispatch, hasPushPermissions, userId]);
Why do you add userId to dep's here?
If only to trigger `DeviceActions.UPDATE_DEVICE_METADATA` then it's better to extract it from here and create a  a separate hook and place it to Devices module, something like
```
useEffect(() => {
 dispatch(
      DeviceActions.UPDATE_DEVICE_METADATA.START.create({forceUpdate: true}),
    );
}, [dispatch, hasPushPermissions, userId])
```
Because now the device and push logic is mixed here

2023-02-22 08:19 UTC, ice-hades commented on src/store/modules/PushNotifications/hooks/useInitNotifications.tsx
> +  }, [dispatch, hasPushPermissions, userId]);
To trigger MoE methods. Testing should that after we logout and login back we need to trigger those methods or notifications won't be enabled for the new user

2023-02-22 08:43 UTC, ice-orion commented on src/store/modules/PushNotifications/hooks/useInitNotifications.tsx
> +  }, [dispatch, hasPushPermissions, userId]);
I see... Probably `ReactMoE.registerForPush` sends apns token for the new user set bt `ReactMoE.setUserUniqueID`. But anyway i would suggest to extract dispatching `DeviceActions.UPDATE_DEVICE_METADATA.START` from here since we don't need to dispatch it when user logs off and when user logs in

2023-02-24 16:18 UTC, ice-hades commented on src/store/modules/PushNotifications/hooks/useInitNotifications.tsx
> +  }, [dispatch, hasPushPermissions, userId]);
It all handled in the PR for pushes

2023-02-24 16:47 UTC, ice-ares approved these changes

2023-02-27 02:01 UTC, ice-orion approved these changes

2023-02-27 09:40 UTC, ice-atlas approved these changes

2023-02-27 09:51 UTC, merged