sentry errors
ice-blockchain/mobile-app pull request #158
Opened 2023-02-22 06:55 UTC by ice-orion

work in progress

2023-02-22 13:38 UTC, ice-atlas approved these changes

2023-02-22 16:18 UTC, ice-ares approved these changes

2023-02-23 08:33 UTC, ice-atlas requested changes

2023-02-23 08:33 UTC, ice-atlas commented on src/store/rootSaga.ts
> +const isImportantError = (error: unknown) => {
`isImportantError` is not really clear name for it. Maybe smth like `isNeedToLogError`. Also nice to add `/** description */` for it :)

2023-02-23 08:33 UTC, ice-atlas commented on src/store/modules/Account/sagas/verifyBeforeUpdateEmail.ts
> +        validateError ?? getAuthErrorMessage(error) ?? getErrorMessage(error),
May we encapsulate `getAuthErrorMessage` in `getErrorMessage`?

2023-02-23 08:41 UTC, ice-ares commented on src/store/rootSaga.ts
> +const isImportantError = (error: unknown) => {
IsUnexpected

2023-02-23 12:41 UTC, ice-ares submitted a review, later dismissed

2023-02-23 12:41 UTC, ice-ares commented on src/utils/phoneNumber.ts
> -export const e164PhoneNumber = (
Why? U still need e164 for firebase as well

2023-02-23 14:12 UTC, ice-orion commented on src/utils/phoneNumber.ts
> -export const e164PhoneNumber = (
i actually removed `beautifyPhoneNumber` method -> git diff shows it weird and `e164PhoneNumber` is now below this change

2023-02-23 15:13 UTC, ice-orion commented on src/store/rootSaga.ts
> +const isImportantError = (error: unknown) => {
done

2023-02-23 15:25 UTC, ice-ares approved these changes

2023-02-23 16:27 UTC, ice-atlas approved these changes

2023-02-24 08:18 UTC, ice-hector approved these changes

2023-02-24 08:18 UTC, merged