chore: move cards rendering and update device metadata after splash disappear
ice-blockchain/mobile-app pull request #159
Opened 2023-02-22 11:30 UTC by ice-hector

2023-02-22 13:31 UTC, ice-atlas requested changes

2023-02-22 13:31 UTC, ice-atlas commented on src/store/modules/AppCommon/actions/index.ts
> +    SUCCESS: true,
`SUCCESS` -> `HIDE`? Otherwise hard to get meaning

2023-02-22 16:17 UTC, ice-ares approved these changes

2023-02-23 02:44 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCard/index.tsx
> +        <CardLoading />
Do we really need `CardLoading`? When !isSplashHidden we don't see this component anyway?

2023-02-23 02:46 UTC, ice-orion commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +      isSplashHidden &&
I think you need to add AppCommon.UPDATE_SPLASH_SCREEN_HIDDEN to the saga trigger actions. Otherwise it wont run on app open

2023-02-23 11:16 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCard/index.tsx
> +        <CardLoading />
Agree, we have empty space on that case but not for all, let me review it little bit, will definitely remove that one

2023-02-23 11:20 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCard/index.tsx
> +        <CardLoading />
Removed it at all, just remained `{isSplashHidden && ()}` everywhere

2023-02-23 11:27 UTC, ice-hector commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +      isSplashHidden &&
Good catch, added

2023-02-23 12:00 UTC, ice-orion approved these changes

2023-02-23 12:31 UTC, ice-ares approved these changes

2023-02-23 13:08 UTC, ice-atlas approved these changes

2023-02-23 13:51 UTC, merged