Feature/ping friends popup
ice-blockchain/mobile-app pull request #162
Opened 2023-08-09 10:22 UTC by ice-hector

2023-08-10 09:41 UTC, ice-hades commented on src/screens/Modals/PingFriendsPopUp/components/CloseButton/index.tsx
> +      onPress={() => {
you can pass just onPress={onPress} should be now TS errors

2023-08-10 14:11 UTC, ice-atlas requested changes

2023-08-10 14:11 UTC, ice-atlas commented on src/store/modules/Referrals/sagas/pingReferralSaga.ts
> +    yield delay(1000);
Let's use https://redux-saga.js.org/docs/api#alleffects---parallel-effects for this.
It will allow us to wait for both and if `pingUser` gonna take more than 1 sec then do not waste 1 more sec. So we gonna wait 1 sec or more, but not `ping time` + `1 sec`

2023-08-10 14:11 UTC, ice-atlas commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +        ReferralsActions.GET_REFERRALS({referralType: 'T1'})(null).START.create(
Do we need to wait for end of this operation or may just proceed to next iteration?

2023-08-10 14:11 UTC, ice-atlas commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +      yield put(ReferralsActions.UPDATE_PING_COUNTER.STATE.create());
What if `FAILED`? Is it OK to do the same for both?

2023-08-10 14:11 UTC, ice-atlas commented on src/store/modules/Referrals/actions/index.ts
> +  START: () => {},
`START: true`?

2023-08-10 14:11 UTC, ice-atlas commented on src/screens/Modals/PingFriendsPopUp/hooks/useFriendsListRenderItems.tsx
> +export const useFriendsListRenderItems = () => {
Do we really need this hook?

2023-08-10 14:11 UTC, ice-atlas commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +      reset: take(ReferralsActions.PING_FRIENDS.RESET.type),
Check example how it can be done in solid way https://redux-saga.js.org/docs/advanced/TaskCancellation. I think we need to do smth similar with `yield fork(X)` and `yield cancel(X)`

2023-08-10 14:16 UTC, ice-hector commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +        ReferralsActions.GET_REFERRALS({referralType: 'T1'})(null).START.create(
We need to wait according to UI

2023-08-10 14:17 UTC, ice-hector commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +      yield put(ReferralsActions.UPDATE_PING_COUNTER.STATE.create());
Yep, it was designed this way before, even for failed ping we set locally that user is pinged

2023-08-10 14:24 UTC, ice-atlas commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +        ReferralsActions.GET_REFERRALS({referralType: 'T1'})(null).START.create(
But now code will sent action and continue. So need to add it

2023-08-10 14:29 UTC, ice-hector commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +      reset: take(ReferralsActions.PING_FRIENDS.RESET.type),
We already use this approach in project on other places so I prefer to keep it same everywhere

2023-08-10 14:30 UTC, ice-hector commented on src/screens/Modals/PingFriendsPopUp/hooks/useFriendsListRenderItems.tsx
> +export const useFriendsListRenderItems = () => {
Removed

2023-08-10 14:41 UTC, ice-atlas commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +      reset: take(ReferralsActions.PING_FRIENDS.RESET.type),
So maybe it make sense to do it by officially suggested way. Because in proposed solution you gonna cancel right away and don't wait extra time on every iteration

2023-08-11 07:23 UTC, ice-orion commented on src/screens/Modals/PingFriendsPopUp/components/FriendsList/index.tsx
Let's stick to Referrals naming instead of "friends" for consistency

2023-08-11 07:23 UTC, ice-orion commented on src/screens/Modals/PingFriendsPopUp/hooks/useFriendsListRenderItems.tsx
> +export const useFriendsListRenderItems = () => {
Seems to be still there

2023-08-11 07:23 UTC, ice-orion commented on src/store/modules/Referrals/actions/index.ts
> +  START: () => {},
@ice-hector please write some comment when closing a thread, especially if no changes were applied

2023-08-11 07:23 UTC, ice-orion commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +      reset: take(ReferralsActions.PING_FRIENDS.RESET.type),
@ice-atlas good point, but both approaches are pretty similar and i don't see any advantages of one over another. Our current approach is also from the docs - https://redux-saga.js.org/docs/api#raceeffects

2023-08-11 07:23 UTC, ice-orion commented on src/screens/Modals/PopUp/components/Title/index.tsx
> -    marginTop: rem(12),
It is removed intentionally?

2023-08-11 07:23 UTC, ice-orion commented on src/screens/Modals/PingFriendsPopUp/components/FriendsList/index.tsx
> +    width: windowWidth - POPUP_SIDE_OFFSET * 2,
It's better not to rely on some constants where possible - e.g. in this case you can do it in a flexible way:
1. Remove this row
2. Remove `alignItems: 'center'` from the outer container
2. Wrap only the Title with a View with `alignItems: 'center'`
3. Done. If any outer styles are changed, you won't need to adjust the styles of the children

2023-08-11 07:23 UTC, ice-orion commented on src/translations/locales/en.json
> +    "title": "Please wait while we ping all your friends · {{count}}"
If i remember correctly we need to translate it to all lagns

2023-08-11 08:17 UTC, ice-atlas commented on src/store/modules/Referrals/sagas/pingFriendsSaga.ts
> +      reset: take(ReferralsActions.PING_FRIENDS.RESET.type),
@ice-orion not really the same. In example we wait for `RESET` OR for `result of operation`, but in current implementation we wait for `DELAY` or `RESET`, so while operation in progress we do not care about `RESET`

2023-08-11 15:29 UTC, ice-hector commented on src/store/modules/Referrals/actions/index.ts
> +  START: () => {},
sorry not pushed, fixed that

2023-08-11 15:30 UTC, ice-hector commented on src/screens/Modals/PopUp/components/Title/index.tsx
> -    marginTop: rem(12),
yep we don't need it any more, popup container has its own padding

2023-08-12 07:23 UTC, ice-hector commented on src/screens/Modals/PingFriendsPopUp/components/FriendsList/index.tsx
Ok, renamed everywhere

2023-08-23 12:01 UTC, ice-atlas submitted a review, later dismissed

2023-08-30 07:12 UTC, ice-orion commented on src/components/ListItems/UserListItem/components/UserListPingButton/index.tsx
> +  const isDisabled = pinged;
It seems to be redundant to create another variable to store the same

2023-08-30 07:20 UTC, ice-orion commented on src/screens/Modals/PingReferralsPopUp/components/ReferralsList/index.tsx
> +      data={data.slice(0, MAX_PINGED_REFS)}
`referralsToShowForPingSelector` already incapsulates the logic to return only `MAX_PINGED_REFS`, so no need to slice here again

2023-08-30 07:21 UTC, ice-orion commented on src/store/modules/Referrals/selectors/index.ts
> +export const MAX_PINGED_REFS = 4;
we have `src/constants`, let's place this constant somewhere there?

2023-08-30 07:26 UTC, ice-orion commented on src/store/modules/Referrals/sagas/pingReferralsSaga.ts
> +  } finally {
why do we need this `finally` block?

2023-08-30 07:30 UTC, ice-orion commented on src/store/modules/Referrals/sagas/pingReferralsSaga.ts
> +    while (true) {
Do we need `while(true)` here?
And if `nextUserIdToPing` is null, we'll stuck in infinity loop

2023-08-30 10:03 UTC, ice-hector commented on src/store/modules/Referrals/sagas/pingReferralsSaga.ts
> +  } finally {
That's the default saga cancel flow implementation that we discussed in previous comments. I put the comment there, if we need to add some extra logic on cancel in the future it can be done there

2023-08-30 10:07 UTC, ice-orion commented on src/store/modules/Referrals/sagas/pingReferralsSaga.ts
> +  } finally {
I would suggest do not add a code that do nothing. If we ever need some extra logic on cancel we will add it

2023-08-30 10:08 UTC, ice-hector commented on src/store/modules/Referrals/sagas/pingReferralsSaga.ts
> +    while (true) {
Yeah, we need while(true) there, we run the code cyclically in this saga and waiting for each code line completion.

As for `nextUserIdToPing` good catch, I added else there with ping referrals session reset for that case

2023-08-30 10:15 UTC, ice-hector commented on src/store/modules/Referrals/sagas/pingReferralsSaga.ts
> +  } finally {
Ok removed

2023-08-30 10:20 UTC, ice-hades submitted a review, later dismissed

2023-08-30 10:22 UTC, ice-orion commented on src/store/modules/Referrals/sagas/pingReferralsSaga.ts
> +      if (data.length > 0) {
what if `data.length === 0` and `hasNext===false`, we'll still be in infinity while-true

2023-08-30 10:42 UTC, ice-atlas commented on src/store/modules/Referrals/reducer/index.ts
> +        draft.pingCounter = draft.pingCounter + 1;
why we need `pingCounter`? We may use `count of pinged users` from `pingSessionUsers`

2023-08-30 10:47 UTC, ice-atlas commented on src/store/modules/Referrals/selectors/index.ts
> +  (referrals, options) => {
Do not use `options` as is, it will be recreated on every call. Get every option separatly and get `option1, option2, ...` as param here

2023-08-30 10:47 UTC, ice-atlas commented on src/store/modules/Referrals/selectors/index.ts
> +  (referrals, options) => {
Same here for `options`

2023-09-01 10:40 UTC, ice-hector commented on src/store/modules/Referrals/sagas/pingReferralsSaga.ts
> +      if (data.length > 0) {
Changed the bottom condition from
` if (data.length === 1 && !hasNext) {`

to 

`if (data.length <= 1 && !hasNext)`

should be good

2023-09-01 13:34 UTC, ice-hector commented on src/store/modules/Referrals/reducer/index.ts
> +        draft.pingCounter = draft.pingCounter + 1;
pingSessionUsers is all the user IDs we have (for ping session) including future pings, so on the first ping it can be like 20 in the array. It's much easier to manage it separately plus I can control which moment to update it (and which moment the UI update will happen basically, so I prefer to keep it as is

2023-09-01 13:40 UTC, ice-orion approved these changes

2023-09-01 13:45 UTC, ice-hades approved these changes

2023-09-01 14:31 UTC, ice-atlas approved these changes

2023-09-01 18:26 UTC, merged