Feature/face auth
ice-blockchain/mobile-app pull request #169
Opened 2023-09-15 12:55 UTC by ice-hades

2023-10-09 11:38 UTC, ice-hector commented on .github/workflows/CICD.yaml
> -          if [[ ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false}} == true ]]
Why did we change the Ci/CD flow, was that a requirement?

2023-10-09 12:07 UTC, ice-orion commented on .github/workflows/CICD.yaml
> +          echo "APP_VERSION=9.9.9" >> $GITHUB_ENV
Don't forget to revert this

2023-10-09 12:07 UTC, ice-orion commented on patches/expo-camera+13.7.0.patch
> +diff --git a/node_modules/expo-camera/android/src/main/java/expo/modules/camera/CameraViewModule.kt b/node_modules/expo-camera/android/src/main/java/expo/modules/camera/CameraViewModule.kt
Can u please add a comment / link to an issue here (as in the patches for @react-native-firebase+auth / react-native-share )

2023-10-09 12:07 UTC, ice-orion commented on src/api/faceRecognition/constants.ts
> +export const FACE_RECOGNITION_PICTURE_SIZE = 224;
We have a `constants` folder in the root, may be move it there?

2023-10-09 12:07 UTC, ice-orion commented on src/api/faceRecognition/emotionsAuth.ts
> +        Platform.OS === 'android'
May be move this logic of processing the url to some function in `@utils/file`?
It is used in several places.

2023-10-09 12:07 UTC, ice-orion commented on src/assets/svg/FaceAuthIcon.tsx
> +  <Svg width="24" height="24" viewBox="0 0 24 24" fill="none" {...props}>
rem for sizes?

2023-10-09 12:07 UTC, ice-orion commented on src/components/CountrySelectFeed/index.tsx
> +      keyboardVerticalOffset={isIOS ? 57 : 0} // presentation: modal top offset on iOS
In case of FaceRecognition flow, this component is rendered not in the "presentation: modal" screen, is it? There should be incorrect offset above the keyboard on iOS in this case.

2023-10-09 12:07 UTC, ice-orion commented on src/components/CountrySelectFeed/index.tsx
> +export function CountrySelectFeed({onSelect, dontShowPhoneCodes}: Props) {
May be place this component to the `screens/Templates`? `components` usually for small / reusable widgets, but `templates` is for the screens that might be reused - like this one.

2023-10-09 12:07 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/index.tsx
> +      setCurrentVideoCountdown(dayjs.duration(VIDEO_DURATION_SEC, 'seconds'));
we have a hook `src/hooks/useCountdown.ts`, can't we reuse it here?

2023-10-09 12:07 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/index.tsx
> +const VIDEO_DURATION_SEC = 5; // 5 seconds
may be put that to `src/constants/faceRecognition`?

2023-10-09 12:07 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/FaceAuthCameraFeed/components/PictureSentStep/index.tsx
> +    transform: [{scaleX: -1}],
I think u can use `...StyleSheet.absoluteFillObject` instead of position+width+height.
And why `transform: [{scaleX: -1}]`?

2023-10-09 12:07 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/FaceAuthCameraFeed/components/PictureSentStep/index.tsx
> +    height: '100%',
It seems `...StyleSheet.absoluteFillObject` should do the trick here

2023-10-09 12:07 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/FaceAuthCameraFeed/components/SendOrRetakeStep/index.tsx
> +  const sendPicture = async () => {
doesn't really matter, but it seems `async` is redundant here

2023-10-09 12:07 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/CountrySelect/index.tsx
> +            onContinue();
Shouldn't we wait for successful user update before going forward?

2023-10-09 12:07 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/components/CameraFeed/CameraFeed.tsx
> +export const ASPECT_RATIO_WIDTH = 9;
Don't we need to check if the device supports 16:9 camera ratio with [this](https://docs.expo.dev/versions/latest/sdk/camera/#getsupportedratiosasync) prior setting it?
What happens if u set a ratio that is not supported by the device?

2023-10-09 12:07 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/components/CameraFeed/CameraFeed.tsx
> +import {useCameraPermissions} from '@screens/Modals/QRCodeScanner/hooks/useCameraPermissions';
Let's move this hook to the common place - `hooks/useCameraPermissions`. It is generally a bad idea to import something from another screen.

2023-10-09 12:07 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/components/StatusOverlay/index.tsx
> +    height: '100%',
`StyleSheet.absoluteFillObject`

2023-10-09 12:07 UTC, ice-orion commented on src/store/modules/FaceRecognition/sagas/fetchEmotionsForAuth.ts
> +        axios.isAxiosError(error) &&
let's create an util func for that and use it in both places - check `is4xxApiError` in `src/api/client/index.ts` for example

2023-10-09 12:07 UTC, ice-orion commented on src/store/modules/FaceRecognition/sagas/fetchEmotionsForAuth.ts
> +      axios.isAxiosError(error) &&
Can't you use `isApiError(error, null, 'USER_DISABLED')` here and in all other places where u're using `axios.isAxiosError`? And usually we're also checking the error status in addition to the error code (second parameter of the `isApiError` util func - e.g. `isApiError(error, 404, 'USER_NOT_FOUND')`).

Anyway using of `axios` lib should be encapsulated in the `src/api/...`.

And what's the point of checking both `error.code` and `error.response.data.code`? When the BE sends an error code, we're relying only on `error.response.data.code` in all other places in the app. Is there a case when it comes as `error.code`?

2023-10-09 12:07 UTC, ice-orion commented on src/utils/array.ts
> +export function returnSecondIfNew<T>(a1: T[], a2: T[]) {
May be name it something like `returnSecondIfDifferent`? `New` sounds confusing.
But in general i would recommend just to write `deepCompare(array1, array2)` and use it like
```
deepCompare(array1, array2) ? array1 : array2
```
Since this is an util func but `returnSecondIfNew` looks too case-specific.

2023-10-09 12:24 UTC, ice-hector commented on src/assets/images/index.ts
> +    anger: require('./emotions/anger.gif'),
Lets store related emotions/previews together, would be easier to add support them in future

anger: require('./emotions/anger.gif'), 
anger_preview: require('./emotions/anger_preview.jpg'),
contempt: require('./emotions/contempt.gif'),
contempt_preview: require('./emotions/contempt_preview.jpg')

etc.

2023-10-09 12:27 UTC, ice-hector commented on src/components/CountrySelectFeed/index.tsx
> +    ...font(17, 22, 'regular', 'codeFieldText'),
We don't name colors to be related to some components, pls use this service
https://chir.ag/projects/name-that-color

2023-10-09 12:29 UTC, ice-hector commented on src/navigation/components/Header/components/BackButton.tsx
> +  onGoBack?: () => void;
onBack ?

2023-10-09 12:30 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/EmotionsSentStep/index.tsx
> +  const onBanned = () => {
Please add extra spaces between functions to make them more readable here

2023-10-09 12:35 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/components/EmotionCard/index.tsx
> +  switch (emotion) {
you don't need this switch... its only one line

`return showPreview ? Images. emotions[emotion] : Images.emotions[`${emotion}_preview`]`

Follow the same approach like in `Profile/components/Role/index.tsx`

2023-10-09 12:38 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/components/EmotionCard/index.tsx
> +  switch (emotion) {
Same here, can we do only one line?

t(`face_auth.emotions_recognition.emotions.${emotion}`)

2023-10-09 12:41 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/CountrySelect/index.tsx
> +            onContinue();
he means 

*wait

2023-10-09 12:48 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/CountrySelect/index.tsx
> +    width: windowWidth / 2 - FOOTER_PADDING_HORIZONTAL - rem(16),
Pls move to constants, you use the same calculations twice

2023-10-09 12:48 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/UserConsent/index.tsx
> +    width: windowWidth / 2 - FOOTER_PADDING_HORIZONTAL - rem(16),
even not twice. Check previous comment, its 4 times already so definitely move to constants

Same for FOOTER_PADDING_HORIZONTAL - you specified it already twice and with the same value, move to constants

2023-10-09 12:48 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/index.tsx
> +        // TODO: update BE
Should we keep this `// TODO:` and merge it to master?

2023-10-09 12:48 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/index.tsx
> +      return 'USER_CONSENT';
Maybe it would be better to create ENUM for these string values?

2023-10-09 12:48 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/index.tsx
> +  const isBanned =
Add please some spacing here, its hard to read

2023-10-09 12:48 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/index.tsx
> +  const [faceRecognitionPhase, setFaceRecognitionPhase] =
Add please some spacing here, its hard to read

2023-10-09 12:48 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/index.tsx
> +  useEffect(() => {
Add please some spacing here, its hard to read

2023-10-09 12:48 UTC, ice-hector commented on src/screens/FaceRecognitionFlow/index.tsx
> +        onGoBack();
onBack?

2023-10-09 14:14 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/CountrySelect/index.tsx
> +            onContinue();
right, thanks, updated :)

2023-10-09 14:46 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/index.tsx
> +      setCurrentVideoCountdown(dayjs.duration(VIDEO_DURATION_SEC, 'seconds'));
doesn't fit this case

2023-10-09 14:48 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/FaceAuthCameraFeed/components/PictureSentStep/index.tsx
> +    transform: [{scaleX: -1}],
we take the picture from the frontal camera. it is mirrored

2023-10-09 14:51 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/CountrySelect/index.tsx
> +            onContinue();
it is not a requirement. but how we can do it anyway?

2023-10-09 15:30 UTC, ice-hades commented on src/components/CountrySelectFeed/index.tsx
> +    ...font(17, 22, 'regular', 'codeFieldText'),
I didn't add or name the color `codeFieldText`

2023-10-09 15:31 UTC, ice-hades commented on src/navigation/components/Header/components/BackButton.tsx
> +  onGoBack?: () => void;
called it `onGoBack ` because it is called before `navigation.goBack()`

2023-10-09 15:36 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/components/EmotionCard/index.tsx
> +  switch (emotion) {
here not. should be static to pass checks

2023-10-09 15:39 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/index.tsx
> +      return 'USER_CONSENT';
it is a number from BE

2023-10-09 15:41 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/index.tsx
> +        onGoBack();
onGoBack here because passed to onGoBack={onGoBack}

2023-10-09 16:12 UTC, ice-hades commented on .github/workflows/CICD.yaml
> -          if [[ ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false}} == true ]]
fixed

2023-10-09 16:12 UTC, ice-hades commented on .github/workflows/CICD.yaml
> +          echo "APP_VERSION=9.9.9" >> $GITHUB_ENV
fixed

2023-10-09 16:12 UTC, ice-hades commented on src/api/faceRecognition/constants.ts
> +export const FACE_RECOGNITION_PICTURE_SIZE = 224;
fixed

2023-10-09 16:12 UTC, ice-hades commented on src/assets/svg/FaceAuthIcon.tsx
> +  <Svg width="24" height="24" viewBox="0 0 24 24" fill="none" {...props}>
fixed

2023-10-09 16:12 UTC, ice-hades commented on src/components/CountrySelectFeed/index.tsx
> +export function CountrySelectFeed({onSelect, dontShowPhoneCodes}: Props) {
fixed

2023-10-09 16:12 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/index.tsx
> +const VIDEO_DURATION_SEC = 5; // 5 seconds
fixed

2023-10-09 16:12 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/FaceAuthCameraFeed/components/PictureSentStep/index.tsx
> +    transform: [{scaleX: -1}],
fixed

2023-10-09 16:13 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/FaceAuthCameraFeed/components/SendOrRetakeStep/index.tsx
> +  const sendPicture = async () => {
fixed

2023-10-09 16:13 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/components/CameraFeed/CameraFeed.tsx
> +export const ASPECT_RATIO_WIDTH = 9;
fixed

2023-10-09 16:13 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/components/CameraFeed/CameraFeed.tsx
> +import {useCameraPermissions} from '@screens/Modals/QRCodeScanner/hooks/useCameraPermissions';
fixed

2023-10-09 16:13 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/components/StatusOverlay/index.tsx
> +    height: '100%',
fixed

2023-10-09 16:13 UTC, ice-hades commented on src/store/modules/FaceRecognition/sagas/fetchEmotionsForAuth.ts
> +        axios.isAxiosError(error) &&
fixed

2023-10-09 16:13 UTC, ice-hades commented on src/store/modules/FaceRecognition/sagas/fetchEmotionsForAuth.ts
> +      axios.isAxiosError(error) &&
fixed

2023-10-09 16:15 UTC, ice-hades commented on src/utils/array.ts
> +export function returnSecondIfNew<T>(a1: T[], a2: T[]) {
fixed

2023-10-09 16:15 UTC, ice-hades commented on src/assets/images/index.ts
> +    anger: require('./emotions/anger.gif'),
fixed

2023-10-09 16:15 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/EmotionsSentStep/index.tsx
> +  const onBanned = () => {
fixed

2023-10-09 16:15 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/CountrySelect/index.tsx
> +    width: windowWidth / 2 - FOOTER_PADDING_HORIZONTAL - rem(16),
fixed

2023-10-09 16:15 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/UserConsent/index.tsx
> +    width: windowWidth / 2 - FOOTER_PADDING_HORIZONTAL - rem(16),
fixed

2023-10-09 16:15 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/index.tsx
> +        // TODO: update BE
fixed

2023-10-09 16:15 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/index.tsx
> +  const isBanned =
fixed

2023-10-09 16:16 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/index.tsx
> +  useEffect(() => {
fixed

2023-10-09 16:16 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/index.tsx
> +  const [faceRecognitionPhase, setFaceRecognitionPhase] =
fixed

2023-10-09 16:16 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/components/EmotionCard/index.tsx
> +  switch (emotion) {
fixed

2023-10-09 16:16 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/FaceAuthCameraFeed/components/PictureSentStep/index.tsx
> +    height: '100%',
fixed

2023-10-09 16:16 UTC, ice-hades commented on src/components/CountrySelectFeed/index.tsx
> +      keyboardVerticalOffset={isIOS ? 57 : 0} // presentation: modal top offset on iOS
fixed

2023-10-09 16:17 UTC, ice-hades commented on src/api/faceRecognition/emotionsAuth.ts
> +        Platform.OS === 'android'
fixed

2023-10-09 16:18 UTC, ice-hades commented on patches/expo-camera+13.7.0.patch
> +diff --git a/node_modules/expo-camera/android/src/main/java/expo/modules/camera/CameraViewModule.kt b/node_modules/expo-camera/android/src/main/java/expo/modules/camera/CameraViewModule.kt
it is not taken from any issue

2023-10-09 16:22 UTC, ice-hector commented on src/components/CountrySelectFeed/index.tsx
> +    ...font(17, 22, 'regular', 'codeFieldText'),
But 4th param in font() is a color, no?

2023-10-09 16:27 UTC, ice-orion commented on patches/expo-camera+13.7.0.patch
> +diff --git a/node_modules/expo-camera/android/src/main/java/expo/modules/camera/CameraViewModule.kt b/node_modules/expo-camera/android/src/main/java/expo/modules/camera/CameraViewModule.kt
ok, then probably a comment why we need this patch

2023-10-09 16:38 UTC, ice-hector commented on src/components/CountrySelectFeed/index.tsx
> +    ...font(17, 22, 'regular', 'codeFieldText'),
No matter who added it, just rename it pls

2023-10-09 16:44 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/CountrySelect/index.tsx
> +            onContinue();
Are you sure it is not? Currently even tho the request fails, we treat this step as successfully completed.
How we can do it - easiest way is to listen to `isSuccessSelector` for this action i think.

2023-10-09 16:49 UTC, ice-orion commented on src/screens/FaceRecognitionFlow/components/CameraFeed/CameraFeed.tsx
> +          ratio={cameraRatio}
Is it correct that the `cameraRatio` is set to `16:9` even before the `getSupportedRatiosAsync` is executed (default value)?
Won't it crash if the device doesn't support it?

2023-10-10 06:49 UTC, ice-hades commented on patches/expo-camera+13.7.0.patch
> +diff --git a/node_modules/expo-camera/android/src/main/java/expo/modules/camera/CameraViewModule.kt b/node_modules/expo-camera/android/src/main/java/expo/modules/camera/CameraViewModule.kt
fixed

2023-10-10 06:49 UTC, ice-hades commented on src/components/CountrySelectFeed/index.tsx
> +    ...font(17, 22, 'regular', 'codeFieldText'),
fixed

2023-10-10 06:49 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/components/CameraFeed/CameraFeed.tsx
> +          ratio={cameraRatio}
fixed

2023-10-10 09:57 UTC, ice-ares requested changes

2023-10-10 09:57 UTC, ice-ares commented on src/api/user/types.ts
> +  repeatableKycSteps?: number[];
This is a json. Key is step value. Value is the timestamp

2023-10-10 09:57 UTC, ice-ares commented on src/screens/FaceRecognitionFlow/index.tsx
> +    default:
1 selfie
2 emotions

2023-10-10 09:57 UTC, ice-ares commented on src/screens/FaceRecognitionFlow/index.tsx
> +        (user?.repeatableKycSteps?.[1] ?? Number.MAX_SAFE_INTEGER) < Date.now()
Its a json

2023-10-10 10:00 UTC, ice-ares commented on src/api/user/types.ts
> +  repeatableKycSteps?: number[];
Map[KycStep][string]

2023-10-10 10:01 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/index.tsx
> +    default:
that is just for UI mapping. it respects the BE mapping. it is fine

2023-10-10 10:09 UTC, ice-ares commented on src/screens/FaceRecognitionFlow/index.tsx
> +    default:
No, because we will add 3 more steps that have nothing to do with face auth. And 3 of those will match that default

2023-10-10 10:12 UTC, ice-ares commented on src/screens/FaceRecognitionFlow/index.tsx
> +        (user?.repeatableKycSteps?.[1] ?? Number.MAX_SAFE_INTEGER) < Date.now()
Check https://github.com/ice-blockchain/web-app/blob/master/src/Components/KYC/Steps/Steps.js

2023-10-10 10:41 UTC, ice-hades commented on src/api/user/types.ts
> +  repeatableKycSteps?: number[];
it is automatically parsed. no json on JS side. objects or arrays. arrays is an object with numbers as keys. so type is correct here. but I will change it to Record<number, number>

2023-10-10 10:41 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/index.tsx
> +        (user?.repeatableKycSteps?.[1] ?? Number.MAX_SAFE_INTEGER) < Date.now()
it is automatically parsed. no json on JS side. objects or arrays. arrays is an object with numbers as keys. so type is correct here. but I will change it to Record<number, number>

2023-10-10 10:43 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/FaceAuthUserConsent/CountrySelect/index.tsx
> +            onContinue();
fixed

2023-10-10 10:45 UTC, ice-atlas commented on src/components/Avatar/Avatar.tsx
> +    const imageRef = useRef(null);
why we removed type from here?

2023-10-10 10:45 UTC, ice-atlas commented on src/store/modules/FaceRecognition/types.ts
> +export type EmotionsAuthStatus =
Let's create `type AuthStatus` and then extend it

2023-10-10 10:45 UTC, ice-atlas commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/components/EmotionCard/index.tsx
> +    : Images.emotions[emotion];
```
Images.emotions[showPreview ? `${emotion}_preview` : emotion]

2023-10-10 10:50 UTC, ice-hades commented on src/components/Avatar/Avatar.tsx
> +    const imageRef = useRef(null);
after RN-reanimated upgrade

2023-10-10 10:57 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/EmotionsAuthCameraFeed/components/GatherEmotionsStep/components/EmotionCard/index.tsx
> +    : Images.emotions[emotion];
TS7053: Element implicitly has an  any  type because expression of type  string  can't be used to index type
{   readonly anger: any;   readonly anger_preview: any;   readonly contempt: any;   readonly contempt_preview: any;   readonly disgust: any;   readonly disgust_preview: any;   readonly fear: any;   readonly fear_preview: any;   ... 7 more ...;   readonly surprise_preview: any; }
No index signature with a parameter of type 'string' was found on type '{ readonly anger: any; readonly anger_preview: any; readonly contempt: any; readonly contempt_preview: any; readonly disgust: any; readonly disgust_preview: any; readonly fear: any; readonly fear_preview: any; ... 7 more ...; readonly surprise_preview: any; }'.

2023-10-10 11:02 UTC, ice-orion submitted a review, later dismissed

2023-10-10 11:09 UTC, ice-ares commented on src/screens/FaceRecognitionFlow/index.tsx
> +        (user?.repeatableKycSteps?.[0] ?? Number.MAX_SAFE_INTEGER) < Date.now()
there is no step 0

2023-10-10 11:10 UTC, ice-ares commented on src/screens/FaceRecognitionFlow/index.tsx
> +        (user?.repeatableKycSteps?.[0] ?? Number.MAX_SAFE_INTEGER) < Date.now()
most likely u need 1 here and 2 in the `else if`

2023-10-10 11:29 UTC, ice-hades commented on src/store/modules/FaceRecognition/types.ts
> +export type EmotionsAuthStatus =
fixed

2023-10-10 11:34 UTC, ice-hades commented on src/screens/FaceRecognitionFlow/index.tsx
> +        (user?.repeatableKycSteps?.[0] ?? Number.MAX_SAFE_INTEGER) < Date.now()
fixed

2023-10-10 11:35 UTC, ice-hector approved these changes

2023-10-10 11:35 UTC, ice-orion approved these changes

2023-10-10 12:24 UTC, ice-ares approved these changes

2023-10-10 12:25 UTC, ice-atlas approved these changes

2023-10-10 12:26 UTC, merged