Feature/tasks to achievements redesign
ice-blockchain/mobile-app pull request #170
Opened 2023-03-02 08:46 UTC by ice-hector

2023-03-03 09:55 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Achievements/components/AchievementIcon/index.tsx
> +  return <>{iconForType()}</>;
```suggestion
  return iconForType;
```

2023-03-03 09:55 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievementItem.ts
> +  invite_friends: COLORS.blueViolet,
May be it would be better to keep those titles, descriptions, iconBackgrounds and Icons itself in 1 place (+ handlers)? In some constant

2023-03-03 09:55 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievementItem.ts
> +  const tabsNavigation =
can't you use 1 navigation with type `MainNavigationParams`

2023-03-03 09:55 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievements.ts
> +    useSelector(getAchievements);
achievementsSelector

2023-03-03 09:55 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievements.ts
> +  useFocusEffect(() => {
> Note: To avoid the running the effect too often, it's important to wrap the callback in useCallback before passing it to useFocusEffect as shown in the example.

https://reactnavigation.org/docs/use-focus-effect/

2023-03-03 09:55 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievements.ts
> +      JSON.stringify(currentAchievements) !== JSON.stringify(achievements)
Do we really need to do these comparisons? What is we just  run
```
 setTimeout(() => {
        setCurrentAchievements(achievements);
}, 1000);
```

Any time user focuses the screen and `achievements` are changed? --- So if you wrap the function that you pass to `useFocusEffect` in `useCallback` with dependency on `achievements`, it will work like this.

2023-03-03 09:55 UTC, ice-orion commented on src/screens/Modals/JoinTelegramPopUp/index.tsx
> +            isKeyboardShown ? {marginTop: -rem(150)} : {},
Can we user KeyboardAvoidingView here? And have you tested android? Because on android we have `android:windowSoftInputMode="adjustResize"`...

2023-03-03 09:55 UTC, ice-orion commented on src/screens/Modals/JoinTelegramPopUp/index.tsx
> +export type JoinTelegramPopUpProps = {
It makes no sense to pass all these props since this is not a common screen. You always going to pass the same values.
It would have made sense to do so it if it had been a common popup with an Input and Button and we could reuse it in different places.

Buy the way - can't we reuse the PopUp screen? Just add the Input prop that we can pass and that's it? Moreover i see you added Input to the Popup screen...

2023-03-03 09:55 UTC, ice-orion commented on src/screens/Modals/PopUp/index.tsx
> +          {!!textInputPlaceholder && (
This is not a good idea to add a specific icon and rely on `textInputPlaceholder` to show the Input... What if we need to pass another props to this input? Just add `Input?: ReactNode` prop to the popup and pass this component with all the handlers

2023-03-06 10:09 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Achievements/components/AchievementIcon/index.tsx
> +  return <>{iconForType()}</>;
Do you mean ` return iconForType(); ` ?

2023-03-06 10:14 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievements.ts
> +    useSelector(getAchievements);
You mean getAchievementsSelector?

2023-03-06 12:28 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievements.ts
> +      JSON.stringify(currentAchievements) !== JSON.stringify(achievements)
That can be changed when the backend will be connected. Right now it is some sort of mix of backend achievements fetch and local updates, that's why we have local state achievements inside the hook and such expressions

2023-03-06 12:44 UTC, ice-hector commented on src/screens/Modals/PopUp/index.tsx
> +          {!!textInputPlaceholder && (
That's my first implementation try (when I thought I can reuse PopUp). We don't need this anymore, removed.

2023-03-06 13:14 UTC, ice-hector commented on src/store/modules/Achievements/sagas/completeJoinTelegramAchievementSaga.ts
> +      user.clientData?.telegramUserHandle &&
That's the field that will be stored on the backend side, the telegram username or something like that. Also, we discussed how to name it in Slack. Right now all this flow is partly mocked so can be fully tested only when backend will be ready

2023-03-06 13:16 UTC, ice-hector commented on src/store/modules/Achievements/sagas/completeInviteFriendsAchievementSaga.ts
> +    yield put(AchievementsActions.COMPLETE_NEXT_ACHIEVEMENT.STATE.create());
Yeah. Naming is curious agree. Lets name it COMPLETE_CURRENT_ACTIVE_ACHIEVEMENT

2023-03-06 15:16 UTC, ice-ares commented on src/store/modules/Achievements/sagas/completeInviteFriendsAchievementSaga.ts
> +    total - 1 >= requiredInvitesCount
get it from t1ReferralsCount . We'll -1 it on the BE

2023-03-06 15:47 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievementItem.ts
> +  invite_friends: COLORS.blueViolet,
Moved to a separate file

2023-03-06 15:49 UTC, ice-hector commented on src/api/achievements/types.ts
> +export interface Achievement {
Thats a big renaming, modules, files, type, just everything. I thought we get rid from Tasks concept and moved to Achievements. Event rest API call called /achievements. 
So I prefer not to rename it back

2023-03-06 16:01 UTC, ice-ares commented on src/api/achievements/types.ts
> +export interface Achievement {
Like i said. Achievements is an umbrella term. A generic one, thats why the api is under /achievements.

Tasks are a kind of stuff you achieve, badges another, levels as well, etc

2023-03-06 16:02 UTC, ice-ares commented on src/api/achievements/types.ts
> +export interface Achievement {
Tasks never stopped being tasks. We just had to change what we display to get the store approvals

2023-03-06 16:48 UTC, ice-hector commented on src/store/modules/Achievements/sagas/completeInviteFriendsAchievementSaga.ts
> +  const inviteFriendsAchievement = achievements.find(
Moved to separate selector

2023-03-06 17:13 UTC, ice-hector commented on src/screens/Modals/JoinTelegramPopUp/index.tsx
> +            isKeyboardShown ? {marginTop: -rem(150)} : {},
Yeah, the keyboard avoider looks better on android. Replaced with it

2023-03-06 17:33 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Achievements/achievements.tsx
> +export const achievements: {[key in AchievementType]: AchievementInfo} = {
`achievements` -> `ACHIEVEMENTS`, because it is hardcoded stuff

2023-03-06 17:34 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Achievements/achievements.tsx
> +    title: t('home.steps.step_one.title'),
It will not be regenerated. Because translation will be taken only once. But `reload` (of the app) maybe fix this

2023-03-06 17:36 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Achievements/achievements.tsx
> +export const iconForType = (type: AchievementType) => {
Why we cannot put it just under `AchievementIcon`?

2023-03-06 17:37 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Achievements/components/AchievementItem/index.tsx
> +        active ? [styles.containerActive, commonStyles.shadow] : null,
active && [styles.containerActive, commonStyles.shadow]

2023-03-06 17:39 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Achievements/components/AchievementItem/index.tsx
> +        <Text style={active ? styles.activeTitle : styles.title}>{title}</Text>
`[styles.title, active && styles.titleActive]`

and

```
title: {
    ...font(12, 14, 'bold', 'downriver'),
  },
  titleActive: {
    color: COLORS.cornflowerBlue
  },
```

2023-03-06 17:41 UTC, ice-atlas commented on src/translations/locales/en.json
> +    "twitterUrl": "https://twitter.com/ice_blockchain"
Why we need this in translation file?

2023-03-06 17:41 UTC, ice-atlas commented on src/translations/locales/en.json
> +  "isRTL-2": "isRTL",
Remove unused keys

2023-03-06 17:55 UTC, ice-atlas requested changes

2023-03-06 17:55 UTC, ice-atlas commented on src/translations/locales/en.json
> +  "global-flag": "global.flag",
check key

2023-03-06 17:55 UTC, ice-atlas commented on src/store/modules/Achievements/selectors/hasUncompletedAchievements.ts
> +  return !!rootSelector(state).achievements.find(
use `reselect`. And try to use `some()` or `every()`

2023-03-06 17:55 UTC, ice-atlas commented on src/store/modules/Achievements/reducer/index.ts
> +  achievements: [],
`state.achievements.achievements` something bad with naming

2023-03-06 17:55 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievementItem.ts
> +      default:
remove if empty

2023-03-06 17:55 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievementItem.ts
> +export function useAchievementItem(achievement: Achievement) {
`export function useAchievementItem({type}: Achievement) {`

2023-03-07 01:46 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievements.ts
> +    useSelector(getAchievements);
Selectors are always get and the naming of selectors usually includes `select` or `selector`.
E.g. if you need to get Entity from the store - either `selectEntity` or `entitySelector` (we're using 2nd approach everywhere in the app)

2023-03-07 02:17 UTC, ice-orion commented on src/store/modules/Achievements/reducer/index.ts
> +  achievements: [],
`list:` ?

2023-03-07 11:33 UTC, ice-atlas commented on src/store/modules/Achievements/reducer/index.ts
> +  achievements: [],
maybe `.tasks` as suggested by @ice-ares, but definitely not like now

2023-03-07 11:39 UTC, ice-hector commented on src/translations/locales/en.json
> +    "twitterUrl": "https://twitter.com/ice_blockchain"
will move to links.ts

2023-03-07 12:52 UTC, ice-hector commented on src/store/modules/Achievements/reducer/index.ts
> +  achievements: [],
I'm fully renaming that module to `tasks` so will create `tasks:  list: []` redux tree structure

2023-03-07 13:31 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Achievements/achievements.tsx
> +export const iconForType = (type: AchievementType) => {
Because I was asked to put it all together. Refactored according to this structure. 
<img width="818" alt="Screenshot 2023-03-07 at 15 30 53" src="https://user-images.githubusercontent.com/96414297/223436629-7f0a3902-0e1b-464a-817c-5205fea5742a.png">

2023-03-07 15:37 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievements.ts
> +    useSelector(getAchievements);
Renamed to tasksSelector

2023-03-07 15:40 UTC, ice-hector commented on src/api/achievements/types.ts
> +export interface Achievement {
Renamed

2023-03-07 15:40 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Achievements/achievements.tsx
> +export const achievements: {[key in AchievementType]: AchievementInfo} = {
Renamed to TASKS

2023-03-07 16:06 UTC, ice-hector commented on src/store/modules/Achievements/sagas/completeInviteFriendsAchievementSaga.ts
> +    total - 1 >= requiredInvitesCount
Removed -1. Kept just `total` (the result of T1 referrals count)
`const {total} = yield select(referralsSelector({referralType: 'T1'}));`

2023-03-07 16:38 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Achievements/achievements.tsx
> +    title: t('home.steps.step_one.title'),
If we are talking about a scenario when we change the language and translations will not be changed/reloaded, I checked - the language changed in the tasks section also successfully.

2023-03-07 16:41 UTC, ice-hector commented on src/store/modules/Achievements/sagas/completeInviteFriendsAchievementSaga.ts
> +    yield put(AchievementsActions.COMPLETE_NEXT_ACHIEVEMENT.STATE.create());
You are right, I should definitely check in saga if the previous task is completed, and only after that call COMPLETE_CURRENT_ACTIVE_TASK
Connecting the API right now so will refactor that part also

2023-03-08 08:12 UTC, ice-ares commented on src/store/modules/Tasks/sagas/index.ts
> +      ReferralsActions.GET_REFERRALS({referralType: 'T1'})('T1').START.type,
Nope, just get user

2023-03-08 08:12 UTC, ice-ares commented on src/store/modules/Tasks/sagas/taskMarkCompletedSaga.ts
> +    const {name} = action.payload;
type

2023-03-08 08:12 UTC, ice-ares commented on src/translations/locales/en.json
> +    "achievements": {
Tasks

2023-03-08 08:37 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Achievements/hooks/useAchievementItem.ts
> +  claim_username: t('home.steps.step_one.title'),
Rename to `home.tasks.${type}.title` format

2023-03-08 08:44 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				CODE_SIGN_STYLE = Automatic;
Removed

2023-03-09 14:12 UTC, ice-atlas commented on src/store/modules/Tasks/sagas/completeNextTaskSaga.ts
> +    const updatedTasks = [...tasks].map((item, index) => {
Why do we need `[...tasks]` here?

2023-03-10 13:59 UTC, ice-atlas commented on src/screens/Modals/JoinTelegramPopUp/index.tsx
> +        <View style={[styles.background]}>
unwrap it `[..]` -> `styles.background`

2023-03-10 14:00 UTC, ice-atlas commented on src/screens/Modals/JoinTelegramPopUp/index.tsx
> +          <View style={[styles.container]} {...stopPropagation}>
and here

2023-03-13 08:55 UTC, ice-atlas approved these changes

2023-03-14 16:56 UTC, ice-ares commented on src/screens/HomeFlow/Home/hooks/useHomeRefresh.ts
> +  // TODO: tasks: remove when api would be connected
Do it?

2023-03-14 16:56 UTC, ice-ares commented on src/translations/locales/en.json
> +      "achievements": "ACHIEVEMENTS",
title

2023-03-14 17:09 UTC, ice-hector commented on src/translations/locales/en.json
> +      "achievements": "ACHIEVEMENTS",
tasks.title already exist

2023-03-14 17:45 UTC, ice-hector commented on src/screens/HomeFlow/Home/hooks/useHomeRefresh.ts
> +  // TODO: tasks: remove when api would be connected
Nice catch. Uncommented pull to refresh flow and removed TODO

2023-03-14 17:49 UTC, ice-ares approved these changes

2023-03-14 17:55 UTC, ice-aiolos approved these changes

2023-03-14 18:00 UTC, merged