team walkthrough
ice-blockchain/mobile-app pull request #171
Opened 2023-03-03 07:35 UTC by ice-orion

2023-03-03 10:18 UTC, ice-ares commented on src/screens/Team/components/Header/components/Info/hooks/useEarningsWalkthrough.tsx
> +        stepKey: 'earnings',
Too generic. U have 3 types of earnings there

2023-03-03 10:18 UTC, ice-ares commented on src/screens/Team/components/Header/components/Info/hooks/useReferralsWalkthrough.tsx
> +        stepKey: 'referrals',
Too generic, u have 3 types of referrals

2023-03-03 10:18 UTC, ice-ares commented on src/screens/Team/components/TierList/components/Header/components/ActiveUsers.tsx
> +        <Text style={styles.label}>{`${t('users.active')}: `}</Text>
rtl wont work with that

2023-03-03 10:18 UTC, ice-ares commented on src/screens/Team/components/TierList/components/Header/hooks/useActiveUsersWalkthrough.tsx
> +        stepKey: 'activeUsers',
Too geneic, 3 types

2023-03-03 10:18 UTC, ice-ares commented on src/store/modules/WalkThrough/sagas/showWalkThroughSaga.tsx
> +      if (action.type === WalkThroughActions.SKIP_WALK_THROUGH.STATE.type) {
Hmmm. Ask the business if we need to know when user skipped 1/all steps

2023-03-07 06:31 UTC, ice-orion commented on ios/NotificationService/NotificationService.entitlements
> +		<string>group.io.ice</string>
actually we don't need it now, will remove

2023-03-07 11:37 UTC, ice-atlas commented on src/assets/svg/NextArrow.tsx
> +export const NextArrow = (props: SvgProps) => {
`NextArrowIcon`?

2023-03-07 11:45 UTC, ice-atlas commented on src/store/modules/WalkThrough/sagas/showWalkThroughSaga.tsx
> +    yield delay(1000);
Need comment here `why?`

2023-03-07 11:46 UTC, ice-atlas commented on src/store/modules/WalkThrough/sagas/showWalkThroughSaga.tsx
> +    yield call(waitForWalkthroughStepCandidates);
May we use `waitForSelector` helper here?

2023-03-07 11:56 UTC, ice-atlas commented on src/screens/WalkThrough/components/StepCircle/hooks/useParseDescription.tsx
> +                Linking.openURL(step.link ?? '');
`if (step.link) {` -> link exists and `!==undefined`

2023-03-07 11:56 UTC, ice-atlas commented on src/screens/WalkThrough/components/StepCircle/hooks/useCirclePosition.ts
> +          return {bottom: -MAX_CIRCLE_OFFSCREEN + bottomInset};
`-MAX_CIRCLE_OFFSCREEN + bottomInset` -> `bottomInset - MAX_CIRCLE_OFFSCREEN`

2023-03-09 03:08 UTC, ice-orion commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key in WalkthroughStepKey]?: WalkThroughStepProgress};
renamed everything

2023-03-09 03:08 UTC, ice-orion commented on src/screens/Team/components/Contacts/components/ContactsList/index.tsx
> +export const ContactsListDummy = ({
moved to the walkthrough hook + renamed

2023-03-09 03:09 UTC, ice-orion commented on ios/NotificationService/NotificationService.entitlements
> +		<string>group.io.ice</string>
removed

2023-03-09 03:10 UTC, ice-orion commented on src/store/modules/WalkThrough/selectors/index.ts
> +export const isStepHasToBeShownSelector =
renamed

2023-03-09 03:32 UTC, ice-orion commented on src/store/modules/WalkThrough/sagas/showWalkThroughSaga.tsx
> +    yield call(waitForWalkthroughStepCandidates);
added new argument to `waitForSelector` cuz here, for example , we're listening for a specific action

2023-03-09 03:35 UTC, ice-orion commented on src/screens/WalkThrough/components/StepCircle/hooks/useParseDescription.tsx
> +                Linking.openURL(step.link ?? '');
Since this is a callback, typescript assumes that at this point `step.link` still might be undefined

2023-03-09 03:36 UTC, ice-orion commented on src/screens/WalkThrough/components/StepCircle/hooks/useCirclePosition.ts
> +          return {bottom: -MAX_CIRCLE_OFFSCREEN + bottomInset};
done

2023-03-09 03:36 UTC, ice-orion commented on src/screens/WalkThrough/components/StepCircle/hooks/useCirclePosition.ts
> +          return {top: -MAX_CIRCLE_OFFSCREEN + topInset};
done

2023-03-09 03:41 UTC, ice-orion commented on src/screens/Team/components/TierList/components/Header/components/ActiveUsers.tsx
> +        <Text style={styles.label}>{`${t('users.active')}: `}</Text>
rtl is currently doesn't work at all and it needs to be researched and implemented as a separate PR - currently 50% of texts + 50% of markdown doesn't support it

2023-03-09 04:52 UTC, ice-orion commented on src/store/modules/WalkThrough/sagas/showWalkThroughSaga.tsx
> +    yield delay(1000);
done

2023-03-09 08:23 UTC, ice-atlas requested changes

2023-03-09 08:23 UTC, ice-atlas commented on src/store/utils/sagas/effects.ts
> +  actionType = '*',
better not just only `string`, but `string[]` or `string`. Check `take()` type pls.

Also let's introduce optional `Options`. So we gonna have `selector` as first parameter and other config in `options` with names. Easier to use and edit. And may add `/** */` explanation for every option

2023-03-09 08:55 UTC, ice-orion commented on src/store/utils/sagas/effects.ts
> +  actionType = '*',
done

2023-03-09 09:04 UTC, ice-atlas approved these changes

2023-03-09 14:05 UTC, ice-atlas submitted a review, later dismissed

2023-03-16 10:31 UTC, ice-hades approved these changes

2023-03-17 10:10 UTC, ice-hector commented on src/screens/Team/components/Contacts/components/ModifyPhoneNumber/hooks/useModifyPhoneNumberWalkthrough.tsx
> +              onChangePhone={() => {}}
Is it not connected? Can we merge it in this state?

2023-03-17 10:15 UTC, ice-hector submitted a review, later dismissed

2023-03-17 10:25 UTC, ice-ares submitted a review, later dismissed

2023-03-17 12:03 UTC, ice-atlas commented on src/screens/Team/components/Contacts/components/ModifyPhoneNumber/hooks/useModifyPhoneNumberWalkthrough.tsx
> +              onChangePhone={() => {}}
it is just element of team walkthrough. It is `editable={false}` and used only as UI representation of real component

2023-03-17 12:08 UTC, ice-hector commented on src/screens/Team/components/Contacts/components/ModifyPhoneNumber/hooks/useModifyPhoneNumberWalkthrough.tsx
> +              onChangePhone={() => {}}
Can we make then value prop not required with default value '' (empty string) and the same for onChangePhone (make it not required)

2023-03-17 12:10 UTC, ice-atlas commented on src/screens/Team/components/Contacts/components/ModifyPhoneNumber/hooks/useModifyPhoneNumberWalkthrough.tsx
> +              onChangePhone={() => {}}
Bad idea. Then it may lead to error misuse in all other places. Here we explicitly ignore them

2023-03-17 12:33 UTC, merged