Feature/early access popup
ice-blockchain/mobile-app pull request #182
Opened 2023-03-15 09:12 UTC by ice-hector

2023-03-16 12:12 UTC, ice-atlas requested changes

2023-03-16 12:12 UTC, ice-atlas commented on src/assets/svg/AgreeIcon.tsx
> +  <Svg width={width} height={height} fill="none" {...props}>
add `viewBox`

2023-03-16 12:12 UTC, ice-atlas commented on src/assets/svg/SquareCheckboxActiveIcon.tsx
> +  <Svg width={rem(22)} height={rem(22)} fill="none" {...props}>
add `viewBox`

2023-03-16 12:12 UTC, ice-atlas commented on src/assets/svg/SquareCheckboxActiveIcon.tsx
> +        fill="#35D487"
Should it be `color`?

2023-03-16 12:12 UTC, ice-atlas commented on src/assets/svg/SquareCheckboxInactiveIcon.tsx
> +  <Svg width={rem(24)} height={rem(24)} fill="none" {...props}>
add `viewBox`

2023-03-16 12:12 UTC, ice-atlas commented on src/screens/Modals/PopUp/components/Checkbox/index.tsx
> +  onCheckboxPress: () => void;
Maybe better use `onPress` name.

2023-03-16 12:12 UTC, ice-atlas commented on src/screens/Modals/PopUp/components/PopUpButton/index.tsx
> +  onPressWithCheckbox?: (checked: boolean) => void;
We need to change the name to something more understandable, because it can be confusing

2023-03-16 12:12 UTC, ice-atlas commented on src/screens/Modals/PopUp/index.tsx
> +      imageStyle = {},
why not `null` or `undefined`?

2023-03-16 12:24 UTC, ice-ares requested changes

2023-03-16 12:24 UTC, ice-ares commented on src/api/tokenomics/getCurrentTime.ts
> +import {Time} from '@api/tokenomics/types';
Has nothing to do with tokenomics. Create a separate folder

2023-03-16 15:38 UTC, ice-hector commented on src/assets/svg/SquareCheckboxActiveIcon.tsx
> +        fill="#35D487"
Nope

2023-03-16 15:39 UTC, ice-hector commented on src/screens/Modals/PopUp/components/Checkbox/index.tsx
> +  onCheckboxPress: () => void;
onPress already taken, that's for another purposes

2023-03-16 15:39 UTC, ice-hector commented on src/screens/Modals/PopUp/components/PopUpButton/index.tsx
> +  onPressWithCheckbox?: (checked: boolean) => void;
What exactly is confusable? We already have onPress.
This onPressWithCheckbox is only responsible for the checkbox on press.

2023-03-16 15:55 UTC, ice-atlas commented on src/screens/Modals/PopUp/components/PopUpButton/index.tsx
> +  onPressWithCheckbox?: (checked: boolean) => void;
`onCheckboxPress`?

2023-03-17 10:12 UTC, ice-ares commented on src/translations/locales/en.json
> +    "checkbox_description": "I’ve acknowledge! Don’t show this pop-up again."
acknowledged

2023-03-17 10:12 UTC, ice-ares commented on src/store/modules/Tokenomics/utils/openEarlyAccess.tsx
> +            resultResolve(checkboxChecked ? 'yes' : 'no'),
What happens if its a 'no'?

2023-03-17 12:53 UTC, ice-atlas approved these changes

2023-03-17 12:54 UTC, merged