feat: ice founder twitter social popup
ice-blockchain/mobile-app pull request #243
Opened 2024-01-09 09:51 UTC by ice-orion

* Add new social popup with founder twitter
* Rework social popups rescheduling in case of adding / removing popups in config to keep the initial order

2024-01-09 09:57 UTC, ice-ares requested changes
rename zeusTwitter to iceFounderTwitter, everywhere

2024-01-09 10:54 UTC, ice-orion commented
> rename zeusTwitter to iceFounderTwitter, everywhere

done

2024-01-11 13:22 UTC, ice-ares approved these changes

2024-01-11 13:31 UTC, ice-hades approved these changes

2024-01-11 14:20 UTC, ice-hector approved these changes

2024-01-11 14:21 UTC, merged