Invite friend screen
ice-blockchain/mobile-app pull request #30
Opened 2022-06-29 20:04 UTC by ice-hector

2022-08-22 07:20 UTC, ice-orion commented on src/screens/InviteFlow/InviteShare/components/ShareButton/index.tsx
> +    switch (button.type) {
FYI: this approach violates SOLID (O) principle - https://blog.ndepend.com/solid-design-the-open-close-principle-ocp/

Optional: The button should not know how to handle each share type, cuz if we add new / remove any of the options, we'll have to modify the component. The `ShareButton` should accept only data to display and `onPress` handler and all the handlers for different types should be defined outside of the component -> something like

```
const shareOptions: ShareOption = [{title: 'google', onPress: () => {ShareMore.doStuff({uri:'...'})}, {title: '...', onPress: () => {}}]

...


shareOptions.map((o) => < ShareButtonProps ... />)
```

2022-08-22 07:20 UTC, ice-orion commented on src/screens/InviteFlow/InviteShare/components/ShareButton/index.tsx
> +    marginTop: 24,
rem?

2022-08-22 07:20 UTC, ice-orion commented on src/screens/InviteFlow/InviteShare/index.tsx
> +    width: screenWidth,
i think we don't need this

2022-08-22 07:20 UTC, ice-orion commented on src/screens/InviteFlow/InviteShare/index.tsx
> +  const {top: topInset} = useSafeAreaInsets();
yea, use `useTopOffsetStyle` hook - https://github.com/ice-blockchain/mobile-app/blob/feature/home-redesign/src/navigation/hooks/useTopOffsetStyle.ts

2022-08-22 07:20 UTC, ice-orion commented on src/screens/InviteFlow/InviteShare/index.tsx
> +  const {shadowStyle} = useScrollShadow();
In the new design the shadow is not used anymore

2022-08-22 07:20 UTC, ice-orion commented on src/screens/Team/components/Contacts/components/ContactsList/index.tsx
> +            onInvite={() => {
`ContactItem` is a pure component, anonymous functions as params break this optimization, use `onInvitePress` directly and pass Contact object (instead of id) from within the ContactItem component

2022-08-22 07:20 UTC, ice-orion commented on src/utils/percentage.ts
> +export {adoptToSmallHeight, widthPercentageToDP};
Let's discuss the necessity of those utils, i believe we can avoid the usage of those

2022-08-29 12:35 UTC, ice-orion commented on src/components/Touchable/index.tsx
>  type TouchableProps = {
just use `TouchableOpacityProps` from `react-native`

2022-08-30 07:26 UTC, ice-hector commented on src/screens/InviteFlow/InviteShare/components/ShareButton/index.tsx
> +      case 'CopyLink':
No,         
copiedRef.current?.updateVisibleState(true);
should be called here, I added

2022-08-30 10:31 UTC, ice-hector commented on src/screens/InviteFlow/InviteShare/components/Copied/index.tsx
> +            Clipboard.setString(t('invite_share.share_full_text'));
Refactored little bit but didnt move vibrate and copying because its related with animation state change

2022-08-30 10:45 UTC, ice-orion submitted a review, later dismissed

2022-08-30 11:06 UTC, ice-orion submitted a review, later dismissed

2022-08-30 11:08 UTC, ice-eros approved these changes

2022-08-30 11:16 UTC, ice-ares requested changes

2022-08-30 11:16 UTC, ice-ares commented on ios/ice.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = io.ice.app.staging;
why do we need to specify the env here? this file is gonna be used by production as well

2022-08-30 11:16 UTC, ice-ares commented on src/screens/InviteFlow/InviteFriend/components/InviteAva/index.tsx
> +// SPDX-License-Identifier: BUSL-1.1
Ava what?

2022-08-30 11:16 UTC, ice-ares commented on src/screens/InviteFlow/InviteShare/components/ShareCard/index.tsx
> +    type: 'Telegram',
u/re not using this

2022-08-30 11:16 UTC, ice-ares commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        apiLevel: apiLevel === -1 ? 1 : apiLevel,
i'd say use latest or some specific number IE. 999

2022-08-30 11:16 UTC, ice-ares commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +          firstInstallTime === -1 ? new Date().getTime() : firstInstallTime,
Date.now()

2022-08-30 11:25 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = io.ice.app.staging;
The project couldn't be built locally without this. And I guess value from .plist will be used on CI compilation (because we copy it from secrets depending on env)

2022-08-30 11:27 UTC, ice-hector commented on src/screens/InviteFlow/InviteShare/components/ShareCard/index.tsx
> +    type: 'Telegram',
What do you mean by not using? We have telegram in share options in designs and we are using it...

2022-08-30 11:27 UTC, ice-hector commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        apiLevel: apiLevel === -1 ? 1 : apiLevel,
Changed to 999

2022-08-30 11:33 UTC, ice-hector commented on src/screens/InviteFlow/InviteFriend/components/InviteAva/index.tsx
> +// SPDX-License-Identifier: BUSL-1.1
Renamed to InviteAvatar

2022-08-30 11:59 UTC, ice-ares commented on src/screens/InviteFlow/InviteShare/components/ShareCard/index.tsx
> +    type: 'Telegram',
I meant the title

2022-08-30 11:59 UTC, ice-ares commented on src/screens/InviteFlow/InviteFriend/components/InviteAva/index.tsx
> +const AVA_SIDE_DIMENSION = rem(112);
U have a lot of Ava stuff everywhere

2022-08-30 12:01 UTC, ice-ares commented on ios/ice.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = io.ice.app.staging;
u should have a npm script that replaces those with the ones from mobile secrets

2022-08-30 12:01 UTC, ice-ares commented on ios/ice.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = io.ice.app.staging;
I'd say remove this entirely

2022-08-30 12:01 UTC, ice-ares commented on ios/ice.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = io.ice.app.staging;
and any other files there are env based and are stored in mobile secrets

2022-08-30 13:16 UTC, ice-hector commented on src/screens/InviteFlow/InviteShare/components/ShareCard/index.tsx
> +    type: 'Telegram',
We use title
<img width="893" alt="Screenshot 2022-08-30 at 16 15 09" src="https://user-images.githubusercontent.com/96414297/187446542-5a9eb8b7-76c3-4f5f-b968-a6239a0704f0.png">

2022-08-31 07:30 UTC, ice-orion submitted a review, later dismissed

2022-08-31 09:02 UTC, ice-ares requested changes

2022-08-31 09:02 UTC, ice-ares commented on src/screens/InviteFlow/InviteFriend/components/InviteAvatar/index.tsx
> +const AVA_SIDE_DIMENSION = rem(112);
Cmon. Find and replace all ava stuff

2022-08-31 09:29 UTC, ice-hector commented on src/screens/InviteFlow/InviteFriend/components/InviteAvatar/index.tsx
> +const AVA_SIDE_DIMENSION = rem(112);
Sorry didnt push yesterday one commit, pushed

2022-08-31 09:55 UTC, ice-ares requested changes

2022-08-31 09:55 UTC, ice-ares commented on src/screens/InviteFlow/InviteFriend/components/InviteAvatar/index.tsx
> +  ava: {
find and replace !!!!!!

2022-08-31 10:25 UTC, ice-hector commented on src/screens/InviteFlow/InviteFriend/components/InviteAvatar/index.tsx
> +  ava: {
done

2022-08-31 10:46 UTC, ice-ares commented on src/screens/InviteFlow/InviteShare/components/ShareCard/index.tsx
> +    title: 'invite_share.telegram',
`buttons[i].title` is not used!!!!!

2022-08-31 11:12 UTC, ice-ares approved these changes

2022-09-02 09:40 UTC, ice-ares approved these changes

2022-09-02 09:51 UTC, ice-ares submitted a review, later dismissed

2022-09-02 09:55 UTC, ice-orion commented on src/assets/svg/InviteFriendIcon.tsx
> +export const InviteFriendIcon = () => {
I think we already have such icon (even duplicated) - 
`InviteFriendsSvg` `InviteIcon`

2022-09-02 11:29 UTC, ice-hector commented on src/assets/svg/InviteFriendIcon.tsx
> +export const InviteFriendIcon = () => {
Done

2022-09-02 11:30 UTC, ice-ares submitted a review, later dismissed

2022-09-02 11:41 UTC, ice-orion submitted a review, later dismissed

2022-09-02 11:45 UTC, ice-eros submitted a review, later dismissed

2022-09-02 11:53 UTC, ice-orion approved these changes

2022-09-02 11:54 UTC, ice-ares approved these changes

2022-09-02 12:11 UTC, ice-eros approved these changes

2022-09-02 12:41 UTC, merged