Notifications screen
ice-blockchain/mobile-app pull request #33
Opened 2022-07-05 13:53 UTC by pisarevkir

2022-07-11 21:46 UTC, victor-oancea-leftclick-io requested changes
Also, pls create an habbit of i18ning everything and error handling everything by default

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/screens/Dialogs/Confirm.tsx
> +  label: 'No, cancel',
I18n?

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/Notifications/components/NotificationControls/components/NotificationRow.tsx
> +          {channel}
i18n

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    //TODO:: get error message
Return a predefined i18n'd one

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +      metadata: settings,
Not metadata

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    if (!deviceUniqueId) {
Something is definitely codes wrong if you need this if. That should be set as soon as the app launches

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    const bufferedActions: Action[] = yield flush<Action>(updateChannel);
How do these work together?

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    ].reduce((summ, action) => merge(summ, action.payload), {});
Thats not a summ, its an snapshot/aggregate

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    yield put(DeviceActions.UPDATE_SETTINGS.SUCCESS.create(updatedSetings));
What are you doing with updatedSettings after this?

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/index.ts
> +    takeLatest(AppCommonActions.APP_LOADED.STATE.type, setDeviceUniqueIdSaga),
You can call this first, then the all, so you can lose the if in the other saga

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/getDeviceSettings.ts
> +    if (!deviceUniqueId) {
Cmon, this should never happen. All these checks and guards and sagas to set the uniqueDeviceId is overkill and over engineered.

UniqueDeviceId should be populated once, at the earliest moment possible in the app launch/start

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/getDeviceSettings.ts
> +    //TODO:: get error message
Predefined i18n'd error

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/reducer/index.ts
> +  rollBackSettings: DeviceSettings | null;
rollback or rolledBack

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/signInSocial.ts
> +      userId: socialLoginInfo.magic.userMetadata.issuer ?? '',
Throw some error, '' is not usable

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/signInPhone.ts
> +        userId: metadata.issuer ?? '',
Throw some error

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/Notifications/index.tsx
> +          <Text style={styles.titleText}>NOTIFICATIONS</Text>
I18n

2022-07-11 21:46 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/Notifications/components/NotificationControls/hooks/useConfirmNotificationsDlg.tsx
> +      navigation.navigate('Confirm', {
I18n

2022-07-12 06:45 UTC, pisarevkir commented on src/api/devices/types.ts
> +  | 'ACHIEVEMENTS'
they can't be fully dynamic since we keep translations on the client side and to make translations type-safe we need to keep the possible values explicitly

2022-07-12 06:51 UTC, pisarevkir commented on src/api/devices/updateDeviceSettings.ts
> +  metadata,
you're right, there was a mess with naming - fixed

2022-07-12 06:52 UTC, pisarevkir commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +      metadata: settings,
fixed -> naming issue

2022-07-12 06:55 UTC, pisarevkir commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    if (!deviceUniqueId) {
the thing is that `syncUniqueId` returns Promise, so even tho we request it right away the app launches, this value can be still null when we need it somewhere

2022-07-12 06:58 UTC, pisarevkir commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    const bufferedActions: Action[] = yield flush<Action>(updateChannel);
`flush` and `take`? `take` waits for the dispatched action or takes the next one for the buffer if the buffer is not empty, `flush` takes the rest items in buffer and cleans it.

2022-07-12 06:59 UTC, pisarevkir commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    ].reduce((summ, action) => merge(summ, action.payload), {});
agree, snapshot is good

2022-07-12 07:02 UTC, pisarevkir commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    yield put(DeviceActions.UPDATE_SETTINGS.SUCCESS.create(updatedSetings));
i save the returned value in `rollBackSettings` so if the next request is failed (the one that is buffered for example) we could roll back to that state

2022-07-12 07:05 UTC, pisarevkir commented on src/store/modules/Devices/sagas/index.ts
> +    takeLatest(AppCommonActions.APP_LOADED.STATE.type, setDeviceUniqueIdSaga),
the order does mean anything in this case - here we just define "listeners". `APP_LOADED` action will be dispatched before `GET_SETTINGS.START` but since `setDeviceUniqueIdSaga` is not sync, the execution could take time so potentially user may open the settings screen -> `GET_SETTINGS.START` will be dispatched but we won't have `deviceUniqueId` yet because `setDeviceUniqueIdSaga` is not done.

2022-07-12 07:07 UTC, pisarevkir commented on src/store/modules/Devices/reducer/index.ts
> +  rollBackSettings: DeviceSettings | null;
i would say rollback - this is the state that we WILL use in case of some error

2022-07-12 07:11 UTC, pisarevkir commented on src/store/modules/Devices/sagas/getDeviceSettings.ts
> +    //TODO:: get error message
We'll have to take error handling task at some point - there we have to handle api errors (do we need to process some statuses in some specific way) + write typesafe function to withdraw error message from "unknown" errors (and return predefined i18n error if we couldn't) + show errors in UI in some way + report to sentry if needed.

2022-07-12 07:18 UTC, pisarevkir commented on src/store/modules/Auth/sagas/signInSocial.ts
> +      userId: socialLoginInfo.magic.userMetadata.issuer ?? '',
done

2022-07-12 07:18 UTC, pisarevkir commented on src/store/modules/Auth/sagas/signInPhone.ts
> +        userId: metadata.issuer ?? '',
done

2022-07-12 07:18 UTC, pisarevkir commented on src/api/devices/updateDeviceMetadata.ts
> +  metadata: DeepPartial<DeviceMetadata>;
removed, added by mistake

2022-07-12 07:58 UTC, pisarevkir commented on src/api/devices/types.ts
> +  | 'ACHIEVEMENTS'
hm, actually i forgot that we don't have type checks for translations because of the translation nesting, but we at least can check it manually... I can remove it if you think we don't need to do so

2022-07-12 08:30 UTC, pisarevkir commented on src/screens/Dialogs/Confirm.tsx
> +  label: 'No, cancel',
done

2022-07-12 08:30 UTC, pisarevkir commented on src/screens/SettingsFlow/Notifications/components/NotificationControls/components/NotificationRow.tsx
> +          {channel}
done

2022-07-12 08:31 UTC, pisarevkir commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    //TODO:: get error message
We can setup the error handling as part of the separate task, now the stub error message is returned

2022-07-12 08:32 UTC, pisarevkir commented on src/screens/SettingsFlow/Notifications/components/NotificationControls/hooks/useConfirmNotificationsDlg.tsx
> +      navigation.navigate('Confirm', {
done

2022-07-12 08:32 UTC, pisarevkir commented on src/screens/SettingsFlow/Notifications/index.tsx
> +          <Text style={styles.titleText}>NOTIFICATIONS</Text>
done

2022-07-12 08:36 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceSettings.ts
> +    //TODO:: get error message
most likely we'll forget to do that, cuz we won't encounter it
So let's do the error handling with the business impl task itself

2022-07-12 08:36 UTC, pisarevkir commented on src/api/devices/types.ts
> +  | 'ACHIEVEMENTS'
ok, removed

2022-07-12 08:39 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/index.ts
> +    takeLatest(AppCommonActions.APP_LOADED.STATE.type, setDeviceUniqueIdSaga),
if you move the deviceUniqueId setting at the start of the app, and wait for that promise to finish everything will fall into place, and you`ll remove all that magic/boilerplate of setting/safe getting it in these sagas

2022-07-12 08:43 UTC, pisarevkir commented on src/store/modules/Devices/sagas/index.ts
> +    takeLatest(AppCommonActions.APP_LOADED.STATE.type, setDeviceUniqueIdSaga),
okay, let's do it like that

2022-07-12 08:48 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/Notifications/components/NotificationControls/components/NotificationRow.tsx
> +          {t(`notifications.channel_${channel}`)}
lower channel and I'd say start renaming every `Notification` into `NotificationSetting` cuz thats what you're doing, `Notifications` is gonna be a whole different screen
I.E.
```t(`settings.notifications.channel_${channel.toLowerCase()}`)```

2022-07-12 08:56 UTC, victor-oancea-leftclick-io commented on src/translations/i18n.ts
> +i18n.missingTranslation = (scope: string) => scope;
fix it properly, don't ignore it.

We'll have more of these use cases with missing/partial translations for a language, and it has to translate into the default language if that happens.

2022-07-12 08:58 UTC, victor-oancea-leftclick-io commented on src/translations/i18n.ts
> +i18n.missingTranslation = (scope: string) => scope;
actually, I think ur use case is that you don`t have any translation at all, which is not something that should happen.

Whenever you add add i18n stuff in the app, you need to add them into localise.biz as well for en/default locale

2022-07-12 08:58 UTC, pisarevkir commented on src/store/modules/Devices/sagas/index.ts
> +    takeLatest(AppCommonActions.APP_LOADED.STATE.type, setDeviceUniqueIdSaga),
done

2022-07-12 08:58 UTC, pisarevkir commented on src/store/modules/Devices/sagas/getDeviceSettings.ts
> +    if (!deviceUniqueId) {
done

2022-07-12 09:31 UTC, pisarevkir commented on src/translations/i18n.ts
> +i18n.missingTranslation = (scope: string) => scope;
yes, so we have 2 possible translation misses - 

1. We have it in out default lang, but don't have for some other one. In this case the lib follows this rule:
> By default missing translations will first be looked for in less specific versions of the requested locale and if that fails by taking them from your I18n#defaultLocale.

So searching in defaultLocale is done automatically (i checked)

2. We don't have a translation at all (that potentially could happen for backend-related translations, like if we added a new notification channel and the app is not updated yet and we don't want to force ppl to update the app because of that). In this case the lib by default returns the translation scope as translation, so i removed out custom `missingTranslation` fallback that does the same as the default one.

2022-07-12 09:32 UTC, pisarevkir commented on src/screens/SettingsFlow/Notifications/components/NotificationControls/components/NotificationRow.tsx
> +          {t(`notifications.channel_${channel}`)}
agree, done

2022-07-12 09:42 UTC, victor-oancea-leftclick-io commented on src/translations/i18n.ts
> +i18n.missingTranslation = (scope: string) => scope;
So, are you 100% sure that:

1. If there are no translations for they key (not even the default locale) then it defaults to the key?

2. If there are no transportation for the specific locale (not default one) then it defaults to the default locale translation?

2022-07-12 09:52 UTC, pisarevkir commented on src/translations/i18n.ts
> +i18n.missingTranslation = (scope: string) => scope;
1. It actually looks like that if there is no translation in any of the locales - 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/102020833/178462893-39ebf25b-97a6-4f50-9e6c-ef1954e61c92.png">

2. Yes, i set 'ro' as my current locale, 'en-GB' was the defaultLocale. I removed the translation from 'ro' and it took the corresponding one from 'en-GB'

2022-07-12 10:08 UTC, victor-oancea-leftclick-io submitted a review, later dismissed

2022-07-14 10:13 UTC, victor-oancea-leftclick-io submitted a review, later dismissed

2022-07-14 11:47 UTC, subbotnik16 commented on src/components/Avatar/index.tsx
> +          Platform.OS === 'android' && commonStyles.shadow,
i think we can use only one variable for both places `const isIos = Platform.OS === 'ios'` and then use it with negation

2022-07-14 11:49 UTC, subbotnik16 commented on src/components/Avatar/index.tsx
> +          Platform.OS === 'android' && commonStyles.shadow,
or we can import isIOS from 'rn-units'

2022-07-14 12:07 UTC, pisarevkir commented on src/components/Avatar/index.tsx
> +          Platform.OS === 'android' && commonStyles.shadow,
done, changed everywhere

2022-07-14 12:09 UTC, subbotnik16 submitted a review, later dismissed

2022-07-14 14:48 UTC, pisarevkir commented on src/screens/Dialogs/Confirm.tsx
> +  button_destructive: {
They are actually used, (eslint plugin can't process assembled style names and treat em like unused) :
```
styles[`button_${button.preset ?? 'default'}`]
```

2022-07-14 15:10 UTC, victor-oancea-leftclick-io submitted a review, later dismissed

2022-07-14 15:37 UTC, OlehPanforov commented on src/screens/Dialogs/Confirm.tsx
> +  button_destructive: {
I mean return exactly the style depending on type
return type === 'default' ? styles.buttonDefault : styles.buttonDestructive

2022-07-15 06:11 UTC, pisarevkir commented on src/screens/Dialogs/Confirm.tsx
> +  button_destructive: {
now i got you... yes it works :)

2022-07-15 07:01 UTC, victor-oancea-leftclick-io approved these changes

2022-07-15 08:47 UTC, OlehPanforov approved these changes

2022-07-15 08:49 UTC, subbotnik16 approved these changes

2022-07-15 08:49 UTC, merged