Fix/team screen
ice-blockchain/mobile-app pull request #36
Opened 2022-07-07 15:28 UTC by subbotnik16

2022-07-07 17:18 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/ContactsList/hooks/useGetContacts.ts
> +      title: 'iceFriends',
I18n

2022-07-08 06:49 UTC, pisarevkir commented on src/screens/Team/components/ContactsList/index.tsx
> +      const contact = contactsByIds[id];
that should be in sagas (everything below `hapticFeedback()`)

2022-07-08 07:32 UTC, subbotnik16 commented on src/screens/Team/components/ContactsList/hooks/useGetContacts.ts
> +      title: 'iceFriends',
no, we shouldn't it's just a string which i compare in the component to show a specific section header

2022-07-14 08:33 UTC, ice-ares requested changes

2022-07-14 08:33 UTC, victor-oancea-leftclick-io commented on src/store/modules/Team/sagas/inviteContactSaga.ts
> +    const text = `${t('team.contacts_list.hi')} ${contact.firstName}, ${t(
use only 1 text

2022-07-14 10:10 UTC, victor-oancea-leftclick-io approved these changes

2022-07-14 10:13 UTC, pisarevkir submitted a review, later dismissed

2022-07-14 13:35 UTC, victor-oancea-leftclick-io approved these changes

2022-07-14 13:37 UTC, OlehPanforov approved these changes

2022-07-14 14:16 UTC, merged