Feature/team screen api
ice-blockchain/mobile-app pull request #37
Opened 2022-07-13 12:26 UTC by subbotnik16

2022-07-14 08:17 UTC, victor-oancea-leftclick-io commented on src/api/user/searchUsers.ts
> +    headers: getHeaders(),
dont need it

2022-07-14 08:18 UTC, victor-oancea-leftclick-io commented on src/api/user/types.ts
> +export interface UserUpdateResult extends UserProfile {
UserAccount

2022-07-14 08:20 UTC, victor-oancea-leftclick-io commented on src/api/user/updateUser.ts
> +  formData: FormData;
can you make it typesafe?

2022-07-14 08:20 UTC, victor-oancea-leftclick-io commented on src/api/user/updateUser.ts
> +export function updateUser({userId, formData}: Params) {
modifyUser

2022-07-14 08:24 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/actions/index.ts
> +enum UserUpdateEnum {
what is this?

2022-07-14 08:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Team/actions/index.ts
> +export interface UserSearchResult {
what is this?

2022-07-15 11:45 UTC, victor-oancea-leftclick-io requested changes

2022-07-15 11:45 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/updateAccount.ts
> +    yield put(AuthActions.SET_PHONE_NUMBER_VERIFIED.STATE.create());
why is this here?

2022-07-21 09:28 UTC, pisarevkir commented on src/screens/Team/components/Header/index.tsx
> +  const search = throttle((searchQuery: string) => {
`debounce` is usually used for searches

2022-07-21 09:35 UTC, pisarevkir commented on src/api/user/updateUser.ts
> +  return patch<{formData: FormData}, Params>(`/users/${userId}`, {
user account? we already have UserProfile type (the one that is returned from createUser or getUserById) - isn't it the same?

2022-07-21 09:43 UTC, pisarevkir commented on src/screens/Team/components/Header/index.tsx
> +  const search = throttle((searchQuery: string) => {
no need to keep query in the state (`const [query, setQuery] = useState('')` + passing `query` to the Search component is excessive), 

```
const onSearch = useCallback(search, []);
```

and 

```
useEffect(() => {
    onSearch(query);
  }, [onSearch, query]);
  ```
  
  are also excessive, just pass debounced function that dispatches `SEARCH_USERS.START` as `onChangeText` of `<Search />` component and that's it

2022-07-21 11:30 UTC, victor-oancea-leftclick-io commented on src/api/user/updateUser.ts
> +  return patch<{formData: FormData}, Params>(`/users/${userId}`, {
yea, use the same type everywhere, its the exact same thing, the only difference is that some endpoints hide some fields, some don't

2022-07-21 11:32 UTC, victor-oancea-leftclick-io commented on src/api/user/updateUser.ts
> +  return patch<{formData: FormData}, Params>(`/users/${userId}`, {
user profile is a subset of visible fields within the user account, so I'd use User account everywhere and make some fields optional, cuz again, its the same entity

2022-07-22 08:16 UTC, victor-oancea-leftclick-io requested changes
We need a common/shared place for working with the phone number. UI + logic

2022-07-22 08:16 UTC, victor-oancea-leftclick-io commented on src/api/user/types.ts
> +export interface UserProfileUpdate {
Stop duplicating stuff for no reason. There is only 1 structure needed for every request under /users

2022-07-22 08:16 UTC, victor-oancea-leftclick-io commented on src/api/user/types.ts
> +export interface UserSearchInfo {
Remove it

2022-07-22 08:16 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/ContactsList/index.tsx
> +      const isFriend = invitedFriends.includes(item);
Why do you need this?

2022-07-22 08:16 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/IceUserItem/index.tsx
> +              <Image
We need a generc/shared component for displaying images

2022-07-22 08:16 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/updateAccount.ts
> +    let errorMessage = 'Failed';
Some error habdling needs to happen

2022-07-28 08:38 UTC, victor-oancea-leftclick-io requested changes

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/components/Calculator.tsx
> +import {formatAsCurrency} from '@utils/number';
Remove this, you dont need it, its gonna be string

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/components/Calculator.tsx
> +                ? `${formatAsCurrency(result)} ${t(
Just result

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +import {formatAsCurrency} from '@utils/number';
Remove this

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +          <Text style={styles.ladderValueText}>{formatAsCurrency(606683)}</Text>
String

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +            <Text style={styles.ladderValueText}>{formatAsCurrency(1024)}</Text>
String

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/Contacts/components/ConfirmCode/index.tsx
Please usw the same component in both places, this is not only for team contacts

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/updateAccount.ts
> +    const formData: FormData = new FormData();
Please, move this inside the patch client method and make everything type safe

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Referrals/actions/index.ts
> +    result: {active: number; total: number; referrals: User[]},
Create type

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Referrals/actions/index.ts
> +    offset: number,
U need limit as well, cuz the default one might be too many/too few

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Referrals/actions/index.ts
> +  SUCCESS: (history: {date: string; t1: number; t2: number}[]) => ({history}),
Create type

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Referrals/reducer/index.ts
> +      [key in ReferralType]?: {
Create type for value

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Referrals/reducer/index.ts
> +          draft.data[userId] = {
You'll have only 1 userId there, so whats the point?

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Referrals/selectors/index.ts
> +    state.referrals.data[userId]?.[referralType];
Theres only 1 userId

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/utils/phoneNumber.ts
> +  return phone;
Throw error

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/utils/phoneNumber.ts
> +} from 'libphonenumber-js/min';
Make sure this library is imported only in this file

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/utils/phoneNumber.ts
> +  return sha256(e164PhoneNumber(phone));
sha256(phone)

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/utils/phoneNumber.ts
> +    return parsePhoneNumber(phone).format('E.164');
Parsing is not enough, you need to make sure it has the country/idd code as well

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/utils/number.ts
> +export const formatAsCurrency = (input: number | string, step = 3) => {
Remove this

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Validation/sagas/phoneValidationSaga.ts
> +    const phoneNumberHash: string = yield call(hashPhoneNumber, phoneNumber);
U should have this already at this point, use a selector

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Validation/sagas/phoneValidationSaga.ts
> +import {hashPhoneNumber} from '@utils/phoneNumber';
Not needed here

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Validation/actions/index.ts
>      validationCode,
I think you need all 4 here

2022-07-28 08:38 UTC, victor-oancea-leftclick-io commented on src/store/modules/Team/sagas/searchUsersSaga.ts
> +    const {query} = action.payload;
Plus pagination

2022-07-29 11:10 UTC, pisarevkir commented on src/api/user/types.ts
> +export interface UserUpdateResult extends UserProfile {
now User type is used

2022-07-29 11:10 UTC, pisarevkir commented on src/api/user/updateUser.ts
> +  formData: FormData;
FormData is now used internally inside `modifyUser` method -> input params are typesafe

2022-07-29 11:11 UTC, pisarevkir commented on src/api/user/updateUser.ts
> +  return patch<{formData: FormData}, Params>(`/users/${userId}`, {
now the return type is `User`

2022-07-29 11:11 UTC, pisarevkir commented on src/api/user/updateUser.ts
> +export function updateUser({userId, formData}: Params) {
renamed

2022-07-29 11:11 UTC, pisarevkir commented on src/store/modules/Auth/actions/index.ts
> +enum UserUpdateEnum {
removed

2022-07-29 11:12 UTC, pisarevkir commented on src/store/modules/Team/actions/index.ts
> +export interface UserSearchResult {
now `User`

2022-07-29 11:13 UTC, pisarevkir commented on src/store/modules/Auth/sagas/updateAccount.ts
> +    yield put(AuthActions.SET_PHONE_NUMBER_VERIFIED.STATE.create());
removed

2022-07-29 11:13 UTC, pisarevkir commented on src/api/user/modifyUser.ts
> +export function modifyUser(userId: string, formData: FormData) {
done

2022-07-29 11:14 UTC, pisarevkir commented on src/api/user/modifyUser.ts
> +    headers: {
it's not -> mobile-app-version and Authorization headers are still there

2022-07-29 11:14 UTC, pisarevkir commented on src/api/user/types.ts
> +export interface UserProfileUpdate {
now only `User` left

2022-07-29 11:14 UTC, pisarevkir commented on src/api/user/types.ts
> +export interface UserSearchInfo {
done

2022-07-29 11:14 UTC, pisarevkir commented on src/screens/Team/components/ContactsList/index.tsx
> +      const isFriend = invitedFriends.includes(item);
removed

2022-07-29 11:15 UTC, pisarevkir commented on src/screens/Team/components/IceUserItem/index.tsx
> +              <Image
we now have `RemoteImage` component that in handles image sizes

2022-07-29 11:16 UTC, pisarevkir commented on src/store/modules/Auth/sagas/updateAccount.ts
> +    let errorMessage = 'Failed';
it will, but as we discussed as part of some separate task

2022-07-29 11:52 UTC, pisarevkir commented on src/api/client/index.ts
> +  config?: AxiosRequestConfig,
why? we use it in some cases (transformRequest, headers and some other params)

2022-07-29 11:59 UTC, pisarevkir commented on src/api/client/index.ts
>    payload: TRequest,
I don't get the point. What is the `type` of request? We're setting a config for some methods, i.e. `modifyUser` and `getReferrals`

2022-07-29 12:02 UTC, pisarevkir commented on src/api/referrals/getReferrals.ts
> +  return get<{
done

2022-07-29 12:03 UTC, pisarevkir commented on src/api/referrals/getReferrals.ts
> +  }>(`/users/${userId}/referrals?type=${referralType}`);
done

2022-07-29 12:04 UTC, pisarevkir commented on src/api/referrals/getReferralsHistoryByUserId.ts
> +    {
done

2022-07-29 12:05 UTC, pisarevkir commented on src/api/referrals/types.ts
> -export interface Referrals {
`Referrals` and `ReferralHistoryRecord` are back

2022-07-29 12:06 UTC, pisarevkir commented on src/api/referrals/types.ts
> -export interface ReferralAcquisition {
`Referrals` and `ReferralHistoryRecord` are back

2022-07-29 12:06 UTC, pisarevkir commented on src/api/referrals/types.ts
> -  referrals: [Referral];
`Referrals` and `ReferralHistoryRecord` are back

2022-07-29 12:06 UTC, pisarevkir commented on src/api/referrals/types.ts
> -export type ReferralType = 'CONTACTS' | 'T1' | 'T2';
`ReferralType` is part of the User now

2022-07-29 12:07 UTC, pisarevkir commented on src/api/user/searchUsers.ts
> +  return get<User[]>(`/users?keyword=${query}`);
i suggest to make everything related to search in a separate task - this method is not used now

2022-07-29 12:07 UTC, pisarevkir commented on src/api/user/types.ts
> +  pingAllowed?: boolean;
done

2022-07-29 12:10 UTC, pisarevkir commented on src/api/user/types.ts
> +  profilePicture?: string | null;
changed to `{
    uri: string;
    name: string;
    type: string;
  }`

2022-07-29 12:13 UTC, pisarevkir commented on src/components/RemoteImage/index.tsx
> +    const pixelHeight = PixelRatio.getPixelSizeForLayoutSize(height);
This is a generic component - there might be cases when we need both width and height. But the other way around is also true - sometimes we might need only one param. So i made them optional and pass only width for avatar images.

2022-07-29 12:14 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/components/Calculator.tsx
> +import {formatAsCurrency} from '@utils/number';
I know, i will remove it as soon as we receive those values from the BE. Now i use that method to make the fake calculated data look exactly like in the design.

2022-07-29 12:15 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/components/Calculator.tsx
> +                ? `${formatAsCurrency(result)} ${t(
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933179078

2022-07-29 12:15 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +import {formatAsCurrency} from '@utils/number';
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933179078

2022-07-29 12:15 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +          <Text style={styles.ladderValueText}>{formatAsCurrency(606683)}</Text>
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933179078

2022-07-29 12:15 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +            <Text style={styles.ladderValueText}>{formatAsCurrency(1024)}</Text>
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933179078

2022-07-29 12:17 UTC, pisarevkir commented on src/screens/Team/components/Contacts/components/ConfirmCode/index.tsx
Yea, that sounds reasonable and i will try to reuse that component on the settings screen when i (or someone else) takes the task "personal information api integration". Now the PR is already pretty huge

2022-07-29 12:17 UTC, pisarevkir commented on src/store/modules/Auth/sagas/updateAccount.ts
> +    const formData: FormData = new FormData();
done

2022-07-29 12:18 UTC, pisarevkir commented on src/store/modules/Referrals/actions/index.ts
> +    result: {active: number; total: number; referrals: User[]},
done

2022-07-29 12:18 UTC, pisarevkir commented on src/store/modules/Referrals/actions/index.ts
> +    offset: number,
done

2022-07-29 12:18 UTC, pisarevkir commented on src/store/modules/Referrals/actions/index.ts
> +  SUCCESS: (history: {date: string; t1: number; t2: number}[]) => ({history}),
done

2022-07-29 12:18 UTC, pisarevkir commented on src/store/modules/Referrals/reducer/index.ts
> +      [key in ReferralType]?: {
done

2022-07-29 12:20 UTC, pisarevkir commented on src/store/modules/Referrals/reducer/index.ts
> +          draft.data[userId] = {
this is just a more flexible structure to be able to store referrals data of other users (if we want to display it total number or even list of referrals in profiles of user users)

2022-07-29 12:20 UTC, pisarevkir commented on src/store/modules/Referrals/selectors/index.ts
> +    state.referrals.data[userId]?.[referralType];
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933184598

2022-07-29 12:21 UTC, pisarevkir commented on src/utils/number.ts
> +export const formatAsCurrency = (input: number | string, step = 3) => {
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933179078

2022-07-29 12:22 UTC, pisarevkir commented on src/store/modules/Team/sagas/searchUsersSaga.ts
> +    const {query} = action.payload;
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933171873

2022-07-29 12:48 UTC, pisarevkir commented on src/api/referrals/getReferralsHistoryByUserId.ts
> -import {ReferralAcquisition} from '@api/referrals/types';
Referrals and ReferralHistoryRecord are back

2022-07-29 12:49 UTC, pisarevkir commented on src/components/RemoteImage/index.tsx
> +  height: number;
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933177476

2022-07-29 12:53 UTC, pisarevkir commented on src/store/modules/Validation/sagas/phoneValidationSaga.ts
> +    const phoneNumberHash: string = yield call(hashPhoneNumber, phoneNumber);
nope, we keep only the original phone in the store, why would we keep both hash and phone there?

2022-07-29 12:53 UTC, pisarevkir commented on src/store/modules/Validation/sagas/phoneValidationSaga.ts
> +import {hashPhoneNumber} from '@utils/phoneNumber';
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933226730

2022-07-29 12:55 UTC, pisarevkir commented on src/store/modules/Validation/actions/index.ts
>      validationCode,
What do you mean?  We pass code from UI as action param and we take phone number that user specified previously from the store

2022-07-29 15:47 UTC, pisarevkir commented on src/utils/phoneNumber.ts
> +  return sha256(e164PhoneNumber(phone));
i was thinking the idea is to unify phones first to make sure that even if the same phone number is written in different formats, the hashes are equal

2022-07-29 16:25 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
> +  config?: AxiosRequestConfig,
then revive the RequestConfig and add what you need there.

I don't want to have axios leaking throughout the app, cuz when we'll replace it, we're gonna have to change a lot of stuff

2022-07-29 16:26 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
> +  config?: AxiosRequestConfig,
the clients/users of this API client do not know what implementation it uses, and thats how it should remain

2022-07-29 16:29 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
> +  config?: AxiosRequestConfig,
but I'd still remove this completely and implement a switch over the actual type of TRequest and if it is a specific type I.E. a specific wrapper over something, then make it form multipart

2022-07-29 16:30 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
>    payload: TRequest,
was saying to implement a switch over the actual type of TRequest and if it is a specific type I.E. a specific wrapper over something, then make it form multipart

2022-07-29 16:33 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/components/Calculator.tsx
> +import {formatAsCurrency} from '@utils/number';
just format them by hand and put em as string, you don't need to wait for the BE to do that

2022-07-29 16:34 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/components/Calculator.tsx
> +                ? `${formatAsCurrency(result)} ${t(
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933442107

2022-07-29 16:34 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +import {formatAsCurrency} from '@utils/number';
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933442107

2022-07-29 16:34 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +          <Text style={styles.ladderValueText}>{formatAsCurrency(606683)}</Text>
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933442107

2022-07-29 16:35 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +            <Text style={styles.ladderValueText}>{formatAsCurrency(1024)}</Text>
https://github.com/ice-blockchain/mobile-app/pull/37#discussion_r933442107

<Text ...> 1,024.0 </Text>

2022-07-29 16:36 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/Contacts/components/ConfirmCode/index.tsx
my point is to put it in a common place, not reuse something from team screen in settings screen, but use something common in both screens

2022-07-29 16:42 UTC, victor-oancea-leftclick-io commented on src/utils/phoneNumber.ts
> +  return sha256(e164PhoneNumber(phone));
the idea is to have the phone number and  source of the hash identical.

with that approach, we might end up with the input != e164PhoneNumber(phone), which is very bad, so just sha256(phone) and make sure u're passing only the result of a e164PhoneNumber call to this function

2022-08-01 06:38 UTC, pisarevkir commented on src/api/client/index.ts
> +  config?: AxiosRequestConfig,
sounds reasonable - D in SOLID... Removed the AxiosRequestConfig dependency and handle required headers in request interceptor if params are of FormData type

2022-08-01 06:38 UTC, pisarevkir commented on src/api/client/index.ts
>    payload: TRequest,
done

2022-08-01 06:50 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/components/Calculator.tsx
> +import {formatAsCurrency} from '@utils/number';
done

2022-08-01 06:51 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/MiningCalculator/components/Calculator.tsx
> +                ? `${formatAsCurrency(result)} ${t(
done

2022-08-01 06:51 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +import {formatAsCurrency} from '@utils/number';
done

2022-08-01 06:51 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +          <Text style={styles.ladderValueText}>{formatAsCurrency(606683)}</Text>
done

2022-08-01 06:51 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +            <Text style={styles.ladderValueText}>{formatAsCurrency(1024)}</Text>
done

2022-08-01 06:53 UTC, pisarevkir commented on src/screens/Team/components/Contacts/components/ConfirmCode/index.tsx
sure, if we reuse it at some point, i'll place it in `components` folder where we store common components

2022-08-01 06:54 UTC, pisarevkir commented on src/utils/number.ts
> +export const formatAsCurrency = (input: number | string, step = 3) => {
done

2022-08-01 07:28 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
> +  urlParams?: unknown,
They’re called query params

2022-08-01 07:30 UTC, victor-oancea-leftclick-io commented on src/api/client/interceptors/request.ts
> +  if (config.data instanceof FormData) {
This makes everything not type sense again, create a type wrapper over the actual data, IE FormData<Request>

2022-08-01 07:32 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/Contacts/components/ConfirmCode/index.tsx
There’s no if, there’s a 100% certainty, so lets do it now

2022-08-01 07:35 UTC, pisarevkir commented on src/api/client/interceptors/request.ts
> +  if (config.data instanceof FormData) {
Why so? Check `src/api/user/modifyUser.ts` - input params of the request are typed, return type is typed. There is no way to pass something wrong here.

2022-08-01 07:53 UTC, victor-oancea-leftclick-io commented on src/api/client/interceptors/request.ts
> +  if (config.data instanceof FormData) {
Not what i meant, but will do for now

2022-08-01 09:48 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
> +  urlParams?: unknown,
Map<string,string>

2022-08-01 10:41 UTC, victor-oancea-leftclick-io requested changes
Pls also make sure the pagination works very precisely: set limit depending on the max number of elements the users can see for their own device's aspect/resolution. Nothing more, nothing less

2022-08-01 10:41 UTC, victor-oancea-leftclick-io commented on src/components/RemoteImage/index.tsx
> +      : '';
Not a good idea, cuz the param is gonna be wmpty, thus invalid

2022-08-01 10:41 UTC, victor-oancea-leftclick-io commented on src/components/UserListItem/index.tsx
> +            ? t('team.tier_one.active')
users.active . Dont need to have 10 keys that represent the same thing

2022-08-01 10:41 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/Contacts/components/ContactsList/components/ContactItem/index.tsx
> +        setActiveHeight(phoneNumbers.length * font(14));
Is this scaleable?

2022-08-01 10:41 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/TierList/index.tsx
> +              text={t('team.tier_one.ping')}
users.ping

2022-08-01 10:41 UTC, victor-oancea-leftclick-io commented on src/store/modules/Team/sagas/syncContactsSaga.ts
> +      .sort((a, b) => a.givenName.localeCompare(b.givenName));
You dont need this

2022-08-01 10:41 UTC, victor-oancea-leftclick-io commented on src/store/utils/sagas/effects.ts
> +export function takeLeadingEveryUnique<
Im not sure u need this. You can call multiple times the get referrals api, it will just refresh itself

2022-08-01 10:51 UTC, pisarevkir commented on src/store/modules/Team/sagas/syncContactsSaga.ts
> +      .sort((a, b) => a.givenName.localeCompare(b.givenName));
why not? as i remember Robert asked for sorting the list by name

2022-08-01 10:54 UTC, pisarevkir commented on src/api/client/index.ts
> +      async () => writeClient.delete<TResponse>(path, {params: urlParams}),
Wont we have them at any point in the future? Delete some collection filtered by some query or something like that?

2022-08-01 10:57 UTC, pisarevkir commented on src/api/client/index.ts
> +  urlParams?: unknown,
`Map` expects an instance of Map structure, changed to `{[key: string]: string | number}`

2022-08-01 11:03 UTC, pisarevkir commented on src/api/referrals/getReferrals.ts
> +  limit = 10,
The rule is to ask "not less" than one viewport. And 10 items is slightly more that 1 viewport on iPhone 13 Max. Actually i would set it to 20 to fill at least 2 viewports

2022-08-01 11:04 UTC, pisarevkir commented on src/components/RemoteImage/index.tsx
> +      : '';
Hm, empty query params break the BE?

2022-08-01 11:11 UTC, pisarevkir commented on src/store/utils/sagas/effects.ts
> +export function takeLeadingEveryUnique<
When user scrolls down the list the "end reached" event might fire multiple times in a row (we call load more in this case) - this util will pick only the first event and skip the others untill it get processed. So what is the case  when we need to process multiple get referrals in parallel?

2022-08-01 11:15 UTC, victor-oancea-leftclick-io commented on src/store/modules/Team/sagas/syncContactsSaga.ts
> +      .sort((a, b) => a.givenName.localeCompare(b.givenName));
Oh, u’re using the same obj for that, ok

2022-08-01 11:17 UTC, victor-oancea-leftclick-io commented on src/api/referrals/getReferrals.ts
> +  limit = 10,
Yea, do some math and test how many you need to request in advance so that the user sees a nice endless scroll without buffering, even if he scrolls through fast

2022-08-01 11:17 UTC, victor-oancea-leftclick-io commented on src/components/RemoteImage/index.tsx
> +      : '';
Every time

2022-08-01 11:18 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
> +      async () => writeClient.delete<TResponse>(path, {params: urlParams}),
Nope

2022-08-01 11:21 UTC, victor-oancea-leftclick-io commented on src/store/utils/sagas/effects.ts
> +export function takeLeadingEveryUnique<
Im saying you dont need to care about how many concurrent and in progress requests are, you just refresh the list and update the last index seen.

you dont have to bother making sure only 1 request is in progress at any given time

2022-08-01 11:30 UTC, victor-oancea-leftclick-io commented on src/utils/phoneNumber.ts
> +export const e164PhoneNumber = (
You need to handle the case when the phone has the idd code included

2022-08-01 11:40 UTC, pisarevkir commented on src/components/RemoteImage/index.tsx
> +      : '';
now they are not sent if empty

2022-08-01 11:41 UTC, pisarevkir commented on src/screens/Team/components/Contacts/components/ContactsList/components/ContactItem/index.tsx
> +        setActiveHeight(phoneNumbers.length * font(14));
made it more accurate and tested with 10 phone numbers

2022-08-01 11:50 UTC, pisarevkir commented on src/utils/phoneNumber.ts
> +export const e164PhoneNumber = (
I tested it with my contacts and it handled all the cases well, here are the real life examples (from my contact list)
on the left the number how it was exported from my contact list and on the right the output of e164PhoneNumber
```
8 (914) 704-87-33 +79147048733
+79774593579 +79774593579
+7 967 201‑13‑01 +79672011301
+79153189512 +79153189512
+358407151583 +358407151583
+995 591 30 04 14 +995591300414
8 (910) 648-90-28 +79106489028
89857675023 +79857675023
+905303097703 +905303097703
+380509201065 +380509201065
+7 906 041-14-53 +79060411453
+1 510-221-8894 +15102218894
+49 1512 7055539 +4915127055539
 ```
 
 It also handles well if there is no idd in the input but the country is provided:
 e164PhoneNumber('9197754887', 'RU') -> '+79197754887'

2022-08-01 11:51 UTC, pisarevkir commented on src/screens/Team/components/TierList/index.tsx
> +              text={t('team.tier_one.ping')}
done

2022-08-01 11:53 UTC, pisarevkir commented on src/screens/Team/components/TierList/index.tsx
> +              text={t('team.tier_one.ping')}
done

2022-08-01 11:53 UTC, pisarevkir commented on src/components/UserListItem/index.tsx
> +            ? t('team.tier_one.active')
done

2022-08-01 11:53 UTC, victor-oancea-leftclick-io commented on src/components/RemoteImage/index.tsx
> +      : '';
Ok

2022-08-01 11:54 UTC, victor-oancea-leftclick-io commented on src/utils/phoneNumber.ts
> +export const e164PhoneNumber = (
Ok

2022-08-01 11:56 UTC, OlehPanforov commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +          <Text style={styles.ladderValueText}>606,683</Text>
Can we get this value from backed or calculate it and not hardcode?

2022-08-01 11:56 UTC, OlehPanforov commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +            <Text style={styles.ladderValueText}>1,024</Text>
Can we get this value from backed or calculate it and not hardcode?

2022-08-01 11:56 UTC, OlehPanforov commented on src/screens/Team/components/Contacts/components/ContactsList/components/SectionHeader/index.tsx
> +        {section.title === 'iceFriends' ? (
Let's create section types and compare with them and not just with simple string

2022-08-01 11:56 UTC, OlehPanforov commented on src/screens/Team/components/SegmentedContent/index.tsx
> +          <Contacts {...props} focused={activeIndex === 0} />
Please use types here and not just index 0, 1, 2 (same for line 59 and line 67)

2022-08-01 11:56 UTC, OlehPanforov commented on src/screens/Team/components/TierList/components/Header/index.tsx
> +        <Text style={styles.title}>{`${t(title)}: 94,412 ice`}</Text>
Can we get it from the backend? Or should be hardcoded for now?

2022-08-01 11:56 UTC, OlehPanforov commented on src/store/modules/Team/reducer/index.ts
> +        draft.search = [];
Should we wipe maybe state contacts also here?

2022-08-01 11:56 UTC, OlehPanforov commented on src/store/modules/Team/sagas/syncContactsSaga.ts
> +  const hasPermissions: boolean = yield select(permissionSelector('contacts'));
Can we replace 'contacts' stings with some contacts permission type here?

2022-08-01 11:57 UTC, pisarevkir commented on src/api/referrals/getReferrals.ts
> +  limit = 10,
set it to 20

2022-08-01 12:03 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/UserInfo/index.tsx
> +            <Text style={styles.ladderValueText}>1,024</Text>
No BE yet

2022-08-01 12:03 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/TierList/components/Header/index.tsx
> +        <Text style={styles.title}>{`${t(title)}: 94,412 ice`}</Text>
No BE yet

2022-08-01 12:15 UTC, pisarevkir commented on src/api/user/searchUsers.ts
> +    headers: getHeaders(),
^

2022-08-01 12:15 UTC, pisarevkir commented on src/api/user/types.ts
> +export interface UserUpdateResult extends UserProfile {
^

2022-08-01 12:15 UTC, pisarevkir commented on src/api/user/updateUser.ts
> +  formData: FormData;
^

2022-08-01 12:15 UTC, pisarevkir commented on src/api/user/updateUser.ts
> +export function updateUser({userId, formData}: Params) {
^

2022-08-01 12:15 UTC, pisarevkir commented on src/store/modules/Auth/actions/index.ts
> +enum UserUpdateEnum {
^

2022-08-01 12:15 UTC, pisarevkir commented on src/store/modules/Team/actions/index.ts
> +export interface UserSearchResult {
^

2022-08-01 12:43 UTC, pisarevkir commented on src/utils/phoneNumber.ts
> +} from 'libphonenumber-js/min';
done

2022-08-01 12:43 UTC, pisarevkir commented on src/utils/phoneNumber.ts
> +  return sha256(e164PhoneNumber(phone));
done

2022-08-01 12:45 UTC, pisarevkir commented on src/utils/phoneNumber.ts
> +    return parsePhoneNumber(phone).format('E.164');
i tested it with different real world cases and it seems to work just fine

2022-08-02 07:11 UTC, pisarevkir commented on src/screens/Team/components/Contacts/components/ContactsList/components/SectionHeader/index.tsx
> +        {section.title === 'iceFriends' ? (
agree, added ContactSection and ContactSectionDataItem types, now all comparisons are type safe

2022-08-02 07:15 UTC, pisarevkir commented on src/screens/Team/components/SegmentedContent/index.tsx
> +          <Contacts {...props} focused={activeIndex === 0} />
added SegmentIndex type

2022-08-02 08:03 UTC, pisarevkir commented on src/store/modules/Team/reducer/index.ts
> +        draft.search = [];
yea, changed the flow - reset contacts on logout, run sync saga on logout as well (it waits for user to auth and ther runs the sync itself)

2022-08-02 08:05 UTC, pisarevkir commented on src/store/modules/Team/sagas/syncContactsSaga.ts
> +  const hasPermissions: boolean = yield select(permissionSelector('contacts'));
It is of already typed (union type)
```
export type PermissionType = 'contacts' | 'pushNotifications';

export const permissionSelector =
  (type: PermissionType) => (state: RootState) => {
    return state.permissions[type] === RESULTS.GRANTED;
  };
```
So it's typesafe

2022-08-02 13:50 UTC, pisarevkir commented on src/screens/Team/components/Contacts/components/ConfirmCode/index.tsx
ConfirmCode and ConfirmPhone components are now reused on Team and Settings screens

2022-08-02 14:00 UTC, pisarevkir commented on src/store/utils/sagas/effects.ts
> +export function takeLeadingEveryUnique<
This function skips only the requests for get-referals if some get-referals request of the same type (T1/T2/CONTACTS) is already executing. The all other requests will go in parallel.

So here is the scenario:
1. Open the Tier1 list -> first page gets loaded
2. User scrolls down the list -> page 2 is requested but not finished
3. User scrolls up and refreshes the list -> page 1 is requested
In this case we either have to either skip refresh request cuz the load-next is not done, or stop the page 2 request and start the refresh one.

2022-08-02 19:29 UTC, victor-oancea-leftclick-io requested changes
That logic with contacts/t1/t2 lists is too complicated; huge cyclomatic complexity; very low maintenability index; hard to understand most of it and I bet it's gonna be just as hard for you in a week or so.

I'd say spend more time on making it easier and if you can't leave it like that and we'll revisit it when we start writing tests

2022-08-02 19:29 UTC, victor-oancea-leftclick-io commented on src/screens/Team/components/TierList/index.tsx
> +            <UserListItemButton
Render it only if pinged is true/false, not null/undefined, this is the case for all Ping buttons everywhere in the app

2022-08-02 19:29 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/reducer/index.ts
> +  profile: User | null;
user

2022-08-02 19:29 UTC, victor-oancea-leftclick-io commented on src/store/modules/Referrals/sagas/getReferralsSaga.ts
> +        offset,
You need to pass in the limit as well, or next offset, cuz offset is prevOffset+limit

2022-08-02 19:29 UTC, victor-oancea-leftclick-io commented on src/store/modules/Team/sagas/syncContactsSaga.ts
> +    if (phoneNumberHashesString !== profile?.agendaPhoneNumberHashes) {
Make sure you always order them in the same way before you send end to the BE and when you collect em here; unless this the only place you update em

2022-08-02 19:29 UTC, victor-oancea-leftclick-io commented on src/store/modules/Team/sagas/syncContactsSaga.ts
> +    let contacts: SagaReturnType<typeof getAllWithoutPhotos> = yield call(
Is this cpu or memory intensive?

2022-08-03 07:01 UTC, pisarevkir commented on src/store/modules/Team/sagas/syncContactsSaga.ts
> +    if (phoneNumberHashesString !== profile?.agendaPhoneNumberHashes) {
yea, this is the only place

2022-08-03 07:03 UTC, pisarevkir commented on src/store/modules/Referrals/sagas/getReferralsSaga.ts
> +        offset,
I pass offset to the request for the next pages with the value of currentReferrals.length

2022-08-03 07:03 UTC, pisarevkir commented on src/screens/Team/components/TierList/index.tsx
> +            <UserListItemButton
done

2022-08-03 07:04 UTC, pisarevkir commented on src/components/ConfirmPhone/index.tsx
> +        .replace(selectedCountry.iddCode, '')
done

2022-08-03 07:07 UTC, pisarevkir commented on src/components/ConfirmCode/index.tsx
>  import {PrimaryButton} from '@components/PrimaryButton';
we currently have `ConfirmCode` and `ConfirmPhone` components with corresponding folders, how do you suggest to rename those?
`ConfirmCode` -> `ConfirmPhoneNumberCode`?

2022-08-03 07:25 UTC, pisarevkir commented on src/store/modules/Team/sagas/syncContactsSaga.ts
> +    let contacts: SagaReturnType<typeof getAllWithoutPhotos> = yield call(
I believe this one is not, until we don't receive something really big like images in base64.
sha256 execution bothers me more - as per the source lib code it happens in the UI thread, so theoretically there might be UI glitches if the num of contacts is huge and we run contacts sync during some UI interactions / animations. But that needs to be tested before we dive in fixing (on my device works smooth)

2022-08-03 09:33 UTC, pisarevkir commented on src/components/ConfirmCode/index.tsx
>  import {PrimaryButton} from '@components/PrimaryButton';
done

2022-08-03 09:33 UTC, pisarevkir commented on src/store/modules/Auth/reducer/index.ts
> +  profile: User | null;
done

2022-08-03 09:51 UTC, victor-oancea-leftclick-io commented on src/components/ModifyPhoneNumber/index.tsx
> +        `${selectedCountry.iddCode}${phoneNumber}`,
Strange choice, just sent the whole object and work with it inside the function

2022-08-03 10:02 UTC, pisarevkir commented on src/components/ModifyPhoneNumber/index.tsx
> +        `${selectedCountry.iddCode}${phoneNumber}`,
What object? This way we can use this function in a more flexible way:
```
formatPhoneNumber('+7919', 'RU') -> +7 919
formatPhoneNumber('+79197754887') -> +7 919 775 48 87
formatPhoneNumber('8 (919) 775 48 87', 'RU') -> +7 919 775 48 87 
formatPhoneNumber('+79197754887', null, +7) -> '919 775 48 87' // cut off the idd code if passed
```

2022-08-03 10:08 UTC, victor-oancea-leftclick-io commented on src/components/ModifyPhoneNumber/index.tsx
> +        `${selectedCountry.iddCode}${phoneNumber}`,
Ok

2022-08-03 10:56 UTC, OlehPanforov commented on src/store/modules/Validation/reducer/index.ts
> +          draft.phoneVerificationStep = 'code';
Lets create step types
'phone' 
 'code'

2022-08-03 10:59 UTC, pisarevkir commented on src/store/modules/Validation/reducer/index.ts
> +          draft.phoneVerificationStep = 'code';
phoneVerificationStep is already of union type `'phone' | 'code'`

<img width="440" alt="image" src="https://user-images.githubusercontent.com/102020833/182592314-100ae56b-4743-42c8-aa1e-9831af998e1e.png">

2022-08-03 11:04 UTC, OlehPanforov submitted a review, later dismissed

2022-08-03 12:18 UTC, victor-oancea-leftclick-io approved these changes

2022-08-03 12:57 UTC, OlehPanforov approved these changes

2022-08-03 13:40 UTC, pisarevkir approved these changes

2022-08-03 13:40 UTC, merged