Feature/connect auth api
ice-blockchain/mobile-app pull request #41
Opened 2022-07-13 19:25 UTC by OlehPanforov

2022-07-14 08:14 UTC, victor-oancea-leftclick-io requested changes

2022-07-14 08:14 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +    console.log(userData);
debugger?

2022-07-14 08:14 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +      username: username || '',
never null, never empty

2022-07-14 08:14 UTC, victor-oancea-leftclick-io commented on src/store/modules/Validation/sagas/phoneValidationSaga.ts
> +    const phoneNumberHash: string = yield call(sha256, phoneNumber);
you need a single/unique place where you process phone number. Cuz you need to format it and sanitize it before you sha246 it

2022-07-14 08:14 UTC, victor-oancea-leftclick-io commented on src/store/modules/Validation/sagas/validateUsernameSaga.ts
> +        ValidationActions.USERNAME_VALIDATION.FAILED.create(
this happens if you get 200 also

2022-07-15 11:33 UTC, OlehPanforov commented on src/screens/AuthFlow/ClaimNickname/components/WhoInvitedYou/index.tsx
>  import {CommonInput} from '@components/CommonInput';
No, its only related to ClaimNickname screen

2022-07-15 11:34 UTC, OlehPanforov commented on src/api/validations/validateUsername.ts
> +export function validateUsername({username}: Params) {
done

2022-07-15 11:35 UTC, OlehPanforov commented on src/screens/AuthFlow/SignIn/index.tsx
> +        return country.isoCode === location.country;
done

2022-07-15 11:36 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/createUser.ts
> +    console.log(userData);
Its was temp solution, already removed

2022-07-15 11:40 UTC, victor-oancea-leftclick-io requested changes

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/api/devices/types.ts
> -  userId: string;
rollback, they should never be null

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/api/validations/validateUsername.ts
> +export function validateUsername({username}: Params) {
getUserByUsername

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/screens/AuthFlow/ClaimNickname/index.tsx
> +  const isUsernameValid = useSelector(isUsernameValidSelector);
you dont validate it on the app, you let the BE do it

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/screens/AuthFlow/ClaimNickname/index.tsx
> +  const isValidName = (name: string) => {
remove this

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/screens/AuthFlow/SignIn/index.tsx
> +    if (inputType === 'phone') {
do this regardless, at app launch

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/reducer/index.ts
> +    username?: string | null;
why do you need this here?

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +      username: username || '',
never null or empty

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +    let errorMessage = 'Failed';
have a switch case here to handle api errors

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUserProfile.ts
> +export function* fetchUserProfile(userId: string) {
use it

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/loadUser.ts
>        yield put(AuthActions.LOAD_USER.STATE.create());
why do you continue if you dont have the token?

2022-07-15 11:40 UTC, victor-oancea-leftclick-io commented on src/store/modules/Validation/sagas/validateUsernameSaga.ts
> +          'Nickname already taken.',
i18n all error messages

2022-07-15 11:41 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/createUser.ts
> +      username: username || '',
From types side, it can be null because we get it from the store using the selector, and it can be null in store (the default initial state). So I just removed it from this `|| ''` part and added it to usernameSelector one

2022-07-15 11:41 UTC, victor-oancea-leftclick-io commented on src/screens/AuthFlow/ClaimNickname/components/WhoInvitedYou/index.tsx
>  import {CommonInput} from '@components/CommonInput';
it has nothing to do with it, claim username & referral screen are 2 independent screens

2022-07-15 11:44 UTC, OlehPanforov commented on src/store/modules/Validation/reducer/index.ts
> +        draft.username = isEmpty(action.payload.username)
agree

2022-07-15 11:54 UTC, OlehPanforov commented on src/store/modules/Validation/sagas/phoneValidationSaga.ts
> +    const phoneNumberHash: string = yield call(sha256, phoneNumber);
Let's do it in the scope of the team branch with the contacts screen. @subbotnik16 please take a look

2022-07-15 11:59 UTC, OlehPanforov commented on src/screens/AuthFlow/ClaimNickname/components/WhoInvitedYou/index.tsx
>  import {CommonInput} from '@components/CommonInput';
No, it's 1 screen with two states. That's how it was implemented by Nikita

2022-07-15 12:25 UTC, victor-oancea-leftclick-io commented on src/screens/AuthFlow/ClaimNickname/components/WhoInvitedYou/index.tsx
>  import {CommonInput} from '@components/CommonInput';
it was badly implemented, please do it properly, 2 screens, independent states

2022-07-15 12:48 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/fetchUserProfile.ts
> +export function* fetchUserProfile(userId: string) {
What you mean here?

2022-07-15 12:58 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUserProfile.ts
> +export function* fetchUserProfile(userId: string) {
u`re not using it in the saga above

2022-07-15 13:04 UTC, victor-oancea-leftclick-io commented on src/screens/AuthFlow/ClaimNickname/components/WhoInvitedYou/index.tsx
>  import {CommonInput} from '@components/CommonInput';
ok, add a todo and fix it in the next task

2022-07-15 13:08 UTC, subbotnik16 commented on src/screens/AuthFlow/ClaimNickname/components/WhoInvitedYou/index.tsx
>  import {CommonInput} from '@components/CommonInput';
@victor-oancea-leftclick-io pls take a look at the design. it's one screen with pager

2022-07-15 14:05 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/fetchUserProfile.ts
> +export function* fetchUserProfile(userId: string) {
No, this function is used in other places (profile fetch in sign-in flows (to make a decision there)), it's different from fetchUserProfileSaga that we are not using right in this branch but planning when we will connect some profiles refetches in different situations like onFocus of some screens to keep the data always up to date on that screens/situation.

2022-07-15 14:08 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/loadUser.ts
>        yield put(AuthActions.LOAD_USER.STATE.create());
Continue what? If we have no token we will just call the yield put(AuthActions.LOAD_USER.STATE.create()); without any data and in reducer it will set magicUser and profile to null in case we didn't pass them.

2022-07-15 14:40 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUserProfile.ts
> +export function* fetchUserProfile(userId: string) {
still, why would you not use it? you'd just reuse the code, it does the same thing

2022-07-15 14:41 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/loadUser.ts
>        yield put(AuthActions.LOAD_USER.STATE.create());
which displays what?

2022-07-15 17:21 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/fetchUserProfile.ts
> +export function* fetchUserProfile(userId: string) {
It doesn't. The function just makes a request and does not dispatch any actions and returns a null profile for the specific error. We don't need this logic in fetchUserProfileSaga.

2022-07-15 17:31 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUserProfile.ts
> +export function* fetchUserProfile(userId: string) {
you`re doing the exact same thing! you`re calling the exact same API! cmon

2022-07-15 17:36 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/loadUser.ts
>        yield put(AuthActions.LOAD_USER.STATE.create());
I don't understand your question. 
What does it affect after setting null to magic user and profile? If yes then many places. You can search for `isAuthorizedSelector` and `profileSelector` to check this and then search who and how uses it. Sagas/ auth flow/ many places affected.

2022-07-18 11:48 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
> +      axios.isAxiosError(error) &&
and 401

2022-07-18 11:49 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
> +      () => writeClient.post<TResponse>(path, payload, config),
put the `async` keyword to be more descriptive

2022-07-18 11:56 UTC, OlehPanforov commented on src/api/client/index.ts
> +      axios.isAxiosError(error) &&
Why should we retry 401 if it is unauthorized? We will have separate flow for it that will try to regenerate the token and if its not regenerated -> logout, if regenerated - retry the request

2022-07-18 12:02 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +    } else if (isApiError(error, 400)) {
not enough,  code is also `INVALID_USERNAME`; you also need to make sure the user doesn't put the same username/nickname in both screens => return a special error "You can't refer yourself " or something

2022-07-18 12:04 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +    if (isApiError(error, 409)) {
not enough, code is also `CONFLICT_WITH_ANOTHER_USER` + based on `data.field` it can be either `username` or `id` ; if `username` => username is already taken, if 'id' you ignore it and just call get and forward to Home Screen

2022-07-18 12:06 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +    yield put(AuthActions.CREATE_USER.FAILED.create(localizedError));
you also need a 404 + `REFERRAL_NOT_FOUND` => referral introduced is invalid

2022-07-18 12:07 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +    } else if (isApiError(error, 400)) {
but I guess, at this point, if 400 + `INVALID_USERNAME` happens, is a programming error, cuz this should have been watched in the claim username part, via getUserByUsername

2022-07-18 12:09 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUserProfile.ts
> +      return null;
how is this handled later on in the flow?

2022-07-18 12:13 UTC, victor-oancea-leftclick-io commented on src/store/modules/Validation/sagas/validateUsernameSaga.ts
> +    } else if (isApiError(error, 400, 'VALIDATION_ERROR')) {
INVALID_USERNAME, not VALIDATION_ERROR

2022-07-18 12:15 UTC, victor-oancea-leftclick-io requested changes
@OlehPanforov please properly test all flows, to see the exact codes and error information that you get

2022-07-18 12:18 UTC, victor-oancea-leftclick-io commented on src/api/client/index.ts
> +      axios.isAxiosError(error) &&
where's that?

2022-07-18 12:25 UTC, OlehPanforov commented on src/api/client/index.ts
> +      axios.isAxiosError(error) &&
this will be done in the scope of general errors handling branch, I didn't implement this in scope of this task/flow because this PR already took forever because of the functionality that is expanding

2022-07-18 12:49 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/fetchUserProfile.ts
> +      return null;
We start UserRegistration flow if after successful Magic login we get USER_NOT_FOUND by id that we get from magic

2022-07-18 13:08 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/createUser.ts
> +    } else if (isApiError(error, 400)) {
Ok, yeah, we should handle locally when user types the same username on ref screen, I will add

2022-07-19 09:15 UTC, pisarevkir commented on src/screens/UserRegistrationFlow/UserRegistration/components/WhoInvitedYou/index.tsx
> +            onPress={() => {
OPTIONAL: `onPress={onSkip}>`

2022-07-19 09:15 UTC, pisarevkir commented on src/navigation/Auth.tsx
> +    } else if (magicUser && !magicUser.username) {
Where do we fullfill the magic user username and why do we check it here? As i understand we keep username and phone number during validation in validation module (`USERNAME_VALIDATION` and `REF_USERNAME_VALIDATION` action)

2022-07-19 09:15 UTC, pisarevkir commented on src/store/modules/Auth/reducer/index.ts
> +    username?: string | null;
+1

2022-07-19 11:51 UTC, subbotnik16 approved these changes

2022-07-19 13:57 UTC, pisarevkir commented on src/store/modules/Auth/sagas/createUser.ts
> +        response?.data.data.field === 'username'
can't we just use `response?.data?.data?.field === 'username'`

2022-07-19 14:02 UTC, pisarevkir commented on src/store/modules/Auth/sagas/createUser.ts
> +      const apiError = error as AxiosError;
```
// SPDX-License-Identifier: BUSL-1.1

import axios, {AxiosError} from 'axios';

export const isApiError = (
  error: unknown,
  expectedStatus?: number,
  expectedCode?: string,
): error is AxiosError => {
  return (
    axios.isAxiosError(error) &&
    (!expectedStatus || error.response?.status === expectedStatus) &&
    (!expectedCode || error.response?.data.code === expectedCode)
  );
};
```

2022-07-19 19:47 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +        localizedError = t('error.user_exist');
Do you also redirect to that claim username view? Or do you let the user navigate?

2022-07-19 19:51 UTC, victor-oancea-leftclick-io approved these changes

2022-07-20 06:18 UTC, pisarevkir approved these changes

2022-07-20 08:26 UTC, subbotnik16 approved these changes

2022-07-20 08:26 UTC, merged