Feature/username prefill
ice-blockchain/mobile-app pull request #45
Opened 2022-07-25 08:09 UTC by OlehPanforov

2022-07-29 12:22 UTC, victor-oancea-leftclick-io commented on src/screens/UserRegistrationFlow/UserRegistration/index.tsx
> +      ? magicUser.email.split('@')[0].replace(/[^a-zA-Z0-9]/g, '')
add -_. as well

2022-07-29 12:22 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/signInSocial.ts
> +          socialLoginInfo.oauth?.userInfo?.preferredUsername ?? null,
you sure this is 100% accurate? why not use userHandle or anything from the scope?

2022-07-29 12:48 UTC, OlehPanforov commented on src/store/modules/Auth/sagas/signInSocial.ts
> +          socialLoginInfo.oauth?.userInfo?.preferredUsername ?? null,
Yep, I tested on Twitter, that's the object structure social returns the username. If not we get it from email for all other cases

2022-07-29 13:08 UTC, OlehPanforov commented on src/screens/UserRegistrationFlow/UserRegistration/index.tsx
> +      ? magicUser.email.split('@')[0].replace(/[^a-zA-Z0-9]/g, '')
done

2022-07-29 15:33 UTC, pisarevkir submitted a review, later dismissed

2022-07-29 15:54 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/signInSocial.ts
> +          socialLoginInfo.oauth?.userInfo?.preferredUsername ?? null,
does it work for all social logins?

2022-08-02 18:24 UTC, victor-oancea-leftclick-io commented on src/assets/svg/Twitter.tsx
>  // SPDX-License-Identifier: BUSL-1.1
Rename to twitter icon

2022-08-02 18:24 UTC, victor-oancea-leftclick-io commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  const isCreatingSettings = useSelector(
What device settings is it creating?

2022-08-04 09:27 UTC, victor-oancea-leftclick-io requested changes
U still need to impl the update required flow

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/api/devices/types.ts
> +  uniqueId: string | null;
Duplicate. Use the one above

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/api/devices/updateDeviceMetadata.ts
> +  return put<DeepPartial<DeviceMetadata>, DeviceMetadata>(
Response is nothing

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/index.ts
> +    //TODO: APP_INITIALIZED
Well? Impl it?

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    if (isAuthorized && isAppActive && !lastUpdateDate && shouldUpdate) {
Why !lastUpdateDate ??

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    const isAppActive: ReturnType<typeof isAppActiveSelector> = yield select(
Or after register/login

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +      const deviceUniqueId: ReturnType<typeof deviceUniqueIdSelector> =
Use the unique device id from above: they're the same

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        uniqueId,
Not needed; its the other one

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        readableVersion: DeviceInfo.getReadableVersion(),
Whats the value for this?

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        pushNotificationToken: '', //TODO: FCM token
Yep, configure it within this task

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        deviceUniqueId,
Not needed in the req body

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        userId,
Not needed in req body

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    let errorMessage = 'Failed';
Handle the 400 + UPDATE_REQUIRED

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +      yield put(DeviceActions.UPDATE_METADATA.SUCCESS.create(metadataResult));
Its nothing

2022-08-04 09:27 UTC, victor-oancea-leftclick-io commented on src/utils/helpers.ts
> +// SPDX-License-Identifier: BUSL-1.1
Use the existing util folder/files

2022-08-05 06:28 UTC, OlehPanforov commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  const isCreatingSettings = useSelector(
`  return post<DeepPartial<DeviceSettings>, DeviceSettings>(
    `/users/${userId}/devices/${deviceUniqueId}/settings`,
    settings,
  );`

2022-08-05 06:31 UTC, pisarevkir commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  const isCreatingSettings = useSelector(
This flag will be always `false` since we don't dispatch `DeviceActions.GET_OR_CREATE_SETTINGS.START` implicitly and i think we don't need to wait for it anyway here

2022-08-05 06:34 UTC, pisarevkir commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +    backgroundColor: 'rgba(0,0,0,0.2)',
we have COLORS.black02opacity

2022-08-05 06:35 UTC, pisarevkir commented on src/store/modules/Auth/reducer/index.ts
> +  phoneVerificationStep: string;
phoneVerificationStep is in the `Validation` module

2022-08-05 06:38 UTC, pisarevkir commented on src/screens/UserRegistrationFlow/UserRegistration/index.tsx
> +    if (claimValidationError && currentPage === 1) {
by the way, why do we keep `usernameValidationError` and `refUsernameValidationError` strings in Validation module, can't we use common `failedReasonSelector` for those actions?

2022-08-05 06:44 UTC, OlehPanforov commented on src/store/modules/Devices/sagas/index.ts
> +    //TODO: APP_INITIALIZED
That part was only in master, rebased and implemented already.

2022-08-05 06:46 UTC, pisarevkir commented on src/store/modules/Devices/sagas/index.ts
> +    takeLatest(
Why not 1 `takeLatest` with 5 actions for `updateDeviceMetadataSaga`?

2022-08-05 06:49 UTC, OlehPanforov commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    const isAppActive: ReturnType<typeof isAppActiveSelector> = yield select(
To cover first update case (when we never do this before and have no dates to compare (to check if 8 hours left or not)

2022-08-05 07:04 UTC, OlehPanforov commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    if (isAuthorized && isAppActive && !lastUpdateDate && shouldUpdate) {
To cover first update case (when we never do this before and have no dates to compare (to check if 8 hours left or not)

2022-08-05 07:10 UTC, OlehPanforov commented on src/screens/UserRegistrationFlow/UserRegistration/index.tsx
> +    if (claimValidationError && currentPage === 1) {
Its just another option to do the same stuff. Plus we have custom RESET_VALIDATION_ERRORS logic around.
I don't wanna change these two right now with alternative solution because current one works and already tested

2022-08-05 09:02 UTC, victor-oancea-leftclick-io commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  const isCreatingSettings = useSelector(
Yea, but why? @pisarevkir any idea?

2022-08-05 10:24 UTC, victor-oancea-leftclick-io commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  const isCreatingSettings = useSelector(
Remove this

2022-08-05 10:38 UTC, pisarevkir commented on src/screens/UserRegistrationFlow/UserRegistration/index.tsx
> +    if (claimValidationError && currentPage === 1) {
Just looks that we could get rid of those extra fields in redux / extra actions and stuff... But ok

2022-08-08 08:30 UTC, victor-oancea-leftclick-io requested changes

2022-08-08 08:30 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/actions/index.ts
> +const UPDATE_METADATA = createAction('SET_METADATA', {
Update device metadata, not just metadata. Rename everywhere

2022-08-08 08:30 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +export function* updateDeviceMetadataSaga() {
Are you running this after a login/register?

2022-08-08 08:30 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        DeviceInfo.getFirstInstallTime(),
Make sure those 2 time properties are always in UTC

2022-08-08 08:30 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        pushNotificationToken: '', //TODO: FCM token
Configure FCM

2022-08-08 08:30 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    //TODO: handle 400 + UPDATE_REQUIRED and show 'App update required' popup
Don't forget about this. You have to make it sticky, meaning it should persist until the next call to update device metadata that returns 200

2022-08-08 15:18 UTC, OlehPanforov commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +export function* updateDeviceMetadataSaga() {
yes

2022-08-08 15:21 UTC, victor-oancea-leftclick-io commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  const isCreatingSettings = useSelector(
there are no device settings that need to be created at sign in

2022-08-08 15:25 UTC, OlehPanforov commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    //TODO: handle 400 + UPDATE_REQUIRED and show 'App update required' popup
For now I just hide the popup when Update Now button selected so not to block the UI. We should replace this hide popup action with go to store one when that can be tested

2022-08-08 15:26 UTC, OlehPanforov commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        pushNotificationToken: '', //TODO: FCM token
In the scope of this PR?

2022-08-08 15:32 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        pushNotificationToken: '', //TODO: FCM token
ofc

2022-08-08 15:34 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    //TODO: handle 400 + UPDATE_REQUIRED and show 'App update required' popup
thats the point: the up is unusable if you don't update. So yes, ofc you should block the UI. Why can't the go to store button be tested now?

2022-08-08 16:44 UTC, OlehPanforov commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    //TODO: handle 400 + UPDATE_REQUIRED and show 'App update required' popup
because app is not app store so you will not be able to update and  hide that require update popup

2022-08-08 17:03 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +    //TODO: handle 400 + UPDATE_REQUIRED and show 'App update required' popup
I see. Then we'll control that from the BE. 400 + UPDATE_REQUIRED will not happen until we can test with that go to store button. So pls add the whole flow/functionality as it it were possible

2022-08-11 07:42 UTC, pisarevkir approved these changes

2022-08-12 11:51 UTC, pisarevkir approved these changes

2022-08-12 12:49 UTC, victor-oancea-leftclick-io requested changes

2022-08-12 12:49 UTC, victor-oancea-leftclick-io commented on src/navigation/hooks/useUpdateRequiredListener.ts
> +  const updateMetadataPayload = useSelector(
put a flag "updateRequired" instead

2022-08-12 12:49 UTC, victor-oancea-leftclick-io commented on src/screens/PopUps/UpdateRequired/index.tsx
> +            navigation.goBack();
u cant go back

2022-08-12 12:49 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        DeviceInfo.getFirstInstallTime(),
those 2 have to be UTC +0

2022-08-12 12:49 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        DeviceActions.UPDATE_DEVICE_METADATA.FAILED.create(errorMessage, 400),
put a flag instead of 400

2022-08-12 15:06 UTC, OlehPanforov commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> +        DeviceInfo.getFirstInstallTime(),
They are UTC +0 I rechecked.. 
basically, its a timestamp that always starts from +0 when created

2022-08-12 15:06 UTC, OlehPanforov commented on src/screens/PopUps/UpdateRequired/index.tsx
> +            navigation.goBack();
Yeah that was for testing purposes will remove

2022-08-12 15:29 UTC, victor-oancea-leftclick-io approved these changes

2022-08-12 17:04 UTC, max-tal approved these changes

2022-08-15 05:26 UTC, pisarevkir commented on src/store/modules/Devices/reducer/index.ts
> +  blacklist: ['lastMetadataUpdateAt'],
setting `lastMetadataUpdateAt` to backlist means that we persist everything except `lastMetadataUpdateAt`, but we shouldn't do so... just remove the `persistReducer` here completely

2022-08-15 07:36 UTC, pisarevkir approved these changes

2022-08-15 07:39 UTC, victor-oancea-leftclick-io commented on src/store/modules/Devices/reducer/index.ts
> +export const devicesReducer = reducer;
How will this work now?

2022-08-15 12:33 UTC, victor-oancea-leftclick-io approved these changes

2022-08-15 12:42 UTC, pisarevkir approved these changes

2022-08-15 12:53 UTC, max-tal approved these changes

2022-08-15 13:16 UTC, merged