Personal Info api
ice-blockchain/mobile-app pull request #47
Opened 2022-08-04 08:50 UTC by pisarevkir

2022-08-04 10:10 UTC, victor-oancea-leftclick-io commented on src/utils/country.ts
> +    default: countries[0],
Whats this for?

2022-08-04 10:15 UTC, victor-oancea-leftclick-io requested changes
user.country will always be set, if user is registered; so remove that default thing

2022-08-04 10:15 UTC, victor-oancea-leftclick-io commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +    deviceCountry.current ?? deviceCountry.default,
Whats the point of that? You default to the one from device location anyway

2022-08-04 10:15 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +    userCountry.current ?? userCountry.default,
The default thing is useless

2022-08-04 10:15 UTC, victor-oancea-leftclick-io commented on src/components/ModifyPhoneNumber/index.tsx
> +    deviceCountry.current ?? deviceCountry.default,
Default is useless

2022-08-04 10:17 UTC, victor-oancea-leftclick-io commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  const deviceLocation = useSelector(deviceLocationSelector);
Actually, u dont need this either

2022-08-05 05:25 UTC, pisarevkir commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  const deviceLocation = useSelector(deviceLocationSelector);
I don't need `deviceLocation`? Why so?

2022-08-05 05:27 UTC, pisarevkir commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +    deviceCountry.current ?? deviceCountry.default,
I open the app on Sign In screen -> I switch the registration method to "Phone", "get device location" method is not completed yet or it returns an error, what country should be selected in the input?

2022-08-05 05:31 UTC, pisarevkir commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +    userCountry.current ?? userCountry.default,
This is a fallback for the cases when user entity doesn't contain country or that country is not from the `@constants/countries`

2022-08-05 05:31 UTC, pisarevkir commented on src/components/ModifyPhoneNumber/index.tsx
> +    deviceCountry.current ?? deviceCountry.default,
https://github.com/ice-blockchain/mobile-app/pull/47#discussion_r938455794

2022-08-05 05:36 UTC, pisarevkir commented on src/utils/country.ts
> +    default: countries[0],
Fallback, so if country in null / is not from the list, we could pre select at least something in the phone input

2022-08-05 07:34 UTC, victor-oancea-leftclick-io approved these changes

2022-08-05 09:06 UTC, victor-oancea-leftclick-io commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +    deviceCountry.current ?? deviceCountry.default,
first one is fine in that case

2022-08-05 09:16 UTC, victor-oancea-leftclick-io approved these changes

2022-08-05 09:25 UTC, max-tal approved these changes

2022-08-05 10:18 UTC, robertpreoteasa approved these changes

2022-08-05 10:18 UTC, merged