chore: implement News screen design
ice-blockchain/mobile-app pull request #48
Opened 2022-08-05 14:14 UTC by max-tal

2022-08-08 09:08 UTC, victor-oancea-leftclick-io requested changes

2022-08-08 09:08 UTC, victor-oancea-leftclick-io commented on src/screens/News/NewsContent.tsx
> +    updatedAt: '30 min ago',
Use date ; and its createdAt

2022-08-08 09:08 UTC, victor-oancea-leftclick-io commented on src/screens/News/NewsContent.tsx
> +        ListHeaderComponent={<Text style={styles.header}>{'News Feed'}</Text>}
I18n

2022-08-08 09:08 UTC, victor-oancea-leftclick-io commented on src/screens/News/TopNews.tsx
> +const topNews: NewsPost = {
FeaturedPost

2022-08-08 09:08 UTC, victor-oancea-leftclick-io commented on src/screens/News/TopNews.tsx
> +                <Text style={styles.readMoreText}>{'read more'}</Text>
I18n

2022-08-08 14:41 UTC, max-tal commented on src/screens/News/NewsContent.tsx
> +    updatedAt: '30 min ago',
use createdAt as Date

2022-08-08 14:41 UTC, max-tal commented on src/screens/News/TopNews.tsx
> +const topNews: NewsPost = {
renamed

2022-08-08 14:41 UTC, max-tal commented on src/screens/News/TopNews.tsx
> +                <Text style={styles.readMoreText}>{'read more'}</Text>
done

2022-08-08 14:49 UTC, victor-oancea-leftclick-io commented on src/assets/images/index.ts
> +    news2: require('./news/newsPic2.png'),
I've just realised you're building it statically. We don't need that. Build it dynamically from an array. Make everything dynamic

2022-08-09 07:42 UTC, max-tal commented on src/assets/images/index.ts
> +    news2: require('./news/newsPic2.png'),
pictures been removed from here

2022-08-09 07:50 UTC, victor-oancea-leftclick-io submitted a review, later dismissed

2022-08-09 07:50 UTC, victor-oancea-leftclick-io commented on src/screens/News/FeaturedPost.tsx
> +  illustration: require('../../assets/images/news/newsBigPic.png'),
rename those assets/pngs as mockxxx, cuz they're mock data

2022-08-10 07:14 UTC, max-tal commented on src/screens/News/FeaturedPost.tsx
> +  illustration: require('../../assets/images/news/newsBigPic.png'),
done

2022-08-10 07:55 UTC, pisarevkir commented on src/screens/News/index.tsx
> +      <StatusBar barStyle="light-content" />
Use `useFocusStatusBar` instead - take a look how it's used on other screens

2022-08-10 07:55 UTC, pisarevkir commented on src/screens/News/NewsContent.tsx
> +    shadowColor: COLORS.mariner,
Use `commonStyles.shadow` instead

2022-08-10 07:55 UTC, pisarevkir commented on src/screens/News/NewsContent.tsx
> +  const renderHeader = () => {
wrap `renderHeader` and `renderItem `  in `useCallback`, cuz FlatList is a pure component

2022-08-10 07:55 UTC, pisarevkir commented on src/screens/News/index.tsx
> +      <View style={styles.contentWrapper}>
It seems this View - `<View style={styles.contentWrapper}>` is redundant

2022-08-10 07:55 UTC, pisarevkir commented on src/store/types/index.ts
> +import {ImageSourcePropType} from 'react-native';
Could you please remove this file (`src/store/types/index.ts`) - we decided to place types in a corresponding folder in `src/api/***`, so `NewsPost` should be in `src/api/news/types`

2022-08-10 07:55 UTC, pisarevkir commented on src/screens/News/FeaturedPost.tsx
> +  createdAt: moment().subtract(1, 'weeks').toDate(),
`moment.js` lib is legacy - https://github.com/moment/moment#project-status
Moreover as i remember the size of the lib is huge (because of the localizations for all the languages that are coming with the lib). In @OlehPanforov PR we created [src/utils/date.ts](https://github.com/ice-blockchain/mobile-app/pull/45/files#diff-10baaa420455f75556cb3f2ab221bd12171abf0c582942a5b0201fd86b784c8a) that contain util functions for dates, may be it'd be better to implement `fromNow` function there manually and remove the moment.js usage?

2022-08-10 09:36 UTC, victor-oancea-leftclick-io commented on src/screens/News/FeaturedPost.tsx
> +  createdAt: moment().subtract(1, 'weeks').toDate(),
not a good idea to reinvent the wheel. Find another library

2022-08-10 14:37 UTC, max-tal commented on src/screens/News/index.tsx
> +      <StatusBar barStyle="light-content" />
done

2022-08-10 14:37 UTC, max-tal commented on src/screens/News/NewsContent.tsx
> +    shadowColor: COLORS.mariner,
done

2022-08-10 14:37 UTC, max-tal commented on src/screens/News/index.tsx
> +      <View style={styles.contentWrapper}>
contentWrapper  been removed

2022-08-10 14:39 UTC, max-tal commented on src/store/types/index.ts
> +import {ImageSourcePropType} from 'react-native';
`NewsPost` type added to `src/api/news/types`.

Actually `User` from `src/store/types/index.ts` is in use, so I leave it there for now,

2022-08-10 14:40 UTC, max-tal commented on src/screens/News/FeaturedPost.tsx
> +  createdAt: moment().subtract(1, 'weeks').toDate(),
`moment.js` replaced with `dayjs` which is actual and much smaller.

2022-08-10 14:41 UTC, max-tal commented on src/screens/News/NewsContent.tsx
> +  const renderHeader = () => {
wrapped with useCallback

2022-08-11 07:36 UTC, pisarevkir commented on src/screens/News/NewsContent.tsx
> +    paddingHorizontal: SCREEN_SIDE_OFFSET,
Do we really need `<View style={styles.container}>` ? Can't we apply those styles to the FlatList directly (justifyContent and alignItems seems to be redundant)? And why this view applies `paddingHorizontal: SCREEN_SIDE_OFFSET` but the only child has `width: screenWidth` to be of the full screen width - what's the point to set list's width to `screenWidth`?

2022-08-11 08:32 UTC, OlehPanforov approved these changes

2022-08-11 08:32 UTC, OlehPanforov commented on src/screens/News/FeaturedPost.tsx
> +  title: 'ice Network Wallet will\n' + 'be released soon',
Please localize if that would be in the final design

2022-08-11 09:53 UTC, max-tal commented on src/screens/News/FeaturedPost.tsx
> +  title: 'ice Network Wallet will\n' + 'be released soon',
@victor-oancea-leftclick-io is this really needed?

2022-08-11 10:55 UTC, max-tal commented on src/screens/News/NewsContent.tsx
> +    paddingHorizontal: SCREEN_SIDE_OFFSET,
Wrapped View removed.

2022-08-11 11:35 UTC, pisarevkir commented on src/screens/News/FeaturedPost.tsx
> +  title: 'ice Network Wallet will\n' + 'be released soon',
This is a mock data that will be removed eventually, won't it?

2022-08-11 11:36 UTC, pisarevkir submitted a review, later dismissed

2022-08-16 07:50 UTC, OlehPanforov approved these changes

2022-08-16 13:13 UTC, ice-orion submitted a review, later dismissed

2022-08-17 21:13 UTC, ice-hector approved these changes

2022-08-18 13:14 UTC, ice-ares approved these changes

2022-08-18 14:27 UTC, ice-hector approved these changes

2022-08-18 14:34 UTC, ice-orion approved these changes

2022-08-18 14:34 UTC, merged