Profile image
ice-blockchain/mobile-app pull request #49
Opened 2022-08-08 06:30 UTC by pisarevkir

2022-08-08 08:35 UTC, victor-oancea-leftclick-io requested changes

2022-08-08 08:35 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +                  width: 400,
Free flow, not fixed

2022-08-08 13:24 UTC, victor-oancea-leftclick-io commented on src/components/Avatar/index.tsx
> +          (useLocalImage ? (
why?

2022-08-08 13:29 UTC, victor-oancea-leftclick-io commented on src/screens/ProfileFlow/Profile/components/UserInfo/components/Avatar.tsx
> +export const Avatar = ({uri}: Props) => {
Why not use the global one?

2022-08-08 13:30 UTC, victor-oancea-leftclick-io commented on src/screens/Home/components/Header/index.tsx
> +          <RemoteImage
Use the avatar component

2022-08-08 13:33 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/PersonalInformation/hooks/usePickImage.ts
> +      width: 400,
is that the default one or is it fixed?

2022-08-08 13:40 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +              useLocalImage={Boolean(userDraft.profilePicture?.uri)}
why do you need this exposed? This should be the internal business of that component. It should have a "dirty" state when you select any photo, which it should clean (re-feed from uri) on render

2022-08-08 13:43 UTC, victor-oancea-leftclick-io requested changes
x

2022-08-08 13:48 UTC, pisarevkir commented on src/screens/SettingsFlow/PersonalInformation/hooks/usePickImage.ts
> +      width: 400,
You mean the width / height params? This is the size of an image in px after cropping. And those numbers affect the shape of the crop shape (width = 400, height = 400 -> square)

2022-08-08 13:51 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/PersonalInformation/hooks/usePickImage.ts
> +      width: 400,
can I increase/decrease that cropping 400 px square?

2022-08-08 13:52 UTC, pisarevkir commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +              useLocalImage={Boolean(userDraft.profilePicture?.uri)}
Unfortunately the component should distinguish between uri from the BE (where we have to add width as query param) and the uri from the local file system, cuz if we add query params to the local uri it stops working. Actually i can take out the query params adding to the util function and control the uri outside of the Avatar component..

2022-08-08 13:52 UTC, pisarevkir commented on src/components/Avatar/index.tsx
> +          (useLocalImage ? (
https://github.com/ice-blockchain/mobile-app/pull/49#discussion_r940267866

2022-08-08 13:56 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +              useLocalImage={Boolean(userDraft.profilePicture?.uri)}
thats not the question im asking. Ofc you have 2 states. My question is : why do you need to expose that info to the users of that component? Just make it hidden. On the callback from onPenPress you set a "dirty" state inside the component, which you clear on the next rendering

2022-08-08 13:56 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/UserInfo/components/Avatar.tsx
> +export const Avatar = ({uri}: Props) => {
This one has different styles + no edit button or something, so using global one has no benefits

2022-08-08 13:56 UTC, pisarevkir commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +                  width: 400,
What do you mean

2022-08-08 13:56 UTC, pisarevkir commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
>  export const ProfileIcon = ({focused}: Props) => {
This one has different styles + no edit button or something, so using global one has no benefits

2022-08-08 13:57 UTC, pisarevkir commented on src/screens/SettingsFlow/PersonalInformation/hooks/usePickImage.ts
> +      width: 400,
Yea, you can zoom the image during the cropping

2022-08-08 14:01 UTC, pisarevkir commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +              useLocalImage={Boolean(userDraft.profilePicture?.uri)}
How do the component should understand to use the simple `Image` component (without adding query params) or RemoteImage to display the image having only uri?

2022-08-08 14:07 UTC, victor-oancea-leftclick-io commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
>  export const ProfileIcon = ({focused}: Props) => {
put the styles as args, and the edit button can be missing. So it has all the benefits in the world to reuse something

2022-08-08 14:08 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +              useLocalImage={Boolean(userDraft.profilePicture?.uri)}
if its dirty or not

2022-08-08 14:10 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +              useLocalImage={Boolean(userDraft.profilePicture?.uri)}
instead of requiring that useLocalImage bool, have an private/internal dirty flag that you change after user picks an image. dirty ? <Image/> : <RemoteImage/>

2022-08-08 14:11 UTC, pisarevkir commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
>  export const ProfileIcon = ({focused}: Props) => {
If we pass styles as props, then the Avatar component don't bring any benefits - under the hood that is only a wrapper on RemoteImage with some styles

2022-08-08 14:18 UTC, pisarevkir commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
>  export const ProfileIcon = ({focused}: Props) => {
i'll rethink the Avatar component

2022-08-08 14:18 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/UserInfo/components/Avatar.tsx
> +export const Avatar = ({uri}: Props) => {
i'll rethink the Avatar component

2022-08-09 07:13 UTC, pisarevkir commented on src/components/Avatar/index.tsx
> +          (useLocalImage ? (
now internal Avatar component state controls what to show - uri from props or local state image

2022-08-09 07:14 UTC, pisarevkir commented on src/screens/ProfileFlow/Profile/components/UserInfo/components/Avatar.tsx
> +export const Avatar = ({uri}: Props) => {
Here the global one is used

2022-08-09 07:19 UTC, pisarevkir commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
>  export const ProfileIcon = ({focused}: Props) => {
I still think it's better to use plain RemoteImage here - it doesn't make any sense to  use Avatar component that has a lot of additional logic inside that is used only when editing is allowed (useState, usePickImage, useEffect, several additional Views - that all affect performance and doesn't bring any benefits in this case).

2022-08-09 07:19 UTC, pisarevkir commented on src/screens/Home/components/Header/index.tsx
> +          <RemoteImage
I still think it's better to use plain RemoteImage here - it doesn't make any sense to  use Avatar component that has a lot of additional logic inside that is used only when editing is allowed (useState, usePickImage, useEffect, several additional Views - that all affect performance and doesn't bring any benefits in this case).

2022-08-09 07:20 UTC, pisarevkir commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +              useLocalImage={Boolean(userDraft.profilePicture?.uri)}
now internal Avatar component state controls what to show - uri from props or local state image, this prop is not exposed anymore

2022-08-09 07:32 UTC, pisarevkir commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
>  export const ProfileIcon = ({focused}: Props) => {
This is the same case as when we display the list of users - we use simple RemoteImage there, but not the Avatar component - cuz the editing is never the case and the ListUserItem has to be as simple as possible

2022-08-09 07:44 UTC, victor-oancea-leftclick-io requested changes

2022-08-09 07:44 UTC, victor-oancea-leftclick-io commented on src/components/Avatar/index.tsx
> +    containerStyle,
u can set defaults for all 3 styles

2022-08-09 07:44 UTC, victor-oancea-leftclick-io commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
>  export const ProfileIcon = ({focused}: Props) => {
then do this: create 2 avatars: what you have atm and ReadOnlyAvatar, and use only those 2, no more custom profile pic everywhere.

Keep edit logic in avatar and move the rest in ReadOnlyAvatar

2022-08-09 07:44 UTC, victor-oancea-leftclick-io commented on src/screens/Home/components/Header/index.tsx
> +          <RemoteImage
same reply

2022-08-09 09:24 UTC, pisarevkir commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
>  export const ProfileIcon = ({focused}: Props) => {
This would be reasonable if we had some custom logic / styles / whatever inside, but it would be just
```
export const ReadOnlyAvatar = RemoteImage;
```

Cuz basically `ReadOnlyAvatar` is just a RemoteImage (same props: uri, style and width) -> nothing to incapsulate.

2022-08-09 09:30 UTC, pisarevkir commented on src/components/Avatar/index.tsx
> +    containerStyle,
those are optional additional styles:
containerStyle - is used for element positioning and has no default value
imageWrapperStyle - is used if you want to overwrite some of the styles.avatarWrapper
imageStyle - is used if you want to change the some of the styles.image styles

If we set `styles.avatarWrapper` as default for `imageWrapperStyle` prop, then if we pass that prop to component, we'll have to set all the styles for that view. But the way it works now, you can overwrite some specific style property without flushing the rest.

2022-08-11 08:09 UTC, pisarevkir commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
>  export const ProfileIcon = ({focused}: Props) => {
now the Avatar component is used

2022-08-11 08:09 UTC, pisarevkir commented on src/screens/Home/components/Header/index.tsx
> +          <RemoteImage
now the Avatar component is used

2022-08-11 09:17 UTC, victor-oancea-leftclick-io requested changes

2022-08-11 09:17 UTC, victor-oancea-leftclick-io commented on src/components/Avatar/EditableAvatar.tsx
> +  editable?: boolean;
Whats the point of this? The whole component states that is is only editable

2022-08-11 09:17 UTC, victor-oancea-leftclick-io commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
> +          allowFullScreen={false}
Why not?

2022-08-11 09:17 UTC, victor-oancea-leftclick-io commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +              editable={true}
Redundant

2022-08-11 09:17 UTC, victor-oancea-leftclick-io commented on src/utils/openSms.ts
> -// SPDX-License-Identifier: BUSL-1.1
Why did u delete it?

2022-08-11 09:17 UTC, victor-oancea-leftclick-io commented on src/screens/ImageView/index.tsx
> +  const {imageUri} = useImageSizedUri(uri, size);
Where are you getting the 1920x1920 picture?

2022-08-11 11:40 UTC, pisarevkir commented on src/components/Avatar/Avatar.tsx
> +export const Avatar = memo(
This is a perf optimization - the component will not be rerendered if the props are not changed

2022-08-11 11:41 UTC, pisarevkir commented on src/components/Avatar/EditableAvatar.tsx
> +  editable?: boolean;
removed

2022-08-11 11:42 UTC, pisarevkir commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
> +          allowFullScreen={false}
In tabbar we open the corresponding tab on press instead of the full screen image

2022-08-11 11:42 UTC, pisarevkir commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> +              editable={true}
removed

2022-08-11 11:44 UTC, pisarevkir commented on src/utils/openSms.ts
> -// SPDX-License-Identifier: BUSL-1.1
the idea is to group util functions by domain (`utils/file` `utils/network` and so on), so i put that function to the `utils/device` file

2022-08-11 11:47 UTC, pisarevkir commented on src/screens/ImageView/index.tsx
> +  const {imageUri} = useImageSizedUri(uri, size);
`useImageSizedUri` returns uri for a full screen image as soon as it is ready, so the flow if like so:
* `useImageSizedUri` returns uri for the small image and starts loading the image with the full screen width
* as soon as the full width image loaded (if it's already in cache, it will be returned right away), the uri is changed to the new one

2022-08-11 17:20 UTC, victor-oancea-leftclick-io commented on src/components/Avatar/Avatar.tsx
> +export const Avatar = memo(
What if the image is updated from BE, do you display that or the cached one?

2022-08-11 17:21 UTC, victor-oancea-leftclick-io commented on src/navigation/components/MainTabBar/components/Icons/ProfileIcon.tsx
> +          allowFullScreen={false}
Right

2022-08-11 17:21 UTC, victor-oancea-leftclick-io commented on src/utils/openSms.ts
> -// SPDX-License-Identifier: BUSL-1.1
Great

2022-08-11 17:26 UTC, victor-oancea-leftclick-io commented on src/screens/ImageView/hooks/useImageSizedUri.ts
> +    const fullScreeUri = getImageUriForSize(uri, {width: screenWidth});
You’ll lose quality if u do that. Just put 1920. Cuz if you’re using low res phone, lets say 480, and you pinch out, you have only 480 pixels that get enlarged, rather than having the whole 1920 pixels to enjoy

2022-08-12 06:10 UTC, pisarevkir commented on src/components/Avatar/Avatar.tsx
> +export const Avatar = memo(
If the image is updated -> the `uri` is changed -> the component will get updated. `memo` caches the component only if the props stay the same

2022-08-12 16:52 UTC, victor-oancea-leftclick-io submitted a review, later dismissed

2022-08-15 06:59 UTC, victor-oancea-leftclick-io approved these changes

2022-08-15 11:51 UTC, merged