chore: connect achievements and badges api
ice-blockchain/mobile-app pull request #5
Opened 2023-03-23 12:03 UTC by ice-hector

- connect achievements API;
- finalize profile badges summary UI;
- finalize my badges screen;
- add loading states for badges;
- optimized badge images;

2023-03-27 13:54 UTC, ice-atlas requested changes

2023-03-27 13:54 UTC, ice-atlas commented on src/store/modules/Contacts/sagas/inviteContactSaga.ts
> -    })} ${url}`;
Why you removed it? I think `url` is part of invitation

2023-03-27 13:54 UTC, ice-atlas commented on src/store/modules/Achievements/sagas/loadUserAchievements.ts
> +      AchievementsActions.USER_ACHIEVEMENTS_LOAD.SUCCESS.create({
We should have only 1 `SUCCESS` action in thread.

2023-03-27 13:54 UTC, ice-atlas commented on src/store/modules/Achievements/sagas/loadUserAchievements.ts
> +      Api.achievements.getLevelsAndRoles,
We have another saga (`loadLevelsAndRolesSaga`) for this. Adjust it pls

2023-03-27 13:54 UTC, ice-atlas commented on src/services/getstream/mockData.ts
> +      description: '**@Robert** and **3 others** have joined your team',
Let's keep it as is

2023-03-27 13:54 UTC, ice-atlas commented on src/services/getstream/mockData.ts
> +      description: '**@oleh** has joined your team',
same here

2023-03-27 13:54 UTC, ice-atlas commented on src/screens/Team/components/TierList/components/Header/components/Earnings.tsx
> -        <FormattedNumber
We need to keep this functionality

2023-03-27 13:54 UTC, ice-atlas commented on src/screens/SettingsFlow/PersonalInformation/index.tsx
> -            numberOfLines={1}
why you decide to do so?

2023-03-27 13:54 UTC, ice-atlas commented on src/screens/ProfileFlow/Profile/components/Badges/components/BadgeSummariesList.tsx
> +  const badgesData = loading
let's use `useMemo` for this

2023-03-27 13:54 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Pager/components/Wallet/components/TotalMiningRateValue/index.tsx
> -    switch (miningRates?.type) {
revert it pls

2023-03-27 13:54 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/index.tsx
> -  const rateValueTextStyle = useMemo(() => {
revert it pls

2023-03-27 13:54 UTC, ice-atlas commented on src/screens/HomeFlow/Home/components/Pager/components/MiningRate/components/MiningRateValue/index.tsx
> -        `${initialValue > 0 && signRequired ? '+' : ''}${formatNumberString(
revert it pls

2023-03-27 13:54 UTC, ice-atlas commented on src/constants/links.ts
> -  FEEDBACK_EMAIL: 'feedback@ice.io',
revert it pls

2023-03-27 13:54 UTC, ice-atlas commented on src/constants/countries.ts
> -    name: 'Bolivia',
revert country names

2023-03-27 13:54 UTC, ice-atlas commented on src/components/Inputs/CommonInput/index.tsx
> -              <Text style={styles.input} {...textInputProps}>
revert it pls

2023-03-27 21:58 UTC, ice-atlas commented on src/screens/ProfileFlow/Badges/components/BadgeCard.tsx
> +    `${type}${index}_achieved_${achieved}` as keyof typeof Images.badges;
use `as const` or put it in the one specific place as is

2023-03-28 03:41 UTC, ice-orion commented on src/assets/svg/PeopleIcon.tsx
> +  <Svg width={13} height={13} fill="none" viewBox="0 0 13 13" {...props}>
rem and color?

2023-03-28 03:45 UTC, ice-orion commented on src/constants/colors.ts
> +  linkWater2: '#D7EAF4', // inactive badges color
kinda weird naming, let's name it `azureishWhite`?  https://www.color-name.com/hex/d7eaf4
And comment here looks redundant

2023-03-28 03:54 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/AvatarHeader/index.tsx
The component is almost 400 lines of code that is too much.
Lest separate code according to single responsibility principle:
e.g. : set all the animation related code to `useAnimatedStyles` hook
e.g. 2: create separate components for buttons - PenButton / ContactsButton
...

2023-03-28 03:56 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/Badges/components/BadgeCard.tsx
> +    const image = `${category}0_achieved_true` as keyof typeof Images.badges;
better use `as const` here as more safe

2023-03-28 03:56 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/Badges/components/BadgeCard.tsx
> +      : (`${category}0_achieved_false` as keyof typeof Images.badges);
and here

2023-03-28 03:59 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/Badges/components/BadgeSummariesList.tsx
> +    : user?.hiddenProfileElements?.includes('badges');
Let's use separate variable for `user?.hiddenProfileElements?.includes('badges')`?

2023-03-28 08:22 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/LadderBar/index.tsx
> +              ? `${achievements?.levelsAndRoles?.level}`
Also, can't the level be 0? In this case the ternar will return wrong result
optional: `achievements.levelsAndRoles.level`

2023-03-28 10:36 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/LadderBar/index.tsx
> +              ? `${achievements?.levelsAndRoles?.level}`
1 is default, not less

2023-03-28 10:40 UTC, ice-hector commented on src/screens/ProfileFlow/Badges/components/BadgeCard.tsx
> +    `${type}${index}_achieved_${achieved}` as keyof typeof Images.badges;
Index here is a number so couldn't be use `as const`
This solution is the temp in general, so we gonna move that images to the backend side and use only URLs on FE side after release.

2023-03-28 11:57 UTC, ice-orion commented on src/store/modules/Achievements/sagas/loadAllBadgesSaga.ts
> +    const getBadgesByTypeResultSocial: SagaReturnType<
can we do getBadgesByType getBadgesByType and getBadgesByType in parallel?

2023-03-28 17:03 UTC, ice-atlas requested changes

2023-03-28 17:03 UTC, ice-atlas commented on src/screens/ProfileFlow/Profile/components/Badges/components/BadgeSummariesList.tsx
> +      ? defaultData
basic idea to use `memo` here also simplify (get rid of) ternary operator. Pls use `if-else` here

2023-03-28 17:03 UTC, ice-atlas commented on src/store/modules/Achievements/sagas/loadAllBadgesSaga.ts
> +    ] = yield all([
Let's try to use `TypeScript tuples` for this

2023-03-29 08:45 UTC, ice-orion approved these changes

2023-03-29 09:26 UTC, ice-hades approved these changes

2023-03-29 09:27 UTC, ice-atlas approved these changes

2023-03-29 09:44 UTC, merged