chore: init sentry
ice-blockchain/mobile-app pull request #50
Opened 2022-08-10 07:06 UTC by max-tal

2022-08-11 07:10 UTC, victor-oancea-leftclick-io requested changes

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/api/client/ApiServiceErrors.ts
> +export function handleServiceError(error: unknown) {
put the async back

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/createUser.ts
> +    Sentry.captureException(error);
do u need this if you already put it in src/api/client/ApiServiceErrors.ts?

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/deleteAccount.ts
> +    Sentry.captureException(errorMessage);
do u need this if you already put it in src/api/client/ApiServiceErrors.ts?

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUser.ts
> +    Sentry.captureException(error);
do u need this if you already put it in src/api/client/ApiServiceErrors.ts?

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUser.ts
> +      email: user.email!,
not needed

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUser.ts
> +    Sentry.setUser({
what does this do?

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUser.ts
> +      username: `${user.firstName} ${user.lastName}`,
user.username

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/loadUser.ts
> +    Sentry.captureException(error);
do u need this if you already put it in src/api/client/ApiServiceErrors.ts?

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/signInEmail.ts
> +    Sentry.captureException(error);
do u need this if you already put it in src/api/client/ApiServiceErrors.ts?

2022-08-11 07:10 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/signInPhone.ts
> +    Sentry.captureException(error);
do u need this if you already put it in src/api/client/ApiServiceErrors.ts?

2022-08-11 07:51 UTC, pisarevkir commented on src/App.tsx
> +export default __DEV__ ? App : Sentry.wrap(App);
We decided to use named export over default one throughout the project because of the easier maintability (refactoring) and better error reports (names exports are also named in the component tree)

2022-08-11 08:01 UTC, pisarevkir commented on src/api/client/ApiServiceErrors.ts
> +  Sentry.captureException(error);
This way we won't see the errors during development, so instead of calling `Sentry.captureException` directry it's better to create some wrapper function like so:
```
export function logError(error: unknown, category: string, extra?: Extras) {
  if(__DEV__ ) {
    console.log('logError' , {
      error,
      category,
      extra,
    });
} else {
  captureException(error, {
    tags: {
      category,
    },
    extra,
  });
}
}
```

2022-08-11 08:07 UTC, pisarevkir commented on src/App.tsx
> +!__DEV__ && Sentry.init({dsn: ENV.SENTRY_KEY});
We can also consider using https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/redux/
Example from prev project:
```
const sentryReduxEnhancer = createReduxEnhancer({
  // don't attach the state to redux events
  stateTransformer: () => null,
  actionTransformer: (action) => {
    // omit payload cuz it can contain private data
    const { payload, ...strippedAction } = action;
    return strippedAction;
  },
});
```

And React Navigation integration https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#react-navigation

Those would provide more insights about the errors

2022-08-11 11:29 UTC, max-tal commented on src/api/client/ApiServiceErrors.ts
> +export function handleServiceError(error: unknown) {
done

2022-08-11 11:29 UTC, max-tal commented on src/store/modules/Auth/sagas/createUser.ts
> +    Sentry.captureException(error);
removed

2022-08-11 11:29 UTC, max-tal commented on src/store/modules/Auth/sagas/fetchUser.ts
> +    Sentry.captureException(error);
removed

2022-08-11 11:30 UTC, max-tal commented on src/store/modules/Auth/sagas/fetchUser.ts
> +      username: `${user.firstName} ${user.lastName}`,
updated

2022-08-11 11:30 UTC, max-tal commented on src/store/modules/Auth/sagas/loadUser.ts
> +    Sentry.captureException(error);
removed

2022-08-11 11:30 UTC, max-tal commented on src/store/modules/Auth/sagas/signInEmail.ts
> +    Sentry.captureException(error);
removed

2022-08-11 11:30 UTC, max-tal commented on src/App.tsx
> +export default __DEV__ ? App : Sentry.wrap(App);
named import used

2022-08-11 11:31 UTC, max-tal commented on src/store/modules/Auth/sagas/fetchUser.ts
> +    Sentry.setUser({
This provides additional information for sentry logs that may allow track problems for certain user

2022-08-11 11:32 UTC, max-tal commented on src/store/modules/Auth/sagas/deleteAccount.ts
> +    Sentry.captureException(errorMessage);
removed

2022-08-11 11:50 UTC, victor-oancea-leftclick-io commented on src/App.tsx
> +!__DEV__ && Sentry.init({dsn: ENV.SENTRY_KEY});
@max-tal lets do that

2022-08-11 11:51 UTC, victor-oancea-leftclick-io commented on src/api/client/ApiServiceErrors.ts
> +  Sentry.captureException(error);
@max-tal lets do that

2022-08-11 11:54 UTC, victor-oancea-leftclick-io requested changes

2022-08-11 11:54 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUser.ts
> +      email: user.email!,
not needed

2022-08-11 11:54 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/fetchUser.ts
> +      username: user.username!,
actually, not needed

2022-08-11 11:54 UTC, victor-oancea-leftclick-io commented on src/store/modules/Auth/sagas/signInSocial.ts
> +    Sentry.captureException(error);
create a global logger, and use sentry only there

2022-08-11 11:54 UTC, victor-oancea-leftclick-io commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +    Sentry.captureException(error);
lets not repeat this all over the place

2022-08-12 07:27 UTC, max-tal commented on src/api/client/ApiServiceErrors.ts
> +  Sentry.captureException(error);
logging errors extracted to separate function

2022-08-12 07:27 UTC, max-tal commented on src/App.tsx
> +!__DEV__ && Sentry.init({dsn: ENV.SENTRY_KEY});
redux and react-navigation integrations added

2022-08-12 07:27 UTC, max-tal commented on src/store/modules/Auth/sagas/fetchUser.ts
> +      email: user.email!,
removed

2022-08-12 07:28 UTC, max-tal commented on src/store/modules/Auth/sagas/fetchUser.ts
> +      username: user.username!,
removed

2022-08-12 07:28 UTC, max-tal commented on src/store/modules/News/sagas/loadNewsSaga.ts
> +    Sentry.captureException(error);
done

2022-08-12 07:44 UTC, victor-oancea-leftclick-io requested changes

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on index.js
> +import {SentryWrapper} from '@services/sentry/sentry';
why sentry/sentry?

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/screens/News/index.tsx
> +import * as Sentry from '@sentry/react-native';
remove

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/screens/News/index.tsx
> +    // debugger;
remove

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/services/sentry/sentry.ts
> +
rename file path to src/services/logging

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/services/sentry/sentry.ts
> +  release: `${getBundleId()}@${getBuildNumber()}`,
see if this is needed, remove it to see if it picks up the correct version

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/services/sentry/sentry.ts
> +export function SentryWrapper(app: React.ComponentType) {
LogWrapper

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/services/sentry/sentry.ts
> +    console.log('logError', {
why not console.error?

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/store/configureStore.ts
> +const sentryReduxEnhancer = Sentry.createReduxEnhancer({
move to src/service/logging, export it as loggingReduxEnhancer

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/services/sentry/sentry.ts
> +Sentry.init({
what about the before breadcrumb part?

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/services/sentry/sentry.ts
> +export function logError(error: unknown) {
add a logInfo one as well

2022-08-12 07:44 UTC, victor-oancea-leftclick-io commented on src/services/sentry/sentry.ts
> +    Sentry.captureException(error);
u need scope here, to set the user

2022-08-12 11:57 UTC, pisarevkir commented on src/store/modules/Auth/sagas/signInSocial.ts
> +    logError(error);
lets create a wrapper that we'll use to wrap every saga? Something like this:
```
export const generatorErrorBoundary = <TFunc,>(wrappedGenerator: TFunc, errorCategory: string) =>
  __DEV__
    ? wrappedGenerator
    : (function* (...args: unknown[]) {
        try {
          // @ts-ignore
          return yield* wrappedGenerator(...args);
        } catch (error: unknown) {
          handleError(`${t('common_error_unknown')} ${errorCategory}`);
          logError(error, errorCategory);
        }
      } as unknown as TFunc);
``

2022-08-15 08:43 UTC, pisarevkir commented on src/store/modules/Devices/sagas/updateDeviceLocation.ts
> +    logError(error);
I think we need to use `logError(error)` in every saga, now only some of them are handled

2022-08-15 08:45 UTC, pisarevkir commented on src/store/rootSaga.ts
>              console.log(`Log this error to Crashlytics ${logError}`);
We don't need this console.log anymore

2022-08-15 08:56 UTC, pisarevkir commented on src/utils/openSms.ts
> +    Sentry.captureException(error);
logError

2022-08-15 09:05 UTC, pisarevkir commented on src/services/sentry/sentry.ts
> +Sentry.init({
```
beforeBreadcrumb: (breadcrumb) => {
    return breadcrumb.category === 'xhr' ? null : breadcrumb;
  },
```

It was used to omit `xhr` logging because on that project Apollo GraphQL was used and every default request log looked like some uninformative junk, so there we had to log request the other way. For us the default logger should do the job well.

2022-08-29 09:41 UTC, ice-orion commented on src/utils/errors.ts
> +  logError(error);
this is a util function that just extracts a message from error, there should no be any side effects like sending the error to sentry

2022-08-30 07:41 UTC, ice-ares requested changes
pay attention to all ur comments and fix em

2022-08-30 07:41 UTC, ice-ares commented on src/store/modules/Devices/sagas/initDevice.ts
> +import {logError} from '@services/sentry/sentry';
find a way to handle errors in root saga for all sagas

2022-09-02 07:23 UTC, ice-eros commented on src/screens/News/index.tsx
> +import * as Sentry from '@sentry/react-native';
done

2022-09-02 07:24 UTC, ice-eros commented on src/screens/News/index.tsx
> +    // debugger;
done

2022-09-02 07:33 UTC, ice-eros commented on src/store/rootSaga.ts
>              console.log(`Log this error to Crashlytics ${logError}`);
done

2022-09-02 08:23 UTC, ice-ares requested changes

2022-09-02 08:23 UTC, ice-ares commented on index.js
> +import {SentryWrapper} from '@services/logging';
LoggingWrapper

2022-09-02 08:23 UTC, ice-ares commented on src/services/logging/index.ts
> +export const sentryReduxEnhancer = Sentry.createReduxEnhancer({
loggingReduxEnhancer

2022-09-02 08:23 UTC, ice-ares commented on src/services/logging/index.ts
> +    Sentry.captureException(error);
Add scope

2022-09-02 08:23 UTC, ice-ares commented on src/services/logging/index.ts
> +    console.error('logError', {
Add scope here as well

2022-09-02 08:23 UTC, ice-ares commented on src/store/modules/Auth/sagas/loadUser.ts
> +    logError(error);
Find a way to handle logging in one place, globally, IE root saga. We shouldn't just add logError everywhere.

@ice-orion @ice-hector any advice on how to do this?

2022-09-02 08:23 UTC, ice-ares commented on src/store/rootSaga.ts
>              console.log('One of rootSaga will be restarted. Error:', error);
Why do u need this?

2022-09-02 08:23 UTC, ice-ares commented on src/store/rootSaga.ts
> +            const errorToLog = new Error();
Dont transform the error, keep it as is

2022-09-02 09:18 UTC, ice-orion commented on src/store/modules/Auth/sagas/loadUser.ts
> +    logError(error);
probably we can use `rootSaga` for that -> there is already try...catch wrapper for every saga there, so hypothetically we can rethrow unexpected errors in sagas so they would be handled in `rootSaga`

2022-09-02 09:21 UTC, ice-orion commented on src/store/modules/Devices/sagas/updateDeviceLocation.ts
> +    logError(error);
or if we log errors globally in the root saga, we need to rethrow unexpected errors in every saga

2022-09-02 09:45 UTC, ice-ares commented on src/store/modules/Auth/sagas/loadUser.ts
> +    logError(error);
yep, lets rethrow em

2022-09-02 09:50 UTC, ice-ares commented on src/api/client/ApiServiceErrors.ts
>  export async function handleServiceError(error: unknown) {
this might make us log the error twice, once here and once in the sagas when the BE api fails

2022-09-02 10:48 UTC, ice-eros commented on index.js
> +import {SentryWrapper} from '@services/sentry/sentry';
fixed

2022-09-02 10:49 UTC, ice-eros commented on src/services/sentry/sentry.ts
> +
done

2022-09-02 10:49 UTC, ice-eros commented on src/services/sentry/sentry.ts
> +    console.log('logError', {
fixed

2022-09-02 10:49 UTC, ice-eros commented on src/store/configureStore.ts
> +const sentryReduxEnhancer = Sentry.createReduxEnhancer({
done

2022-09-05 07:43 UTC, ice-eros commented on src/services/sentry/sentry.ts
> +  release: `${getBundleId()}@${getBuildNumber()}`,
removed

2022-09-05 07:43 UTC, ice-eros commented on src/services/sentry/sentry.ts
> +    Sentry.captureException(error);
scope added

2022-09-05 07:43 UTC, ice-eros commented on src/store/modules/Devices/sagas/updateDeviceLocation.ts
> +    logError(error);
removed from here

2022-09-05 07:43 UTC, ice-eros commented on src/utils/errors.ts
> +  logError(error);
removed from here

2022-09-05 07:44 UTC, ice-eros commented on src/store/modules/Devices/sagas/initDevice.ts
> +import {logError} from '@services/sentry/sentry';
error logged in custom middleware

2022-09-05 07:44 UTC, ice-eros commented on index.js
> +import {SentryWrapper} from '@services/logging';
renamed

2022-09-05 07:44 UTC, ice-eros commented on src/services/logging/index.ts
> +export const sentryReduxEnhancer = Sentry.createReduxEnhancer({
renamed

2022-09-05 07:44 UTC, ice-eros commented on src/services/logging/index.ts
> +    Sentry.captureException(error);
scope added

2022-09-05 07:45 UTC, ice-eros commented on src/store/modules/Auth/sagas/loadUser.ts
> +    logError(error);
error logged in custom middleware

2022-09-05 07:45 UTC, ice-eros commented on src/store/rootSaga.ts
> +            const errorToLog = new Error();
removed

2022-09-05 07:45 UTC, ice-eros commented on src/services/sentry/sentry.ts
> +export function SentryWrapper(app: React.ComponentType) {
renamed

2022-09-05 07:53 UTC, ice-ares requested changes

2022-09-05 07:53 UTC, ice-ares commented on src/services/logging/index.ts
> +export function logError(error: unknown, userId?: string) {
Hell ho, use selector to get the user

2022-09-05 07:53 UTC, ice-ares commented on src/services/logging/index.ts
> +      logError(JSON.stringify(payload), userId);
Why make it json? Its an error

2022-09-05 07:55 UTC, ice-orion commented on src/services/logging/index.ts
> +export const actionLogger: Middleware =
This might work, but there is one flaw - we'll log some errors that we should not, like `CONFLICT_WITH_ANOTHER_USER` or `REFERRAL_NOT_FOUND` - they also produce `ValidationActions.USERNAME_VALIDATION.FAILED` actions so they'll be logged automatically.

2022-09-05 08:11 UTC, ice-eros commented on src/services/logging/index.ts
> +export function logError(error: unknown, userId?: string) {
done

2022-09-05 08:11 UTC, ice-eros commented on src/services/logging/index.ts
> +      logError(JSON.stringify(payload), userId);
json removed

2022-09-05 08:27 UTC, ice-ares commented on src/services/logging/index.ts
> +export const actionLogger: Middleware =
Actually, I think it might be a good idea to log those as well, cuz we can have some analytics on em

2022-09-05 08:30 UTC, ice-ares commented
@ice-orion pls make sure every error is logged: native ones, js 3rd party ones, js business logic, BE api, etc, everything. And try to find global entry points for all of them

2022-09-05 08:41 UTC, ice-orion commented on src/services/logging/index.ts
> +export const actionLogger: Middleware =
hmmm, if we also need to log those, then ok, i'll get the middleware back

2022-09-05 08:52 UTC, ice-ares commented on src/services/logging/index.ts
> +      scope.setUser({id: userSelector(store.getState())?.id});
Pls add the username as well

2022-09-05 09:03 UTC, ice-orion commented on src/services/logging/index.ts
> +export const actionLogger: Middleware =
actually we don't have the whole error (stack and so on in *.FAILED actions and sometimes don't have FAILED actions at all), so i end up with rethrowing errors

2022-09-05 09:05 UTC, ice-orion commented on src/services/logging/index.ts
> +      scope.setUser({id: userSelector(store.getState())?.id});
done

2022-09-05 09:10 UTC, ice-ares submitted a review, later dismissed

2022-09-05 09:50 UTC, ice-hector submitted a review, later dismissed

2022-09-05 11:25 UTC, ice-orion approved these changes

2022-09-05 11:30 UTC, ice-ares approved these changes

2022-09-05 11:31 UTC, ice-hector approved these changes

2022-09-05 11:46 UTC, ice-orion approved these changes

2022-09-05 11:59 UTC, ice-hector approved these changes

2022-09-05 12:34 UTC, merged