User search
ice-blockchain/mobile-app pull request #52
Opened 2022-08-15 12:44 UTC by pisarevkir

2022-08-16 19:46 UTC, victor-oancea-leftclick-io requested changes
Would have been a great PR if all features were implemented

2022-08-17 09:58 UTC, ice-ares commented on src/components/UserListItem/components/UserListPingButton/index.tsx
> +  if (pinged == null) {
or undefined

2022-08-17 10:06 UTC, ice-ares commented on src/utils/errors.ts
> +  return t('error.general_error');
or check if its API error, and in that case return some default message + code from resp body

2022-08-17 10:10 UTC, ice-orion commented on src/components/UserListItem/components/UserListPingButton/index.tsx
> +  if (pinged == null) {
`==` is used intentionally to match `undefined`, so 
```
undefined == null -> true
null == null -> true
```

2022-08-17 11:23 UTC, ice-orion commented on src/utils/errors.ts
> +  return t('error.general_error');
done, in case of isApiError->true the message is `Request failed with status {{status}} and code {{code}}`

2022-08-17 11:43 UTC, ice-ares approved these changes

2022-08-17 13:59 UTC, ice-eros approved these changes

2022-08-17 15:28 UTC, ice-hector approved these changes

2022-08-17 15:28 UTC, merged