feat: implement pop-ups
ice-blockchain/mobile-app pull request #69
Opened 2022-09-13 06:39 UTC by ice-eros

2022-09-13 07:37 UTC, ice-ares requested changes
u need to use the error & updated popups

2022-09-13 08:19 UTC, ice-orion commented on src/components/PopUp/index.tsx
> +const PopUp = ({
Nice that you created this component to reduce copy/paste! Let's put such components into the screens/Templates folder? Like here in my branch i also created a template - https://github.com/ice-blockchain/mobile-app/pull/61/files#diff-1d0e44cea7c5d4b7f6d715636feb9eecd565e10c5d9f852e0ec7d3cdb674ec02

2022-09-13 08:19 UTC, ice-orion commented on src/components/PopUp/index.tsx
> +export enum PopUpType {
Let's get rid of passing `PopUpType` - this violated the SOLID `O` principle - if we create any new type of PopUp, we'll have to modify this template [link](https://blog.ndepend.com/solid-design-the-open-close-principle-ocp/#:~:text=The%20Open%2DClose%20principle%20(OCP)%20is%20the%20O%20in,the%20well%20known%20SOLID%20acronym.&text=A%20module%20will%20be%20said,set%20of%20functions%20it%20performs).

It's better to pass the image directly as a prop.

2022-09-13 08:19 UTC, ice-orion commented on src/components/PopUp/index.tsx
> +    <View style={styles.container}>
Do we need this View? It looks like we can get rid of `<View style={styles.container}>`

2022-09-13 08:19 UTC, ice-orion commented on src/components/PopUp/index.tsx
> +          <TouchableWithoutFeedback onPress={() => {}}>
What is it for? To prevent closing the popup? If so, use `stopPropagination`  from `@components/KeyboardDismiss`

2022-09-13 08:19 UTC, ice-orion commented on src/screens/PopUps/UpdateSuccessful/index.tsx
> +      onButtonPress={() => {}}
Probably passing `navigation.goBack` can do the trick?

2022-09-13 08:19 UTC, ice-orion commented on src/screens/PopUps/UpdateRequired/index.tsx
> +      onButtonPress={() => {}}
Open the corresponding store

2022-09-23 06:39 UTC, ice-eros commented on src/components/PopUp/index.tsx
> +const PopUp = ({
moved to template

2022-09-23 06:39 UTC, ice-eros commented on src/components/PopUp/index.tsx
> +export enum PopUpType {
PopUpType removed

2022-09-23 06:40 UTC, ice-eros commented on src/components/PopUp/index.tsx
> +    <View style={styles.container}>
removed

2022-09-23 06:40 UTC, ice-eros commented on src/components/PopUp/index.tsx
> +          <TouchableWithoutFeedback onPress={() => {}}>
extra Touchable removed

2022-09-23 06:40 UTC, ice-eros commented on src/screens/PopUps/UpdateSuccessful/index.tsx
> +      onButtonPress={() => {}}
yes, added

2022-09-23 06:40 UTC, ice-eros commented on src/screens/PopUps/UpdateRequired/index.tsx
> +      onButtonPress={() => {}}
added

2022-09-28 06:36 UTC, ice-orion commented on src/screens/PopUps/Error/index.tsx
> +      onButtonPress={() => {}}
The goal of the PR is to implement a new design only or the pop-ups should work as part of the app?

2022-09-28 06:36 UTC, ice-orion commented on src/screens/PopUps/UpdateRequired/index.tsx
> +const APP_STORE_LINK = '';
let's place these constants to `constants/links`

2022-09-28 06:36 UTC, ice-orion commented on src/screens/PopUps/UpdateRequired/index.tsx
> +    } catch {}
Use `logError`, never leave empty catch blocks

2022-09-28 06:36 UTC, ice-orion commented on src/screens/PopUps/UpdateRequired/index.tsx
> +      if (isIOS) {
optional: `await Linking.openURL(isIOS  ? APP_STORE_LINK : PLAY_STORE_LINK);`

2022-09-28 06:36 UTC, ice-orion commented on src/screens/Templates/PopUp/index.tsx
> +          <TouchableOpacity onPress={onPress}>
use the wrapper from `components/Touchable`

2022-09-28 06:36 UTC, ice-orion commented on src/screens/PopUps/UpdateRequired/index.tsx
> +      dismissOnOutsideTouch={false}
Shouldn't we use `dismissOnButtonPress=false` as well? Otherwise user may press the update button, go back to the app and the pop-up will be closed, won't it?

2022-10-03 09:40 UTC, ice-hector commented on src/screens/PopUps/Error/index.tsx
> +      onButtonPress={() => {}}
Why is the onButtonPress not handled?

2022-10-03 09:40 UTC, ice-hector commented on src/screens/PopUps/UpdateRequired/index.tsx
> +const PLAY_STORE_LINK = '';
Should the value be here?

2022-10-03 09:40 UTC, ice-hector commented on src/screens/Templates/PopUp/index.tsx
> +    marginTop: -rem(45),
Should this top margin vary depending on if the phone has a notch or not?

2022-10-03 10:04 UTC, ice-eros commented on src/screens/PopUps/UpdateRequired/index.tsx
> +    } catch {}
logError added

2022-10-03 10:05 UTC, ice-eros commented on src/screens/PopUps/UpdateRequired/index.tsx
> +      if (isIOS) {
refactored this way

2022-10-03 10:06 UTC, ice-eros commented on src/screens/PopUps/UpdateRequired/index.tsx
> +      dismissOnOutsideTouch={false}
`dismissOnButtonPress={false}` added but not sure if this is better behaviour

2022-10-03 10:07 UTC, ice-eros commented on src/screens/PopUps/UpdateRequired/index.tsx
> +const PLAY_STORE_LINK = '';
moved to `constants/links`

2022-10-03 10:08 UTC, ice-eros commented on src/screens/Templates/PopUp/index.tsx
> +    marginTop: -rem(45),
Actually not, this is just picture overflow over pop-up box

2022-10-03 10:12 UTC, ice-eros commented on src/screens/PopUps/Error/index.tsx
> +      onButtonPress={() => {}}
Yes, this is rather design PR, but with some functional additions for update pop-up.
As for action for button in error pop-up - probably there should be two options:
1. do nothing, just close pop-up
2. retry action that cause error
Decision about action could be done only inside saga/component.

2022-10-03 10:15 UTC, ice-orion commented on src/screens/PopUps/Error/index.tsx
> +      onButtonPress={() => {}}
We anyway have to react in some way to the button press... Let's at least close the popup?

2022-10-03 10:22 UTC, ice-eros commented on src/screens/PopUps/Error/index.tsx
> +      onButtonPress={() => {}}
as there is  default ` dismissOnButtonPress = true`, it will be closed

2022-10-03 11:03 UTC, ice-orion commented on src/screens/PopUps/Error/index.tsx
> +      onButtonPress={() => {}}
Why do we pass the anonymous function then? Let's remove it

2022-10-03 11:05 UTC, ice-eros commented on src/screens/PopUps/Error/index.tsx
> +      onButtonPress={() => {}}
removed

2022-10-03 11:06 UTC, ice-orion submitted a review, later dismissed

2022-10-03 11:49 UTC, ice-hector submitted a review, later dismissed

2022-10-04 13:54 UTC, ice-ares commented on src/constants/links.ts
> +export const APP_STORE_LINK = '';
will those have sensitive data in them?

2022-10-04 13:59 UTC, ice-ares commented on src/assets/svg/PopUp/TryAgain.tsx
> +export const TryAgain = (props: SvgProps) => (
where is this used?

2022-10-05 08:13 UTC, ice-eros commented on src/assets/images/index.ts
> +    success: require('./popup/already_updated.png'),
renamed

2022-10-05 08:14 UTC, ice-eros commented on src/constants/links.ts
> +export const APP_STORE_LINK = '';
no, this URL is visible for example in address bar of browser in PlayMarket

2022-10-05 08:14 UTC, ice-eros commented on src/assets/svg/PopUp/TryAgain.tsx
> +export const TryAgain = (props: SvgProps) => (
removed

2022-10-05 08:47 UTC, ice-ares approved these changes

2022-10-05 08:49 UTC, ice-orion approved these changes

2022-10-05 10:10 UTC, ice-hector approved these changes

2022-10-05 10:10 UTC, merged