Refactor auth-flow
ice-blockchain/mobile-app pull request #70
Opened 2022-09-20 12:58 UTC by ice-orion

2022-09-30 07:15 UTC, ice-ares commented on src/screens/Team/components/Header/components/InfoItem/index.tsx
> -  const refsCount = 0; //TODO: get from selectors
why? u might be missing this without the comment

2022-09-30 07:18 UTC, ice-ares commented on src/screens/UserRegistrationFlow/ProfileFill/components/ClaimNickname/hooks/useClaimUsername.ts
> +            'username',
u might have that duplicate in the array

2022-09-30 07:19 UTC, ice-orion commented on src/screens/Team/components/Header/components/InfoItem/index.tsx
> -  const refsCount = 0; //TODO: get from selectors
The point is that we have hardcoded values everywhere throught the app but the `TODO` is set only here, so we might need to mark all the places or don't mark at all

2022-09-30 07:19 UTC, ice-ares commented on src/screens/UserRegistrationFlow/ProfileFill/components/ClaimNickname/hooks/useClaimUsername.ts
> +    validateUsername(usernameToPrefill.current);
use setUsername

2022-09-30 07:20 UTC, ice-ares commented on src/screens/UserRegistrationFlow/ProfileFill/components/ClaimNickname/hooks/useClaimUsername.ts
> +    usernameToPrefill.current = '';
use setUsername

2022-09-30 07:21 UTC, ice-ares commented on src/screens/UserRegistrationFlow/ProfileFill/components/ClaimNickname/hooks/useClaimUsername.ts
> +  if (usernameToPrefill.current) {
can’t understand what this if is for

2022-09-30 07:22 UTC, ice-ares commented on src/screens/UserRegistrationFlow/ProfileFill/components/ClaimNickname/hooks/useClaimUsername.ts
> +export const useClaimUsername = () => {
replace “nickname” to “username” everywhere across the app

2022-09-30 07:27 UTC, ice-ares commented on src/screens/UserRegistrationFlow/ProfileFill/components/WhoInvitedYou/hooks/useWhoInvited.ts
> +            'referral',
u might insert a duplicate

2022-09-30 07:28 UTC, ice-ares commented on src/screens/UserRegistrationFlow/ProfileFill/components/WhoInvitedYou/hooks/useWhoInvited.ts
> +            'referral',
same here

2022-09-30 07:29 UTC, ice-ares commented on src/screens/UserRegistrationFlow/ProfileFill/components/WhoInvitedYou/hooks/useWhoInvited.ts
> +export const useWhoInvited = () => {
whoInvitedYou, same for the filename

2022-09-30 07:34 UTC, ice-ares commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> -    if (isAuthorized && deviceSettings) {
why?

2022-09-30 07:37 UTC, ice-ares commented on src/store/modules/Auth/actions/index.ts
> -const CREATE_USER = createAction('CREATE_USER', {
why did u remove this?

2022-09-30 07:39 UTC, ice-ares commented on src/store/modules/Auth/reducer/index.ts
> -  | typeof AuthActions.SIGN_IN_EMAIL.SUCCESS.create
why did u remove those?

2022-09-30 07:43 UTC, ice-ares commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +    phoneNumberHash = yield call(hashPhoneNumber, phoneNumber);
formatedNumber, not phoneNumber. Make sure its like that everywhere across the app

2022-09-30 07:44 UTC, ice-ares commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +        registrationProcessFinalizedSteps: ['email'],
merge with existing

2022-09-30 07:48 UTC, ice-ares commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      errorMessage = t('errors.multiple_accounts');
this should not happen when when we switch to firebase auth. Add a todo here

2022-09-30 07:54 UTC, ice-ares commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      errorMessage = t('errors.multiple_accounts');
actually, even after that, you can get a conflict on phoneNumber. So check for field === ‘phoneNumber’ || field === ‘phoneNumberHash’ in the response. And if so, remove phonenumber &hash from create user request and try again + send an error to sentry :”phoneNumber was taken by another user, so we had to remove it from current user’s “ + userId

2022-09-30 07:56 UTC, ice-ares commented on src/store/modules/Auth/sagas/fetchUser.ts
> -export function* fetchUserSaga() {
u don’t need this?

2022-09-30 07:59 UTC, ice-ares commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      errorMessage = t('errors.multiple_accounts');
`error?.response?.data?.data?.field`

2022-09-30 08:06 UTC, ice-ares commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> +    if (user?.username === username) {
compare ids

2022-09-30 08:08 UTC, ice-ares requested changes
❄️

2022-09-30 16:19 UTC, ice-orion commented on src/screens/UserRegistrationFlow/ProfileFill/components/ClaimNickname/hooks/useClaimUsername.ts
> +            'username',
done, checking if the value is not present in the array

2022-09-30 16:20 UTC, ice-orion commented on src/screens/UserRegistrationFlow/ProfileFill/components/ClaimNickname/hooks/useClaimUsername.ts
> +    usernameToPrefill.current = '';
reworked this part

2022-09-30 16:20 UTC, ice-orion commented on src/screens/UserRegistrationFlow/ProfileFill/components/ClaimNickname/hooks/useClaimUsername.ts
> +  if (usernameToPrefill.current) {
That was to launch the validation if we have the default value (if we could pick the preferred username from the social auth). Reworked this part

2022-09-30 16:20 UTC, ice-orion commented on src/screens/UserRegistrationFlow/ProfileFill/components/ClaimNickname/hooks/useClaimUsername.ts
> +export const useClaimUsername = () => {
done

2022-09-30 16:20 UTC, ice-orion commented on src/screens/UserRegistrationFlow/ProfileFill/components/WhoInvitedYou/hooks/useWhoInvited.ts
> +            'referral',
handled

2022-09-30 16:20 UTC, ice-orion commented on src/screens/UserRegistrationFlow/ProfileFill/components/WhoInvitedYou/hooks/useWhoInvited.ts
> +            'referral',
handled

2022-09-30 16:21 UTC, ice-orion commented on src/screens/UserRegistrationFlow/ProfileFill/components/WhoInvitedYou/hooks/useWhoInvited.ts
> +export const useWhoInvited = () => {
done

2022-09-30 16:23 UTC, ice-orion commented on src/store/modules/Auth/actions/index.ts
> -const CREATE_USER = createAction('CREATE_USER', {
now the flow is like so
```
takeLatest(
      [
        AuthActions.SIGN_IN_SOCIAL.SUCCESS.type,
        AuthActions.SIGN_IN_EMAIL.SUCCESS.type,
        AuthActions.SIGN_IN_PHONE.SUCCESS.type,
      ],
      finishAuthSaga,
    ),
```

So we're receiving or creating the user as a result of successfull auth via phone/email/social.

2022-09-30 16:25 UTC, ice-orion commented on src/store/modules/Auth/reducer/index.ts
> -  | typeof AuthActions.SIGN_IN_EMAIL.SUCCESS.create
This was removed cuz it is not used in the reducer - we don't need to store anything after login via email. We actually only storing the preferred username for the later use in case of login via social.

2022-09-30 16:25 UTC, ice-orion commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +    phoneNumberHash = yield call(hashPhoneNumber, phoneNumber);
fixed, checked other places

2022-09-30 16:25 UTC, ice-orion commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +        registrationProcessFinalizedSteps: ['email'],
done

2022-09-30 16:26 UTC, ice-orion commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      errorMessage = t('errors.multiple_accounts');
done `src/store/modules/Auth/sagas/finishAuthSaga.ts` -> `createUser` function

2022-09-30 16:26 UTC, ice-orion commented on src/store/modules/Auth/sagas/fetchUser.ts
> -export function* fetchUserSaga() {
this is now happens in one place - in `src/store/modules/Auth/sagas/finishAuthSaga.ts`

2022-09-30 16:28 UTC, ice-orion commented on src/store/modules/Validation/reducer/index.ts
> -  username: string | null;
Yea, we do validate it, but we don't need to store it anymore. Now we're setting the username right away via modifyUser.

2022-09-30 16:32 UTC, ice-orion commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> +    if (user?.username === username) {
What do you mean? `username` is a string, so this condition is needed to catch the case when user typed his own username in the refUsername field

2022-10-02 13:00 UTC, ice-ares requested changes
check the errors I mentioned in the task and handle them

2022-10-02 18:29 UTC, ice-ares commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      const field = error?.response?.data?.data?.field;
i’ve been thinking about this alot. The solution i proposed earlier is not ok. This exact scenario can happen for the email as well. So the best thing for us is to logout the user and display a text somehow that “Email/phonenumber is associated with another account. Please log into that account to prove ownership, then logout and log back into this one”

2022-10-02 18:32 UTC, ice-ares commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +    if (isApiError(error, 409, 'CONFLICT_WITH_ANOTHER_USER')) {
i’d handle this only in create user

2022-10-02 19:34 UTC, ice-ares commented on src/api/user/types.ts
> +  referredBy?: string;
add these 2 as well:

````
skipEmailValidation?: boolean | null;

skipPhoneNumberValidation?: boolean | null;

2022-10-03 05:40 UTC, ice-orion commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> +    if (user?.username === username) {
done

2022-10-03 06:00 UTC, ice-orion commented on src/screens/UserRegistrationFlow/ProfileFill/components/WhoInvitedYou/hooks/useWhoInvitedYou.ts
> +          referredBy: refUser?.id,
Changed the `if` condition here. I think we have to distinguish skip and submit anyway - i can type some username and then instead of submitting i can press `skip` -> `referredBy` should not be set even thought the `refUser` is not null

2022-10-03 06:02 UTC, ice-orion commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +    if (isApiError(error, 409, 'CONFLICT_WITH_ANOTHER_USER')) {
done

2022-10-03 06:12 UTC, ice-ares commented on src/screens/UserRegistrationFlow/ProfileFill/components/WhoInvitedYou/hooks/useWhoInvitedYou.ts
> +          referredBy: refUser?.id,
referredBy being null or undefined is ignored

2022-10-03 06:17 UTC, ice-orion commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      user = yield call(Api.user.modifyUser, user.id, {
We just created the user, how is it possible that it is already outdate (so the race-condition occurs)?

2022-10-03 06:19 UTC, ice-ares commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      user = yield call(Api.user.modifyUser, user.id, {
if u have 2 devices and to the same thing on both, at the same time

2022-10-03 06:27 UTC, ice-orion commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      user = yield call(Api.user.modifyUser, user.id, {
But in this case the `createUser` on the second device will throw an error, won't it? I can handle it but it doesn't look  like a real world scenario

2022-10-03 07:22 UTC, ice-orion commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      const field = error?.response?.data?.data?.field;
```
if (isApiError(error, 409, 'CONFLICT_WITH_ANOTHER_USER')) {
      const field = error?.response?.data?.data?.field;
      if (field === 'id') {
        throw new Error(t('errors.please_retry'));
      } else {
        throw new Error(t('errors.multiple_accounts')); // Email/phonenumber is associated with another account....
      }
}
```

2022-10-03 07:22 UTC, ice-orion commented on src/api/user/types.ts
> +  referredBy?: string;
done

2022-10-03 07:23 UTC, ice-orion commented on src/store/modules/Auth/sagas/finishAuthSaga.ts
> +      user = yield call(Api.user.modifyUser, user.id, {
throwing `please_retry` error in case `createUser` returns 409+`field.id`

2022-10-04 07:23 UTC, ice-ares requested changes

2022-10-04 07:23 UTC, ice-ares commented on src/store/modules/Validation/sagas/validatePhoneNumberSaga.ts
> +          localizedError = t('errors.already_taken', {field});
this needs a redirect as well, to the first screen

2022-10-04 07:23 UTC, ice-ares commented on src/store/modules/Validation/sagas/validatePhoneNumberSaga.ts
> +      localizedError = t('errors.validation_not_found');
this is equivalent to the race condition for modify user. Call get user, update the store value and redirect to the first screen and tell the user to restart the whole process

2022-10-04 07:23 UTC, ice-ares commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> +          agendaPhoneNumberHashes: phoneNumberHashesString,
u need to check if the agenda hash was changed, and recalculate it, then try again

2022-10-04 07:42 UTC, ice-orion commented on src/store/modules/Validation/sagas/validatePhoneNumberSaga.ts
> +          localizedError = t('errors.already_taken', {field});
This method is called on the first screen - where you type the phone number itself, so it seems we don't need to redirect

2022-10-04 20:49 UTC, ice-ares commented on src/store/modules/Validation/sagas/validatePhoneNumberSaga.ts
> +import axios from 'axios';
move the logic in the api client

2022-10-04 20:55 UTC, ice-ares commented on src/store/modules/Validation/sagas/validatePhoneNumberSaga.ts
> +      localizedError = t('errors.validation_not_found');
what about this one?

2022-10-05 06:35 UTC, ice-orion commented on src/store/modules/Validation/sagas/validatePhoneNumberSaga.ts
> +import axios from 'axios';
done

2022-10-05 06:36 UTC, ice-orion commented on src/store/modules/Validation/sagas/validatePhoneNumberSaga.ts
> +      localizedError = t('errors.validation_not_found');
processed

2022-10-05 07:14 UTC, ice-orion commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> +          agendaPhoneNumberHashes: phoneNumberHashesString,
the sync contacts flow changed

2022-10-05 07:23 UTC, ice-ares commented on src/screens/SettingsFlow/ConfirmPhoneNumber/index.tsx
> -  const isLoading = useSelector(
u dont need this?

2022-10-05 07:24 UTC, ice-ares commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> -      .filter(c => c.phoneNumbers.length > 0)
u still need to ignore contacts without phone numbers

2022-10-05 07:25 UTC, ice-orion commented on src/screens/SettingsFlow/ConfirmPhoneNumber/index.tsx
> -  const isLoading = useSelector(
i moved it inside the `ConfirmPhoneNumber` component and added error displaying also inside the `ConfirmPhoneNumber`

2022-10-05 07:26 UTC, ice-orion commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> -      .filter(c => c.phoneNumbers.length > 0)
they'll be ignored since `contact.phoneNumbers.reduce...` will return empty array and nothing will be added to the final `agendaPhoneNumbers`

2022-10-05 07:31 UTC, ice-ares commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> +      yield put(
where’s the logic to  re-run this whole saga with the fresh user if u get a race condition?

2022-10-05 09:25 UTC, ice-hector commented on src/components/ConfirmPhoneNumber/index.tsx
> +      //TODO::navigate to error popup here with failedReason
Should we show maybe simple alert for now?

2022-10-05 09:25 UTC, ice-hector commented on src/screens/UserRegistrationFlow/ProfileFill/index.tsx
> +  // 'email',
Do we need this commented code?

2022-10-05 09:25 UTC, ice-hector commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  //TODO::navigate to error popup in case of error
Same here, should we show simple alert for now?

2022-10-05 09:36 UTC, ice-eros commented on src/screens/UserRegistrationFlow/ProfileFill/components/WhoInvitedYou/hooks/useWhoInvitedYou.ts
> +  const finilizedSteps =
looks like typo of finalised

2022-10-05 09:46 UTC, ice-orion commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> +      yield put(
added

2022-10-05 09:57 UTC, ice-orion commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  //TODO::navigate to error popup in case of error
i'll take the UI part of the auth-flow in the next PR, by that time i think the PR with Error popup will be there and i'll close this TODO

2022-10-05 09:58 UTC, ice-orion commented on src/screens/UserRegistrationFlow/ProfileFill/index.tsx
> +  // 'email',
added TODO -> i'll add the email step in the next PR (UI part of the auth flow redesign)

2022-10-05 09:58 UTC, ice-orion commented on src/components/ConfirmPhoneNumber/index.tsx
> +      //TODO::navigate to error popup here with failedReason
i'll take the UI part of the auth-flow in the next PR, by that time i think the PR with Error popup will be there and i'll close this TODO

2022-10-05 12:37 UTC, ice-orion commented on src/screens/UserRegistrationFlow/SignIn/index.tsx
> +  //TODO::navigate to error popup in case of error
implemented

2022-10-05 12:37 UTC, ice-orion commented on src/components/ConfirmPhoneNumber/index.tsx
> +      //TODO::navigate to error popup here with failedReason
implemented

2022-10-05 13:19 UTC, ice-eros submitted a review, later dismissed

2022-10-06 07:08 UTC, merged