Feature/getstream
ice-blockchain/mobile-app pull request #71
Opened 2022-09-30 07:18 UTC by ice-hector

2022-09-30 08:29 UTC, ice-ares commented on src/api/notifications/types.ts
> +  updated_at?: Date | string | null;
u have time, do u really need this?

2022-09-30 08:29 UTC, ice-ares commented on src/api/notifications/types.ts
> +  participants?: NotificationUser[];
whats this for?

2022-09-30 08:29 UTC, ice-ares commented on src/api/notifications/types.ts
> + * The news post type
wrong

2022-09-30 08:29 UTC, ice-ares commented on src/api/notifications/types.ts
> +  level?: number;
not gonna exist here

2022-09-30 08:29 UTC, ice-ares commented on src/api/notifications/types.ts
> +  username?: string;
not gonna exist here

2022-09-30 08:29 UTC, ice-ares commented on src/api/notifications/types.ts
> +  profileUrl?: string;
not gonna exist here

2022-09-30 08:29 UTC, ice-ares commented on src/api/notifications/types.ts
> +  secondProfileUrl?: string;
not gonna exist here

2022-09-30 08:29 UTC, ice-ares commented on src/api/notifications/types.ts
> +  deleted: string[];
why do u need both?

2022-09-30 08:29 UTC, ice-ares commented on src/constants/env.ts
> +  GETSTREAM_API_KEY: config.GETSTREAM_API_KEY,
those are gonna come from BE, fyi

2022-09-30 08:29 UTC, ice-ares commented on src/screens/Notifications/NotificationsList.tsx
> +const levelIcon = require('./assets/level.png');
these should not be here, you should have a separate file for each verb, where you handle the business logic: what& how u display & what u do on tap

2022-09-30 08:29 UTC, ice-ares commented on src/screens/Notifications/index.tsx
> +          return '[More than a week]';
i18n

2022-09-30 08:29 UTC, ice-ares commented on src/screens/Notifications/index.tsx
> +              return `[${from.format('MMMM')}]`;
i18n everything

2022-09-30 08:29 UTC, ice-ares commented on src/screens/Notifications/index.tsx
> +      const title = moment.utc(activity.time).calendar(null, {
dayjs, not moment

2022-09-30 12:25 UTC, ice-hector commented on src/api/notifications/types.ts
> +  updated_at?: Date | string | null;
Yeah, I used it for sorting and then added the time field. 
Removed. Thanks

2022-09-30 12:31 UTC, ice-hector commented on src/api/notifications/types.ts
> +  level?: number;
@ice-ares where would it exist?

2022-09-30 12:32 UTC, ice-hector commented on src/api/notifications/types.ts
> +  username?: string;
Same question.. where can I get this field?

2022-09-30 12:46 UTC, ice-ares commented on src/api/notifications/types.ts
> +  level?: number;
nowhere, you don't need it. All notifications have a `description`, an `imageUrl` and a `deeplink` (all 3 via extra field). Some have extra stuff (also in extra field), I.E. maybe some name for the badges cuz those are stored on the device, not fetched from some url.

+ the time, foreign_id, verb, actor and object fields. Those are everything u need.

2022-09-30 12:47 UTC, ice-ares commented on src/api/notifications/types.ts
> +  username?: string;
same answer

2022-09-30 12:47 UTC, ice-ares commented on src/constants/env.ts
> +  GETSTREAM_API_KEY: config.GETSTREAM_API_KEY,
not now, was letting u know

2022-09-30 13:19 UTC, ice-hector commented on src/screens/Notifications/NotificationsList.tsx
> +const levelIcon = require('./assets/level.png');
@ice-ares you mean create a separate component for each Verb type and handle the UI and business logic inside it?

2022-09-30 13:29 UTC, ice-ares commented on src/screens/Notifications/NotificationsList.tsx
> +const levelIcon = require('./assets/level.png');
yep

2022-09-30 13:29 UTC, ice-ares commented on src/screens/Notifications/NotificationsList.tsx
> +const levelIcon = require('./assets/level.png');
put em in a nice folder named `src/screens/Notifications/types`

2022-10-06 22:56 UTC, ice-ares commented on src/api/notifications/types.ts
> +  username?: string;
u dont need this

2022-10-06 22:58 UTC, ice-ares commented on src/api/notifications/types.ts
> +  deleted: string[];
why do u need both?

2022-10-06 22:59 UTC, ice-ares commented on src/api/notifications/types.ts
> +  deleted_foreign_ids: [id: string, time: string][];
u can use the Activity as the type

2022-10-06 23:01 UTC, ice-ares commented on src/api/notifications/types.ts
> +export interface GetstreamResults {
UserNotifications

2022-10-06 23:01 UTC, ice-ares commented on src/api/notifications/types.ts
> +  // secondProfileUrl?: string;
remove

2022-10-06 23:02 UTC, ice-ares commented on src/constants/env.ts
> +  GETSTREAM_NOTIFICATIONS_USER_TOKEN: config.GETSTREAM_NOTIFICATIONS_USER_TOKEN,
u’re gonna have the same one

2022-10-06 23:04 UTC, ice-ares commented on src/screens/Notifications/EmptyNotifications.tsx
> +const EmptyNotifications = ({onActivitiesAdd}: EmptyNotifications) => {
add a todo to remove this later

2022-10-06 23:06 UTC, ice-ares commented on src/api/notifications/types.ts
> +  verb?:
keep in mind, the verb and the naming of files/objects derived from it across the app will change

2022-10-06 23:07 UTC, ice-ares commented on src/screens/Notifications/NotificationsList.tsx
> +        <RectButton
whats rect?

2022-10-06 23:08 UTC, ice-ares commented on src/screens/Notifications/NotificationsList.tsx
> +              console.log(error);
use logger

2022-10-06 23:08 UTC, ice-ares commented on src/screens/Notifications/NotificationsList.tsx
> +              await removeNotificationActivity(item?.foreign_id || '');
dont u need the time as well?

2022-10-06 23:09 UTC, ice-ares commented on src/screens/Notifications/NotificationsList.tsx
> +              await removeAnnouncementActivity(item?.foreign_id || '');
Also, promise all em

2022-10-06 23:10 UTC, ice-ares commented on src/screens/Notifications/components/Avatar/index.tsx
> +export const Avatar = ({source, children}: AvatarProps) => {
u already have an avatar, use that

2022-10-06 23:12 UTC, ice-ares commented on src/screens/Notifications/components/Time/index.tsx
> +      {moment(time).fromNow() || ''}
why moment?

2022-10-06 23:13 UTC, ice-ares commented on src/screens/Notifications/helpers.ts
> +    const date2: Date = new Date(activityTwo.time || '');
why not use dayjs?

2022-10-06 23:18 UTC, ice-ares commented on src/screens/Notifications/helpers.ts
> +        return `${t('notification_feed_screen.more_than_week')}`;
this is ‘this week’ actually

2022-10-06 23:21 UTC, ice-ares commented on src/screens/Notifications/index.tsx
> +    console.log('now listening to changes in realtime');
huh?

2022-10-06 23:21 UTC, ice-ares commented on src/screens/Notifications/index.tsx
> +  const failCallback = () => {
huh? Also, pretty sure u have an error as arg there

2022-10-06 23:22 UTC, ice-ares commented on src/screens/Notifications/index.tsx
> +    await clearNotifications(foreignIds);
promise all

2022-10-06 23:22 UTC, ice-ares commented on src/screens/Notifications/index.tsx
> +        foreignIds.push(data.foreign_id || '');
u sure u dont need the time?

2022-10-06 23:23 UTC, ice-ares commented on src/screens/Notifications/index.tsx
> +    const notificationsData = await loadNotifications();
promise all

2022-10-06 23:24 UTC, ice-ares commented on src/screens/Notifications/styles/index.tsx
> +export const notificationStyles = StyleSheet.create({
why not move it where u need it?

2022-10-06 23:26 UTC, ice-ares commented on src/screens/Notifications/types/FollowUs/index.tsx
> +    handleUrl(mainStackNavigation, activity.extra?.deeplink);
btw, forgot to mention, some deeplinks are https://, which have to open in app browser

2022-10-06 23:27 UTC, ice-ares commented on src/screens/Notifications/types/FollowUs/index.tsx
> +    <DefaultNotification
where/s the image?

2022-10-06 23:30 UTC, ice-ares commented on src/screens/Notifications/types/Badge/index.tsx
> +const badgeIcon = require('../../assets/notificationsBadgePic.png');
whats this?

2022-10-06 23:31 UTC, ice-ares commented on src/screens/Notifications/types/Adoption/index.tsx
> +const badgeIcon = require('../../assets/notificationsBadgePic.png');
remove these and use some urls in ur mock data, get some urls with profile pics

2022-10-06 23:34 UTC, ice-ares commented on src/screens/Notifications/types/Badge/index.tsx
> +const badgeIcon = require('../../assets/notificationsBadgePic.png');
remove it, use only urls

2022-10-06 23:35 UTC, ice-ares commented on src/screens/Notifications/types/Badge/index.tsx
> +    homeStackNavigation.navigate('MyBadges');
remove all manual navigations and navigate only from deeplink

2022-10-06 23:37 UTC, ice-ares commented on src/screens/Notifications/types/Joined/index.tsx
> +    if (activity.extra?.imageUrls && activity.extra?.imageUrls.length >= 2) {
can you pls try with 3&4 and send us a screenshot of how it looks?

2022-10-06 23:38 UTC, ice-ares commented on src/screens/Notifications/types/Joined/index.tsx
> +          value={`**@${activity.extra?.username || ''}**${t(
add it in mock data, you use the description as is

2022-10-06 23:39 UTC, ice-ares commented on src/screens/Notifications/types/Pinged/index.tsx
> +        value={`@${activity.extra?.username || ''} ${t('notifications.ping')}`}
nope, description as is

2022-10-06 23:40 UTC, ice-ares commented on src/screens/Notifications/types/RefJoined/index.tsx
> +    handleUrl(mainStackNavigation, activity.extra?.deeplink);
it doesnt make sense now to have a separate component for each verb, since they all behave identically, except that one with 2+ pictures

2022-10-06 23:43 UTC, ice-ares commented on src/services/getstream/index.ts
> +const getstreamClient = connect(
don’t u need  to subscribe to some thing to get notifications in real time while you are in other screens?

2022-10-06 23:45 UTC, ice-ares commented on src/services/getstream/mockData.ts
> +      description: 'Will a Bitcoin ETF be Launched This Month?',
all of them have deeplink, cuz we control where we redirect the user from BE

2022-10-07 08:49 UTC, ice-hector commented on src/api/notifications/types.ts
> +export interface GetstreamResults {
Removed. I'm using the default type from getstream

2022-10-07 08:52 UTC, ice-hector commented on src/constants/env.ts
> +  GETSTREAM_NOTIFICATIONS_USER_TOKEN: config.GETSTREAM_NOTIFICATIONS_USER_TOKEN,
@ice-ares it is hardcoded for now (for all users) as we agreed. Or do you mean for notifications and announcements it would be the same? I guess that's not possible because you create a specific token for each StreamFeed

2022-10-07 09:07 UTC, ice-hector commented on src/screens/Notifications/NotificationsList.tsx
> +        <RectButton
Replaced with Touchable.

2022-10-07 09:12 UTC, ice-hector commented on src/screens/Notifications/NotificationsList.tsx
> +              await removeNotificationActivity(item?.foreign_id || '');
Nope, thie remove activity API accepts in params only the foreignId or the activityId

2022-10-07 09:14 UTC, ice-hector commented on src/screens/Notifications/components/Time/index.tsx
> +      {moment(time).fromNow() || ''}
changed to dayjs

2022-10-07 09:22 UTC, ice-hector commented on src/screens/Notifications/helpers.ts
> +    const date2: Date = new Date(activityTwo.time || '');
done

2022-10-07 09:24 UTC, ice-ares commented on src/constants/env.ts
> +  GETSTREAM_NOTIFICATIONS_USER_TOKEN: config.GETSTREAM_NOTIFICATIONS_USER_TOKEN,
Nope, same token for all feeds

2022-10-07 09:24 UTC, ice-hector commented on src/screens/Notifications/index.tsx
> +        foreignIds.push(data.foreign_id || '');
Remove activity API accepts only ids, should be fine

2022-10-07 09:25 UTC, ice-hector commented on src/screens/Notifications/styles/index.tsx
> +export const notificationStyles = StyleSheet.create({
I reuse notificationStyles in many places, that's why I created separate styles file

2022-10-07 09:26 UTC, ice-ares commented on src/screens/Notifications/NotificationsList.tsx
> +              await removeNotificationActivity(item?.foreign_id || '');
Whats activityId?

foreign_id is not enough to identify 1 activity. Cuz there are multiple activities with it, but different time

2022-10-07 12:52 UTC, ice-hector commented on src/screens/Notifications/types/FollowUs/index.tsx
> +    handleUrl(mainStackNavigation, activity.extra?.deeplink);
@ice-ares in-app browser or just phone browser (leave the app)? 
If in-app we don't have it ready to go created. Should I implement the WebView wrapper component?

2022-10-07 13:15 UTC, ice-hector commented on src/screens/Notifications/types/Joined/index.tsx
> +    if (activity.extra?.imageUrls && activity.extra?.imageUrls.length >= 2) {
@ice-ares it will take just the first two photos and the UI will look the same as for 2 urls/avatars combined
<img width="523" alt="Screenshot 2022-10-07 at 16 13 04" src="https://user-images.githubusercontent.com/96414297/194562472-1eb11b95-307b-4c42-b33a-79350f06696d.png">

2022-10-07 13:44 UTC, ice-orion commented on src/screens/Notifications/EmptyNotifications.tsx
> +interface EmptyNotifications {
This is the type for props, isn't it? May be name it the same way we do in the other components:
```
type Props = {...} // or at least EmptyNotificationsProps
```

2022-10-07 13:44 UTC, ice-orion commented on src/screens/Notifications/EmptyNotifications.tsx
> +        {translate('notifications.no_notifications')}
use `t(...)`

2022-10-07 13:44 UTC, ice-orion commented on src/screens/Notifications/EmptyNotifications.tsx
> +    height: screenHeight - rem(200),
Why is it necessary to hard code the height?

2022-10-07 13:44 UTC, ice-orion commented on src/screens/Notifications/EmptyNotifications.tsx
> +export default EmptyNotifications;
we don't use default export

2022-10-07 13:44 UTC, ice-orion commented on src/screens/Notifications/NotificationsList.tsx
> +export const NotificationsList = ({
May be it makes sense to split the component a little - it looks overcomplicated. 
`renderHeader` -> might be a separate component
or probably take out some function/animations to hooks

2022-10-07 13:44 UTC, ice-orion commented on src/services/getstream/index.ts
> +// SPDX-License-Identifier: BUSL-1.1
We're using redux to store the business logic and all the data, why do we use some "service" for the notifications?

2022-10-07 13:44 UTC, ice-orion commented on src/utils/deepLinkingManager.ts
> +      return pathname && Linking.openURL(url).catch(() => false);
use logError instead of `() => false`

2022-10-07 13:44 UTC, ice-orion commented on src/utils/deepLinkingManager.ts
> +const Parser = require('url-parse');
what is the `require('url-parse')`?

2022-10-07 13:44 UTC, ice-orion commented on src/utils/deepLinkingManager.ts
> +    case 'profile':
Is it the only pathname that has to be processed via navigation?

2022-10-07 13:44 UTC, ice-orion commented on src/screens/Notifications/styles/index.tsx
> +export const notificationStyles = StyleSheet.create({
You can create components that use these styles and reuse that components instead.

And some of the styles are used only in 1 place, so they can be places in the place of usage, e.g. `notificationStyles.descriptionContainer`, `notificationStyles.timeLabel ` , `notificationStyles.description`

`. textBold` seems to be not used at all

2022-10-07 13:46 UTC, ice-orion commented on src/screens/Notifications/NotificationsList.tsx
> +          colors={['rgba(255, 255, 255, 0)', 'rgba(255, 255, 255, 1)']}
use constants for colors
COLORS.transparent / COLORS.white

2022-10-07 14:11 UTC, ice-hector commented on src/services/getstream/index.ts
> +// SPDX-License-Identifier: BUSL-1.1
Because we don't store them

2022-10-07 14:20 UTC, ice-hector commented on src/screens/Notifications/NotificationsList.tsx
> +              await removeNotificationActivity(item?.foreign_id || '');
ok I refactored to using the activity.id
all good

2022-10-07 19:27 UTC, ice-ares commented on src/screens/Notifications/types/FollowUs/index.tsx
> +    handleUrl(mainStackNavigation, activity.extra?.deeplink);
We’ll have some displayed with the In app browser, some with the phone default browser. So implement both. Ask Robert which one’s with the in app one, which one’s with the phone browser

2022-10-07 19:29 UTC, ice-ares commented on src/screens/Notifications/types/Joined/index.tsx
> +    if (activity.extra?.imageUrls && activity.extra?.imageUrls.length >= 2) {
I know, my point was to modify the code to allow 3 & 4 and show us how it looks

2022-10-10 05:35 UTC, ice-orion commented on src/services/getstream/index.ts
> +// SPDX-License-Identifier: BUSL-1.1
What do you mean? We fetch them (now directly from the screen, but i suggest to use redux actions) -> we store them (now in the screen state, but i suggest to do so in the redux store) -> we display them (now from the screen state, but we could use selectors and keep the grouping/sorting logic there).
The same way we would do with the news, for witch we already have a module in the redux.

2022-10-10 05:45 UTC, ice-orion commented on src/utils/deepLinkingManager.ts
> +export const handleUrl = async (
This function doesn't look like a util function - it stores the business logic of the app.
May be it would be better to create a module `linking` and action `handleUrl`? So there would no be needed to pass the `navigation` (we can use navigation by ref) + then the logic would be in the saga + the sentry would log the event in case of handleUrl error.
And the Universal Links / Android App Links are not set + `Linking.getInitialURL` and `Linking.addEventListener('url', callback)` are not used. So opening the app via deeplinks / handling deeplinks press outside of the app is not a part of the PR?

2022-10-10 07:51 UTC, ice-ares commented on src/services/getstream/index.ts
> +// SPDX-License-Identifier: BUSL-1.1
Agree with orion

2022-10-11 12:50 UTC, ice-hector commented on src/screens/Notifications/styles/index.tsx
> +export const notificationStyles = StyleSheet.create({
Removed it

2022-10-11 12:56 UTC, ice-hector commented on src/screens/Notifications/types/Joined/index.tsx
> +    if (activity.extra?.imageUrls && activity.extra?.imageUrls.length >= 2) {
@ice-ares sorry but I didn't get what you mean here, like right now code supports 1 image (we display one) and 2 and more images (we display just the first two in this case). If you want to support 3, 4, or whatever let's just add such states to designs so I can implement it

2022-10-11 13:31 UTC, ice-ares commented on src/screens/Notifications/types/Joined/index.tsx
> +    if (activity.extra?.imageUrls && activity.extra?.imageUrls.length >= 2) {
forget about it

2022-10-11 13:39 UTC, ice-hector commented on src/utils/deepLinkingManager.ts
> +const Parser = require('url-parse');
Thats for parsing the deep linking urls. Added to package json

2022-10-11 13:45 UTC, ice-hector commented on src/utils/deepLinkingManager.ts
> +export const handleUrl = async (
Nope, deeplinking  press outside the app definitely not the part, but we can reuse the handleUrl method in future for this yeah. 
As for Linking module I got the idea, will do

2022-10-11 14:22 UTC, ice-hector commented on src/screens/Notifications/components/Avatar/index.tsx
> +export const Avatar = ({source, children}: AvatarProps) => {
done

2022-10-14 12:28 UTC, ice-hector commented on src/screens/Notifications/NotificationsList.tsx
> +export const NotificationsList = ({
After i moved data loading to redux and reduced number of component types to render its become much cleaner

2022-10-14 13:33 UTC, ice-hector commented on src/services/getstream/index.ts
> +// SPDX-License-Identifier: BUSL-1.1
Yep moved to hook as listener

2022-10-14 13:34 UTC, ice-hector commented on src/services/getstream/index.ts
> +const getstreamClient = connect(
Moved to hook listener in Router.tsx

2022-10-14 13:35 UTC, ice-hector commented on src/screens/Notifications/index.tsx
> +    const notificationsData = await loadNotifications();
Refactored (using sagas from now)

2022-10-17 08:46 UTC, ice-hector commented on src/screens/Notifications/types/FollowUs/index.tsx
> +    handleUrl(mainStackNavigation, activity.extra?.deeplink);
Refactored. Component removed. Handle press migrated to Linking module

2022-10-18 06:31 UTC, ice-orion commented on src/store/modules/AppCommon/hooks/useGetstreamListener.ts
> +export const useGetstreamListener = () => {
let's place the hook to the notifications module

2022-10-18 06:31 UTC, ice-orion commented on src/store/modules/Linking/reducer/index.ts
> +  handledUrl: string;
Why do we need the reducer and selector for this module?

2022-10-18 06:31 UTC, ice-orion commented on src/screens/SettingsFlow/Settings/index.tsx
> -  const navigation =
let's try to use that new `MainNavigationParams` type so we won't need 2 navigation's (`profileNavigation` and `mainNavigation `)

2022-10-18 06:31 UTC, ice-orion commented on src/assets/svg/ClearIcon.tsx
> +export const ClearIcon = ({fill = COLORS.white}: Props) => (
use `SvgProps` for prop types (nice service to transform common svgs to the RN format - https://react-svgr.com/playground/?native=true&typescript=true)
and pass `{...props}` to the `Svg` tag so it would be possible to pass width / height if needed

2022-10-18 06:31 UTC, ice-orion commented on src/store/modules/Notifications/sagas/addNotificationsSaga.ts
> +        hasMore: false, //TODO: handle pagination
it's not possible to handle it now?

2022-10-18 06:37 UTC, ice-orion commented on src/store/modules/AppCommon/hooks/useGetstreamListener.ts
> +        newActivities.forEach((result: Activity) => {
What's the point of this loop? It looks like `allActivities` is the same as `newActivities` or i miss something?

2022-10-18 06:39 UTC, ice-orion commented on src/store/modules/AppCommon/hooks/useGetstreamListener.ts
> +      if (data && data.new && !isEmpty(data.new)) {
`isEmpty` works with `object, collection, map, or set` but if `data.new`  is an array, then just use `if (data?.new?.length)`

2022-10-18 06:45 UTC, ice-orion commented on src/screens/Notifications/NotificationsList.tsx
> +          return isEmpty(notifications) ? null : (
`isEmpty` is overhead here -> 
`return notifications.length > 0 && (<ClearButton .../>)`

2022-10-18 06:49 UTC, ice-orion commented on src/screens/Notifications/NotificationsList.tsx
> +      {!isEmpty(Object.keys(notifications)) && (
`Object.keys(notifications).length > 0`

2022-10-18 07:06 UTC, ice-hector commented on src/store/modules/AppCommon/hooks/useGetstreamListener.ts
> +export const useGetstreamListener = () => {
fixed

2022-10-18 07:09 UTC, ice-hector commented on src/store/modules/Linking/reducer/index.ts
> +  handledUrl: string;
Potentially we gonna use linking not just for notifications but for any handle URL-related stuff.
In this case, sometimes we need to save the last handled URL and get it to make some extra delayed stuff (transitions to some items/ screens/animations/ whatever).

2022-10-18 07:15 UTC, ice-orion commented on src/store/modules/Linking/reducer/index.ts
> +  handledUrl: string;
ah, right

2022-10-18 07:46 UTC, ice-hector commented on src/screens/Notifications/NotificationsList.tsx
> +      {!isEmpty(Object.keys(notifications)) && (
No, notifications obhect it has section type structure
```export interface ActivitySection {
  sectionTitle?: string | null;
  data?: Activity[];
}```

as for .length checking - fixed

2022-10-18 07:58 UTC, ice-hector commented on src/assets/svg/ClearIcon.tsx
> +export const ClearIcon = ({fill = COLORS.white}: Props) => (
Fixed

2022-10-18 12:44 UTC, ice-hector commented on src/store/modules/AppCommon/hooks/useGetstreamListener.ts
> +        newActivities.forEach((result: Activity) => {
Fixed

2022-10-18 12:45 UTC, ice-hector commented on src/store/modules/AppCommon/hooks/useGetstreamListener.ts
> +      if (data && data.new && !isEmpty(data.new)) {
Fixed

2022-10-18 13:06 UTC, ice-ares commented on src/screens/Notifications/helpers.ts
> +        return `${t('notification_feed_screen.this_week')}`;
move this  to an other ` if dayDiff < 7` at the top

2022-10-18 13:07 UTC, ice-hector commented on src/screens/Notifications/NotificationsList.tsx
> +            return Joined;
Buy why? There is a custom-rendered avatar layout. Or you will return me from the backend already combined one asset? I'm not sure that yes. And why we added imageUrls to the extra field then? 
`activity.extra?.imageUrls`
<img width="187" alt="Screenshot 2022-10-18 at 16 05 14" src="https://user-images.githubusercontent.com/96414297/196437875-267e2ff3-40c4-47a0-8187-9d6bbf3c3395.png">

2022-10-18 13:07 UTC, ice-ares commented on src/screens/Notifications/helpers.ts
> +          if (monthDiff > 0 && monthDiff <= 1) {
monthDiff === 1

2022-10-18 13:09 UTC, ice-ares commented on src/screens/Notifications/types/Joined/index.tsx
> +    if (activity.extra?.imageUrls && activity.extra?.imageUrls.length >= 2) {
move this logic into the default one

2022-10-18 13:09 UTC, ice-ares commented on src/screens/Notifications/types/Pinged/index.tsx
> +export const Pinged = ({activity, onPress}: ActivityItemProps) => {
remove this, use the default one

2022-10-18 13:20 UTC, ice-ares commented on src/services/getstream/mockData.ts
> +      description: 'You have unlocked "ice Breaker" badge',
all of them have deep link

2022-10-18 13:33 UTC, ice-ares commented on src/store/modules/Linking/sagas/handleUrlSaga.ts
> +  switch (pathname) {
this won't look like that.

It will look like:

1. `ice.app://users/0123ba01-c196-4a37-b0d4-63936b8e6ac9`
2. `ice.app://home`
3. `ice.app://browser&url=https%3A%2F%2Fyoutube.com`
4. `https://youtube.com`

There's gonna be more like 1. and 2. we'll setup the correct ones when we connect to the BE.

2022-10-18 13:36 UTC, ice-ares commented on src/store/modules/Notifications/hooks/useGetstreamListener.ts
> +    notificationsFeed.subscribe(callback).then(successCallback, failCallback);
what about the announcements ? Which is a flat feed

2022-10-18 13:36 UTC, ice-ares commented on src/store/modules/Notifications/hooks/useGetstreamListener.ts
> +        dispatch(
u also need to display that counter badge

2022-10-18 13:39 UTC, ice-ares commented on src/services/getstream/index.ts
> +export async function clearNotifications(activityIds: string[]) {
removeNotifications
removeAnnouncements

2022-10-18 13:39 UTC, ice-ares commented on src/services/getstream/index.ts
> +export async function removeNotificationActivity(activityId: string) {
removeNotification
removeAnnouncement

2022-10-18 13:40 UTC, ice-ares commented on src/store/modules/Notifications/sagas/deleteNotiticationSaga.ts
> +export function* deleteNotiticationSaga(
remove this and use the clear one with array of 1 element

2022-10-18 13:43 UTC, ice-ares commented on src/utils/parseUrl.ts
> +export const parseUrl = (url: string) => {
you need to rethink this completely and  also rename it. I'd suggest  you move this function to where you need it, in that linking saga

2022-10-18 13:44 UTC, ice-ares commented on src/screens/Notifications/NotificationsList.tsx
> +            return Joined;
if you use DefaultNotification, you'd display that for any other notification that we might add in the future, without dev time + deploy time + release time.

2022-10-18 13:45 UTC, ice-hector commented on src/screens/Notifications/NotificationsList.tsx
> +            return Joined;
Ok I got the idea

2022-10-21 08:51 UTC, ice-hector commented on src/store/modules/Notifications/hooks/useGetstreamListener.ts
> +        dispatch(
Connected badge counter displaying

2022-10-21 09:54 UTC, ice-hector commented on src/store/modules/Notifications/hooks/useGetstreamListener.ts
> +    notificationsFeed.subscribe(callback).then(successCallback, failCallback);
added subscribe to announcements

2022-10-21 12:58 UTC, ice-hector commented on src/store/modules/Linking/sagas/handleUrlSaga.ts
> +  switch (pathname) {
I refactored deeplinking, it support now all link types you mentioned

2022-10-21 13:01 UTC, ice-hector commented on src/store/modules/Notifications/sagas/deleteNotiticationSaga.ts
> +export function* deleteNotiticationSaga(
I kept it separate so we can in future show a unique loading indicator (when we delete for example) an item by id

2022-10-21 13:01 UTC, ice-hector commented on src/utils/parseUrl.ts
> +export const parseUrl = (url: string) => {
moved and refactored

2022-10-21 13:15 UTC, ice-hector commented on src/services/getstream/mockData.ts
> +      description: 'You have unlocked "ice Breaker" badge',
Can you send pls the example of deeplink for each notification type? 
Here is how the behave now, but of course that would be optimized. Some Navigate actions will receive params from the url, some will be kept as is, and some will be removed because cases like user and browser (when we get that fields from url params) will be handled separately. The core thing is parser and it should work now with all url types you've provided before. So when we will have all examples - that will take 5-10 mins to clean up on how to handle them
```


    case 'users':
    case 'pinged':
      //TODO: Navigate to user profile screen, not own profile
      navigate({name: 'ProfileTab', params: undefined});
      break;
    case 'browser':
      navigate({
        name: 'WebView',
        params: {
          url: url,
        },
      });
      break;
    case 'followUs':
    case 'refJoined':
    case 'announcements':
      navigate({name: 'WebView', params: {url: urlToParse}});
      break;
    case 'mining':
      navigate({name: 'HomeTab', params: undefined});
      break;
    case 'staking':
      navigate({name: 'HomeTab', params: undefined});
      break;
    case 'weeklyStats':
      navigate({name: 'Stats', params: undefined});
      break;
    case 'inviteFriends':
      navigate({name: 'InviteShare', params: undefined});
      break;
    case 'joined':
      navigate({name: 'TeamTab', params: undefined});
      break;
    case 'news':
      navigate({name: 'NewsTab', params: undefined});
      break;
    case 'level':
      navigate({name: 'ProfileTab', params: undefined});
      break;
    case 'role':
      navigate({name: 'MyRoles', params: undefined});
      break;
    case 'badge':
      navigate({name: 'MyBadges', params: undefined}); //TODO: focus on badge
      break;
    case 'task':
      navigate({name: 'HomeTab', params: undefined}); //TODO: focus on the task
      break;
    case 'adoption':
      navigate({name: 'HomeTab', params: undefined}); //TODO: focus on adoption card
      break;
    case 'loginLinked':
      navigate({name: 'Settings', params: undefined});
      break;
```

2022-10-21 13:33 UTC, ice-hector commented on src/api/notifications/types.ts
> +  username?: string;
removed

2022-10-24 07:48 UTC, ice-orion commented on src/store/modules/Notifications/hooks/useGetstreamListener.ts
> +      console.log('data');
console.log here and on the 31-th line

2022-10-24 07:50 UTC, ice-orion commented on src/store/modules/Notifications/sagas/deleteNotiticationSaga.ts
> +export function* deleteNotiticationSaga(
We can achieve that by using both `isLoadingSelector` and `actionPayloadSelector` (to get the id from the payload)

2022-10-24 07:59 UTC, ice-orion commented on src/screens/Notifications/EmptyNotifications.tsx
> +export const EmptyNotifications = () => {
let's place UI stuff into the `components` subfolder?

2022-10-28 10:28 UTC, ice-ares requested changes

2022-10-28 10:28 UTC, ice-ares commented on src/store/modules/Linking/sagas/handleUrlSaga.ts
> +    const urlWithParams = url.split('?')[1];
Array out of bounds if url doesnt have ?

2022-10-28 10:28 UTC, ice-ares commented on src/store/modules/Linking/sagas/handleUrlSaga.ts
> +    url: params?.url,
...params

2022-10-28 10:28 UTC, ice-ares commented on src/store/modules/Linking/sagas/handleUrlSaga.ts
> +      navigate({name: 'ProfileTab', params: undefined});
Why undefined? U need to specify the user id

2022-10-28 10:28 UTC, ice-ares commented on src/store/modules/Notifications/sagas/deleteNotiticationSaga.ts
> +export function* deleteNotiticationSaga(
@ice-hector lets try what @ice-orion suggested pls

2022-10-28 13:02 UTC, ice-hector commented on src/store/modules/Linking/sagas/handleUrlSaga.ts
> +      navigate({name: 'ProfileTab', params: undefined});
The navigation to another user profile is not implemented at all in the app, that's why it's undefined there

2022-10-28 14:38 UTC, ice-hector commented on src/store/modules/Notifications/sagas/deleteNotiticationSaga.ts
> +export function* deleteNotiticationSaga(
Done

2022-10-28 15:10 UTC, ice-orion approved these changes

2022-10-28 15:37 UTC, ice-ares approved these changes

2022-10-28 16:04 UTC, ice-minos approved these changes

2022-10-28 16:06 UTC, merged