Feature/privacy walkthrough
ice-blockchain/mobile-app pull request #73
Opened 2022-10-10 05:51 UTC by ice-eros

2022-10-10 06:05 UTC, ice-orion commented on src/screens/PopUps/PrivacyWalkthrough/step3/components/BadgeCard.tsx
> +export const BadgeCard = memo(
Isn't it a copy / paste of the existing component from `ProfileFlow`? If so, let's just place it to the common `components` folder and reuse

2022-10-10 06:05 UTC, ice-orion commented on src/screens/PopUps/PrivacyWalkthrough/step3/components/BadgeList.tsx
> +export const BadgeList = ({data}: Props) => {
copy of the `src/screens/ProfileFlow/Profile/components/Badges/components/BadgeList.tsx` ?

2022-10-10 06:05 UTC, ice-orion commented on src/screens/PopUps/PrivacyWalkthrough/step2/components/CurrentRoleCard.tsx
> +export const CurrentRoleCard = ({
copy of the `src/screens/ProfileFlow/Profile/components/Role/components/CurrentRoleCard.tsx` ?

2022-10-10 06:05 UTC, ice-orion commented on src/screens/PopUps/PrivacyWalkthrough/step1/components/LadderBar.tsx
> +export const LadderBar = memo(() => {
copy of the `src/screens/ProfileFlow/Profile/components/LabberBar/index.tsx`?

2022-10-10 06:05 UTC, ice-orion commented on src/screens/PopUps/PrivacyWalkthrough/step1/components/LadderItem.tsx
> +export const LadderItem = ({hidden, title, value, enabled = false}: Props) => {
copy of the `src/screens/ProfileFlow/Profile/components/LabberBar/components/LadderItem.tsx`

2022-10-10 06:10 UTC, ice-orion commented on src/assets/images/index.ts
> +    privacyBg1: require('./backgrounds/privacyBg1.png'),
let's try to use only 1 image for all the steps (1 general, rectangle shaped image -> using border-radius and margins achieve the desired view for every step). Otherwise we would have +2mb * number-of-steps for the app size.

2022-10-10 06:16 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +    route?.params?.showWalkThrough &&
We're using the navigation flag `showWalkThrough` only to navigate to another screen? May be we can achieve the same using 2 navigation calls instead?
```
navigation.navigate('Profile'))
navigation.navigate('PrivacyWalkThroughStep1');

or 

navigation.navigate('Profile'))
setTimeout(() => navigation.navigate('PrivacyWalkThroughStep1'));
```

2022-10-11 05:58 UTC, ice-eros commented on src/screens/PopUps/PrivacyWalkthrough/step3/components/BadgeCard.tsx
> +export const BadgeCard = memo(
Here and further all components have option to be hided like design required.
Not sure if app read for 'real' components to be hide-able.
If yes, sure same components should be used.

2022-10-11 06:02 UTC, ice-eros commented on src/screens/ProfileFlow/Profile/index.tsx
> +    route?.params?.showWalkThrough &&
Yes, this was first obvious approach, but sequential navigate or using timeout looks ugly.
Sure, 'knowledge' of some walkthrough in Profile does not look consistent, maybe some navigation interceptor will looks beter.

2022-10-11 06:17 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +    route?.params?.showWalkThrough &&
> but sequential navigate or using timeout looks ugly
You're basically just pushing 2 screens in the navigation stack - probably there is a better solution, but as for me, it doesn't look ugly. Anyway it would be better to get rid of anything related to walkthrough from the actual profile screen

2022-10-11 06:27 UTC, ice-orion commented on src/screens/PopUps/PrivacyWalkthrough/step3/components/BadgeCard.tsx
> +export const BadgeCard = memo(
It looks we do have an ability to hide blocks if we promote this feature in the walkthrough..
We have `user.clientData.hiddenProfileElements` to store those elements.
So yea, it makes sense to improve the components to write / remove the element name from the `user.clientData.hiddenProfileElements` on walkthrough and in the "real" app and reuse those components.

2022-10-14 07:42 UTC, ice-eros commented on src/screens/PopUps/PrivacyWalkthrough/step3/components/BadgeCard.tsx
> +export const BadgeCard = memo(
component in profile flow update and used here

2022-10-14 07:42 UTC, ice-eros commented on src/screens/PopUps/PrivacyWalkthrough/step2/components/CurrentRoleCard.tsx
> +export const CurrentRoleCard = ({
used extended src/screens/ProfileFlow/Profile/components/Role/components/CurrentRoleCard.tsx

2022-10-14 07:43 UTC, ice-eros commented on src/screens/PopUps/PrivacyWalkthrough/step1/components/LadderBar.tsx
> +export const LadderBar = memo(() => {
used extended `src/screens/ProfileFlow/Profile/components/LabberBar/index.tsx`

2022-10-14 07:43 UTC, ice-eros commented on src/screens/PopUps/PrivacyWalkthrough/step1/components/LadderItem.tsx
> +export const LadderItem = ({hidden, title, value, enabled = false}: Props) => {
used extended `src/screens/ProfileFlow/Profile/components/LabberBar/components/LadderItem.tsx`

2022-10-14 07:46 UTC, ice-eros commented on src/assets/images/index.ts
> +    privacyBg1: require('./backgrounds/privacyBg1.png'),
yes, these images are huge but there are too much differences to build them from parts programatically.
First design should be updated to allow this.

2022-10-18 06:57 UTC, ice-orion commented on src/assets/images/index.ts
> +    privacyBg1: require('./backgrounds/privacyBg1.png'),
Let's have a call and see how we can handle it, i think we can deal with one image instead of separate ones for all the 30 walkthrough steps we have

2022-10-26 19:24 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/Badges/components/BadgeCard.tsx
> +    inWalkthroughMode = false,
inProfilePrivacyEditMode.

Rename all walkthrough stuff related to the privacy edit screen to XXX ProfilePrivacyEditXXX

2022-10-26 19:24 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/LabberBar/index.tsx
> +export const LadderBar = memo(({inWalkthroughMode = false}: Props) => {
The name of the file is not that

2022-10-28 06:53 UTC, ice-hector commented on src/assets/images/index.ts
> +    privacyBg1: require('./backgrounds/privacyBg1.png'),
Agreed just to rename them

2022-10-28 06:54 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +    route?.params?.showWalkThrough &&
Fixed

2022-10-28 07:35 UTC, ice-ares commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      elementsToUpdate = hiddenElements.filter(
why do u remove it?

2022-10-28 07:37 UTC, ice-ares commented on src/screens/PopUps/ProfilePrivacyEdit/step2/index.tsx
> +            description={'Are you flesh and blood?'}
i18n everything

2022-10-28 07:39 UTC, ice-ares commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +          return {retry: false};
not enough, see how agendaHashes are updated

2022-10-28 07:42 UTC, ice-ares commented on src/store/modules/Auth/actions/index.ts
> +    mockResponse?: boolean,
remove this

2022-10-28 07:42 UTC, ice-hector commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      elementsToUpdate = hiddenElements.filter(
Because that how it works no? It exist or not exist in HiddenProfileElement array. 
Like: 
In this case, we should hide globalRank and level values
`user.hiddenProfileElements = ['globalRank', 'level']`
In this case, we hide nothing
`user.hiddenProfileElements = []`

2022-10-28 07:43 UTC, ice-ares commented on src/store/modules/Auth/sagas/updateAccount.ts
> +  const {mockResponse} = action.payload;
remove this

2022-10-28 07:43 UTC, ice-hector commented on src/store/modules/Auth/actions/index.ts
> +    mockResponse?: boolean,
Why? How should I mock results for testing without this?

2022-10-28 07:44 UTC, ice-ares commented on src/store/modules/Auth/actions/index.ts
> +    mockResponse?: boolean,
whats not deployed?

2022-10-28 07:47 UTC, ice-ares commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      elementsToUpdate = hiddenElements.filter(
the logic doesnt seem correct.

if u have the element already in the source array you remove it, but if you dont, you add it?.

2022-10-28 07:48 UTC, ice-hector commented on src/store/modules/Auth/actions/index.ts
> +    mockResponse?: boolean,
You wrote before: 
`Cant deploy any fix until we have firebase auth implemented, so mock that use-case for now`

2022-10-28 07:53 UTC, ice-hector commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      elementsToUpdate = hiddenElements.filter(
Yes, so what's wrong with it?
For UI and this hook, the only source of truth is the user profile values. So If 'globalRank' value exists in the array that UI will be displayed as hidden and clicking on it in privacy edit mode will remove that value from the array and that UI part will become visible, and visa versa

2022-10-28 11:10 UTC, ice-minos requested changes
In general, codes look pretty good to me 🙂
Good job 🎉

2022-10-28 11:10 UTC, ice-minos commented on src/screens/ProfileFlow/Profile/components/LadderBar/components/LadderItem.tsx
> +        onPress={() => {
I think would be better to create an independent function for that, before return statement

2022-10-28 11:10 UTC, ice-minos commented on src/screens/ProfileFlow/Profile/components/Role/components/CurrentRoleCard.tsx
> +          onPress={
Also here, try to split business logic from UI

2022-10-28 11:10 UTC, ice-minos commented on src/screens/SettingsFlow/Settings/index.tsx
> +              onPress={() => {
Here one too

2022-10-28 11:12 UTC, ice-ares approved these changes

2022-10-28 11:19 UTC, ice-orion commented on src/screens/PopUps/ProfilePrivacyEdit/step1/index.tsx
> +  const goNext = useCallback(() => {
no need to use `useCallback` here

2022-10-28 11:19 UTC, ice-orion commented on src/screens/PopUps/ProfilePrivacyEdit/step3/index.tsx
> +  const navigation =
```
const navigation = useNavigation()
....
<NextButton
          text={t('button.finish')}
          style={styles.finishButton}
          onPress={navigation.goBack}
        />

```

2022-10-28 11:19 UTC, ice-orion commented on src/screens/PopUps/ProfilePrivacyEdit/step2/index.tsx
> +  const goNext = useCallback(() => {
`useCallback` is no needed

2022-10-28 11:19 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/LadderBar/components/LadderItem.tsx
> +        isProfilePrivacyEditMode && {backgroundColor: COLORS.white02opacity},
let's create styles via StyleSheet.create and pass it like `isProfilePrivacyEditMode  && styles.something` for this and all similar places where the inline styles are used (also in `CurrentRoleCard.tsx`)

2022-10-28 11:19 UTC, ice-orion commented on src/screens/PopUps/ProfilePrivacyEdit/step1/index.tsx
> +            hiddenElements={user?.hiddenProfileElements || []}
it's better to select user from within the LadderBar component instead of passing it like a prop -> that will reduce the number of rerenders (LadderBar is wrapped in `memo` and most of the users won't have `hiddenProfileElements` -> every time new array will be passed as prop that will violate the `memo`)
```
// inside LadderBar.tsx
const user = useSelector(userSelector);
const hiddenProfileElements = user?.hiddenProfileElements || []
```

2022-10-28 11:31 UTC, ice-hector commented on src/navigation/Main.tsx
> +import {ProfilePrivacyEditStep1} from '@screens/PopUps/ProfilePrivacyEdit/step1';
Just another file will be created with imports/export, I guess we won't win anything if we do this

2022-10-28 11:33 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/Role/components/CurrentRoleCard.tsx
> +          onPress={
Fixed

2022-10-28 11:34 UTC, ice-hector commented on src/screens/SettingsFlow/Settings/index.tsx
> +              onPress={() => {
Fixed

2022-10-28 11:37 UTC, ice-hector commented on src/screens/PopUps/ProfilePrivacyEdit/components/BackButton.tsx
> +export const BackButton = ({style}: Props) => {
Fixed

2022-10-28 11:38 UTC, ice-hector commented on src/screens/PopUps/ProfilePrivacyEdit/components/BackButton.tsx
> +    <Touchable style={[styles.container, style]} onPress={goBack}>
Fixed

2022-10-28 11:39 UTC, ice-hector commented on src/screens/PopUps/ProfilePrivacyEdit/step1/index.tsx
> +  const goNext = useCallback(() => {
Fixed

2022-10-28 11:39 UTC, ice-hector commented on src/screens/PopUps/ProfilePrivacyEdit/step3/index.tsx
> +  const navigation =
Fixed

2022-10-28 11:40 UTC, ice-hector commented on src/screens/PopUps/ProfilePrivacyEdit/step2/index.tsx
> +  const goNext = useCallback(() => {
Fixed

2022-10-28 11:43 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/LadderBar/components/LadderItem.tsx
> +        isProfilePrivacyEditMode && {backgroundColor: COLORS.white02opacity},
Fixed

2022-10-28 12:00 UTC, ice-hector commented on src/screens/PopUps/ProfilePrivacyEdit/step1/index.tsx
> +            hiddenElements={user?.hiddenProfileElements || []}
Fixed

2022-10-28 12:04 UTC, ice-orion approved these changes

2022-10-28 12:05 UTC, ice-ares approved these changes

2022-10-28 12:07 UTC, ice-minos approved these changes

2022-10-28 12:54 UTC, merged