Firebase auth
ice-blockchain/mobile-app pull request #74
Opened 2022-10-19 12:16 UTC by ice-orion

2022-10-26 20:09 UTC, ice-ares requested changes
The auth & login logic was a mess and you're trying to implement a different mess.


Create a folder **src/services/auth ** where u put all the firebase auth logic. Then create a subfolder in it (**src/services/auth/login/providers **) where you put all the logic u need for each provider, apple, google, email, phone, etc.

All the auth logic will be in that folder, and that folder will contain only auth logic. Same goes for the **login** and **login/providers** subfolders.

2022-10-27 06:03 UTC, ice-orion commented on android/app/src/main/AndroidManifest.xml
> -        <intent-filter>
This particular filter was for MAGIC_DEEPLINK_SCHEME, so we don't need it anymore

2022-10-27 06:07 UTC, ice-orion commented on ios/ice.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "match AppStore io.ice.app.staging";
I reverted it... commited by mistake

2022-10-27 06:24 UTC, ice-orion commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
>      user?.email?.split('@')[0].replace(/[^a-zA-Z0-9-_.]/g, '') ??
I created an util function `removeSpecialCharacters` for that and apply it for the social username as well now, but why do you want to remove `_.`? 
`kirill.pisarev@framey.io` -> `kirill.pisarev`
`kirill_pisarev@framey.io` -> `kirill_pisarev`
or those are not valid usernames in our case?

2022-10-27 06:33 UTC, ice-orion commented on src/store/modules/Auth/actions/index.ts
> +  username?: string | null;
This is a username that we've got from a social provider and we're using it as a suggestion later on, so the idea was to name the field of what it is, but not how we're using it

2022-10-27 06:41 UTC, ice-orion commented on src/store/modules/Auth/hooks/useAuthStateListener.ts
> +    return auth().onAuthStateChanged(() => {
The argument of `onAuthStateChanged` is a `user` or `null`, you're right, and initially i used this argument to pass to the dispatched `AuthActions.AUTH_STATE_CHANGE.START.create` but it turned out that the `user` object is `Non-serializable` - it contains functions in addition to data, so it violates redux rules and we get warnings and even `maximum call stack` error (probably at some point redux or someone tries so stringify it and stuck in circular links inside that object).
So to bypass that i perform `const firebaseUser = auth().currentUser;` to get the same user or null at the begining of the authStateChangeSaga

2022-10-27 06:43 UTC, ice-orion commented on src/store/modules/Auth/reducer/index.ts
> +    username?: string | null;
This is a username that we've got from a social provider and we're using it as a suggestion later on, so the idea was to name the field of what it is, but not how we use it
To make things clearer, that this is just a temp data from the auth providers, i can rename `userInfo` to `signInUserInfo ` or something

2022-10-27 06:45 UTC, ice-orion commented on src/store/modules/Auth/sagas/deleteAccount.ts
> +    const firebaseUser = auth().currentUser;
okay, renamed

2022-10-27 06:50 UTC, ice-orion commented on src/store/modules/Auth/sagas/authStateChange.ts
> +      const token: SagaReturnType<FirebaseAuthTypes.User['getIdToken']> =
This is not a registration saga - `authStateChangeSaga`, it gets executed any time the user gets authenticated / logged out + on the app start

2022-10-27 07:04 UTC, ice-orion commented on src/store/modules/Auth/sagas/authStateChange.ts
> +          email: firebaseUser.email,
Hm, we might but the idea is that in `userInfo` we store something `optional` cuz there might be a chance when we loose that data, like so:
* We get authenticated via let's say google -> `authStateChange` gets triggered
* But `getUser` or `createUser` returns error (no internet or something)
* User closes the app -> `userInfo` is flushed since we don't persist it
* User opens the app when the internet is ok, `authStateChangeSaga` get's triggered by firebase at the start of the app and with `firebaseUser` populated cuz from the firebase's perspective the user is already authenticated and we're trying to `createUser` -> `firebaseUser` might contain email/phone number but `userInfo` is empty

2022-10-27 07:25 UTC, ice-ares commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
>      user?.email?.split('@')[0].replace(/[^a-zA-Z0-9-_.]/g, '') ??
._ no longer valid

2022-10-27 07:25 UTC, ice-ares commented on src/store/modules/Auth/actions/index.ts
> +  username?: string | null;
Then its the userHandle

2022-10-27 07:26 UTC, ice-ares commented on src/store/modules/Auth/hooks/useAuthStateListener.ts
> +    return auth().onAuthStateChanged(() => {
Ok

2022-10-27 07:58 UTC, ice-ares commented on src/store/modules/Auth/reducer/index.ts
> +    username?: string | null;
Yea, thats what an username is called by 3rd parties: userHandle

2022-10-27 15:07 UTC, ice-ares commented on \
> +<script async src="https://telegram.org/js/telegram-widget.js?21" data-telegram-login="samplebot" data-size="large" data-onauth="onTelegramAuth(user)" data-request-access="write"></script>
what's this?

2022-10-27 15:13 UTC, ice-ares commented on src/screens/AuthFlow/SignIn/hooks/useSocialAuth.tsx
> +export const useSocialAuth = () => {
u can use this for phone & email as well

2022-10-27 15:15 UTC, ice-ares commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +import {removeSpecialCharacters} from '@utils/string';
removeInvalidUsernameCharacters

2022-10-27 15:16 UTC, ice-ares commented on src/services/auth/index.ts
> +import {startAppleSignIn} from '@services/auth/providers/apple';
@services/auth/signin/apple
@services/auth/signin/google
@services/auth/signin/facebook
@services/auth/signin/twitter

2022-10-27 15:19 UTC, ice-ares commented on src/services/auth/index.ts
> +export const signInWithTwitter = async () => {
add `signInWithEmail` and `signInWithPhoneNumber` as well

2022-10-27 15:25 UTC, ice-ares commented on src/store/modules/Auth/sagas/deleteAccount.ts
> +    yield call(deleteAccount);
move this after Api.user.deleteUser

2022-10-27 15:27 UTC, ice-ares commented on src/store/modules/Auth/sagas/signInSocial.ts
> +const getSignInMethodForProvider = (provider: SocialSignInProvider) => {
move this inside @services/auth/index.ts

2022-10-27 15:28 UTC, ice-ares commented on src/store/modules/Auth/sagas/signInSocial.ts
> +export function* signInSocialSaga(
u can use this for the email and phone number sign in as well

2022-10-27 15:29 UTC, ice-ares commented on src/utils/string.ts
> +  return input.replace(/[^a-zA-Z0-9-_.]/g, '');
`input.replace(/[^a-zA-Z0-9-]/g, '');`

2022-10-27 15:33 UTC, ice-ares commented on index.html
> +<script async src="https://telegram.org/js/telegram-widget.js?21" data-telegram-login="samplebot" data-size="large" data-onauth="onTelegramAuth(user)" data-request-access="write"></script>
whats this?

2022-10-28 05:32 UTC, ice-orion commented on src/api/client/interceptors/response.ts
> +import auth from '@react-native-firebase/auth';
done

2022-10-28 05:33 UTC, ice-orion commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
>      user?.email?.split('@')[0].replace(/[^a-zA-Z0-9-_.]/g, '') ??
done

2022-10-28 05:35 UTC, ice-orion commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +import {removeSpecialCharacters} from '@utils/string';
done

2022-10-28 05:36 UTC, ice-orion commented on src/store/modules/Auth/sagas/deleteAccount.ts
> +    yield call(deleteAccount);
done

2022-10-28 05:43 UTC, ice-orion commented on src/store/modules/Auth/sagas/signInSocial.ts
> +const getSignInMethodForProvider = (provider: SocialSignInProvider) => {
done

2022-10-28 05:44 UTC, ice-orion commented on src/utils/string.ts
> +  return input.replace(/[^a-zA-Z0-9-_.]/g, '');
done

2022-10-28 05:44 UTC, ice-orion commented on index.html
> +<script async src="https://telegram.org/js/telegram-widget.js?21" data-telegram-login="samplebot" data-size="large" data-onauth="onTelegramAuth(user)" data-request-access="write"></script>
removed, added by mistake

2022-10-28 05:49 UTC, ice-orion commented on src/store/modules/Auth/sagas/index.ts
> +import {updateAccountSaga} from '@store/modules/Auth/sagas/updateAccount';
Usually this kind of stuff is grouped under `User` module (user auth + user manipulations), so we can rename module Auth -> User

2022-10-28 06:16 UTC, ice-orion commented on src/store/modules/Auth/reducer/index.ts
> +    username?: string | null;
done

2022-10-28 06:16 UTC, ice-orion commented on src/store/modules/Auth/actions/index.ts
> +  username?: string | null;
done

2022-10-28 09:11 UTC, ice-ares commented on src/store/modules/Auth/sagas/index.ts
> +import {updateAccountSaga} from '@store/modules/Auth/sagas/updateAccount';
Still, update has nothing to do with auth

2022-10-31 13:27 UTC, ice-ares commented on src/services/auth/index.ts
> +  forceResend?: boolean,
this is always true

2022-10-31 13:29 UTC, ice-ares commented on src/services/auth/index.ts
> +      case 'auth/invalid-phone-number':
add all the possible errors here, from all sign in methods, including the social ones.

2022-10-31 13:30 UTC, ice-ares commented on src/store/modules/Auth/actions/index.ts
> +  RESEND: true,
unnecessary, cuz always true

2022-11-02 08:13 UTC, ice-orion commented on src/store/modules/Auth/sagas/authStateChange.ts
> +import {FirebaseAuthTypes} from '@react-native-firebase/auth';
done, everything firebase/auth related is in the `services/auth` now

2022-11-02 08:13 UTC, ice-orion commented on src/services/auth/index.ts
> +import {startAppleSignIn} from '@services/auth/providers/apple';
done

2022-11-02 08:14 UTC, ice-orion commented on src/store/modules/Auth/sagas/index.ts
> +import {updateAccountSaga} from '@store/modules/Auth/sagas/updateAccount';
Yea, that's why i suggest to rename `Auth` module to `User`

2022-11-03 07:24 UTC, ice-orion commented on src/services/auth/index.ts
> +  forceResend?: boolean,
ok, changed to always true

2022-11-03 07:45 UTC, ice-orion commented on src/store/modules/Auth/sagas/signInPhone.ts
> +          confirmation = yield call(signInWithPhoneNumber, phoneNumber, true);
Changed to always true in `signInWithPhoneNumber`
But keep in mind that user can press login button on the sign-in screen (send sms), then press back on the confirmation screen, and going this way back and forth send sms messages without any restrictions

2022-11-03 08:22 UTC, ice-ares commented on src/store/modules/Auth/sagas/signInPhone.ts
> +          confirmation = yield call(signInWithPhoneNumber, phoneNumber, true);
Nope, cuz its blocked by that 30s

2022-11-03 09:20 UTC, ice-orion commented on src/services/auth/index.ts
> +      case 'auth/invalid-phone-number':
added all possible auth user errors here
possible social errors are handled in providers (99% of social auth user errors are handled internally and will be shown in the auth modals)

2022-11-03 16:49 UTC, ice-ares commented on src/services/auth/index.ts
> +      uid: currentUser.uid,
...currentUser,

2022-11-04 11:23 UTC, ice-ares commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/DeveloperMenuSection.tsx
> +        <MenuItem
can you add a copy to clipboard button? for both userID and token

2022-11-04 11:23 UTC, ice-ares commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/DeveloperMenuSection.tsx
> +          onPress={() => Share.share({message: user?.id ?? ''})}
does share include copy to clipboard?

2022-11-04 11:37 UTC, ice-ares commented on src/store/modules/Auth/sagas/index.ts
> +import {updateAccountSaga} from '@store/modules/Auth/sagas/updateAccount';
Then, rename it to "Account"

2022-11-04 11:41 UTC, ice-ares commented on src/store/modules/Auth/sagas/signInSocial.ts
> +    //TODO::find out how to catch account-exists-with-different-credential -> run "unusual activity" flow
add this todo to the email sign in as well

2022-11-04 11:43 UTC, ice-ares commented on src/store/modules/Auth/sagas/userStateChange.ts
> +    if (authenticatedUser) {
we should know why the userState changed

2022-11-04 11:43 UTC, ice-ares commented on src/store/modules/Auth/sagas/userStateChange.ts
> +    if (authenticatedUser) {
or what has changed

2022-11-04 11:45 UTC, ice-ares commented on src/store/modules/Auth/sagas/userStateChange.ts
> +      yield put(AuthActions.USER_STATE_CHANGE.SUCCESS.create(null, null));
does this force a logout?

2022-11-04 11:46 UTC, ice-ares commented on src/store/modules/Auth/sagas/userStateChange.ts
> +          authenticatedUser.isAdmin,
why do u need to pass this?

2022-11-04 11:49 UTC, ice-ares commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> -      yield put(
why?

2022-11-04 11:50 UTC, ice-ares commented on src/store/modules/Linking/actions/index.ts
> +  STATE: (url: string, fromLinking?: boolean) => ({url, fromLinking}),
looks more like an `internal?: boolean` or an `handledInApp?: boolean`

2022-11-07 09:15 UTC, ice-orion commented on src/store/modules/Auth/sagas/signInPhone.ts
> +          confirmation = yield call(signInWithPhoneNumber, phoneNumber, true);
resend reworked, so now we disable the button on the main sign-in scree if the timeout is not expired

2022-11-07 10:42 UTC, ice-orion commented on src/services/auth/index.ts
> +export const onUserChanged = (listener: () => void) => {
We can't dispatch that user, cuz it contains methods (non-serializable object) and we're receiving the fresh user data when in `getAuthenticatedUser`

2022-11-07 10:47 UTC, ice-orion commented on src/services/auth/index.ts
> +      uid: currentUser.uid,
The main idea was to get away from the `FirebaseAuthTypes.User` type that is in the `currentUser` so we won't rely on the lib's type outside of the `src/services/auth` service -> so i don't copy everything, but only that what we need.
And the `currentUser` contains methods in addition to data and i'm not sure they will work as expected in the new object

2022-11-07 10:48 UTC, ice-orion commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/DeveloperMenuSection.tsx
> +          onPress={() => Share.share({message: user?.id ?? ''})}
yea, it does + in addition to copy you can send it to a messenger or something

2022-11-07 10:48 UTC, ice-orion commented on src/screens/SettingsFlow/Settings/components/SettingsMenuSections/DeveloperMenuSection.tsx
> +        <MenuItem
Share contains the copy action, may be that is enough?

2022-11-07 10:49 UTC, ice-orion commented on src/store/modules/Auth/sagas/signInSocial.ts
> +    //TODO::find out how to catch account-exists-with-different-credential -> run "unusual activity" flow
done

2022-11-07 10:51 UTC, ice-orion commented on src/store/modules/Auth/sagas/userStateChange.ts
> +    if (authenticatedUser) {
why do we need to know it?

2022-11-07 10:52 UTC, ice-orion commented on src/store/modules/Auth/sagas/userStateChange.ts
> +      yield put(AuthActions.USER_STATE_CHANGE.SUCCESS.create(null, null));
yea, this will force the user in the store to be null -> `isAuthorizedSelector` will return false and the `Auth` navigator will be rendered

2022-11-07 10:59 UTC, ice-orion commented on src/store/modules/Auth/sagas/userStateChange.ts
> +          authenticatedUser.isAdmin,
i store this flag in the store, so UI can react to it.
if it's true -> show developer menu section, if not -> hide

2022-11-07 11:02 UTC, ice-orion commented on src/store/modules/Devices/sagas/updateDeviceMetadata.ts
> -      yield put(
this is the place where we're skipping the update (if not authorized, if we get to the background instead of foreground, if the update timeout is not passed yet) -> so it's not an error and we just don't need to do anything

2022-11-07 11:17 UTC, ice-ares commented on src/store/modules/Auth/sagas/userStateChange.ts
> +          authenticatedUser.isAdmin,
{…user,isAdmin}

2022-11-07 11:21 UTC, ice-ares commented on src/components/ModifyPhoneNumber/index.tsx
> +        // selectedCountry={selectedCountry}
let’s change it then

2022-11-07 11:23 UTC, ice-orion commented on src/store/modules/Auth/sagas/userStateChange.ts
> +          authenticatedUser.isAdmin,
This way we would modify the `User` type that we're currently receiving from the BE and using everywhere in the app.  I'm storing the custom user props separately, so we won't need to create separate user type "after modifications"

2022-11-07 11:25 UTC, ice-orion commented on src/components/ModifyPhoneNumber/index.tsx
> +        // selectedCountry={selectedCountry}
I left it like that because the modify phone (as well as the settings redesign) is a part of the https://github.com/ice-blockchain/mobile-app/pull/66

2022-11-07 11:25 UTC, ice-orion commented on src/components/ModifyPhoneNumber/index.tsx
> +        // selectedCountry={selectedCountry}
i can take it next when this PR is in the master

2022-11-10 10:21 UTC, ice-orion commented on src/screens/AuthFlow/SignIn/components/SocialButtons/index.tsx
> +      <Touchable
done

2022-11-10 11:49 UTC, ice-orion commented on src/constants/env.ts
> +  APP_ID: config.APP_ID,
this constant is here
```
export const sendSignInLinkToEmail = async (email: string) => {
  return auth().sendSignInLinkToEmail(email, {
    dynamicLinkDomain: ENV.DEEPLINK_DOMAIN,
    handleCodeInApp: true,
    iOS: {
      bundleId: ENV.APP_ID,
    },
    android: {
      packageName: ENV.APP_ID ?? '',
      installApp: true,
    },
    url: `https://${ENV.DEEPLINK_DOMAIN}/email-confirmation`,
  });
};
``` 
So we need to specify bundleId / packageName when using firebase `sendSignInLinkToEmail `

2022-11-10 11:56 UTC, ice-orion commented on src/services/auth/signin/twitter.ts
> +        firstName: null,
the response has this type:
```
declare type Auth = {
    /**
     * Twitter AuthToken
     */
    authToken?: string;
    /**
     * Twitter AuthToken Secret
     */
    authTokenSecret?: string;
    /**
     * email of logged in user
     */
    email?: string;
    /**
     * Twitter userID
     */
    userID?: string;
    /**
     * Twitter userName
     */
    userName?: string;
}
```

2022-11-10 11:57 UTC, ice-orion commented on src/services/auth/signin/facebook.ts
> +      firstName: [profile?.middleName, profile?.firstName].join(' ').trim(),
done

2022-11-10 11:57 UTC, ice-orion commented on src/services/auth/signin/apple.ts
> +        firstName: [
done

2022-11-10 11:57 UTC, ice-orion commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +  const [username, setUsername] = useState(userInfo?.userHandle ?? '');
right... got back user.email usage in `usernameToPrefill`, this will also be useful if userInfo is flushed

2022-11-10 12:08 UTC, ice-orion commented on src/services/auth/signin/google.ts
> +        userHandle: removeInvalidUsernameCharacters(
here is what we have there (name = givenName + familyName)
```
export interface User {
    user: {
        id: string;
        name: string | null;
        email: string;
        photo: string | null;
        familyName: string | null;
        givenName: string | null;
    };
    scopes?: string[];
    idToken: string | null;
    /**
     * Not null only if a valid webClientId and offlineAccess: true was
     * specified in configure().
     */
    serverAuthCode: string | null;
}
```

2022-11-10 12:08 UTC, ice-ares commented on src/services/auth/signin/apple.ts
> +          fullName?.namePrefix,
we dont need prefix or suffix

2022-11-10 12:11 UTC, ice-orion commented on src/services/auth/signin/twitter.ts
> +        userHandle: removeInvalidUsernameCharacters(userName ?? ''),
added email there

2022-11-10 12:27 UTC, ice-orion commented on src/services/auth/signin/facebook.ts
> +      userHandle: removeInvalidUsernameCharacters(
i haven't found explicit `userhandle`/`username` fields - https://developers.facebook.com/docs/graph-api/reference/user/

2022-11-10 12:27 UTC, ice-orion commented on src/services/auth/signin/apple.ts
> +          fullName?.namePrefix,
removed

2022-11-10 14:13 UTC, ice-ares commented on src/services/auth/signin/twitter.ts
> +        firstName: null,
maybe try [this](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-by-username-username)

2022-11-11 08:43 UTC, ice-hector commented on src/components/Inputs/PhoneNumberInput/components/CountryButton.tsx
> +    fontSize: rem(28),
use font wrapper

2022-11-11 08:47 UTC, ice-orion commented on src/services/auth/signin/twitter.ts
> +        firstName: null,
The lib uses old twitter api version (v1.1). Here is for example how to receive user settings - [link](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-settings) - there is the `screen_name` props, but that is the same as `username` that we already have

2022-11-11 08:48 UTC, ice-hector commented on src/screens/AuthFlow/ConfirmEmailLink/components/Header/index.tsx
> +      {/* for too tall devices */}
Should it be optional? Should we check the phone sides dimension to detect tall devices?

2022-11-11 08:49 UTC, ice-hector commented on src/screens/AuthFlow/ConfirmPhone/components/Header/index.tsx
> +      {/* for too tall devices */}
Same question

2022-11-11 08:51 UTC, ice-ares commented on src/services/auth/signin/twitter.ts
> +        firstName: null,
then try https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup

2022-11-11 10:42 UTC, ice-orion commented on src/screens/AuthFlow/ConfirmEmailLink/components/Header/index.tsx
> +      {/* for too tall devices */}
Not really. This component is only visible if you hardly scroll the screen to the bottom without releasing the finger or for the tall devices. In other cases you won't see it.

2022-11-11 10:42 UTC, ice-orion commented on src/screens/AuthFlow/ConfirmPhone/components/Header/index.tsx
> +      {/* for too tall devices */}
Not really. This component is only visible if you hardly scroll the screen to the bottom without releasing the finger or for the tall devices. In other cases you won't see it.

2022-11-11 10:44 UTC, ice-orion commented on src/components/Inputs/PhoneNumberInput/components/CountryButton.tsx
> +    fontSize: rem(28),
there is no advantage in using `font` here - in this particular case `fontSize` = `width` or `height` of the flag

2022-11-11 11:08 UTC, ice-orion commented on src/services/auth/signin/twitter.ts
> +        firstName: null,
added TODO

2022-11-11 11:25 UTC, ice-hector approved these changes

2022-11-11 11:30 UTC, ice-ares approved these changes

2022-11-11 11:41 UTC, ice-minos approved these changes

2022-11-11 11:44 UTC, merged