chore: Home screen
ice-blockchain/mobile-app pull request #76
Opened 2022-10-27 07:43 UTC by ice-minos

Task 4 (first part):
Redirecting from home screen to profile;
Real data of referrals on pioneer card;

2022-10-27 08:48 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/index.tsx
> -            <AdoptionCard />
add that back

2022-10-27 08:52 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/index.tsx
> +              frontComponent={<LevelCard />}
First card is called “profile”, 2nd referrals, 3rd adoption .

back of 2nd card is referralAcquisitionHistory 
back of 3rd card is  onlineUsersHistory

2022-11-07 10:13 UTC, ice-ares requested changes

2022-11-07 10:13 UTC, ice-ares commented on ios/Podfile
> +        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
Whats this for?

2022-11-07 10:13 UTC, ice-ares commented on ios/ice.xcodeproj/project.pbxproj
> +				"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "match AdHoc io.ice.app.staging";
Why do u need that?

2022-11-07 10:13 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/components/LevelCard/index.tsx
> +  const referrals = (user?.t1ReferralCount || 0) + (user?.t1ReferralCount || 0);
t1 + t2

2022-11-07 10:13 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCard/index.tsx
> +  const referrals = (user?.t1ReferralCount || 0) + (user?.t1ReferralCount || 0);
t1 + t2

2022-11-07 10:13 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCardBack/index.tsx
> +  const referralHistory = useSelector(referralHistorySelector).slice(0, 5);
Nope, use the query param to limit the size

2022-11-07 10:13 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCardBack/index.tsx
> +    const fullDate = new Date(date);
Use dayjs

2022-11-07 10:13 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCardBack/index.tsx
> +    return `${day}/${month + 1}`;
Use format

2022-11-07 10:13 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/components/VerticalBar/index.tsx
> +      // eslint-disable-next-line react-native/no-unused-styles
Fix em

2022-11-09 08:33 UTC, ice-ares requested changes

2022-11-09 08:33 UTC, ice-ares commented on src/components/ListItems/UserListItem/index.tsx
> +          onPress={() => navigation.navigate('Profile', {userId: name})}>
userid not name

2022-11-09 08:33 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Team/components/TeamMember.tsx
> +        onPress={() => navigation.navigate('Profile', {userId: username})}>
userid not username

2022-11-09 09:37 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/LevelCard/index.tsx
> +  const referrals = (user?.t1ReferralCount || 0) + (user?.t1ReferralCount || 0);
Fixed

2022-11-09 09:38 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCard/index.tsx
> +  const referrals = (user?.t1ReferralCount || 0) + (user?.t1ReferralCount || 0);
Fixed

2022-11-09 09:59 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCardBack/index.tsx
> +    const fullDate = new Date(date);
Reworked using dayjs

2022-11-09 09:59 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCardBack/index.tsx
> +    return `${day}/${month + 1}`;
Reworked using dayjs.format()

2022-11-09 10:58 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/VerticalBar/index.tsx
> +      // eslint-disable-next-line react-native/no-unused-styles
Reworked with conditional rendering styles

2022-11-09 10:59 UTC, ice-hector commented on ios/Podfile
> +        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
This is the compilation errors fix. Some pod libraries (new releases) are broken and required signing. They shouldn't work this way that's why we applied that fixed

2022-11-09 10:59 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				"DEVELOPMENT_TEAM[sdk=iphoneos*]" = YJJ6X8TG5Y;
Don't commit this to repo

2022-11-09 10:59 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "match AdHoc io.ice.app.staging";
Don't commit this to repo

2022-11-09 10:59 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				"DEVELOPMENT_TEAM[sdk=iphoneos*]" = YJJ6X8TG5Y;
same

2022-11-09 10:59 UTC, ice-hector commented on ios/ice.xcodeproj/project.pbxproj
> +				"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "match AdHoc io.ice.app.staging";
same

2022-11-09 10:59 UTC, ice-hector commented on src/components/FlipCard/index.tsx
> +    width: '100%',
I'm not sure that would work with 'absolute'. Probably use StyleSheet.absoluteFill or {top: 0, bottom: 0, left: 0, right: 9}

2022-11-09 10:59 UTC, ice-hector commented on src/components/ListItems/UserListItem/index.tsx
> +            <Text style={styles.nameText} numberOfLines={1}>
What if it would be the long name? is numberOfLines={1} required by design?

2022-11-09 10:59 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Overview/components/AdoptionCardBack/index.tsx
> +            .fill(null)
I guess there is no need to put null in fill()

2022-11-09 10:59 UTC, ice-hector commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCardBack/index.tsx
> +            .fill(null)
same, no need to put null

2022-11-09 10:59 UTC, ice-hector commented on src/store/modules/Referrals/sagas/index.ts
> +      ReferralsActions.GET_REFERRALS({})(null).START.type,
ReferralsActions.GET_REFERRALS.START.type

2022-11-09 12:35 UTC, ice-ares commented on src/components/ListItems/UserListItem/index.tsx
> +        <Touchable
Yes, by default all avatars redirect to the user's profile, unless you are already there, at which point you full screen the picture

2022-11-09 12:40 UTC, ice-ares commented on src/store/modules/Referrals/reducer/index.ts
> +  history: ReferralHistoryRecord[];
nope, we only need the history for the logged in user. So we don't need the userId param there

2022-11-09 13:03 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/index.tsx
> +                  data={MOCK_TOTAL_USERS_GRAPH_DATA.slice(0, 7).reverse()}
Have you tested it with empty array and when mocked data contain items with `value: 0`?

2022-11-09 13:21 UTC, ice-minos commented on src/components/ListItems/UserListItem/index.tsx
> +            <Text style={styles.nameText} numberOfLines={1}>
I asked in designer about that and he said - everything is ok. But also, this property was early in the repo I only added an onPress callback.

2022-11-09 14:18 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +  const isOwner = !route.params;
const route = useRoute<RouteProp<ProfileTabStackParamList, 'Profile'>>();
  const isOwner =
    (route.params && !route.params.userId) ||
    (route.params && route.params.userId === user?.id);

2022-11-09 15:55 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/AdoptionCardBack/index.tsx
> +            .fill(null)
Ok, I changed to empty string.

2022-11-09 15:55 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCardBack/index.tsx
> +            .fill(null)
Same, empty string

2022-11-09 15:57 UTC, ice-minos commented on src/store/modules/Referrals/sagas/index.ts
> +      ReferralsActions.GET_REFERRALS({})(null).START.type,
ReferralsActions.GET_REFERRALS.START.type was written not be me. I just put it to the yield all. Try to run it without parameters and got a crash.

2022-11-09 18:17 UTC, ice-minos commented on src/screens/ProfileFlow/Profile/index.tsx
>    const user = useSelector(userSelector);
Right now we haven't any API for that, so true or false for us is the temporary statement

2022-11-09 18:24 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
>    const user = useSelector(userSelector);
What do you mean u dont have an API for that? How do you think the profile screen is working right now?

2022-11-09 18:33 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/index.tsx
> +                  data={MOCK_TOTAL_USERS_GRAPH_DATA.slice(0, 7).reverse()}
Will be Infinity I can try to handle it, but we have same scenarios in BarGraph component

2022-11-09 18:34 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/index.tsx
> +                  data={MOCK_TOTAL_USERS_GRAPH_DATA.slice(0, 7).reverse()}
Will be Infinity I can try to handle it, but we have same scenarios in BarGraph component

2022-11-10 06:37 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +  const isOwner = !route.params;
@ice-hector there might be a case when we don't pass params at all and this should be `isOwner` also.
so it's either as you said:
```
const isOwner = !route.params || !route.params.userId || route.params.userId === user?.id;
```
or
```
const isOwner = !route.params?.userId || route.params.userId === user?.id;
```

2022-11-10 06:40 UTC, ice-orion commented on src/store/modules/Referrals/sagas/index.ts
> +      ReferralsActions.GET_REFERRALS({})(null).START.type,
`ReferralsActions.GET_REFERRALS` should be like that - this action is kinda tricky cuz it is `{isMultiInstanceProcess: true}`

2022-11-10 06:42 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/index.tsx
> +                  data={MOCK_TOTAL_USERS_GRAPH_DATA.slice(0, 7).reverse()}
What do you mean? What scenarios?

2022-11-10 07:16 UTC, ice-orion commented on src/components/ListItems/UserListItem/index.tsx
> +    userId?: string | undefined;
`userId: string` - it would never be an undefined (otherwise we would open our own profile)

2022-11-10 07:16 UTC, ice-orion commented on src/navigation/Main.tsx
> +  Profile: {userId: string | undefined} | undefined;
`{userId: string} | undefined` - if you pass an id, it would never be an undefined

2022-11-10 07:16 UTC, ice-orion commented on src/navigation/Main.tsx
> +  Profile: {userId: string | undefined} | undefined;
`{userId: string} | undefined`

2022-11-10 07:16 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/components/AdoptionCard/index.tsx
> +      backgroundImageSource={require('../../../../../../../assets/images/backgrounds/adoptionCardBg.png')}
use `Images.backgrounds.adoptionCardBg` -> to be able to do that, add it to the `src/assets/images/index.ts`

2022-11-10 07:16 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/components/LevelCard/index.tsx
> +      backgroundImageSource={require('../../../../../../../assets/images/backgrounds/levelCardBg.png')}
use `Images.backgrounds. levelCardBg`

2022-11-10 07:16 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralAcquisitionHistory/index.tsx
> +    dispatch(ReferralsActions.GET_REFERRALS_HISTORY.START.create(user!.id));
remove id from `ReferralsActions.GET_REFERRALS_HISTORY` action since we always receive history for our own user

2022-11-10 07:16 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralAcquisitionHistory/index.tsx
> +      backgroundImageSource={require('../../../../../../../assets/images/backgrounds/referralsCardBg.png')}
same, use `Images.backgrounds. referralsCardBg`

2022-11-10 07:16 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralsCard/index.tsx
> +      backgroundImageSource={require('../../../../../../../assets/images/backgrounds/referralsCardBg.png')}
`Images.backgrounds`

2022-11-10 07:16 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +    !route.params || (route.params && route.params.userId === user?.id);
`const isOwner =
    !route.params || route.params.userId === user?.id;`
    
  `route.params` check in the right side is redundant

2022-11-10 08:28 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/index.tsx
> +                  data={MOCK_TOTAL_USERS_GRAPH_DATA.slice(0, 7).reverse()}
If we took the empty array to the BarGraph, which was like an example for me - it will return Infinity too.

2022-11-10 09:44 UTC, ice-minos commented on src/screens/ProfileFlow/Profile/index.tsx
>    const user = useSelector(userSelector);
I was trying to call the API for that, but in response, I only get a small piece of full data which I expected. A lot of fields are optional. 
Do you mean to connect it right now and "hard code" the existing field? Or how I can get the whole needed data for that. For example badges, levels, etc.

2022-11-10 09:55 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
>    const user = useSelector(userSelector);
Yes, some of them are not implemented,  mock em. Just use the same data u have at the moment in master

2022-11-10 10:59 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/index.tsx
> +                  data={MOCK_TOTAL_USERS_GRAPH_DATA.slice(0, 7).reverse()}
I fixed BarGraph [here](https://github.com/ice-blockchain/mobile-app/commit/eaa2aa2a36da5fa32fc480beca98e49b5117f06f)
Please also test the new graph components with 
```
data = []
data = [{value: 0}, {value: 0}]
data = [{value: 100}, {value: 0}]
```

2022-11-10 13:49 UTC, ice-ares commented on src/navigation/Main.tsx
> +    <ProfileTabStack.Screen name="Settings" component={Settings} />
Why are settings in the home tab?

2022-11-10 14:00 UTC, ice-minos commented on src/navigation/Main.tsx
> +    <ProfileTabStack.Screen name="Settings" component={Settings} />
Cause in Profile we need to have an opportunity to redirect user to Settings

2022-11-10 14:17 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/components/OnlineUsersHistory/index.tsx
> +  const totalAdoptionUsers =
you don't calculate anything, you just display the data you get from the BE (in the future), for now mock it

2022-11-10 14:30 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
> +        allowFullScreen={isOwner}
all the time, not only for the owner

2022-11-10 14:32 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
>            <Role />
u have to implement the privacy policy as well. Some parts of the profile will be hidden if the owner of that profile wanted that. @ice-hector worked on that, it's in master already, check how `user.hiddenProfileElements` are used

2022-11-10 14:34 UTC, ice-ares commented on src/store/modules/Auth/selectors/index.ts
> +export const anotherUserSelector = (state: RootState) => state.users.user;
whats that `users.user` thing?

2022-11-10 14:38 UTC, ice-ares commented on src/store/modules/Users/sagas/getUserByIdSaga.ts
> +    yield put(
handle 404 with USER_NOT_FOUND (see examples in the codebase) and display an empty profile screen (see Figma)

2022-11-10 14:48 UTC, ice-minos commented on src/store/modules/Auth/selectors/index.ts
> +export const anotherUserSelector = (state: RootState) => state.users.user;
I decided to do like that, cause maybe in future we will have other ones data in users obj. I can do just state.user if you wanna

2022-11-10 14:55 UTC, ice-ares commented on src/store/modules/Auth/selectors/index.ts
> +export const anotherUserSelector = (state: RootState) => state.users.user;
port const otherUserSelector = (state: RootState) => state.otherUser;

2022-11-11 07:08 UTC, ice-orion commented on src/navigation/Main.tsx
> +    <ProfileTabStack.Screen name="Settings" component={Settings} />
Settings screen leads to bunch of other screens like `PersonalInformation` `NotificationSettings` etc, but Settings available only for the current user, so instead of adding all those screens to every tab, it probably makes sense to open ProfileTab->Settings when you press the settings icon.

2022-11-11 07:19 UTC, ice-orion commented on src/store/modules/Auth/selectors/index.ts
> +export const anotherUserSelector = (state: RootState) => state.users.user;
Place the selector in the corresponding module (Users)

2022-11-11 07:31 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +  const user = useSelector(isOwner ? userSelector : anotherUserSelector);
I think we have to change the way the store / select users:
The problem here is that we will see the prev profile until the current user is loaded (anotherUserSelector will return the prev user -> only when the getUserByIdSaga loads the user for the current id, we will see the correct data). Moreover if we get an error during the fetching, we will end up displaying the wrong user data until user refreshes the page.

Preferred way (as it is usually done) - store all the fetched users by id:
```
{[userId: string]: User}
```

And select them by id 
```
const user = useSelector(isOwner ? userSelector : userByIdSelector(route.params.userId));
```

We can keep the fetching on the screen open anyway to refresh the data but in this case we will display the data instantly, if we have the user in the store, and the request will just refresh data.

2022-11-11 08:43 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
> +  const user = useSelector(isOwner ? userSelector : anotherUserSelector);
+1

2022-11-11 11:09 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/OnlineUsersHistory/index.tsx
> +  const totalAdoptionUsers =
Now i calculate min and max and other values from mock data. But in the future I will calculate them from the BE.

2022-11-11 11:53 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
> +        allowFullScreen={isOwner}
no, the picture has nothing to do with the agenda contact element.
 
 Top on photo => fullscreen
 tap on the contact => tooltip

2022-11-11 12:38 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralAcquisitionHistory/index.tsx
> +    return dayjs(date).format('DD/MM');
how better to check from where user? cause if I'll use locale from dayjs or i18n - it'll be return only "en" to me. and if I'll depend on this, the format for example for UK users will be wrong

2022-11-11 12:44 UTC, ice-ares commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralAcquisitionHistory/index.tsx
> +    return dayjs(date).format('DD/MM');
you need to check for system settings I think, google it. @ice-hector @ice-orion any ideas?

2022-11-11 12:49 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralAcquisitionHistory/index.tsx
> +    return dayjs(date).format('DD/MM');
will try to use for that react-native-localize. it already installed in project

2022-11-11 16:39 UTC, ice-minos commented on src/store/modules/Auth/selectors/index.ts
> +export const anotherUserSelector = (state: RootState) => state.users.user;
done

2022-11-11 16:45 UTC, ice-minos commented on src/screens/ProfileFlow/Profile/index.tsx
> +  const user = useSelector(isOwner ? userSelector : anotherUserSelector);
done

2022-11-11 16:46 UTC, ice-minos commented on src/screens/ProfileFlow/Profile/index.tsx
> +        allowFullScreen={isOwner}
done

2022-11-11 16:46 UTC, ice-minos commented on src/navigation/Main.tsx
> +    <ProfileTabStack.Screen name="Settings" component={Settings} />
done

2022-11-11 17:03 UTC, ice-orion commented on src/screens/HomeFlow/Home/components/Overview/components/ReferralAcquisitionHistory/index.tsx
> +    return dayjs(date).format('DD/MM');
summary after the call:
create date service
move all `dayjs.extend(plugin_name)` there + wrap all dayjs calls
add `const localizedFormat = (date, format) => dayjs(date).locate(appLocale).format(format)`

2022-11-11 17:04 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
>            <Role />
summary after the call:
pass user to <Role />, <Badges />, <LadderBar /> components, properly handle `hidden` prop

2022-11-11 17:07 UTC, ice-orion commented on src/store/modules/Users/sagas/getUserByIdSaga.ts
> +    yield put(
summary after the call:
create `useUser.ts` hook in Profile screen
`const {user, isOwner, isNotFound, isLoading} = useUser()`

pass error code to the GET_USER_BY_ID.ERROR.create({errorMessage, errorCode})
then take it in the `useUser` hook via `actionPayloadSelector` (example: src/screens/WelcomeFlow/ConfirmEmailCode/hooks/useConfirmEmail.ts)

2022-11-14 10:37 UTC, ice-minos commented on src/store/modules/Users/sagas/getUserByIdSaga.ts
> +    yield put(
@ice-hector works on that

2022-11-14 17:05 UTC, ice-minos commented on src/screens/ProfileFlow/Profile/index.tsx
>            <Role />
done

2022-11-14 18:25 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/AvatarHeader/index.tsx
> -export const AvatarHeader = memo(({uri, scrollY}: Props) => {
This

2022-11-14 18:25 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/LadderBar/index.tsx
> -    <View style={styles.ladder}>
This

2022-11-14 18:27 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Header/index.tsx
> +            {user && <Text style={styles.nickText}>{user.username}</Text>}
are you style naming?

2022-11-14 18:30 UTC, ice-minos commented on src/screens/ProfileFlow/Profile/components/LadderBar/index.tsx
> -    <View style={styles.ladder}>
same here

2022-11-17 13:02 UTC, ice-hector submitted a review, later dismissed

2022-11-17 13:37 UTC, ice-minos commented on src/components/ListItems/UserListItem/index.tsx
> +          onPress={() => navigation.navigate('Profile', {userId: name})}>
done

2022-11-17 13:37 UTC, ice-minos commented on src/screens/HomeFlow/Home/components/Team/components/TeamMember.tsx
> +        onPress={() => navigation.navigate('Profile', {userId: username})}>
done

2022-11-17 13:38 UTC, ice-hector approved these changes

2022-11-17 14:27 UTC, merged