User profile tooltip
ice-blockchain/mobile-app pull request #77
Opened 2022-11-10 14:55 UTC by ice-hector

2022-11-11 12:11 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +    zIndex: 1,
why do we need it?

2022-11-11 12:11 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +          updateTooltipVisibleState(!isTooltipVisible);
`updateTooltipVisibleState(state =>  !state);`

2022-11-11 12:11 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +  const updateTooltipVisibleState = (isVisible: boolean) => {
lets keep the tooltip + tooltip state inside the AvatarHeader to keep the main screen index file clean?

2022-11-11 12:11 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +    (!route.params.userId || route.params.userId === authUser?.id);
`const isOwner = !route.params || route.params.userId === authUser?.id;` - this one seems to be more correct

2022-11-11 12:11 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/index.tsx
> +    if (!isOwner && route.params) {
the condition here will be changed anyway, so i would rollback this change

2022-11-11 12:11 UTC, ice-orion commented on src/screens/ProfileFlow/Profile/components/TooltipAvatar/index.tsx
> +        <View
May be it makes sense to create a common component for the contact icon? We could use it 
here + 
src/screens/InviteFlow/InviteFriend/components/InviteAvatar/index.tsx +
src/screens/Team/components/Contacts/components/ContactsList/components/ContactItem/index.tsx +
That would render that colored rectangle with the `Acronym`?

2022-11-11 12:37 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +          updateTooltipVisibleState(!isTooltipVisible);
you mean
`setIsTooltipVisible(state => !state);`
?

2022-11-11 12:40 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +  const updateTooltipVisibleState = (isVisible: boolean) => {
Its not a part of avatar header

2022-11-11 12:40 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +    (!route.params.userId || route.params.userId === authUser?.id);
Fixed

2022-11-11 12:40 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +          updateTooltipVisibleState(!isTooltipVisible);
Fixed

2022-11-11 12:56 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +    zIndex: 1,
This is required to display the header over the other content

2022-11-11 13:03 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +    if (!isOwner && route.params) {
Fixed

2022-11-15 15:40 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/TooltipAvatar/index.tsx
> +        <View
This one will not support thumbnails, only acronyms, that's why its separate and will only be used here I assume

2022-11-15 18:37 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/AvatarHeader/index.tsx
> +                    allowFullScreen={isOwner}
true

2022-11-15 18:40 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/AvatarHeader/index.tsx
> +                <TooltipAvatar
rendered if phoneNumber is not empty

2022-11-15 18:40 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/AvatarHeader/index.tsx
> +          {user && !isOwner && (
remove !isOwner

2022-11-15 18:41 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/AvatarHeader/index.tsx
> +                <TooltipAvatar
the whole element (the [AB] thing), including the tooltip

2022-11-15 18:45 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/UserInfoTooltip/index.tsx
> +  const fullName = `${user.firstName || ''} ${user.lastName || ''}`;
.trim()

2022-11-15 18:46 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/UserInfoTooltip/index.tsx
> +        <TooltipAvatar
what tooltip is this for? how is it different than `src/screens/ProfileFlow/Profile/components/TooltipAvatar/index.tsx` ?

2022-11-15 18:51 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
> +    canShowTooltip = !!authUser?.agendaPhoneNumberHashes?.includes(
just check if phoneNumber is not empty

2022-11-15 18:52 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
> +  if (userExist && !isOwner && user.phoneNumberHash) {
!isOwner is not needed, cuz u dont care

2022-11-16 11:27 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/AvatarHeader/index.tsx
> +                    allowFullScreen={isOwner}
@ice-ares  Why true? In case I will set it true here, when you open another user profile and will click on avatar -> tooltip will not be shown, the photo avatar will be opened full screen. I suppose that's not what we need

2022-11-16 11:36 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/AvatarHeader/index.tsx
> +          {user && !isOwner && (
Replaced with user.phoneNumber check (according to previous comment)

2022-11-16 11:39 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/UserInfoTooltip/index.tsx
> +        <TooltipAvatar
Not sure I understood the question..
UserInfoTooltip is this thing (and the avatar with letters inside is TooltipAvatar)
<img width="455" alt="Screenshot 2022-11-16 at 13 38 21" src="https://user-images.githubusercontent.com/96414297/202170971-2fc4c1f6-ebff-4c1c-b320-8cc70f0d6fdf.png">

2022-11-16 11:42 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +    canShowTooltip = !!authUser?.agendaPhoneNumberHashes?.includes(
Should I do something with !isOwner check here?
Like right now for our own profile we not showing the tooltip. Is that correct, right?

2022-11-16 11:43 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +    canShowTooltip = !!authUser?.agendaPhoneNumberHashes?.includes(
So condition will look like this 

`  let canShowTooltip = userExist && !isOwner && user.phoneNumber;`

2022-11-16 13:38 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/UserInfoTooltip/index.tsx
> +        <TooltipAvatar
then name it AgendaContactTooltip, as for TooltipAvatar, the avatar has nothing to do with that [AB] element as we discussed on slack

2022-11-16 17:58 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/AvatarHeader/index.tsx
> +                    allowFullScreen={isOwner}
Fixed

2022-11-16 17:59 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +    canShowTooltip = !!authUser?.agendaPhoneNumberHashes?.includes(
Fixed

2022-11-16 18:06 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/UserInfoTooltip/index.tsx
> +        <TooltipAvatar
I kept TooltipAvatar because what we have in ContactItem has a different content structure

2022-11-16 18:08 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/UserInfoTooltip/index.tsx
> +        <TooltipAvatar
The avatar does not have any tooltip, rename/move it

2022-11-16 18:29 UTC, ice-ares requested changes

2022-11-16 18:29 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/AgendaContactTooltip/index.tsx
> +  const fullName = `${contact?.givenName?.trim() || ''} ${
Trim fullname

2022-11-16 18:29 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/AgendaContactTooltip/index.tsx
> +        <TooltipAvatar
Has nothing to do with the avatar

2022-11-16 18:29 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/AgendaContactTooltip/index.tsx
> +          textStyle={styles.avatarText}
Nothing to do with the avatar

2022-11-16 18:29 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/components/AgendaContactTooltip/index.tsx
> +          {contact.phoneNumbers[0]?.number || ''}
Lets add all of em, separated by /n

2022-11-16 18:29 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
> +            const normalizedNumber = e164PhoneNumber(
If the phone is already e164, that function return it as is, right?

2022-11-16 18:29 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
> +        console.log(userContactDetails);
Huh?

2022-11-16 18:29 UTC, ice-ares commented on src/screens/ProfileFlow/Profile/index.tsx
> +      const userContactDetails = contacts.find(contact => {
find returns first one right?

2022-11-16 20:41 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +      const userContactDetails = contacts.find(contact => {
yes

2022-11-16 20:43 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/AgendaContactTooltip/index.tsx
> +        <TooltipAvatar
Renamed to ContactAvatar

2022-11-16 20:43 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/AgendaContactTooltip/index.tsx
> +          textStyle={styles.avatarText}
Renamed to ContactAvatar

2022-11-16 20:44 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +        console.log(userContactDetails);
Removed

2022-11-16 22:16 UTC, ice-ares commented on src/components/ContactAvatar/index.tsx
> +                contact.givenName || contact.phoneNumbers[0].number,
given, or family or phone

2022-11-17 09:28 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/index.tsx
> +            const normalizedNumber = e164PhoneNumber(
Yeah it returns the same I just rechecked

2022-11-17 09:58 UTC, ice-hector commented on src/screens/ProfileFlow/Profile/components/AgendaContactTooltip/index.tsx
> +          {contact.phoneNumbers[0]?.number || ''}
Done

2022-11-17 10:39 UTC, ice-minos commented on ios/Podfile
> +        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
@ice-orion asked me to remove these lines in my Pull Request, so maybe we need to do it here too.
https://github.com/ice-blockchain/mobile-app/pull/76#discussion_r1017781638

2022-11-17 10:43 UTC, ice-hector commented on ios/Podfile
> +        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
@ice-ares what do you think? Until we update to react-native 0.70.3 this issue blocks us from building the code locally to real devices which I use for testing

2022-11-17 11:23 UTC, ice-ares commented on ios/Podfile
> +        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
update to latest version

2022-11-17 11:26 UTC, ice-hector commented on ios/Podfile
> +        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
I think that's not the case right now, migration will take time and can cause other problems not related to PR at all. 
These three lines affect nothing, just fix the problems related to building on real device

2022-11-17 11:36 UTC, merged

2022-11-17 11:39 UTC, ice-minos approved these changes