translation types
ice-blockchain/mobile-app pull request #89
Opened 2022-12-23 07:20 UTC by ice-orion

2022-12-23 12:02 UTC, ice-atlas requested changes

2022-12-23 12:02 UTC, ice-atlas commented on src/translations/i18n.ts
> +>(tag: T, options: S = {}) {
let's keep name as everyone know it. `key` and `options`. So `tag` -> `key`, `T` -> `K`, `S` -> `O`

2022-12-23 12:11 UTC, ice-ares requested changes
revert the license.header change. That file has to stay at project root

2022-12-23 12:11 UTC, ice-ares commented on src/translations/i18n.ts
> +  // @ts-ignore TODO::fix warning
fix it

2022-12-23 12:11 UTC, ice-ares commented on scripts/generateTranslationTypes/utils/getParamsFromString.mjs
> +  return [...input.matchAll(/{{(.*?)}}/g)].map(match => match[1]);
be more strict, allow atleast 1 letter, and only alphanumerics

2022-12-23 12:31 UTC, ice-atlas commented
@ice-ares 
> revert the license.header change. That file has to stay at project root

Maybe better use `LICENSE` file for this and leave `license.header` as is now?

2022-12-23 12:33 UTC, ice-ares commented
no, both license and license header have to be at project root

> @ice-ares 
> 
> > revert the license.header change. That file has to stay at project root
> 
> 
> 
> Maybe better use `LICENSE` file for this and leave `license.header` as is now?

2022-12-26 09:11 UTC, ice-orion commented on package.json
> +    "check-license": "./scripts/checkLicense/checklicense.sh",
done

2022-12-26 09:11 UTC, ice-orion commented on scripts/run-e2e-android-release.sh
> -yarn start &
done

2022-12-26 09:11 UTC, ice-orion commented on scripts/run-e2e-ios-release.sh
> -yarn start &
done

2022-12-26 09:12 UTC, ice-orion commented on src/screens/InviteFlow/InviteShare/components/ShareButton/index.tsx
> +  title: keyof Translations;
done

2022-12-26 09:12 UTC, ice-orion commented on src/translations/i18n.ts
> +>(tag: T, options: S = {}) {
done

2022-12-26 09:12 UTC, ice-orion commented on scripts/generateTranslationTypes/utils/getParamsFromString.mjs
> +  return [...input.matchAll(/{{(.*?)}}/g)].map(match => match[1]);
done

2022-12-26 13:25 UTC, ice-orion commented on src/translations/i18n.ts
> +  // @ts-ignore TODO::fix warning
done

2022-12-26 13:33 UTC, ice-ares approved these changes

2022-12-28 08:22 UTC, ice-ares approved these changes

2022-12-28 08:30 UTC, ice-hector commented on src/services/auth/signin/apple.ts
> +            t('errors.unknown_error_with_code', {code: error.code as string}),
Can we avoid force type casting here?

2022-12-28 08:34 UTC, ice-hector commented on src/services/auth/signin/google.ts
> +            t('errors.unknown_error_with_code', {code: error.code as string}),
Same here

2022-12-28 08:38 UTC, ice-orion commented on src/services/auth/signin/apple.ts
> +            t('errors.unknown_error_with_code', {code: error.code as string}),
Yea, we actually can convert it to string, fixed

2022-12-28 08:39 UTC, ice-orion commented on src/services/auth/signin/google.ts
> +            t('errors.unknown_error_with_code', {code: error.code as string}),
fixed

2022-12-28 08:41 UTC, ice-hector approved these changes

2022-12-28 09:43 UTC, merged