feat: news and team walkthroughs
ice-blockchain/mobile-app pull request #90
Opened 2022-12-23 12:42 UTC by ice-hades

2022-12-23 13:20 UTC, ice-ares commented on src/api/user/types.ts
> -export type WalkthroughElement = {
walkthrough is a word, not an expression. so u don’t camel case it

2022-12-23 13:21 UTC, ice-ares commented on src/api/user/types.ts
> +  type: WalkThroughType;
i would put step here

2022-12-23 13:21 UTC, ice-ares commented on src/api/user/types.ts
> -  walkthroughProgress?: WalkthroughElement[];
i would make the

2022-12-23 13:22 UTC, ice-ares commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
i would make the type as key and the value either an array of that, or a map of step:version

2022-12-23 13:23 UTC, ice-ares commented on src/contexts/WalkThroughContext.tsx
> +  top: number;
whats this?

2022-12-23 13:24 UTC, ice-hades commented on src/api/user/types.ts
> -export type WalkthroughElement = {
My IDE underlines it

2022-12-23 13:25 UTC, ice-ares commented on src/screens/News/FeaturedPost.tsx
> +        stepData: {
add the versions in const at the top of the file, per step preferably

2022-12-23 13:28 UTC, ice-ares commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      AccountActions.UPDATE_ACCOUNT.START.create({
rollback

2022-12-23 13:33 UTC, ice-hades commented on src/contexts/WalkThroughContext.tsx
> +  top: number;
top is a position of the highlighted element for each step. based on it we render the  highlighted itself and calculate the position of the circle with the text. above or below it based where there are more space

2022-12-23 13:33 UTC, ice-hades commented on src/screens/News/FeaturedPost.tsx
> +        stepData: {
Cool

2022-12-23 13:34 UTC, ice-hades commented on src/api/user/types.ts
> +  type: WalkThroughType;
You want me to remember also last shown step so if a user closes the walkthrough in the progress next will we will show from the next step?

2022-12-23 13:35 UTC, ice-ares commented on src/screens/Team/components/TierList/index.tsx
> +    const addSteps = referralType === 'T1';
do that based on the pinged flag being not null and not undefined

2022-12-23 13:37 UTC, ice-hades commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      AccountActions.UPDATE_ACCOUNT.START.create({
I knew you guys would pick up on this. But let's discuss it. At runtime it causes a error like this
`A non-serializable value was detected in an action, in the path: `payload.raceConditionStrategy`. Value: [Function anonymous] 
Take a look at the logic that dispatched this action:  {"id": undefined, "payload": {"raceConditionStrategy": [Function anonymous], "userInfo": {"clientData": [Object]}}, "type": "UPDATE_ACCOUNT -> START"} 
(See https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants) 
(To allow non-serializable values see: https://redux-toolkit.js.org/usage/usage-guide#working-with-non-serializable-data)`
looks like we are not supposed to pass functions in there. It is not a crash but still. It is a hack what we use here.
If we need that logic probably need to come up with some other approach to retry.
Or do we leave it like this?

cc: @ice-orion

2022-12-23 13:37 UTC, ice-ares commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +        AccountActions.UPDATE_ACCOUNT.START.create({
rollback

2022-12-23 13:37 UTC, ice-ares commented on src/screens/WelcomeFlow/IceBonus/hooks/useIceBonus.ts
> -        AccountActions.UPDATE_ACCOUNT.START.create(
rollback

2022-12-23 13:38 UTC, ice-ares commented on src/screens/WelcomeFlow/Onboarding/hooks/useFinishOnboarding.ts
> -          {
rollback

2022-12-23 13:38 UTC, ice-ares commented on src/screens/WelcomeFlow/WhoInvitedYou/hooks/useWhoInvitedYou.ts
> -                ...finalizedSteps,
rollback

2022-12-23 13:38 UTC, ice-ares commented on src/store/modules/Account/actions/index.ts
> -  START: (
rollback

2022-12-23 13:38 UTC, ice-ares commented on src/store/modules/Account/sagas/updateAccount.ts
> -      const {retry} = yield action.payload.raceConditionStrategy(freshUser);
rollback

2022-12-23 13:39 UTC, ice-ares commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> -        AccountActions.UPDATE_ACCOUNT.START.create(
rollback

2022-12-23 13:39 UTC, ice-ares commented on src/store/modules/Validation/sagas/validateEmailSaga.ts
> -      AccountActions.UPDATE_ACCOUNT.START.create(
rollback

2022-12-23 13:40 UTC, ice-ares commented on src/screens/WalkThrough/WalkThrough.tsx
> +                            {t('news.read_more')}
that is very specific. this file is meant to be generic

2022-12-23 13:40 UTC, ice-hades commented on src/screens/Team/components/TierList/index.tsx
> +    const addSteps = referralType === 'T1';
what do you mean? Like now I use the first data element `referrals[0].pinged` but should chose one with not null pinged flag?

2022-12-23 13:42 UTC, ice-hades commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +        AccountActions.UPDATE_ACCOUNT.START.create({
https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056348891

2022-12-23 13:42 UTC, ice-hades commented on src/screens/WelcomeFlow/IceBonus/hooks/useIceBonus.ts
> -        AccountActions.UPDATE_ACCOUNT.START.create(
https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056348891

2022-12-23 13:42 UTC, ice-hades commented on src/screens/WelcomeFlow/Onboarding/hooks/useFinishOnboarding.ts
> -          {
https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056348891

2022-12-23 13:42 UTC, ice-hades commented on src/screens/WelcomeFlow/WhoInvitedYou/hooks/useWhoInvitedYou.ts
> -                ...finalizedSteps,
https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056348891

2022-12-23 13:42 UTC, ice-hades commented on src/store/modules/Account/actions/index.ts
> -  START: (
https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056348891

2022-12-23 13:42 UTC, ice-hades commented on src/store/modules/Account/sagas/updateAccount.ts
> -      const {retry} = yield action.payload.raceConditionStrategy(freshUser);
https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056348891

2022-12-23 13:42 UTC, ice-hades commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> -        AccountActions.UPDATE_ACCOUNT.START.create(
https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056348891

2022-12-23 13:42 UTC, ice-hades commented on src/store/modules/Validation/sagas/validateEmailSaga.ts
> -      AccountActions.UPDATE_ACCOUNT.START.create(
https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056348891

2022-12-23 13:43 UTC, ice-ares commented on src/screens/WalkThrough/WalkThrough.tsx
> +        AccountActions.UPDATE_ACCOUNT.START.create({
implement the retry strategy as well

2022-12-23 13:43 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +                            {t('news.read_more')}
which file? it is a translation for `Read More` text not a link. Link is generic and can be configured for every step

2022-12-23 13:44 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +        AccountActions.UPDATE_ACCOUNT.START.create({
let's discuss it https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056348891

2022-12-23 13:45 UTC, ice-ares commented on src/screens/WalkThrough/WalkThrough.tsx
> +        setStep((s: number) => s + 1);
why? this else would imply that the versions are equal, cuz u cant downgrade the version

2022-12-23 13:47 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +        setStep((s: number) => s + 1);
If version are even means we saw that step. mean we don't show it again

2022-12-23 13:48 UTC, ice-ares commented on src/screens/WalkThrough/WalkThrough.tsx
> +    setVersion((v: number) => Math.max(v, stepDataCandidate.version));
u always get the one hardcoded, cuz u can’t downgrade versions

2022-12-23 13:48 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +        setStep((s: number) => s + 1);
here I iterate through steps and show only those with version greater. like new steps or updated steps. like we discussed yesterday

2022-12-23 13:50 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +    setVersion((v: number) => Math.max(v, stepDataCandidate.version));
yep. but hardcoded can be different for different steps. we can upgrade only few

2022-12-23 13:50 UTC, ice-ares commented on src/screens/WalkThrough/WalkThrough.tsx
> +                            {t('news.read_more')}
this file im commenting on is generic, that transition key is specific

2022-12-23 13:51 UTC, ice-ares commented on src/screens/Team/components/TierList/index.tsx
> +    const addSteps = referralType === 'T1';
yes, if the flag is true or false u display that icon, and the walkthrough for it

2022-12-23 13:52 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +                            {t('news.read_more')}
yeah, file is generic. we show that read more only if there is a link for that specific step. which is generic, right? Or you mean the text can be different, not only `Read More` to click on the link?

2022-12-23 13:52 UTC, ice-ares commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      AccountActions.UPDATE_ACCOUNT.START.create({
we definitely need that logic, but if the current implementation is not the best, we should find the best/optimal one and implement that

2022-12-23 13:53 UTC, ice-ares commented on src/contexts/WalkThroughContext.tsx
> +  top: number;
then rename it to be more descriptive

2022-12-23 13:54 UTC, ice-ares commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
u can change it to be whatever you need. You dont have to keep it as is, you can change it entirely if you want.

that type was just the initial idea

2022-12-23 13:54 UTC, ice-hades commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      AccountActions.UPDATE_ACCOUNT.START.create({
I can revert those removals and we can add it to the tech debt and work on it separately

2022-12-23 13:55 UTC, ice-ares commented on src/api/user/types.ts
> -export type WalkthroughElement = {
i guess u can mark it as false negative in ur IDE

2022-12-23 13:56 UTC, ice-hades commented on src/screens/Team/components/TierList/index.tsx
> +    const addSteps = referralType === 'T1';
What if there are no such data rows. or it is out of current view port. For the walkthrough case that should be enough. If it is part of the dynamic data it is hard to pinpoint it and highlight in walkthrough

2022-12-23 13:57 UTC, ice-ares commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
i would see that progress field as a map[walkthroughType] : map[step]version

2022-12-23 13:58 UTC, ice-ares commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
oh, and btw, when the user skips 1..N steps, you should add those steps in that progress still

2022-12-23 13:59 UTC, ice-ares commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      AccountActions.UPDATE_ACCOUNT.START.create({
sure

2022-12-23 13:59 UTC, ice-ares commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      AccountActions.UPDATE_ACCOUNT.START.create({
add it in that notion page we have for tech debt pls

2022-12-23 14:00 UTC, ice-ares commented on src/screens/Team/components/TierList/index.tsx
> +    const addSteps = referralType === 'T1';
thats a question for the business

2022-12-23 14:00 UTC, ice-hades commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
that way we can version each step independently. I don't think we need it. Latest version should be one for all steps. Like we can update only few step not all of them. But every time we update the latest version is one. So I like the current structure. I would only add a field `lastDisplayedStep` to track that and to continue showing the walkthrough from that step

2022-12-23 14:01 UTC, ice-ares commented on src/screens/WalkThrough/WalkThrough.tsx
> +                            {t('news.read_more')}
everything can be different. I would pass that translator key as arg

2022-12-23 14:03 UTC, ice-ares commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
nope, each step can have different versions. We can choose to replace a step, or add a new one in the middle(which would force all steps after that to be redispolayed)

2022-12-23 14:06 UTC, ice-ares commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
we don’t need that lastDisplayedStep, cuz we’ll redisplay either only 1 step (if the version changed for that step) or that step & all others after it if the number of steps changed

2022-12-23 15:34 UTC, ice-ares commented on src/screens/Team/components/TierList/index.tsx
> +    const addSteps = referralType === 'T1';
Actually, for this particular case, u'll be fine, cuz there will always be atleast 1 row that has that ping button

2022-12-23 15:36 UTC, ice-ares commented on src/screens/Team/components/TierList/index.tsx
> +    const addSteps = referralType === 'T1';
So all u have to do is look for the first element that has that pinged flag true/false (regardless if its the t1 or t2 tab) and display that walkthrough

2022-12-25 06:05 UTC, ice-hades commented on src/api/user/types.ts
> -export type WalkthroughElement = {
Oxford dictionary says it is a two words as a noun and one as an adjective
<img width="650" alt="Screenshot 2022-12-25 at 09 04 02" src="https://user-images.githubusercontent.com/119406114/209458525-9985fb9c-3059-490d-98fb-68d0f491bfb5.png">

2022-12-25 06:24 UTC, ice-hades commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
Ok. If we don't need lastDisplayedStep we don't need to change anything here then. Versioning is happening on the app side. We don't need to keep per step versions in the user data. For example, let's say we decided to update one step and to add one new step. Let's take a user who saw existing walkthrough. In his `walkTroughProgress` data he would have version 1. For the new step and for the updated one we set the version 2 on the app side. The user would see those 2 steps next time bases on the algorithm and get version 2 in his `walkTroughProgress`. Next time we want to update/add steps we assign them version 3. If there is independent versioning for each step - it would work as well until we decide to add a new step in the middle.   Let's say we have 9 steps as now. All of them have version 1. We add a new step at position 5. We can assign it version 2 so it will be picked up. But our 9 step moves to position 10. And it will be shown as well because we don't have a record for step 12 in the user data.

2022-12-25 06:25 UTC, ice-hades commented on src/contexts/WalkThroughContext.tsx
> +  top: number;
Ok. Will rename to `topPositionOfHighlightedElement`

2022-12-25 06:26 UTC, ice-hades commented on src/screens/News/FeaturedPost.tsx
> +        stepData: {
I even will put them all in one place so it will be easier to see what is the current max version to increase it in case of updates

2022-12-25 06:30 UTC, ice-hades commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      AccountActions.UPDATE_ACCOUNT.START.create({
Added here https://www.notion.so/leftclick/Tech-debt-2a7217b55d77440e8755e239dd21e410

2022-12-25 06:38 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +                            {t('news.read_more')}
I checked the Home walkthroughs and it doesn't have any `Read More` link. So among all walkthroughs we have only 2 with `Read More` and it is 'news.read_more' translator. In current situation does it make sense to add an extra argument?

2022-12-25 10:27 UTC, ice-ares commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
Sure, but please test all the possibilities to be sure

2022-12-25 10:29 UTC, ice-ares commented on src/screens/WalkThrough/WalkThrough.tsx
> +                            {t('news.read_more')}
Yep, it always makes sense to not couple things unnecessarily

2022-12-26 05:58 UTC, ice-orion commented on src/screens/PopUps/ProfilePrivacyEdit/hooks/useUpdateHiddenProfileElements.ts
> +      AccountActions.UPDATE_ACCOUNT.START.create({
In the warning itself there is a link to our problem - https://redux-toolkit.js.org/usage/usage-guide#working-with-non-serializable-data

> However, like most rules, there are exceptions. There may be occasions when you have to deal with actions that need to accept non-serializable data. This should be done very rarely and only if necessary, and these non-serializable payloads shouldn't ever make it into your application state through a reducer.

So this is our case (we don't save it into our application state through a reducer). So the solution is to configure [serializability dev check middleware](https://redux-toolkit.js.org/api/serializabilityMiddleware) as they suggest

2022-12-26 08:12 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +  const onNext = useCallback(() => {
What's the point of using `useCallback` for all these handlers? I mean `onNext`, `onFinalise`, `onFinalise`, etc?

2022-12-26 08:12 UTC, ice-orion commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
> +  const renderAllowContactButton = useCallback(() => {
Here is an example of how we could make the code more readable - 
1. Create a separate component for `AllowContactButton` -> move the markdown of the button + related styles to a separate place
2. Move everything related to the walkthrough to a hook + reuse `AllowContactButton` component there as well 

As a result we would have small and readable pieces of UI

2022-12-26 08:12 UTC, ice-orion commented on src/screens/News/FeaturedPost.tsx
> +  const onLayout = useCallback(({nativeEvent}: LayoutChangeEvent) => {
there is no point to use `useCallback` if you don't use the function with a pure component / as a dependency

2022-12-26 08:29 UTC, ice-orion commented on src/contexts/WalkThroughContext.tsx
> +export const WalkThroughContext = React.createContext<WalkThroughContextType>(
Is it a good idea to use Context directly since we have Redux? Redux has everything the same + a lot more (it even uses Context under the hood) + we're keeping all the business logic in the sagas, so probably it would be better to use redux to keep the data (since we're using it in the app) and place the steps calculation / other logic in the sagas instead of the `WalkThrough` component?

2022-12-26 09:37 UTC, ice-hades commented on src/components/Labels/FormattedNumber/index.tsx
> +  const dynamicStyles = useMemo(
Funny, I got this approach from your SegmentedControl. You pass style prop and construct dynamicStyles

2022-12-26 09:41 UTC, ice-orion commented on src/components/Labels/FormattedNumber/index.tsx
> +  const dynamicStyles = useMemo(
Yea, but the big difference there is that i don't pass any additional props to do that - i construct dynamicStyles based on `segments` prop (the actual data) that i have to pass anyway

2022-12-26 09:49 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
You didn't notice but we actually don't render it most of the time. We render it only when we need to show the walkthroughs. Makes sense, right?
` if (isFinished || !stepData) {
    return null;
  }`
  And if you don't know the difference between portal and react navigation modals. I can demonstrate on the example of our walkthroughs for privacy which uses react navigation modals
  

https://user-images.githubusercontent.com/119406114/209534285-4d34e7f8-5fe4-49f7-b2d2-0b4a45f55d54.mp4

2022-12-26 09:50 UTC, ice-hades commented on src/api/user/types.ts
> +  walkTroughProgress?: {[key: string]: WalkThroughElement};
done

2022-12-26 09:50 UTC, ice-hades commented on src/contexts/WalkThroughContext.tsx
> +  top: number;
done

2022-12-26 09:50 UTC, ice-hades commented on src/screens/News/FeaturedPost.tsx
> +        stepData: {
done

2022-12-26 09:51 UTC, ice-hades commented on src/screens/Team/components/TierList/index.tsx
> +    const addSteps = referralType === 'T1';
done

2022-12-26 09:51 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +                            {t('news.read_more')}
done

2022-12-26 09:57 UTC, ice-hades commented on src/components/Labels/FormattedNumber/index.tsx
> +  const dynamicStyles = useMemo(
The big difference. I see. But let's imagine the situation when we have to pass that dynamic color style from many places. Like 2 is enough to have duplication on the side which uses that FormattedNumber. We will have to construct that same dynamicStyle from many places. Which is bad because that is code duplication. And also it shifts concerns. We as a component users should not care about constructing dynamic styles through useMemo. It should be done on the lowest  level and in single place. What if we decide not to use useMemo in the future we will have to refactor the code in many places instead of one.

2022-12-26 09:58 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
Every time i open the team tab, the `Walkthrough` component gets rendered even tho i don't see the actual Walkthrough, so where is the `if (isFinished || !stepData) { return null; }` ?

> And if you don't know the difference between portal and react navigation modals. I can demonstrate on the example of our walkthroughs for privacy which uses react navigation modals

I know the difference, so what's your point? What i should have noticed on the video?

2022-12-26 10:06 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
Because react navigation modals don't render on top of the bottom navigation there are multiple UI issues.

And I will check if it renders every time. Like you passed the walkthrough and it still renders for you?

2022-12-26 10:06 UTC, ice-orion commented on src/components/Labels/FormattedNumber/index.tsx
> +  const dynamicStyles = useMemo(
Initial point was to get rid of adding extra props for specific use cases because you can achieve that without initial component modification. This is `Open-Closed Principle` from SOLID. And yes, this is a big difference in this case because in case of SegmentedControl you don't violate this rule - you don't modificate entity for specific use case.
As for imagining situations - let's imagine that we also need to specify fontSize? Should we add a separate prop for that? What about `fontWeight`? Other 20+ styles? We currently have 11 usages of this component and the need of passing color dynamically is only here.

2022-12-26 10:11 UTC, ice-hades commented on src/components/Labels/FormattedNumber/index.tsx
> +  const dynamicStyles = useMemo(
I won't make changes which might force to do the code duplication. Yes, if we need 20 dynamic style variables we declare them all and inside FormattedNumber we construct one dynamic style out of them. It makes very big sense to me

2022-12-26 10:15 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
I will check but I am very sceptical about your numbers. Like 1 second to render? Such numbers should surely be visible without any profiling but I didn't see any delays in rendering

2022-12-26 10:19 UTC, ice-orion commented on src/components/Labels/FormattedNumber/index.tsx
> +  const dynamicStyles = useMemo(
This is a premature optimization - only 1 case of 11 where you need to pass a color (actually it seems that you don't even need to). Moreover you slow down the component rendering in all other cases where you don' need this prop but force it to use `useMemo` + `StyleSheet.create` fro no need.

2022-12-26 10:21 UTC, ice-hades commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
> +  const renderAllowContactButton = useCallback(() => {
The code doesn't get any smaller. You just move it around. It actually blows because you need to duplicate many dependencies. It doesn't get any more readable as well. You need to jump between file to get the whole picture. Good readable code isn't about splitting files into more smaller ones.
There is a feature in IDE which allows you to collapse all such sections by default. So when you open the file all such sections are collapsed and you can expand them when you need

2022-12-26 10:23 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
As for the walkthroughs for privacy - this is just a bug and you could fix it pretty easily, by moving the `ProfilePrivacyEditStep1` screen from the ProfileStack to the MainStack (MainStack is a parent for the tabbar, so the screen would be on top of it). Here is the result:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/102020833/209537853-93094a59-73eb-4f8b-8f78-3485e56e338d.png">

2022-12-26 10:28 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
The point is that the render becomes twice slower comparing to the react-native-modal approach. In the release build the numbers will be surely much smaller, but the main idea is that on slow devices the UI with the walkthrough components will be twice less responsible.

2022-12-26 10:41 UTC, ice-orion commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
> +  const renderAllowContactButton = useCallback(() => {
To get the whole picture, you want to open a file and briefly understand it - that's why it should be as small as possible. 
If you want to see the details of some piece  - you can open a child component / hook (that should have only one responsibility).
Without splitting you have those components that do everything at once that complicates the understanding and maintenance (and testing, but we don't have those so don't matter).
Anyway that is up to developer since we don't have that lint-rule for restricting the file length.

2022-12-26 11:07 UTC, ice-ares commented on src/components/Labels/FormattedNumber/index.tsx
> +  const dynamicStyles = useMemo(
Decoupling is alot better than avoiding code duplication.

2022-12-26 12:24 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
@ice-orion please provide a PR for that fix

2022-12-26 13:51 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
sure, https://github.com/ice-blockchain/mobile-app/pull/91

2022-12-27 04:12 UTC, ice-hades commented on src/components/Labels/FormattedNumber/index.tsx
> +  const dynamicStyles = useMemo(
ok. fixed

2022-12-27 04:25 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
@ice-orion just checked and it renders null when there is no walkthrough to show
` if (isFinished || !stepData) {
    return null;
  }`
  
If it is not rendered when there are no walkthrough to show I think we can close that thread.
I think it is a more clear architecture for that feature with Portal and RN context usage.

You can see here there are no delays even when walkthrough is rendered. It is an old android device debug build - https://frameyapp.slack.com/archives/C0391DUR5GD/p1671802230608369?thread_ts=1671802187.535629&cid=C0391DUR5GD

2022-12-27 04:26 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +export function WalkThrough({walkThroughType, numberOfSteps}: Props) {
Ok. Will try to extract some hooks

2022-12-27 04:29 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
> Every time i open the team tab, the `Walkthrough` component gets rendered even tho i don't see the actual Walkthrough, so where is the `if (isFinished || !stepData) { return null; }` ?
> 
> > And if you don't know the difference between portal and react navigation modals. I can demonstrate on the example of our walkthroughs for privacy which uses react navigation modals
> 
> I know the difference, so what's your point? What i should have noticed on the video?

Walkthrough is a function. It is called but nothing is rendered as a result of its execution. Nothing but a null when there is no walkthrough to show

2022-12-27 04:31 UTC, ice-hades commented on src/contexts/WalkThroughContext.tsx
> +  icon?: React.ReactNode;
I would rather not waste my time on this. I don't see any value in this

2022-12-27 04:34 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
As I stated in the thread above when there are no walkthroughs to show Portal is not rendered inside WalkThrough component. When there are walkthroughs to show it is natural rendering will take more time because there is an overlaying new layer. Which case did you measure?

2022-12-27 04:37 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +  const onNext = useCallback(() => {
I use useCallback in all cases. You can try to prove me in tons on text it doesn't provide any benefit or even maybe for worse. But can you prove it by some test or experiment? If that matter is so important to you I think we should come up with a test case which should reveal the truth once and for all. Like a list with hundreds on rows each  of the row has dozens on callbacks. And properly measure it for memory and CPU usage

2022-12-27 06:26 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +  const onNext = useCallback(() => {
What about a common sense?
There is a plain js function vs there is a hook that creates exactly the same plain js function plus keeps additional state inside and do additional work on every render.
And you decide to choose the hook... Why? Just because you are used to? Ok, keep using, i was thinking CR is to detect the code flaws

2022-12-27 06:27 UTC, ice-orion commented on src/contexts/WalkThroughContext.tsx
> +  icon?: React.ReactNode;
ok, as you say

2022-12-27 06:27 UTC, ice-hades commented on src/components/Labels/FormattedNumber/index.tsx
> +  const dynamicStyles = useMemo(
done

2022-12-27 06:28 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +export function WalkThrough({walkThroughType, numberOfSteps}: Props) {
done

2022-12-27 06:46 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
Yea, the function actually returns null if the walkthrough is finished. But still this function get's executed 14 times (??) only when i open the tab. And this function itself contains pile of hooks, useEffect-s that are executed and so on. So that's why even tho the function do nothing (renders nothing), it still slows down the main screen by half (i measured once again, the code above 600ms -> 1100ms). 
So to summ up:
* This approach with portal brings extra 3rd party lib as dependency
* We already have the similar screens but implemented differently (via modals)
* This approach with portals much worse in terms of the app performance (no matter if the walkthrough is finished or not)
* We're using redux everywhere in the app but this is the only feature that is implemented with Context 

If you still think that all of this doesn't really matter then ok, close the thread

2022-12-27 06:47 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +  const onNext = useCallback(() => {
I get that it looks like a flaw to you. But my point can you prove it?
There should be some validation to CR comments as well. Like something indisputable or something that provides some value. Like for example you found a bug, or mismatch to a design, or typo, or it is visually slow. Not just moving code around based on someones vision. What value does it provide to our users, to us as a team, to our product?
Or we can end up just wasting our time instead of making our product better.

I like that you do the CR very thoroughly.  That is very good for the product. I wish every team to have such a reviewer. I just want for us all to validate the comments for a value the requested change will provide. So we don't waste our time and put more effort in improving our product in the areas it really needs.

About `useCallback`. Really, we better create a test case to check instead of referencing some articles. But it will take time to create one

2022-12-27 06:47 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
Answered above - i measured the case when `null` is returned, it still takes a lot to execute the function

2022-12-27 06:48 UTC, ice-hades commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
> +  const renderAllowContactButton = useCallback(() => {
done

2022-12-27 06:48 UTC, ice-hades commented on src/screens/News/FeaturedPost.tsx
> +  const onLayout = useCallback(({nativeEvent}: LayoutChangeEvent) => {
done

2022-12-27 07:10 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
> This approach with portals much worse in terms of the app performance (no matter if the walkthrough is finished or not)
Why is the Portal is still a culprit if it is not even rendered? There are rerenders inside WalkThrough function because new steps are added. And not all hooks and effects are executed as you say on each rerender. Like non of them.
> We already have the similar screens but implemented differently (via modals)
To my opinion those better to refactor to be aligned with new walkthroughs. Because a new screen for every walkthrough step is a poor decision.
> We're using redux everywhere in the app but this is the only feature that is implemented with Context
Context is better suited tool in that case. If we use redux here it will be like using a screwdriver for nailing instead of using a hammer just because we already use it.

About your measurements, maybe we can have a call and you will teach me.

2022-12-27 07:43 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +  const onNext = useCallback(() => {
It looks like a flaw to me just because this:
```
const onSkippAll = () => {
    onFinalise(true);
};
```

Does exactly the same as this (more sophisticated and slow)
```
const onSkippAll = useCallback(() => {
    onFinalise(true);
}, [onFinalise]);
```

Latter has an extra layer of wrapping that is useful only when you pass this function to a pure component / use as dependency.
<img width="804" alt="image" src="https://user-images.githubusercontent.com/102020833/209629795-a0a8a436-8236-4ab3-a08b-9ed361e5aefe.png">

 So it's not my personal vision, this is just a misuse of the hook.
 > What value does it provide to our users
 App is faster / consumes less memory
> to us as a team
code is more readable 

And there is no any arguments to use `useCallback` here except that you don't want to "waste" time

2022-12-27 07:44 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
@ice-orion I made my measurements as well.
I isolated the Team tab content in the profiler to see how Walkthrough affects its rendering.

`<WalkThroughContextProvider>
      <Profiler
        id="Team"
        onRender={(
          id, // the "id" prop of the Profiler tree that has just committed
          phase, // either "mount" (if the tree just mounted) or "update" (if it re-rendered)
          actualDuration, // time spent rendering the committed update
          baseDuration, // estimated time to render the entire subtree without memoization
          startTime, // when React began rendering this update
          commitTime, // when React committed this update
          interactions, // the Set of interactions belonging to this update
        ) => {
          console.log('Profiler', {
            id,
            phase,
            actualDuration,
            baseDuration,
            startTime,
            commitTime,
            interactions,
          });
        }}>
        <View style={styles.container}>
          <LinesBackground />
          <Header
            isSearchActive={isSearchActive}
            setIsSearchActive={setIsSearchActive}
          />
          <DynamicHeight isSearchActive={isSearchActive}>
            <SegmentedContent />
            {isSearchActive && <SearchResults />}
          </DynamicHeight>
        </View>
      </Profiler>
      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
    </WalkThroughContextProvider>`

And got the data
` LOG  Profiler {"actualDuration": 476.71022295951843, "baseDuration": 284.2845196723938, "commitTime": 1354570670.753354, "id": "Team", "interactions": undefined, "phase": "mount", "startTime": 1354570127.582816}
 LOG  Profiler {"actualDuration": 76.71094417572021, "baseDuration": 178.97495436668396, "commitTime": 1354570917.909815, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354570830.8102}
 LOG  Profiler {"actualDuration": 5.916882038116455, "baseDuration": 167.6547932624817, "commitTime": 1354571036.495123, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571027.879123}
 LOG  Profiler {"actualDuration": 8.308648824691772, "baseDuration": 169.62929892539978, "commitTime": 1354571066.796815, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571051.069276}
 LOG  Profiler {"actualDuration": 100.9060230255127, "baseDuration": 191.26912188529968, "commitTime": 1354571188.746853, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571076.855392}
 LOG  Profiler {"actualDuration": 48.68658208847046, "baseDuration": 188.54696822166443, "commitTime": 1354571346.949969, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571292.592892}
 LOG  Profiler {"actualDuration": 96.76318430900574, "baseDuration": 187.521497964859, "commitTime": 1354571475.58243, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571368.611199}
 LOG  Profiler {"actualDuration": 0.777003288269043, "baseDuration": 187.46907591819763, "commitTime": 1354571525.838622, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571521.576776}
 LOG  Profiler {"actualDuration": 0.7552728652954102, "baseDuration": 187.40880823135376, "commitTime": 1354571536.843315, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571532.627315}
 LOG  Profiler {"actualDuration": 0.8099610805511475, "baseDuration": 187.43346309661865, "commitTime": 1354571550.698161, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571546.396238}
 LOG  Profiler {"actualDuration": 0.7546172142028809, "baseDuration": 187.41484808921814, "commitTime": 1354571561.651699, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571557.448391}
 LOG  Profiler {"actualDuration": 0.7608041763305664, "baseDuration": 187.42119359970093, "commitTime": 1354571572.704238, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571568.477199}
 LOG  Profiler {"actualDuration": 0.7675418853759766, "baseDuration": 187.4037322998047, "commitTime": 1354571583.90243, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571579.394161}
 LOG  Profiler {"actualDuration": 0.7736167907714844, "baseDuration": 187.4337317943573, "commitTime": 1354571597.184853, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571592.956815}
 LOG  Profiler {"actualDuration": 0.7556538581848145, "baseDuration": 187.43296360969543, "commitTime": 1354571608.282238, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571604.102468}
 LOG  Profiler {"actualDuration": 0.7578489780426025, "baseDuration": 187.43584966659546, "commitTime": 1354571619.193661, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571614.994353}
 LOG  Profiler {"actualDuration": 0.7946527004241943, "baseDuration": 187.48004269599915, "commitTime": 1354571630.588738, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571626.374545}
 LOG  Profiler {"actualDuration": 0.3811521530151367, "baseDuration": 187.48004269599915, "commitTime": 1354571645.90193, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571642.108045}
 LOG  Profiler {"actualDuration": 10.847999811172485, "baseDuration": 190.61369585990906, "commitTime": 1354571741.956661, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571725.787391}
 LOG  Profiler {"actualDuration": 104.28013372421265, "baseDuration": 195.10149788856506, "commitTime": 1354571868.555468, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571753.964661}
 LOG  Profiler {"actualDuration": 11.063694715499878, "baseDuration": 198.40868854522705, "commitTime": 1354571914.641045, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571899.682584}
 LOG  Profiler {"actualDuration": 8.554231405258179, "baseDuration": 199.99072670936584, "commitTime": 1354571942.968891, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571930.61293}
 LOG  Profiler {"actualDuration": 8.605072736740112, "baseDuration": 201.7253429889679, "commitTime": 1354571967.751083, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571955.297007}
 LOG  Profiler {"actualDuration": 12.164538145065308, "baseDuration": 203.50791764259338, "commitTime": 1354571996.76566, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354571980.651583}
 LOG  Profiler {"actualDuration": 8.646689176559448, "baseDuration": 205.32722306251526, "commitTime": 1354572021.442007, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354572009.025776}
 LOG  Profiler {"actualDuration": 8.558229684829712, "baseDuration": 207.16626048088074, "commitTime": 1354572045.719853, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354572033.328891}
 LOG  Profiler {"actualDuration": 8.66300106048584, "baseDuration": 209.0258767604828, "commitTime": 1354572074.104045, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354572061.586853}
 LOG  Profiler {"actualDuration": 8.377150297164917, "baseDuration": 210.88203048706055, "commitTime": 1354572098.747122, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354572086.575314}
 LOG  Profiler {"actualDuration": 11.204771995544434, "baseDuration": 212.8458776473999, "commitTime": 1354572126.10543, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354572111.133814}
 LOG  Profiler {"actualDuration": 8.771084308624268, "baseDuration": 214.66533970832825, "commitTime": 1354572152.176968, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1354572139.569314}
 LOG  Profiler {"actualDuration": 0.36484336853027344, "baseDuration": 214.66 [...]

2022-12-27 07:49 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
Numbers are the same because you didn't remove `WalkThroughContextProvider ` and `WalkThrough ` from rendering

2022-12-27 08:04 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +    <Portal>
> Why is the Portal is still a culprit if it is not even rendered
Because it get's executed anyway (14 times for some reason) and it takes time. Probably `WalkThroughContextProvider` forces the whole screen to rerender, i don't know but the numbers show the impact.

> And not all hooks and effects are executed as you say on each rerender. Like non of them.
hooks = functions, since you have `()` at the end of the function name that means that it gets executed.

> Because a new screen for every walkthrough step is a poor decision.
ok, you can make a single screen for all steps, it's up to you

> Context is better suited tool in that case
because....

Anyway i provided my arguments and it seems we're not moving forward, so do it the way you think right

2022-12-27 08:08 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +  const onNext = useCallback(() => {
Anyway it makes more useless work, but the impact is probably not that big, so you can keep using it if you think it worth it

2022-12-27 08:15 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
Of course I removed the WalkThrough. Let's see how it is without `WalkThroughContextProvider` and WalkThrough 
```
 LOG  Profiler {"actualDuration": 496.27616572380066, "baseDuration": 294.20731949806213, "commitTime": 1356844899.985035, "id": "Team", "interactions": undefined, "phase": "mount", "startTime": 1356844351.127497}
 LOG  Profiler {"actualDuration": 6.124458074569702, "baseDuration": 281.725159406662, "commitTime": 1356845124.89115, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845116.115958}
 LOG  Profiler {"actualDuration": 6.751353740692139, "baseDuration": 274.41020154953003, "commitTime": 1356845155.397342, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845144.482265}
 LOG  Profiler {"actualDuration": 35.60843086242676, "baseDuration": 231.55946826934814, "commitTime": 1356845207.362034, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845166.131804}
 LOG  Profiler {"actualDuration": 0.8140823841094971, "baseDuration": 225.62396955490112, "commitTime": 1356845245.926188, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845241.569457}
 LOG  Profiler {"actualDuration": 0.7957766056060791, "baseDuration": 225.076007604599, "commitTime": 1356845256.964419, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845252.814073}
 LOG  Profiler {"actualDuration": 0.8686141967773438, "baseDuration": 224.701007604599, "commitTime": 1356845270.81265, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845266.582304}
 LOG  Profiler {"actualDuration": 0.8107302188873291, "baseDuration": 224.35142946243286, "commitTime": 1356845281.863265, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845277.779304}
 LOG  Profiler {"actualDuration": 0.7783114910125732, "baseDuration": 223.93112182617188, "commitTime": 1356845292.542842, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845288.474419}
 LOG  Profiler {"actualDuration": 0.7809586524963379, "baseDuration": 223.56289100646973, "commitTime": 1356845303.494381, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845299.117188}
 LOG  Profiler {"actualDuration": 0.8218867778778076, "baseDuration": 223.29892706871033, "commitTime": 1356845322.277534, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845315.793688}
 LOG  Profiler {"actualDuration": 0.7753849029541016, "baseDuration": 223.01081013679504, "commitTime": 1356845333.312573, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845329.228304}
 LOG  Profiler {"actualDuration": 0.8033077716827393, "baseDuration": 222.698157787323, "commitTime": 1356845344.415688, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845340.230611}
 LOG  Profiler {"actualDuration": 0.815387487411499, "baseDuration": 222.36984872817993, "commitTime": 1356845355.720573, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845351.322496}
 LOG  Profiler {"actualDuration": 4.469569444656372, "baseDuration": 222.36984872817993, "commitTime": 1356845498.407303, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845489.649303}
 LOG  Profiler {"actualDuration": 8.197839260101318, "baseDuration": 223.80695867538452, "commitTime": 1356845518.350342, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845506.320034}
 LOG  Profiler {"actualDuration": 10.344811201095581, "baseDuration": 227.0671465396881, "commitTime": 1356845542.775842, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845528.872496}
 LOG  Profiler {"actualDuration": 8.402074098587036, "baseDuration": 228.7006483078003, "commitTime": 1356845570.753919, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845554.623919}
 LOG  Profiler {"actualDuration": 8.165533065795898, "baseDuration": 230.2798788547516, "commitTime": 1356845597.496111, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845585.71338}
 LOG  Profiler {"actualDuration": 8.863578796386719, "baseDuration": 231.9114956855774, "commitTime": 1356845623.858726, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845609.448573}
 LOG  Profiler {"actualDuration": 8.946036100387573, "baseDuration": 233.82810926437378, "commitTime": 1356845653.209996, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845640.428226}
 LOG  Profiler {"actualDuration": 8.686193943023682, "baseDuration": 235.6597638130188, "commitTime": 1356845678.388688, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845665.945188}
 LOG  Profiler {"actualDuration": 8.978998899459839, "baseDuration": 237.565612077713, "commitTime": 1356845706.134034, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845693.341149}
 LOG  Profiler {"actualDuration": 8.789803981781006, "baseDuration": 239.44049644470215, "commitTime": 1356845731.731265, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845719.158765}
 LOG  Profiler {"actualDuration": 10.764424800872803, "baseDuration": 241.3860728740692, "commitTime": 1356845762.333303, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845744.471573}
 LOG  Profiler {"actualDuration": 8.550144910812378, "baseDuration": 243.22038054466248, "commitTime": 1356845787.835149, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845775.571342}
 LOG  Profiler {"actualDuration": 0.3641526699066162, "baseDuration": 243.22038054466248, "commitTime": 1356845813.230034, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845809.29238}
 LOG  Profiler {"actualDuration": 0.342926025390625, "baseDuration": 243.22038054466248, "commitTime": 1356845888.174226, "id": "Team", "interactions": undefined, "phase": "update", "startTime": 1356845884.328534}
 ```

2022-12-27 08:28 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
Have you removed the `WalkThroughContextProvider` and `WalkThrough` completely (not just place them outside of the Profiler like you showing here - https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1057498092)?

Can you use the code below, run it like 5 times and show the results? I provided mine at the end

So the case 1 :
```
let renderTime = 0;
export const Team = memo(() => {
  useFocusStatusBar({style: 'light-content'});
  const [isSearchActive, setIsSearchActive] = useState(false);
  return (
    <Profiler
      id="test"
      onRender={(
        _,
        __,
        actualDuration, // time spent rendering the committed update
      ) => {
        renderTime += actualDuration;
        console.log(renderTime);
      }}>
      <View style={styles.container}>
        <LinesBackground />
        <Header
          isSearchActive={isSearchActive}
          setIsSearchActive={setIsSearchActive}
        />
        <DynamicHeight isSearchActive={isSearchActive}>
          <SegmentedContent />
          {isSearchActive && <SearchResults />}
        </DynamicHeight>
      </View>
    </Profiler>
  );
});
```

case 2:
```
let renderTime = 0;
export const Team = memo(() => {
  useFocusStatusBar({style: 'light-content'});
  const [isSearchActive, setIsSearchActive] = useState(false);

  return (
    <Profiler
      id="test"
      onRender={(
        _,
        __,
        actualDuration, // time spent rendering the committed update
      ) => {
        renderTime += actualDuration;
        console.log(renderTime);
      }}>
      <WalkThroughContextProvider>
        <View style={styles.container}>
          <LinesBackground />
          <Header
            isSearchActive={isSearchActive}
            setIsSearchActive={setIsSearchActive}
          />
          <DynamicHeight isSearchActive={isSearchActive}>
            <SegmentedContent />
            {isSearchActive && <SearchResults />}
          </DynamicHeight>
        </View>

        <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
      </WalkThroughContextProvider>
    </Profiler>
  );
});
```

So my results:
case 1: 524 562 563 565 507
case 2: 1082, 1055, 1033, 1075, 1071

2022-12-27 08:33 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
I think that is not the proper test. Why do you group them? It is just more stuff to render of course it will take longer. If you put a Profiler just around the Team tab content - times are the same. Initial render the same.

2022-12-27 08:42 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
`case 1` - the exact markdown of the screen without walkthrough (if we would use modals)
`case 2` - the exact markdown of the current approach
Why should keep / remove something from those?

> just more stuff to render of course it will take longer

Exactly. That's why the existence of `WalkThrough` and `WalkThroughContextProvider` in the render slows down the app

2022-12-27 08:50 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
Presence of WalkThrough and WalkThroughContextProvider doesn't affect the render of team tab content. if we would use modals state updates won't go away. It will remove only the WalkThrough from the tree rendering of which take 9 ms. That is our argue point here - 9ms

2022-12-27 09:31 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
> Presence of WalkThrough and WalkThroughContextProvider doesn't affect the render of team tab content.

What do you mean "they don't affect"? Try to remove those and measure the screen render as i provided above (case 1)

> if we would use modals state updates won't go away

If we use modals + redux, we won't have `WalkThrough ` and we won't have `WalkThroughContextProvider` at all. So the markdown of the team screen would be exactly as in `case 1`

2022-12-27 13:04 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
@ice-orion your screen render counts updates as well. Anyway @ice-ares what do you thing should I spend more time and switch it to Redux and Modals rails? If you approve I work on it

2022-12-27 13:27 UTC, ice-ares commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
i prefer uniformity, so lets go with redux + modals

2022-12-27 13:29 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
@ice-orion please explain how you see it fit our current redux setup. Given there are multiple tabs with multiple steps. How do you see the scructure?

2022-12-28 06:20 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
We can have a call and discuss it, but the first that comes to mind is -

You can listen to `AccountActions.USER_STATE_CHANGE.SUCCESS` action to call a saga that would build the walkthrought sequence depending on `user.clientData` filed and the current version of walkthrought. So any time a user opens the app / logins you build this sequence from scratch.

As for the WalkthroughStep type, would do it like so (almost like your WalkThroughData, but with small changes):
```
{
  topPositionOfHighlightedElement?: number; // we don't have this at the beginning
  version: number;
  finished: boolean;
  HighlightedElement: React.ReactNode;
  Icon?: React.ReactNode;
  before?: () => void; // we can use it to navigate to some screen or pass params to the current screen
}
```

So we could have it like so:
```
const walkthroughSequence = ['HOME_TAB', 'TEAM_TAB', 'MINING_ICON', ...]

const walkthroughSteps = {
   HOME_TAB: {
      version: '1',
      finished: false,
      HighlightedElement: <HomeTabIcon />,
      before: () => navigate('HomeTab')
   },
   TEAM_TAB: {
      version: '1',
      finished: false,
      HighlightedElement: <TeamTabIcon />,
      before: () => navigate('TeamTab')
   },
   MINING_ICON: {
      version: '1',
      finished: false,
      HighlightedElement: <MiningIcon />,
   },
   ...
}
```

So at this point you have the array of steps that you need to show one by one, the only thing you need from UI is that `topPositionOfHighlightedElement` for every step, right?

We can have an action, like `SET_WALKTHROUGH_ELEMENT_TOP` that we can dispatch in `onLayout` of the corresponding component:

E.g.
```
<TabBarMiningItem onLayout={(e) => dispatch(SET_WALKTHROUGH_ELEMENT_TOP({key: 'MINING_ICON', topPositionOfHighlightedElement: e.top}))} />
```

And the main saga that would run each step one by one (e.g. `showWalkthroughStep`)
1. take the first unfinished step
2. call `before`
3.1. if topPositionOfHighlightedElement is there for this step, then `navigate('Walkthrough', {stepData})`
3.2. If topPositionOfHighlightedElement is not there, wait until it is set and then navigate to `Walkthrough`. In sagas you can wait by something like that:
```
while (!currentWalkthroughStep.topPositionOfHighlightedElement) {
   yield take (SET_WALKTHROUGH_ELEMENT_TOP)
}
```

And you also would need one more action to go to the next walkthrough step (that would mark the current step as `finished` and call `showWalkthroughStep`)

2022-12-28 13:03 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
@ice-orion thanks for your effort. But we need to pass a version for every step as well, an Icon and a renderHighlightedElement (or HighlightedElement as you suggest). I just remembered that Redux discourages keeping non serialisable data in its state. Means Redux doesn't fit here, right? So I will try to switch from Portal to Modals for now. 
cc: @ice-ares

2022-12-28 13:08 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
Redux fits here very well, since you're using saga middleware here (part of the redux) to separate business logic as i described above. You can keep the steps data in a plain object / array without saving it to the state

2022-12-28 13:41 UTC, OlegPanfyorov commented on src/screens/News/FeaturedPost.tsx
> +        onPress={() => {}}>
Can we handle this on press?

2022-12-28 13:41 UTC, OlegPanfyorov commented on src/screens/News/FeaturedPost.tsx
> +    useState(3);
Why 3? How did you get this number? Lets use some sort of type here with name and value that would be a number, or steps arrays length or what ever that would be more clear

2022-12-28 13:41 UTC, OlegPanfyorov commented on src/screens/News/constants.tsx
> +export const NEWS_WALK_THROUGH_STEPS_VERSIONS = {
NEWS_WALKTHROUGH_***

2022-12-28 13:41 UTC, OlegPanfyorov commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
> +        dispatch(PermissionsActions.GET_PERMISSIONS.START.create('contacts'))
Lets move to separate const function

2022-12-28 13:41 UTC, OlegPanfyorov commented on src/screens/WalkThrough/WalkThrough.tsx
> +  const user = useSelector(userSelector) as User;
Why do we need force casting to User object here?

2022-12-28 13:41 UTC, OlegPanfyorov commented on src/screens/WalkThrough/WalkThrough.tsx
> +              <NextArrowSvg style={{marginLeft: rem(12)}} />
Pls remove inline style

2022-12-28 13:48 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
@ice-orion you want to keep walkThrough data in some file level constant? And don't use Redux state or selectors but still use it, right? And you want to subscribe to some event and based on event do the staff, right?

Now when user data and walkthrough steps data are there in the state we show the walkthrough. Moving to Redux we will show walkthrough based on some event which tells us user data and walkthrough steps are there?

2022-12-28 13:57 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +  const user = useSelector(userSelector) as User;
IDK. copied form other place

2022-12-28 13:57 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +  const user = useSelector(userSelector) as User;
There are 9 such usages in the codebase

2022-12-28 13:58 UTC, ice-hades commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
> +        dispatch(PermissionsActions.GET_PERMISSIONS.START.create('contacts'))
cool

2022-12-28 13:58 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
Moving to Redux we will remove context usage (the very initial point that context + portal usage slows down the main screens, the goal is to avoid it right?). Plus we will separate business logic from UI cuz everything will be in sagas <--- this is the part that we need from redux ecosystem in this case.

2022-12-28 13:58 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +              <NextArrowSvg style={{marginLeft: rem(12)}} />
sure. copied as well )

2022-12-28 14:04 UTC, ice-orion commented on src/screens/WalkThrough/WalkThrough.tsx
> +              <NextArrowSvg style={{marginLeft: rem(12)}} />
Please fix small issues if we see those (like this with inline style) - https://www.notion.so/leftclick/Code-standards-417aca6329c646dd932e1b808db84c4e#33721170aad742bf94b96776788ee2a1

2022-12-28 14:05 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
The goal is for consistency sake. They don't slow down anything. You can launch it on any slow device and it works perfectly. Your numbers are from improper profiling. I thought we are done with all this theory and arguing yet you move back to it.

- What business logic do we move to the sagas?
- Where to keep the data if not in the redux state? Do you suggest a file level constant?
- If we don't keep it in the state, how do we know it is ready and we can use it? Do you suggest some event triggering?

2022-12-28 14:16 UTC, ice-orion commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
Well, i'm getting tired of arguing here... I was also thinking that we already decided that the team screen works twice faster without context-provider and walkthrough component... 
You haven't provided the numbers from this test case by the way - https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1057522218

> Your numbers are from improper profiling
Why do they improper? 1 case with context and portal, 2 case is exactly how it would be with redux and saga (as it is now actually).

> I thought we are done with all this theory and arguing yet you move back to it.
yea exactly my thoughts

> What business logic do we move to the sagas?
Everything related to walkthrough - what steps to show, depending on user data and current walkthrough version. If we had tests, we could even write tests for those versioning stuff without involving any UI.

> Where to keep the data if not in the redux state? Do you suggest a file level constant?
Yea, why not? Or you can keep it in the state and suppress the warning because as they state "However, like most rules, there are exceptions. There may be occasions when you have to deal with actions that need to accept non-serializable data." -- it's up to you

> If we don't keep it in the state, how do we know it is ready and we can use it? Do you suggest some event triggering?
we have event that user is authorized / loaded -> here you build the sequence depending on user data
then you're starting to show the steps one by one as i described above

2022-12-28 14:20 UTC, ice-hector requested changes

2022-12-28 14:20 UTC, ice-hector commented on src/screens/WalkThrough/WalkThrough.tsx
> +              <NextArrowSvg style={{marginLeft: rem(12)}} />
Pls remove inline style

2022-12-28 14:22 UTC, ice-hector commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
>  const icon = require('../../../../assets/images/teamAgendaNotShared.png');
Pls fix path here

2022-12-28 14:33 UTC, ice-hades commented on src/screens/News/FeaturedPost.tsx
> +        onPress={() => {}}>
Seems it is not working for now. I just moved it to render callback.

2022-12-28 14:33 UTC, ice-hades commented on src/screens/News/FeaturedPost.tsx
> +    useState(3);
Cool

2022-12-28 14:35 UTC, ice-hades commented on src/screens/News/constants.tsx
> +export const NEWS_WALK_THROUGH_STEPS_VERSIONS = {
https://github.com/ice-blockchain/mobile-app/pull/90#discussion_r1056905246

2022-12-28 14:36 UTC, ice-hades commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
> +        dispatch(PermissionsActions.GET_PERMISSIONS.START.create('contacts'))
It is a separate function. Do you mean a separate file?

2022-12-28 14:36 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +              <NextArrowSvg style={{marginLeft: rem(12)}} />
Cool

2022-12-28 14:42 UTC, ice-hades commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
>  const icon = require('../../../../assets/images/teamAgendaNotShared.png');
What it should be? It's absolute path `src/screens/Team/assets/images/teamAgendaNotShared.png`

2022-12-28 16:45 UTC, ice-atlas commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
>  const icon = require('../../../../assets/images/teamAgendaNotShared.png');
btw, why is `require`? -> `import from`

2022-12-29 14:01 UTC, ice-hades commented on src/screens/News/FeaturedPost.tsx
> +    useState(3);
done

2022-12-29 14:01 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +              <NextArrowSvg style={{marginLeft: rem(12)}} />
done

2022-12-29 14:01 UTC, ice-hades commented on src/contexts/WalkThroughContext.tsx
> +export const WalkThroughContext = React.createContext<WalkThroughContextType>(
done

2022-12-29 14:01 UTC, ice-hades commented on src/screens/Team/index.tsx
> +      <WalkThrough walkThroughType={'team'} numberOfSteps={9} />
done

2022-12-30 07:44 UTC, ice-orion commented on src/screens/WalkThrough/hooks/useDescriptionData.ts
> +    // @ts-ignore
FYI(optional): You could have avoided all these `@ts-ignore` and make the translations typesafe here and later for url_lint and title, if you had defined the step content (titte, description, url and so on) statically in a constant (just like you define versions for the steps). And then you wouldn't have needed to rely on translation existence to show / hide urls.

2022-12-30 07:44 UTC, ice-orion commented on src/screens/WalkThrough/hooks/useOnFinalize.ts
> +            return {retry: true};
You have to process the freshUser here - you can overwrite the prev changes if you just retry with the same `clientData`. Take a look for example here - `src/screens/WelcomeFlow/WhoInvitedYou/hooks/useWhoInvitedYou.ts`

2022-12-30 07:44 UTC, ice-orion commented on src/screens/WalkThrough/hooks/useOnFinalize.ts
> +              ...(user.clientData ?? {}),
FYI (optional): 
this:
`...(user.clientData ?? {}),`
is the same as this:
`...user.clientData,`
Meaning you can safely unpack undefined and null

2022-12-30 08:47 UTC, ice-hades commented on babel.config.js
> +            '@contexts': './src/contexts',
done

2022-12-30 08:47 UTC, ice-hades commented on src/components/Labels/FormattedNumber/index.tsx
> +  color?: string;
done

2022-12-30 08:47 UTC, ice-hades commented on src/screens/WalkThrough/hooks/useOnFinalize.ts
> +              ...(user.clientData ?? {}),
done

2022-12-30 08:48 UTC, ice-hades commented on src/screens/WalkThrough/hooks/useOnFinalize.ts
> +            return {retry: true};
done

2022-12-30 08:48 UTC, ice-hades commented on tsconfig.json
> +      "@contexts/*": ["src/contexts/*"]
done

2022-12-30 08:48 UTC, ice-hades commented on package.json
> +    "react-native-portalize": "1.0.7",
done

2022-12-30 09:15 UTC, ice-hector commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
>  const icon = require('../../../../assets/images/teamAgendaNotShared.png');
@ice-hades you should use in this case
`@screens/Team//assets/images/teamAgendaNotShared.png`

2022-12-30 09:18 UTC, ice-hades commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
>  const icon = require('../../../../assets/images/teamAgendaNotShared.png');
ok. it is not my code. but ok will fix it

2022-12-30 09:18 UTC, ice-hector commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
> +        dispatch(PermissionsActions.GET_PERMISSIONS.START.create('contacts'))
No, separate const function like

`const handlePress = () => { // do dispatch here }`

and in button
`onPress={handlePress}`

2022-12-30 09:22 UTC, ice-hector commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
>  const icon = require('../../../../assets/images/teamAgendaNotShared.png');
All project code is your code by default because we are a team and everyone should be responsible to make it as clean as possible, no matter whose PR is it and who is on duty today :)

2022-12-30 09:24 UTC, ice-hades commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
>  const icon = require('../../../../assets/images/teamAgendaNotShared.png');
@ice-hector if we are a team please use words `we should use in this case` next time.

2022-12-30 09:27 UTC, ice-hades commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
> +        dispatch(PermissionsActions.GET_PERMISSIONS.START.create('contacts'))
Got it

2022-12-30 09:32 UTC, ice-hector commented on src/screens/Team/components/Contacts/components/ContactsPermissions/index.tsx
>  const icon = require('../../../../assets/images/teamAgendaNotShared.png');
@ice-hades What you just wrote here is not appropriate. Respect others and it will return

2022-12-30 09:50 UTC, ice-hector commented on src/screens/WalkThrough/WalkThrough.tsx
> +                {/*@ts-ignore*/}
Please remove ts ignore from here

2022-12-30 09:51 UTC, ice-hector commented on src/screens/WalkThrough/WalkThrough.tsx
> +                      // @ts-ignore
Please remove ts ignore from here

2022-12-30 09:57 UTC, ice-hades commented on src/screens/WalkThrough/WalkThrough.tsx
> +                      // @ts-ignore
The translation path should be dynamic here. @ice-orion added some checks for  translation paths. If not found then there is a TS error. Since those TS checks are static and the path is dynamic no way it can recognise it.
@ice-orion suggested some workaround here. But I not quite get it. Something about moving description and title to constants. But there are supposed to be multiple translations.

That should be a common pattern to use dynamic translation path can we add some exceptions @ice-orion ?

2023-01-02 15:23 UTC, ice-hector approved these changes

2023-03-03 07:34 UTC, closed without merging