Feature/contacts fix
ice-blockchain/mobile-app pull request #96
Opened 2022-12-30 16:37 UTC by ice-hector

2022-12-30 17:01 UTC, ice-ares commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> +  nationalPhoneNumberWithCountryCode,
name it for its purpose, not for its implementation: I.E. beautifyPhoneNumber

2022-12-30 17:06 UTC, ice-ares commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> +          } catch (e) {
log it

2022-12-30 17:09 UTC, ice-ares commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> +            agendaPhoneNumbers.push(e164FormattedForHash);
u can build the hash array as u go, you don't need this aux array

2022-12-30 17:12 UTC, ice-ares commented on src/store/modules/Referrals/selectors/index.ts
> +            } catch (error) {
log it

2022-12-30 17:12 UTC, ice-ares commented on src/utils/validations.ts
> +export function notNull<V>(value: V | null): value is V {
over engineering, just inline it

2022-12-30 17:14 UTC, ice-ares commented on src/utils/phoneNumber.ts
> +  defaultCountryCode?: string | null,
name is misleading, its not default. Modify the e164PhoneNumber arg as well

2022-12-30 17:15 UTC, ice-ares commented on src/utils/phoneNumber.ts
> +  } catch (error) {
log it or better to not try catch it at all

2022-12-30 17:17 UTC, ice-ares commented on src/utils/phoneNumber.ts
> +export const nationalPhoneNumberWithCountryCode = (
have you tested with various inputs for phone? with various formats? with country code, without country code, e164 format, national format, empty string, etc.

Actually, better to create a jest for that. Do the same for e164PhoneNumber as well

2023-01-02 15:47 UTC, ice-hector commented on src/store/modules/Contacts/sagas/syncContactsSaga.ts
> +            agendaPhoneNumbers.push(e164FormattedForHash);
But that would increase the complexity. Right now I fill the agendaPhoneNumbers inside filtering, if I will move it out then I will have to map filteredNumbersArray once again

2023-01-02 15:53 UTC, ice-hector commented on src/utils/phoneNumber.ts
> +  } catch (error) {
Logged error. 
That's not an option here to remove try catch because we return combined results from several function calls, not just the result from parsePhoneNumberWithError as in e164PhoneNumber

2023-01-02 16:17 UTC, ice-hector commented on src/utils/phoneNumber.ts
> +export const nationalPhoneNumberWithCountryCode = (
Yep I tested on US/UA/CY numbers all good
What you wanna test with jest? 
Everything is already tested by library owners according to specific number standards/formats for each country/region
https://gitlab.com/catamphetamine/libphonenumber-js/-/tree/master/test

2023-01-02 17:41 UTC, ice-ares commented on src/utils/phoneNumber.ts
> +  } catch (error) {
it makes not sense to try catch something just to throw it back again

2023-01-02 17:42 UTC, ice-ares commented on src/utils/phoneNumber.ts
> +export const nationalPhoneNumberWithCountryCode = (
create unit tests for those 2 funcs

2023-01-03 14:01 UTC, ice-atlas requested changes

2023-01-03 14:01 UTC, ice-atlas commented on src/store/modules/Referrals/selectors/index.ts
> +        ? referralData?.referrals.map(ref => {
Maybe better to use `reselect` to memorize result of computation? Since it will call `array.map()` every invocation => will create new array every time

2023-01-03 14:01 UTC, ice-atlas commented on src/utils/phoneNumber.ts
> +  } catch (error) {
good point!

2023-01-03 14:29 UTC, ice-hector commented on src/utils/phoneNumber.ts
> +  } catch (error) {
Yeah, removed from here

2023-01-03 14:49 UTC, ice-hector commented on src/screens/Team/components/Header/components/Search/index.tsx
> +const CANCEL_FONT_SIZE = rem(16);
Removed

2023-01-03 14:52 UTC, ice-hector commented on src/screens/Team/components/Header/components/Search/index.tsx
> +  const [cancelWidth] = useState(CANCEL_WIDTH);
Removed it from useState, but remained CANCEL_WIDTH const because its used in styles also

2023-01-03 15:58 UTC, ice-hector commented on src/store/modules/Referrals/selectors/index.ts
> +        ? referralData?.referrals.map(ref => {
Good catch, done. Thanks

2023-01-03 16:21 UTC, ice-ares commented on __tests__/functions/beautifyPhoneNumber.test.ts
> +    expect(beautifyPhoneNumber('1234567890', 'US')).toBe('+1 1234567890');
Thats not what the format should be. Check figma

2023-01-03 16:23 UTC, ice-ares commented on __tests__/functions/beautifyPhoneNumber.test.ts
> +describe('beautifyPhoneNumber', () => {
Very poor coverage. Add all possible usecases

2023-01-03 17:30 UTC, ice-atlas requested changes

2023-01-03 17:31 UTC, ice-atlas commented on src/store/modules/Referrals/selectors/index.ts
> +      data: referralData?.referrals
or `(referralData?.referrals ?? []).map(...)` easier to read

2023-01-03 17:36 UTC, ice-ares commented on src/utils/phoneNumber.ts
> + * e.g. 0503332211 -> +380 50 333 2211 (format is different for each country/locale)
Format is not as expected, check figma

2023-01-04 18:34 UTC, ice-hector commented on src/utils/phoneNumber.ts
> + * e.g. 0503332211 -> +380 50 333 2211 (format is different for each country/locale)
What do you mean by format not as expected? We've discussed it all in the slack thread, the format is different for different countries, and that's how it works

2023-01-05 12:21 UTC, ice-ares approved these changes

2023-01-05 12:58 UTC, ice-atlas approved these changes

2023-01-05 14:08 UTC, merged