Feature/login flow fixes
ice-blockchain/mobile-app pull request #97
Opened 2023-01-05 18:55 UTC by ice-hector

2023-01-10 06:18 UTC, ice-orion commented on .github/workflows/CICD.yaml
> -          yarn fetch-translations
rebase with master please

2023-01-19 12:34 UTC, ice-ares reviewed
Cant see where u are handling errors from firebase auth for that invalid link UI

2023-01-19 12:34 UTC, ice-ares commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +      if (newUsername.length < 4) {
Make those into constants

2023-01-19 14:56 UTC, ice-ares commented on src/hooks/useAsyncStorage.ts
> +  const setStored = async (value: any) => {
use this to delete item as well, if value is null

2023-01-19 14:56 UTC, ice-ares commented on src/screens/WelcomeFlow/Onboarding/hooks/useFinishOnboarding.ts
> +    if (!onboardingIds.includes(deviceUniqueId)) {
huh? this is a device storage, why are u doing that? there is only 1 device

2023-01-19 14:56 UTC, ice-ares commented on src/translations/translations.json
> -        "settings": {
why did u do this?

2023-01-19 19:32 UTC, ice-hector commented on src/screens/WelcomeFlow/Onboarding/hooks/useFinishOnboarding.ts
> +    if (!onboardingIds.includes(deviceUniqueId)) {
Yeah, my bad, I had the idea to store device ids if we save on the backend side but we switched to async storage and local storing. Here should be userId.

2023-01-19 19:35 UTC, ice-hector commented on src/translations/translations.json
> -        "settings": {
Do what? Diff just displayed in a strange way like a lot of lines were deleted and then added. From translation file should be correct

2023-01-20 07:49 UTC, ice-orion commented on src/navigation/options.ts
> +  gestureEnabled: false,
why?

2023-01-20 07:49 UTC, ice-orion commented on src/screens/AuthFlow/ConfirmEmailLink/hooks/useConfirmEmailLink.ts
> +  }, [validateError, navigation]);
Shouldn't we rely on error code? Or `InvalidLink` screen is suitable for any possible validation error?

2023-01-20 07:49 UTC, ice-orion commented on src/screens/AuthFlow/InvalidLink/components/Header/index.tsx
> +      <View style={styles.overscrollTop} />
I think you don't need this since you don't have scroll on this screen

2023-01-20 07:49 UTC, ice-orion commented on src/screens/AuthFlow/InvalidLink/hooks/useInvalidLink.ts
> +    validateLoading,
It seems you don't use `email` and `validateError` from this hook, let's remove them.
+ why do we have `validateLoading` and loading animation on the InvalidLink screen, what's the case when this loading is `true`?

2023-01-20 07:49 UTC, ice-orion commented on src/screens/AuthFlow/SignIn/index.tsx
> +import {DIVIDER_HEIGHT} from '@screens/HomeFlow/Home/components/Overview/components/AdoptionCard/components/LevelRow';
I think you import it from a wrong place

2023-01-20 07:49 UTC, ice-orion commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +      if (newUsername.length < USERNAME_MIN_LENGTH) {
Let's have all the validations in sagas so we won't need to duplicate it (e.g. we also may edit username in settings so we also need validations there. If we have that logic in saga, it would be handled at one place).

And same for the `whoInvitedYou` hook

2023-01-20 07:49 UTC, ice-orion commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +              if (freshUser.username !== username) {
`username` might be that same, but you also modify the `finalizedSteps`, so the conflict might be there. Also you're calling `updateUsername` in this case that first calls validate, then wait's for a second and only then calls update once again. You can just call update right away, since you already passed the validation with this username. Take a look how it's made in other places (separate function that accepts user and modified fields and then we pass freshUser in recursion in this callback)

2023-01-20 07:49 UTC, ice-orion commented on src/screens/WelcomeFlow/ConfirmEmailCode/index.tsx
> +          selectionColor={'green'}
COLORS.shamrock?

2023-01-20 07:49 UTC, ice-orion commented on src/screens/WelcomeFlow/IceBonus/index.tsx
> +                value: Number(currentBalance),
Why Number? I think it will be string that we will receive from the BE.

+ let's use `reactStringReplace` and one translation tag instead of breaking it on separate parts. (take a look at `staking.terms_agree` translation and `reactStringReplace` usage for it)

2023-01-20 07:49 UTC, ice-orion commented on src/screens/WelcomeFlow/Onboarding/hooks/useFinishOnboarding.ts
> +    const result = await checkNotifications();
Why do we have it here? We have permissions module for that and you can use `permissionSelector` to grab the status on the push permissions.

2023-01-20 07:49 UTC, ice-orion commented on src/screens/WelcomeFlow/Onboarding/hooks/useFinishOnboarding.ts
> +    canAskNotificationPermissions().then(result => {
use permissions module

2023-01-20 07:49 UTC, ice-orion commented on src/screens/WelcomeFlow/Onboarding/slides.tsx
> +const ICON_SIZE = 23;
rem

2023-01-20 07:49 UTC, ice-orion commented on src/screens/WelcomeFlow/SetEmail/hooks/useSetEmail.ts
> +        AccountActions.UPDATE_ACCOUNT.START.create({
add race condition callback

2023-01-20 07:49 UTC, ice-orion commented on src/screens/WelcomeFlow/WhoInvitedYou/hooks/useWhoInvitedYou.ts
> +        AccountActions.UPDATE_ACCOUNT.START.create({
race condition callback

2023-01-20 07:49 UTC, ice-orion commented on src/utils/string.ts
> +export const usernameValidationRegex: RegExp = /^[a-zA-Z0-9-]+$/;
may be it would be better to have `validateUsername` function that would use this regexp to check the username argument since this is the only possible use case for this regexp anyway?

2023-01-20 16:26 UTC, ice-ares commented on src/screens/WelcomeFlow/Onboarding/hooks/useFinishOnboarding.ts
> +    console.log('finishOnboarding');
remove all console logs

2023-01-20 16:28 UTC, ice-ares commented on src/translations/translations.json
> -    "ro": {
you need to make sure u’re not indenting differently, cuz i cant see what changed

2023-01-21 13:41 UTC, ice-hector commented on src/navigation/options.ts
> +  gestureEnabled: false,
Because we don't allow to go back there but you can do this with swipe gesture if its set to true

2023-01-21 13:42 UTC, ice-hector commented on src/screens/AuthFlow/ConfirmEmailLink/hooks/useConfirmEmailLink.ts
> +  }, [validateError, navigation]);
Yeah, for any email link validation error we show this screen, that was the requirement

2023-01-21 15:43 UTC, ice-hector commented on src/utils/string.ts
> +export const usernameValidationRegex: RegExp = /^[a-zA-Z0-9-]+$/;
Done

2023-01-21 15:47 UTC, ice-hector commented on src/translations/translations.json
> -    "ro": {
I'm using auto-formatting, so there are not many options. From the key/values side, all should be good because we covered localization with types so if the project uses some localization keys that do not exist we will definitely see this in the commit error

2023-01-21 15:49 UTC, ice-hector commented on src/hooks/useAsyncStorage.ts
> +export const useAsyncStorage = (key: string, initialValue: any) => {
I fully rewrote that storage and removed the default value from there, and added types

2023-01-21 16:04 UTC, ice-hector commented on src/navigation/Welcome.tsx
> +  const {getStored} = useAsyncStorage('onboarding', []);
Moved to constants/persist

2023-01-21 16:08 UTC, ice-hector commented on src/screens/AuthFlow/InvalidLink/hooks/useInvalidLink.ts
> +    validateLoading,
There is no case for validateLoading. Also removed same as email and validateError

2023-01-21 16:27 UTC, ice-hector commented on src/screens/WelcomeFlow/IceBonus/index.tsx
> +                value: Number(currentBalance),
Because on the backend side it's a string with .00 (Example: 17.00). We need only an integer according to design.
Translation string supports both (number | string) so in this case Number() just converts the value to an integer in our case.

As for reactStringReplace, are you sure that we should use it? I checked `staking.terms_agree` and It's VERY hard to read it (same as ternary expressions, looks like not readable overhead to me).

2023-01-21 22:06 UTC, ice-hector commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +      if (newUsername.length < USERNAME_MIN_LENGTH) {
Moved to sagas

2023-01-22 13:50 UTC, ice-hector commented on src/hooks/useAsyncStorage.ts
> +export const useAsyncStorage = (key: string, initialValue: any) => {
I remained it as a hook but refactored it, can you check pls? 
I don't want to rewrite it right now just because we can "potentially" use it in sagas sometime in the future, there were no such requirements

2023-01-22 14:36 UTC, ice-hector commented on src/navigation/Welcome.tsx
> +    getStored().then(onboardingIds => {
You couldn't return null instead of navigator... Any other options?

2023-01-23 05:57 UTC, ice-orion commented on src/hooks/useAsyncStorage.ts
> +export const useAsyncStorage = (key: string, initialValue: any) => {
My point here is that you don't need to wrap it in `memo`, cuz those 2 functions have nothing to do with react and you can just export those as is:
```
export const getStored = async (): Promise<T | undefined> => {
        try {
          const item = await AsyncStorage.getItem(key);
          return item ? JSON.parse(item) : undefined;
        } catch (error) {
          logError(error);
        }
      }
      
export const setStored = async (value: T) => {
        try {
          if (value) {
            await AsyncStorage.setItem(key, JSON.stringify(value));
          } else {
            await AsyncStorage.removeItem(key);
          }
        } catch (error) {
          logError(error);
        }
      }
      ```
      
And that's it - no need to rewrite anything, just get rid of unnecessary complications here.

2023-01-23 06:05 UTC, ice-orion commented on src/screens/WelcomeFlow/IceBonus/index.tsx
> +                value: Number(currentBalance),
```
Number('1,234.00') -> NaN
```
I would clarify if we really have to cut off the decimals, cuz everywhere else we show it as is.

2023-01-23 06:10 UTC, ice-orion commented on src/components/AnimatedSplash/index.tsx
> +  const isAppInitialized = useSelector(isAppInitializedSelector);
We have this code and component in the Router:
```
if (!isAppInitialized) {
    return <Initialization />;
  }
```

It seems it can be:
```
if (!isAppInitialized) {
   return null
}
```
And the `Initialization` component can be removed?

2023-01-23 06:23 UTC, ice-orion commented on src/navigation/Welcome.tsx
> +    getStored().then(onboardingIds => {
Well, it seems we should have used redux persist here, then reading `onboardingIds` wouldn't be async here and everything would have been fine... But ok, if there are no straight ways to handle it and the screen change is not noticeable then close the thread

2023-01-23 08:57 UTC, ice-hector commented on src/screens/WelcomeFlow/SetEmail/hooks/useSetEmail.ts
> +  const removeRefStep = (userToUpdate: User) => {
Otherwise, front navigation will not work if we go back. All these finalized steps storing on backend to restore something is tricky implementation. On my mind its much better to make a decision depending on user model fields (like you have not email -> you show Set email screen, you didnt get ice bonus -> you show ice bonus screen. Same for username / reffered by/ etc.)

2023-01-23 08:58 UTC, ice-hector commented on src/components/AnimatedSplash/index.tsx
> +  const isAppInitialized = useSelector(isAppInitializedSelector);
Yeah, good catch

2023-01-26 19:52 UTC, ice-ares commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +    if (username !== user.username) {
Equal ignore csse

2023-01-26 19:52 UTC, ice-ares commented on src/screens/WelcomeFlow/WhoInvitedYou/hooks/useWhoInvitedYou.ts
> +  const initialRefUsername = useRef(user.referredBy ?? null);
ReferredBy is not username

2023-01-26 19:52 UTC, ice-ares commented on src/screens/WelcomeFlow/WhoInvitedYou/hooks/useWhoInvitedYou.ts
> +      AccountActions.UPDATE_ACCOUNT.START.create({referredBy: refUsername}),
ReferredBy is userId

2023-01-26 19:52 UTC, ice-ares commented on src/services/auth/index.ts
> +        return t('errors.code_expired');
You dont display that, you just retry

2023-01-26 19:52 UTC, ice-ares commented on src/services/auth/index.ts
> +        return t('errors.too_many_requests');
U dont display that, u just retry

2023-01-26 19:52 UTC, ice-ares commented on src/store/modules/Account/sagas/updateAccount.ts
> +      const refUser: SagaReturnType<typeof validateRefUsername> = yield call(
No, u already have it when u validate the input, take it from there, dont call it again

2023-01-26 19:52 UTC, ice-ares commented on src/store/modules/Account/sagas/updateAccount.ts
> +function* validateUsername(username: string) {
No, u dont need those, u have everything u need already

2023-01-26 19:52 UTC, ice-ares commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
Bad idea to move this out of here and into updateAccount

2023-01-26 19:52 UTC, ice-ares commented on src/store/modules/Validation/sagas/validateUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
Same thing here

2023-01-26 19:52 UTC, ice-ares commented on src/translations/locales/en.json
> +      "description_part1": "The power is in your hands.\nEverything that we develop at ",
Dont do that

2023-01-26 19:52 UTC, ice-ares commented on src/translations/locales/en.json
> +      "description": "Invite your friends and earn (both of you) up to 25% bonus on your base mining rate for each friend that joins your team."
Every number is a parameter, not hardcoded

2023-01-29 11:16 UTC, ice-hector commented on src/translations/locales/en.json
> +      "description": "Invite your friends and earn (both of you) up to 25% bonus on your base mining rate for each friend that joins your team."
Should I hardcode it or is this one dynamic and can be gotten from the backend?

2023-01-29 11:25 UTC, ice-hector commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
Why it's a bad idea? The flow has been changed. Now we have two layers of validation
1) Local validations 
2) Backend-related validations

So yeah, getting ref user now located in Update_account (same as Claim username backend-related part)
There are several advantages of using such an approach and we discussed this on a team call.
1) We have different places in the app where we do pretty same things (claim username in auth flow vs change username in settings and so on). From now we simply call first the local validations reactively when the user types and then just the update profile (on some user action) which already contains the backend-related validations.
2) We change the user field (like username). Why is it bad to validate it in the update account saga? It's all fully related.

2023-01-29 11:25 UTC, ice-hector commented on src/store/modules/Validation/sagas/validateUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
Same answer as here
https://github.com/ice-blockchain/mobile-app/pull/97#discussion_r1089934015

2023-01-29 11:26 UTC, ice-hector commented on src/store/modules/Account/sagas/updateAccount.ts
> +function* validateUsername(username: string) {
Looks like you didn't understand how the new validation flow works. We separated the local one and backend-related one.

2023-01-29 11:33 UTC, ice-hector commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +    if (username !== user.username) {
So what is the issue here? If they equal I just skip validation and do` updateFinalizedSteps(user);` in else

2023-01-29 11:43 UTC, ice-hector commented on src/store/modules/Account/sagas/updateAccount.ts
> +      const refUser: SagaReturnType<typeof validateRefUsername> = yield call(
No, I don't have, flow has been changed. 
https://github.com/ice-blockchain/mobile-app/pull/97#discussion_r1089934015

2023-01-29 11:46 UTC, ice-ares commented on src/translations/locales/en.json
> +      "description": "Invite your friends and earn (both of you) up to 25% bonus on your base mining rate for each friend that joins your team."
Const everything, but get them out of the translations

2023-01-29 11:48 UTC, ice-hector commented on src/translations/locales/en.json
> +      "description": "Invite your friends and earn (both of you) up to 25% bonus on your base mining rate for each friend that joins your team."
Yeah ok, I refactoring this translations part right now to support our new approach

2023-01-29 11:48 UTC, ice-ares commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
Cuz you messed up the separation of concerns. Validation saga is the obly one that validates, update saga is the only pne that updates. 

Moving all the validation login to those validation sagas fixes that

2023-01-29 11:48 UTC, ice-ares commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
@ice-orion fyi

2023-01-29 11:50 UTC, ice-ares commented on src/store/modules/Account/sagas/updateAccount.ts
> +function* validateUsername(username: string) {
I know, but the code doesn’t have to be like that, u can run all ur FE validation logic, in the validate saga, before calling the BE

2023-01-29 11:51 UTC, ice-ares commented on src/screens/WelcomeFlow/ClaimUsername/hooks/useClaimUsername.ts
> +    if (username !== user.username) {
Ignore case when u compare em

2023-01-29 14:01 UTC, ice-hector commented on src/store/modules/Account/sagas/updateAccount.ts
> +function* validateUsername(username: string) {
I do exactly this way. The only difference is that in the validation saga, we do all local validations and we do them reactively when the user is typing. All other validations/errors (that basically, we know about from BE requests are moved to updateAccountSaga, because we already handle there tens other errors, so there is no reason not to handle several others there

2023-01-29 14:02 UTC, ice-hector commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
I disagree. Please check this comment
https://github.com/ice-blockchain/mobile-app/pull/97#discussion_r1089970832

2023-01-29 18:47 UTC, ice-hector commented on src/screens/WelcomeFlow/IceBonus/index.tsx
> +                value: Number(currentBalance),
Yeah we need to cut, that's the design requirement, we have there 00  near in fully different size and style

2023-01-29 20:50 UTC, ice-ares commented on src/store/modules/Account/sagas/updateAccount.ts
> +      const refUser: SagaReturnType<typeof validateRefUsername> = yield call(
The GetUserByUsername u use to validate referral returns an user, with an id, use that id as the referredBy

2023-01-30 06:17 UTC, ice-orion commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
Generally for me it also looks fine having validations as part of the update logic. If we have those separated, we can potentially bypass validations and call update with a corrupted data. On the other hand if we have the same checks during the update on the BE side, then probably we can remove it from here. 

So we can probably remove `validateUsername` function where we check that username is already taken since the update function does the same (+ we even already handle the error).

So only `validateRefUsername` left and here the problem exists with the way we pass `referredBy`. So from the UI we're setting `referredBy` as username (since this is what user types). Then in saga we're taking username, fetching a user, taking user's id and setting back this id as `referredBy`. This looks confusing. Here is how we can fix it:
1. Pass the ref's username as a separate field. E.g. `referredByUsername`
2. Add `referredByUsername` field to the user's entity on the BE side, so we can set it during the update and BE do the verifications and populate `referredBy` with the ref's id
3. (probably the most clean way) We can have a separate action and saga for updating ref. If would accept `refUsername`, validate that the user exists, pick id and call `updateUser` with the correct `referredBy` field.

2023-01-30 09:16 UTC, ice-ares commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
I am ok with what @ice-orion suggests

2023-01-30 09:18 UTC, ice-ares commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
> -      yield call(Api.user.getUserByUsername, {username});
@ice-orion resolve this if/when u see fit

2023-01-30 09:38 UTC, ice-orion commented on src/screens/WelcomeFlow/IceBonus/index.tsx
> +                value: Number(currentBalance),
use <FormattedNumber />

2023-01-30 14:54 UTC, ice-hector commented on src/screens/WelcomeFlow/IceBonus/index.tsx
> +                value: Number(currentBalance),
@ice-orion please fix in scope of you backend rest api connection task

2023-01-31 18:20 UTC, ice-atlas requested changes

2023-01-31 18:20 UTC, ice-atlas commented on src/store/modules/Validation/sagas/validateUsernameSaga.ts
>  export function* validateUsernameSaga(
Why do we need to keep it as saga, if it can be just plain function for validation? (if we remove request to BE)

2023-01-31 18:20 UTC, ice-atlas commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
>  export function* validateRefUsernameSaga(
Same here `Why do we need to keep it as saga, if it can be just plain function for validation? (if we remove request to BE)`

Any significant difference from `validateUsernameSaga `?

2023-01-31 18:20 UTC, ice-atlas commented on src/store/modules/Permissions/selectors/index.ts
> +export const grantedPermissionSelector =
Maybe better to use `is...` naming for `bool` selectors? Example `isPermissionGrantedSelector`

2023-01-31 18:20 UTC, ice-atlas commented on src/store/configureStore.ts
> +        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
Why we ignore all this actions?

2023-01-31 18:20 UTC, ice-atlas commented on src/store/configureStore.ts
> +  whitelist: ['users'],
Also you can implement persisting on `usersReducer` level (whitelist only needed fields)

2023-01-31 18:20 UTC, ice-atlas commented on src/store/modules/Account/sagas/updateRefByUsernameSaga.ts
> +        AccountActions.UPDATE_REF_BY_USERNAME.FAILED.create(
just `throw` error here with errorMessage. SO you do not need `else` just `SUCCESS` in the end of `OK` flow

2023-01-31 18:30 UTC, ice-hector commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
>  export function* validateRefUsernameSaga(
Yeah, big difference, in validateUsernameSaga there are only local validation, this one (validateRefUsernameSaga) is like a middleware between local validations and Update_account call.

2023-01-31 18:34 UTC, ice-hector commented on src/store/configureStore.ts
> +        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
It part of rehydration integration was  in the required steps, or their official recommendation to fix some issue, don't remember

2023-01-31 18:35 UTC, ice-hector commented on src/store/configureStore.ts
> +  whitelist: ['users'],
As I understood  from their dox redux persist doesn't support deep tree white listing

2023-01-31 18:35 UTC, ice-hector commented on src/store/modules/Permissions/selectors/index.ts
> +export const grantedPermissionSelector =
We try to avoid is... naming

2023-01-31 18:37 UTC, ice-hector commented on src/store/modules/Validation/sagas/validateUsernameSaga.ts
>  export function* validateUsernameSaga(
It couldn't be the plain function, because we listen to action states/results, reset errors when needed (that affects UI), and so on.  So to keep things consistent that's also done using the same approach

2023-01-31 18:39 UTC, ice-hector commented on src/translations/locales/en.json
> +    "clear_title": "Clear all notifications? ",
Dont know where it came from, not the code in scope of my tasks, but I thing we gonna definitely recheck all the localization and remove all the rest places with \n and things like this in scope of one separate task

2023-01-31 18:39 UTC, ice-hector commented on src/App.tsx
> +            <AnimatedSplash />
I have to check and retest how it behave on both platforms if I move it outside

2023-01-31 21:35 UTC, ice-hector commented on src/translations/locales/en.json
> +    "clear_title": "Clear all notifications? ",
Fixed

2023-01-31 21:46 UTC, ice-hector commented on src/store/modules/Account/sagas/updateRefByUsernameSaga.ts
> +        AccountActions.UPDATE_REF_BY_USERNAME.FAILED.create(
I removed if statement at all, it's not possible to get it because we moved the refer itself validation when the user is typing, so next button will just be disabled for that case

2023-02-01 07:22 UTC, ice-orion commented on src/screens/WelcomeFlow/WhoInvitedYou/hooks/useWhoInvitedYou.ts
> +  const [updateAccountFinished, setUpdateAccountFinished] = useState(false);
just out of curiosity - in `useClaimUsername` you rely on `isSuccessUpdate` to show the green checkmark on the text input, but here you store this flag in state. Can't we handle it the same way in both places? Or there are some differences?

2023-02-01 07:22 UTC, ice-orion commented on src/store/configureStore.ts
> +  whitelist: ['users'],
`+ 1`
https://github.com/rt2zz/redux-persist#nested-persists
persist only 1 flag by wrapping 
```
export const usersReducer = persistReducer({whitelist: ....}, reducer),;
```

2023-02-01 07:22 UTC, ice-orion commented on src/store/modules/Permissions/selectors/index.ts
> +export const grantedPermissionSelector =
In this particular case i would also say that `isPermissionGrantedSelector` is more clear. As for the naming ... It's not a rule to avoid `is` in the bool variable naming, but it's not a something required as well

2023-02-01 08:45 UTC, ice-atlas commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
>  export function* validateRefUsernameSaga(
but the rule for naming almost the same, maybe we can reuse it some how? It may lead to bug if we need to change validation rule in one place we may forget about another

2023-02-01 08:45 UTC, ice-atlas commented on src/store/modules/Validation/sagas/validateUsernameSaga.ts
>  export function* validateUsernameSaga(
any problem to have it as `hook`?

2023-02-01 08:52 UTC, ice-hector commented on src/store/modules/Validation/sagas/validateUsernameSaga.ts
>  export function* validateUsernameSaga(
We already have related hooks/validations, that is the level above all that

2023-02-01 08:55 UTC, ice-hector commented on src/store/modules/Validation/sagas/validateRefUsernameSaga.ts
>  export function* validateRefUsernameSaga(
My bad didn't read the first question properly, That is two different things related to different scenarios (username and refUsername are not the same). So its nothing to change here in that sense

2023-02-01 10:42 UTC, ice-hector commented on src/store/configureStore.ts
> +  whitelist: ['users'],
Fixed

2023-02-01 10:55 UTC, ice-hector commented on src/screens/AuthFlow/SignIn/index.tsx
> +      {isSocialAuthLoading && selectedSocialType !== 'apple' && (
Yep, for apple we don't show loading, it has its own dark overlay

2023-02-01 10:55 UTC, ice-hector commented on src/screens/WelcomeFlow/Onboarding/components/OnboardingSlide/index.tsx
> +    zIndex: 1,
Because sometimes on low res screens text goes under the bottom image. This way its always on top of it

2023-02-01 10:58 UTC, ice-hector commented on src/components/PrivacyTerms/index.tsx
> +  const handlePress = (url: string) => {
Fixed

2023-02-01 11:27 UTC, ice-atlas requested changes

2023-02-01 11:27 UTC, ice-atlas commented on src/screens/AuthFlow/InvalidLink/hooks/useInvalidLink.ts
> +export const useInvalidLink = () => {
Naming. `useBackHandler`?

2023-02-01 11:27 UTC, ice-atlas commented on src/screens/AuthFlow/SignIn/index.tsx
> +    <KeyboardAvoider keyboardVerticalOffset={-SOCIAL_BUTTONS_HEIGHT + rem(15)}>
`rem(15) - SOCIAL_BUTTONS_HEIGHT`

2023-02-01 14:57 UTC, ice-hector commented on src/navigation/Router.tsx
> +    requiredAuthSteps = requiredAuthSteps.filter(step => step !== 'email');
Removed

2023-02-01 14:57 UTC, ice-hector commented on src/navigation/Router.tsx
> +    difference(requiredAuthSteps, finalizedAuthSteps).length !== 0 ||
Refactored

2023-02-01 15:34 UTC, ice-atlas submitted a review, later dismissed

2023-02-01 15:35 UTC, ice-hades submitted a review, later dismissed

2023-02-01 15:50 UTC, ice-atlas approved these changes

2023-02-01 15:52 UTC, ice-orion approved these changes

2023-02-01 17:38 UTC, ice-ares commented on src/translations/locales/en.json
> +    "dontHaveCodeTip": "If you don't have an invitation code we will\nselect a random member as your referral!"
busted!

2023-02-01 17:39 UTC, ice-ares approved these changes

2023-02-01 17:39 UTC, merged